bufr2synop: src/libraries/bufr2tac_x11.c File Reference
bufr2tac_x11.c File Reference
decodes the descriptors with X = 11 (wind)
#include "bufr2tac.h"
Functions
char * secs_to_tt (char *tt, int secs)
get tt code from seconds
char * wind_to_dndnfnfnfn (char *target, double dd, double ff)
int syn_parse_x11 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 11.
int buoy_parse_x11 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 11.
int climat_parse_x11 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 11.
int temp_parse_x11 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 11.
Detailed Description
decodes the descriptors with X = 11 (wind)
Definition in file bufr2tac_x11.c.
Function Documentation
buoy_parse_x11()
int buoy_parse_x11 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 376 of file bufr2tac_x11.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 11 001 . Wind direction
    case 11: // 0 11 011 . Wind direction at 10m
      sprintf ( b->s1.dd, "%02d", abs((s->ival + 5 ) / 10) % 100 );
      b->mask |= BUOY_SEC1;
      break;
    case 2: // 0 11 002 . Wind speed
    case 12: // 0 11 012 . Wind speed at 10 meters
      if ( b->s0.iw[0] == '4' )
        {
          s->val *= 1.94384449;
        }
      if ( s->val < 100.0 )
        {
          sprintf ( b->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
        }
      else
        {
          sprintf ( b->s1.ff,"99" );
          sprintf ( b->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
        }
      b->mask |= BUOY_SEC1;
      break;
    case 84: // 0 11 084  (wind in knots)
      if ( b->s0.iw[0] == '1' )
        {
          s->val /= 1.94384449;
        }
      if ( s->val < 100.0 )
        {
          sprintf ( b->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
        }
      else
        {
          sprintf ( b->s1.ff,"99" );
          sprintf ( b->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
        }
      b->mask |= BUOY_SEC1;
      break;
    default:
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUOY_SEC1, buoy_sec1::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec1::ff, buoy_sec1::fff, bufr2tac_subset_state::ival, buoy_sec0::iw, bufr_atom_data::mask, buoy_chunks::mask, buoy_chunks::s0, buoy_chunks::s1, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
climat_parse_x11()
int climat_parse_x11 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
c pointer to a struct climat_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 439 of file bufr2tac_x11.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 46: // 0 11 046 . Maximum wind speed
      if ( c->s4.iw[0] == '4' )
        {
          sprintf ( c->s4.fxfxfx, "%03d", ( int ) ( s->val * 10.0 * 1.94384449 + 0.5 ) );
        }
      else
        {
          sprintf ( c->s4.fxfxfx, "%03d", ( int ) ( s->val * 10.0 + 0.5 ) );
        }
      if ( s->isq_val == 0 )
        {
          sprintf ( c->s4.yfx, "%02d", s->day );
        }
      else
        {
          sprintf ( c->s4.yfx, "%02d", (s->day + 50) % 100 );
        }
      c->mask |= CLIMAT_SEC4;
      break;
    default:
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, CLIMAT_SEC4, bufr2tac_subset_state::day, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, climat_sec4::fxfxfx, bufr2tac_subset_state::isq_val, climat_sec4::iw, bufr_atom_data::mask, climat_chunks::mask, climat_chunks::s4, bufr2tac_subset_state::val, bufr_descriptor::y, and climat_sec4::yfx.
Referenced by parse_subset_as_climat().
secs_to_tt()
char * secs_to_tt (char * tt, int secs)
get tt code from seconds
Parameters
tt string with the resulting table code
secs second
returns the pointer to tt
Definition at line 34 of file bufr2tac_x11.c.
{
  int i;
  if ( secs < 0 )
    {
      i = ( -secs ) / 360;
    }
  else
    {
      i = ( secs ) / 360;
    }
  if ( i <= 60 )
    {
      sprintf ( tt, "%02d", i );
    }
  else if ( i < 700 )
    {
      sprintf ( tt, "61" );
    }
  else if ( i < 800 )
    {
      sprintf ( tt, "62" );
    }
  else if ( i < 900 )
    {
      sprintf ( tt, "63" );
    }
  else if ( i < 1000 )
    {
      sprintf ( tt, "64" );
    }
  else if ( i < 1100 )
    {
      sprintf ( tt, "65" );
    }
  else if ( i < 1200 )
    {
      sprintf ( tt, "66" );
    }
  else if ( i < 1800 )
    {
      sprintf ( tt, "67" );
    }
  else
    {
      sprintf ( tt, "68" );
    }
  return tt;
}
Referenced by syn_parse_x11(), and syn_parse_x20().
syn_parse_x11()
int syn_parse_x11 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 116 of file bufr2tac_x11.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 11 001 . Wind direction
    case 11: // 0 11 011 . Wind direction at 10 meters
      sprintf ( syn->s1.dd, "%02d", abs((s->ival + 5 ) / 10) % 100 );
      syn->mask |= SYNOP_SEC1;
      break;
    case 2: // 0 11 002 . Wind speed
    case 12: // 0 11 012 . Wind speed at 10 meters
      if ( syn->s0.iw[0] == '4' )
        {
          s->val *= 1.94384449;
        }
      if ( s->val < 100.0 )
        {
          sprintf ( syn->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
        }
      else
        {
          sprintf ( syn->s1.ff,"99" );
          sprintf ( syn->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
        }
      syn->mask |= SYNOP_SEC1;
      break;
    case 41: // 0 11 041 . Max wind gust speed
      if ( syn->s3.d9.n == SYNOP_NMISC )
        {
          return 0;
        }
      if ( s->itval == -600 )
        {
          if ( syn->mask & SUBSET_MASK_HAVE_GUST10 )
            {
              break;
            }
          sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "910" );
          s->SnSn = 910;
          if ( syn->s0.iw[0] == '4' )
            {
              s->val *= 1.94384449;
            }
          if ( s->val < 100.0 )
            {
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
            }
          else
            {
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
              syn->s3.d9.n++;
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00" );
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
            }
          syn->s3.d9.n++;
          syn->mask |= SUBSET_MASK_HAVE_GUST10;
          syn->mask |= SYNOP_SEC3;
        }
      else if ( s->itval )
        {
          if ( s->mask & SUBSET_MASK_HAVE_GUST )
            {
              sprintf ( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "907" );
              secs_to_tt ( syn->s5.d9.misc[syn->s5.d9.n].spsp, s->itval );
              syn->s5.d9.n++;
              sprintf ( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "911" );
              s->SnSn = 911;
              if ( syn->s0.iw[0] == '4' )
                {
                  s->val *= 1.94384449;
                }
              if ( s->val < 100.0 )
                {
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
                }
              else
                {
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp,"99" );
                  syn->s5.d9.n++;
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "00" );
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                }
              syn->s5.d9.n++;
              syn->mask |= SYNOP_SEC5;
            }
          else
            {
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "907" );
              secs_to_tt ( syn->s3.d9.misc[syn->s3.d9.n].spsp, s->itval );
              syn->s3.d9.n++;
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "911" );
              s->SnSn = 911;
              if ( syn->s0.iw[0] == '4' )
                {
                  s->val *= 1.94384449;
                }
              if ( s->val < 100.0 )
                {
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
                }
              else
                {
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
                  syn->s3.d9.n++;
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00" );
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                }
              syn->s3.d9.n++;
              syn->mask |= SYNOP_SEC3;
              s->mask |= SUBSET_MASK_HAVE_GUST;
            }
        }
      break;
    case 42: // 0 11 042 . Max wind speed (10-minutes mean)
      if ( syn->s3.d9.n == SYNOP_NMISC )
        {
          return 0;
        }
      sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "907" );
      secs_to_tt ( syn->s3.d9.misc[syn->s3.d9.n].spsp, s->itval );
      syn->s3.d9.n++;
      sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "912" );
      s->SnSn = 912;
      if ( syn->s0.iw[0] == '4' )
        {
          s->val *= 1.94384449;
        }
      if ( s->val < 100.0 )
        {
          sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
        }
      else
        {
          sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
          syn->s3.d9.n++;
          sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00" );
          sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
        }
      syn->s3.d9.n++;
      syn->mask |= SYNOP_SEC3;
      break;
    case 43: // 0 11 043 . Max wind gust direction
      break;
    case 84: // 0 11 084 . Wind speed in knots
      if ( syn->s0.iw[0] == '1' )
        {
          s->val /= 1.94384449;
        }
      if ( s->val < 100.0 )
        {
          sprintf ( syn->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
        }
      else
        {
          sprintf ( syn->s1.ff,"99" );
          sprintf ( syn->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
        }
      syn->mask |= SYNOP_SEC1;
      break;
    case 86: // 0 11 086 . Max wind speed in knots
      if ( syn->s3.d9.n == SYNOP_NMISC )
        {
          return 0;
        }
      if ( s->itval == -600 )
        {
          sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "910" );
          if ( syn->s0.iw[0] == '1' )
            {
              s->val /= 1.94384449;
            }
          if ( s->val < 100.0 )
            {
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
            }
          else
            {
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
              syn->s3.d9.n++;
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00" );
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
            }
          syn->mask |= SYNOP_SEC3;
          syn->s3.d9.n++;
        }
      else if ( s->itval )
        {
          if ( s->mask & SUBSET_MASK_HAVE_GUST )
            {
              sprintf ( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "907" );
              secs_to_tt ( syn->s5.d9.misc[syn->s5.d9.n].spsp, s->itval );
              syn->s5.d9.n++;
              sprintf ( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "911" );
              if ( syn->s0.iw[0] == '1' )
                {
                  s->val /= 1.94384449;
                }
              if ( s->val < 100.0 )
                {
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
                }
              else
                {
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp,"99" );
                  syn->s5.d9.n++;
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "00" );
                  sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                }
              syn->s5.d9.n++;
              syn->mask |= SYNOP_SEC5;
            }
          else
            {
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "907" );
              secs_to_tt ( syn->s3.d9.misc[syn->s3.d9.n].spsp, s->itval );
              syn->s3.d9.n++;
              sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "911" );
              if ( syn->s0.iw[0] == '1' )
                {
                  s->val /= 1.94384449;
                }
              if ( s->val < 100.0 )
                {
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
                }
              else
                {
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
                  syn->s3.d9.n++;
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00" );
                  sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                }
              syn->s3.d9.n++;
              syn->mask |= SYNOP_SEC3;
              s->mask |= SUBSET_MASK_HAVE_GUST;
            }
        }
      break;
    default:
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, synop_sec3::d9, synop_sec5::d9, synop_sec1::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec1::ff, synop_sec1::fff, bufr2tac_subset_state::itval, bufr2tac_subset_state::ival, synop_sec0::iw, bufr_atom_data::mask, bufr2tac_subset_state::mask, synop_chunks::mask, data9::misc, data9::n, synop_chunks::s0, synop_chunks::s1, synop_chunks::s3, synop_chunks::s5, secs_to_tt(), bufr2tac_subset_state::SnSn, misc3::SpSp, misc3::spsp, SUBSET_MASK_HAVE_GUST, SUBSET_MASK_HAVE_GUST10, SYNOP_NMISC, SYNOP_SEC1, SYNOP_SEC3, SYNOP_SEC5, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x11()
int temp_parse_x11 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 482 of file bufr2tac_x11.c.
{
  if ( t == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 11 001. Wind direction
      if ( s->rep > 0 && s->r->n > 0 )
        {
          if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
            {
              s->r->raw[s->r->n - 1].dd = MISSING_REAL;
            }
          else
            {
              s->r->raw[s->r->n - 1].dd = s->val;
            }
        }
      break;
    case 2: // 0 11 002. Wind speed
      if ( s->rep > 0 && s->r->n > 0 )
        {
          if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
            {
              s->r->raw[s->r->n - 1].ff = MISSING_REAL;
            }
          else
            {
              s->r->raw[s->r->n - 1].ff = s->val;
            }
        }
      break;
    case 61: // 0 11 061. Absolute wind shear in 1 km layer below
      if ( s->w->n > 0 )
        {
          if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
            {
              s->w->raw[s->w->n - 1].ws_blw = MISSING_REAL;
            }
          else
            {
              s->w->raw[s->w->n - 1].ws_blw = s->val;
            }
        }
      break;
    case 62: // 0 11 062. Absolute wind shear in 1 km layer above
      if ( s->w->n > 0 )
        {
          if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
            {
              s->w->raw[s->w->n - 1].ws_abv = MISSING_REAL;
            }
          else
            {
              s->w->raw[s->w->n - 1].ws_abv = s->val;
            }
        }
      break;
    default:
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, temp_raw_point_data::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_raw_point_data::ff, bufr_atom_data::mask, MISSING_REAL, temp_raw_data::n, temp_raw_wind_shear_data::n, bufr2tac_subset_state::r, temp_raw_data::raw, temp_raw_wind_shear_data::raw, bufr2tac_subset_state::rep, bufr2tac_subset_state::val, bufr2tac_subset_state::w, temp_raw_wind_shear_point::ws_abv, temp_raw_wind_shear_point::ws_blw, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().
wind_to_dndnfnfnfn()
char * wind_to_dndnfnfnfn (char * target, double dd, double ff)
Definition at line 93 of file bufr2tac_x11.c.
{
  int ix;
  if ( dd == MISSING_REAL || ff == MISSING_REAL )
    {
      strcpy ( target, "/////" );
      return target;
    }
  ix = ( int ) ( ( dd + 2.5 ) / 5 ) * 5 * 100 + ( int ) ( ff + 0.5 );
  sprintf ( target, "%05d", ix );
  return target;
}
References MISSING_REAL.
Referenced by parse_temp_raw_data().