bufr2synop: src/libraries/bufr2syn_x01.c File Reference
bufr2syn_x01.c File Reference
decodes the descriptors with X = 01 (station index, name and country)
#include "bufr2syn.h"
Functions
int syn_parse_x01 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 01.
int buoy_parse_x01 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 01.
Detailed Description
decodes the descriptors with X = 01 (station index, name and country)
Definition in file bufr2syn_x01.c.
Function Documentation
int buoy_parse_x01 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
b pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 109 of file bufr2syn_x01.c.
References bufr_subset_state::a, buoy_sec0::A1, adjust_string(), buoy_sec0::bw, bufr_atom_data::ctable, bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, bufr_atom_data::mask, bufr_subset_state::mask, bufr_subset_state::name, buoy_sec0::nbnbnb, buoy_chunks::s0, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   char aux[80];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 3: // 0 01 003
       if (s->ival > 0)
         sprintf ( b->s0.A1, "%d", s->ival );
       else if (s->ival == 0)
         sprintf ( b->s0.A1, "7");
       break;
     case 4: // 0 01 004
     case 20: // 0 01 004
       sprintf ( b->s0.bw, "%d", s->ival );
       break;
     case 5: // 0 01 005
       if ( s->ival < 1000)
         sprintf(b->s0.nbnbnb, "%03d", s->ival);
       else
         sprintf(b->s0.nbnbnb, "%05d", s->ival); // note this is a nnnnn extension
       break;
     case 15: // 0 01 015
       if (strlen(s->a->cval) <= 80)
         {
           strcpy(aux, s->a->cval);
           adjust_string(aux);
           strcpy(s->name, aux);
           s->mask |= SUBSET_MASK_HAVE_NAME;
         }
       break;
     case 101: // 0 01 101
       if (strlen(s->a->ctable) <= 80)
         {
           strcpy(aux, s->a->ctable);
           adjust_string(aux);
           strcpy(s->name, aux);
           s->mask |= SUBSET_MASK_HAVE_COUNTRY;
         }
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x01 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x01.c.
References bufr_subset_state::a, synop_sec0::A1, adjust_string(), synop_sec0::bw, bufr_subset_state::country, bufr_atom_data::ctable, bufr_atom_data::cval, synop_sec0::D_D, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::II, synop_sec0::iii, bufr_subset_state::ival, bufr_atom_data::mask, bufr_subset_state::mask, bufr_subset_state::name, synop_sec0::Reg, synop_chunks::s0, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[80];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 01 001
       sprintf ( syn->s0.II, "%02d", s->ival );
       break;
     case 2: // 0 01 002
       sprintf ( syn->s0.iii, "%03d", s->ival );
       break;
     case 3: // 0 01 003
       sprintf ( syn->s0.A1, "%d", s->ival );
       if (strcmp(syn->s0.A1, "1") == 0)
         strcpy(syn->s0.Reg, "I");
       else if (strcmp(syn->s0.A1, "2") == 0)
         strcpy(syn->s0.Reg, "II");
       else if (strcmp(syn->s0.A1, "3") == 0)
         strcpy(syn->s0.Reg, "III");
       else if (strcmp(syn->s0.A1, "4") == 0)
         strcpy(syn->s0.Reg, "IV");
       else if (strcmp(syn->s0.A1, "5") == 0)
         strcpy(syn->s0.Reg, "V");
       else if (strcmp(syn->s0.A1, "6") == 0)
         strcpy(syn->s0.Reg, "VI");
       break;
     case 4: // 0 01 004
     case 20: // 0 01 004
       sprintf ( syn->s0.bw, "%d", s->ival );
       break;
     case 11: // 0 01 011
       if (strlen(s->a->cval) < 16)
         {
           strcpy(aux, s->a->cval);
           adjust_string(aux);
           if (strlen(aux) < 10)
             strcpy( syn->s0.D_D, aux);
         }
       break;
     case 15: // 0 01 015
       if (strlen(s->a->cval) <= 80)
         {
           strcpy(aux, s->a->cval);
           adjust_string(aux);
           strcpy(s->name, aux);
           s->mask |= SUBSET_MASK_HAVE_NAME;
         }
       break;
     case 101: // 0 01 101
       if (strlen(s->a->ctable) <= 256)
         {
           strcpy(aux, s->a->ctable);
           adjust_string(aux);
           strcpy(s->country, aux);
           s->mask |= SUBSET_MASK_HAVE_COUNTRY;
         }
       break;
     default:
       break;
     }
   return 0;
 }