bufr2synop: src/bufrdeco/bufrdeco_read.c File Reference
bufrdeco_read.c File Reference
This file has the code to read bufr files.
#include "bufrdeco.h"
Functions
int get_ecmwf_tablenames (struct bufrdeco *b, const char *bufrtables_dir)
Get the complete pathnames for EMCWF table files needed by a bufr message.
int bufr_read_tables (struct bufrdeco *b, char *tables_dir)
Read the tables according with bufr file data from a bufr table directory.
int bufrdeco_read_bufr (struct bufrdeco *b, char *filename)
Read bufr file and does preliminary and first decode pass.
Variables
const char DEFAULT_BUFRTABLES_DIR1 [] = "/usr/local/lib/bufrtables/"
const char DEFAULT_BUFRTABLES_DIR2 [] = "/usr/lib/bufrtables/"
Detailed Description
This file has the code to read bufr files.
Definition in file bufrdeco_read.c.
Function Documentation
int bufr_read_tables (struct bufrdeco * b, char * tables_dir)
Read the tables according with bufr file data from a bufr table directory.
Parameters
b basic struct with needed data
tables_dir complete path string for directory with ECMWF bufr tables. Must be ended with a '/' . If NULL then is the default
The default directories where to search bufr tables are stored in DEFAULT_BUFRTABLES_DIR1 and DEFAULT_BUFRTABLES_DIR2
Definition at line 168 of file bufrdeco_read.c.
References bufr_tables::b, bufr_read_tableb(), bufr_read_tablec(), bufr_read_tabled(), bufrdeco_init_tables(), bufr_tables::c, bufr_tables::d, bufrdeco::error, get_ecmwf_tablenames(), and bufrdeco::tables.
Referenced by bufrdeco_read_bufr().
 {
   // get tablenames
   if ( get_ecmwf_tablenames ( b, tables_dir ) )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): Cannot find bufr tebles\n" );
       return 1;
     }
   // If tables still not initialized then do it
   if ( b->tables == NULL && bufrdeco_init_tables ( & ( b->tables ) ) )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): Cannot allocate memory for tables\n" );
       return 1;
     }
   // And now read tables
   if ( bufr_read_tableb ( & ( b->tables->b ), b->error ) )
     {
       return 1;
     }
   if ( bufr_read_tablec ( & ( b->tables->c ), b->error ) )
     {
       return 1;
     }
   if ( bufr_read_tabled ( & ( b->tables->d ), b->error ) )
     {
       return 1;
     }
   return 0;
 }
int bufrdeco_read_bufr (struct bufrdeco * b, char * filename)
Read bufr file and does preliminary and first decode pass.
Parameters
b pointer to struct bufrdeco
filename complete path of BUFR file
This function does the folowing tasks:
Read the file and checks the marks at the begining and end to see wheter is a BUFR file
Init the structs and allocate the needed memory if not done previously
Splits and parse the BUFR sections (without expanding descriptors nor parsing data)
Reads the needed Table files and store them in memory.
Returns 0 if all is OK, 1 otherwise
< pointer to a memory buffer where we write raw bufr file
Definition at line 216 of file bufrdeco_read.c.
References bufr_sec4::bit_offset, BUFR_LEN, BUFR_LEN_UNEXPANDED_DESCRIPTOR, bufr_sec0::bufr_length, bufr_read_tables(), bufr_sec1::category, bufr_sec1::centre, bufr_sec3::compressed, bufr_sec1::day, bufr_sec0::edition, bufrdeco::error, bufr_descriptor::f, bufr_sec1::hour, bufr_sec1::length, bufr_sec2::length, bufr_sec3::length, bufr_sec4::length, bufr_sec1::master, bufr_sec1::master_local, bufr_sec1::master_version, bufr_sec1::minute, bufr_sec1::month, bufr_sec3::ndesc, bufr_sec3::observed, bufr_sec1::options, bufr_sec0::raw, bufr_sec1::raw, bufr_sec2::raw, bufr_sec3::raw, bufr_sec4::raw, bufrdeco::sec0, bufrdeco::sec1, bufrdeco::sec2, bufrdeco::sec3, bufrdeco::sec4, bufr_sec1::second, bufr_sec1::subcategory, bufr_sec1::subcategory_local, bufr_sec1::subcentre, bufr_sec3::subsets, three_bytes_to_uint32(), two_bytes_to_descriptor(), two_bytes_to_uint32(), bufr_sec3::unexpanded, bufr_sec1::update, bufr_descriptor::x, bufr_descriptor::y, and bufr_sec1::year.
Referenced by main().
 {
   int aux;
   uint8_t *bufrx = NULL; /*!< pointer to a memory buffer where we write raw bufr file */
   uint8_t *c;
   size_t ix, ud, n = 0;
   FILE *fp;
   struct stat st;
   /* Stat input file */
   if ( stat ( filename, &st ) < 0 )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): cannot stat file '%s'\n", filename );
       return 1;
     }
   /* Alloc nedeed memory for bufr */
   if ( S_ISREG ( st.st_mode ) || S_ISLNK ( st.st_mode ) )
     {
       if ( ( bufrx = ( uint8_t * ) calloc ( 1, st.st_size + 4 ) ) == NULL )
         {
           sprintf ( b->error, "bufrdeco_read_bufr(): cannot alloc memory for file '%s'\n", filename );
           return 1;
         }
     }
   else
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): '%s' is not a regular file nor symbolic link\n", filename );
       return 1;
     }
   /* Inits bufr struct */
   if ( ( st.st_size + 4 ) >= BUFR_LEN )
     {
       sprintf ( b->error, "File '%s' too large. Consider increase BUFR_LEN\n", filename );
       free ( ( void * ) bufrx );
       return 1;
     }
   // Open and read the file
   if ( ( fp = fopen ( filename, "r" ) ) == NULL )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): cannot open file '%s'\n", filename );
       free ( ( void * ) bufrx );
       return 1;
     }
   while ( ( aux = fgetc ( fp ) ) != EOF && ( int ) n < st.st_size )
     bufrx[n++] = ( uint8_t ) aux;
   // close the file
   fclose ( fp );
   // Some fast checks
   if ( n < 8 )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): Too few bytes for a bufr\n" );
       free ( ( void * ) bufrx );
       return 1;
     }
   // check if begins with BUFR
   if ( bufrx[0] != 'B' || bufrx[1] != 'U' || bufrx[2] != 'F' || bufrx[3] != 'R' )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): file '%s' does not begin with 'BUFR' chars\n", filename );
       free ( ( void * ) bufrx );
       return 1;
     }
   // check if end with '7777'
   if ( bufrx[n - 4] != '7' || bufrx[n - 3] != '7' || bufrx[n - 2] != '7' || bufrx[n - 1] != '7' )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): file '%s' does not end with '7777' chars\n", filename );
       free ( ( void * ) bufrx );
       return 1;
     }
   /******************* section 0  *****************************/
   // we have already checked about begin and end
   // length of whole message
   b->sec0.bufr_length = three_bytes_to_uint32 ( &bufrx[4] );
   // check if length is correct
   if ( b->sec0.bufr_length != ( uint32_t ) n )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): file '%s' have %u bytes and it says %u\n", filename,
                 ( uint32_t ) n, b->sec0.bufr_length );
       free ( ( void * ) bufrx );
       return 1;
     }
   // set bufr edition number
   b->sec0.edition = bufrx[7];
   if ( b->sec0.edition < 3 )
     {
       sprintf ( b->error, "bufrdeco_read_bufr(): Bufr edition must be 3 or superior and this file is coded with version %u\n", b->sec0.edition );
       free ( ( void * ) bufrx );
       return 1;
     }
   // raw
   memcpy ( &b->sec0.raw[0], &bufrx[0], 8 );
   /******************* section 1 *****************************/
   c = &bufrx[8]; // pointer to begin of sec1
   switch ( b->sec0.edition )
     {
     case 3:
       b->sec1.length = three_bytes_to_uint32 ( c );
       b->sec1.master = c[3];
       b->sec1.subcentre = c[4];
       b->sec1.centre = c[5];
       b->sec1.update = c[6];
       b->sec1.options = c[7];
       b->sec1.category = c[8];
       b->sec1.subcategory = c[9];
       b->sec1.subcategory_local = 0; // not in version 3
       b->sec1.master_version = c[10];
       b->sec1.master_local = c[11];
       if ( c[12] > 80 )
         b->sec1.year = 1900 + c[12];
       else
         b->sec1.year = 2900 + c[12];
       b->sec1.month = c[13];
       b->sec1.day = c[14];
       b->sec1.hour = c[15];
       b->sec1.minute = c[16];
       b->sec1.second = 0; // not in version 3
       break;
     case 4:
       b->sec1.length = three_bytes_to_uint32 ( c );
       b->sec1.master = c[3];
       b->sec1.centre = two_bytes_to_uint32 ( &c[4] );
       b->sec1.subcentre = two_bytes_to_uint32 ( &c[6] );
       b->sec1.update = c[8];
       b->sec1.options = c[9];
       b->sec1.category = c[10];
       b->sec1.subcategory = c[11];
       b->sec1.subcategory_local = c[12];
       b->sec1.master_version = c[13];
       b->sec1.master_local = c[14];
       b->sec1.year = two_bytes_to_uint32 ( &c[15] );
       b->sec1.month = c[17];
       b->sec1.day = c[18];
       b->sec1.hour = c[19];
       b->sec1.minute = c[20];
       b->sec1.second = c[21];
       break;
     default:
       sprintf ( b->error, "bufrdeco_read_bufr(): This file is coded with version %u and is not supported\n", b->sec0.edition );
       free ( ( void * ) bufrx );
       return 1;
     }
   memcpy ( b->sec1.raw, c, b->sec1.length ); // raw data
   c += b->sec1.length;
   //print_sec1_info(b);
   /******************* section 2 (Optional) ******************/
   if ( b->sec1.options & 0x80 )
     {
       b->sec2.length = three_bytes_to_uint32 ( c );
       memcpy ( b->sec2.raw, c, b->sec2.length );
       c += b->sec2.length;
     }
   /******************* section 3 *****************************/
   b->sec3.length = three_bytes_to_uint32 ( c );
   b->sec3.subsets = two_bytes_to_uint32 ( &c[4] );
   if ( c[6] & 0x80 )
     b->sec3.observed = 1;
   else
     b->sec3.observed = 0;
   if ( c[6] & 0x40 )
     b->sec3.compressed = 1;
   else
     b->sec3.compressed = 0;
   // loop of unexpanded descriptors
   for ( ix = 7, ud = 0; ix < b->sec3.length && ud < BUFR_LEN_UNEXPANDED_DESCRIPTOR; ix += 2 )
     {
       two_bytes_to_descriptor ( &b->sec3.unexpanded[ud], &c[ix] );
       if ( b->sec3.unexpanded[ud].f || b->sec3.unexpanded[ud].x || b->sec3.unexpanded[ud].y )
         ud++;
     }
   b->sec3.ndesc = ud;
   memcpy ( b->sec3.raw, c, b->sec3.length );
   c += b->sec3.length;
   /******************* section 4 *****************************/
   b->sec4.length = three_bytes_to_uint32 ( c );
   // we copy 4 byte more without danger because of latest '7777' and to use fastest exctracting bits algorithm
   memcpy ( b->sec4.raw, c, b->sec4.length + 4 );
   b->sec4.bit_offset = 32; // the first bit in byte 4
   free ( ( void * ) bufrx );
   // Now read tables needed for current readed bufr file
   if ( bufr_read_tables ( b, NULL ) )
     {
       return 1;
     }
   return 0;
 }
int get_ecmwf_tablenames (struct bufrdeco * b, const char * bufrtables_dir)
Get the complete pathnames for EMCWF table files needed by a bufr message.
Parameters
bufrtables_dir string with path to bufr file tables dir
b pointer for a struct bufrdeco
In ECMWF library the name of a table file is Kssswwwwwxxxxxyyyzzz.TXT , where
K - type of table, i.e, 'B', 'C', or 'D'
sss - Master table number (zero for WMO meteorological tables)
wwwww - Originating sub-centre
xxxxx - Originating centre
yyy - Version number of master table used
zzz - Version number of local table used
Definition at line 47 of file bufrdeco_read.c.
References bufr_tables::b, bufr_tables::c, bufr_sec1::centre, bufr_tables::d, DEFAULT_BUFRTABLES_DIR1, DEFAULT_BUFRTABLES_DIR2, bufr_sec1::master, bufr_sec1::master_local, bufr_sec1::master_version, bufr_tableb::path, bufr_tablec::path, bufr_tabled::path, bufrdeco::sec1, bufr_sec1::subcentre, and bufrdeco::tables.
Referenced by bufr_read_tables().
 {
   struct stat st;
   char aux[256];
   if ( bufrtables_dir == NULL )
     {
       // try to guess directory
       if ( stat ( DEFAULT_BUFRTABLES_DIR1, &st ) )
         {
           if ( stat ( DEFAULT_BUFRTABLES_DIR2, &st ) )
             {
               return 1;
             }
           else
             {
               if ( S_ISDIR ( st.st_mode ) )
                 {
                   strcpy ( aux,DEFAULT_BUFRTABLES_DIR2 );
                 }
             }
         }
       else
         {
           if ( S_ISDIR ( st.st_mode ) )
             {
               strcpy ( aux,DEFAULT_BUFRTABLES_DIR1 );
             }
         }
     }
   else
     {
       strcpy ( aux, bufrtables_dir );
     }
   sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
   sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
   sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
   /* check for table b, if problems then we try alternative */
   if ( stat ( b->tables->b.path, &st ) )
     {
       // here we set originating centre xxxxx to 00000 for WMO tables
       if ( b->sec1.master != 0 ) // case of not WMO tables
         {
           sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
                     b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
                     b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
                     b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
         }
       else
         {
           sprintf ( b->tables->b.path,"%sB000%05d00000%03d%03d.TXT", aux, b->sec1.subcentre,
                     b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->c.path,"%sC000%05d00000%03d%03d.TXT", aux, b->sec1.subcentre,
                     b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->d.path,"%sD000%05d00000%03d%03d.TXT", aux, b->sec1.subcentre,
                     b->sec1.master_version, b->sec1.master_local );
         }
       if ( stat ( b->tables->b.path, &st ) )
         {
           // Another chance. Set local zzz to 000
           if ( b->sec1.master != 0 ) // case of not WMO tables
             {
               sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                         b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
               sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                         b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
               sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                         b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
             }
           else
             {
               sprintf ( b->tables->b.path,"%sB000%05d00000%03d000.TXT", aux, b->sec1.subcentre,
                         b->sec1.master_version );
               sprintf ( b->tables->c.path,"%sC000%05d00000%03d000.TXT", aux, b->sec1.subcentre,
                         b->sec1.master_version );
               sprintf ( b->tables->d.path,"%sD000%05d00000%03d000.TXT", aux, b->sec1.subcentre,
                         b->sec1.master_version );
             }
           if ( stat ( b->tables->b.path, &st ) )
             {
               // Another chance. Set subcentre wwwww to 00000
               if ( b->sec1.master != 0 ) // case of not WMO tables
                 {
                   sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
                   sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
                   sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
                 }
               else
                 {
                   sprintf ( b->tables->b.path,"%sB0000000000000%03d000.TXT", aux, b->sec1.master_version );
                   sprintf ( b->tables->c.path,"%sC0000000000000%03d000.TXT", aux, b->sec1.master_version );
                   sprintf ( b->tables->d.path,"%sD0000000000000%03d000.TXT", aux, b->sec1.master_version );
                 }
             }
         }
     }
   return 0;
 }
Variable Documentation
const char DEFAULT_BUFRTABLES_DIR1[] = "/usr/local/lib/bufrtables/"
These are the default directories where the ECMWF package install bufrtables
Definition at line 29 of file bufrdeco_read.c.
Referenced by get_ecmwf_tablenames().
const char DEFAULT_BUFRTABLES_DIR2[] = "/usr/lib/bufrtables/"
Definition at line 30 of file bufrdeco_read.c.
Referenced by get_ecmwf_tablenames().