bufr2synop: src/libraries/bufr2tac_x06.c File Reference
bufr2tac_x06.c File Reference
decodes the descriptors with X = 06 (Horizontal Position-2)
#include "bufr2tac.h"
Functions
char * latlon_to_MMM (char *target, double lat, double lon)
convert latitude and longitude to a MMM string
int syn_parse_x06 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 06.
int buoy_parse_x06 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 06.
int climat_parse_x06 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 06.
int temp_parse_x06 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Detailed Description
decodes the descriptors with X = 06 (Horizontal Position-2)
Definition in file bufr2tac_x06.c.
Function Documentation
int buoy_parse_x06 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 06.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 126 of file bufr2tac_x06.c.
References bufr2tac_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec0::LoLoLoLoLoLo, bufr2tac_subset_state::lon, bufr_atom_data::mask, bufr2tac_subset_state::mask, buoy_chunks::s0, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LONGITUDE_WEST, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 06 001 . Longitude (High accuracy)
     case 2: // 0 06 002 . Longitude (Coarse accuracy)
       if ( s->val < 0.0 )
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       s->lon = s->val;
       ia = ( int ) ( fabs ( s->val ) * 1000.0 + 0.5 );
       sprintf ( b->s0.LoLoLoLoLoLo, "%06d",ia );
       break;
     default:
       break;
     }
   return 0;
 }
int climat_parse_x06 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 06.
Parameters
c pointer to a struct climat_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 159 of file bufr2tac_x06.c.
References bufr2tac_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::lon, bufr_atom_data::mask, bufr2tac_subset_state::mask, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LONGITUDE_WEST, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_climat().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
     return 0;
   // this is to avoid warning
   if ( c == NULL )
     return 1;
   switch ( s->a->desc.y )
     {
     case 1: // 0 06 001 . Longitude (High accuracy)
     case 2: // 0 06 002 . Longitude (Coarse accuracy)
       if ( s->val < 0.0 )
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       s->lon = s->val;
       break;
     default:
       break;
     }
   return 0;
 }
char* latlon_to_MMM (char * target, double lat, double lon)
convert latitude and longitude to a MMM string
Parameters
lat latitude (degree, N positive)
lon longitude (degree, E positive)
target resulting MMM string
Definition at line 34 of file bufr2tac_x06.c.
Referenced by syn_parse_x05(), syn_parse_x06(), temp_parse_x05(), and temp_parse_x06().
 {
   int col, row, ori = 0;
   if ( lon < 0.0 )
     col = ( int ) ( -lat * 0.1 ) + 1;
   else
     col = 36 - ( int ) ( lat * 0.1 );
   if ( lat >= 80.0 )
     row = 25;
   else if ( lat >=  0.0 )
     row = ( int ) ( lat * 0.1 );
   else
     {
       ori = 299;
       row = ( int ) ( -lat * 0.1 );
     }
   sprintf ( target,"%03d", col + ori + row * 36 );
   return target;
 }
int syn_parse_x06 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 06.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 67 of file bufr2tac_x06.c.
References bufr2tac_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::LaLaLa, bufr2tac_subset_state::lat, latlon_to_MMM(), synop_sec0::LoLoLoLo, bufr2tac_subset_state::lon, bufr_atom_data::mask, bufr2tac_subset_state::mask, synop_sec0::MMM, synop_sec0::Qc, synop_chunks::s0, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, synop_sec0::Ulo, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 06 001 . Longitude (High accuracy)
     case 2: // 0 06 002 . Longitude (Coarse)
       if ( s->val < 0.0 )
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = ( int ) ( fabs ( s->val ) * 10.0 + 0.5 );
       sprintf ( syn->s0.LoLoLoLo, "%04d",ia );
       syn->s0.Ulo[0] = syn->s0.LoLoLoLo[2];
       s->lon = s->val;
       break;
     default:
       break;
     }
   // check if set both LaLaLa and LoLoLoLo to set Qc
   if ( ( syn->s0.Qc[0] == 0 ) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0] )
     {
       if ( s->mask & SUBSET_MASK_LATITUDE_SOUTH )
         {
           if ( s->mask & SUBSET_MASK_LONGITUDE_WEST )
             strcpy ( syn->s0.Qc, "5" );
           else
             strcpy ( syn->s0.Qc, "3" );
         }
       else
         {
           if ( s->mask & SUBSET_MASK_LONGITUDE_WEST )
             strcpy ( syn->s0.Qc, "7" );
           else
             strcpy ( syn->s0.Qc, "1" );
         }
     }
   // check if about MMM
   if ( ( syn->s0.MMM[0] == 0 ) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0] )
     {
       latlon_to_MMM ( syn->s0.MMM, s->lat, s->lon );
     }
   return 0;
 }
int temp_parse_x06 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Definition at line 191 of file bufr2tac_x06.c.
References bufr2tac_subset_state::a, temp_chunks::a, temp_chunks::b, temp_chunks::c, temp_chunks::d, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_raw_point_data::dlon, temp_raw_wind_shear_point::dlon, temp_acd_sec1::LaLaLa, bufr2tac_subset_state::lat, latlon_to_MMM(), temp_acd_sec1::LoLoLoLo, temp_b_sec1::LoLoLoLo, bufr2tac_subset_state::lon, bufr_atom_data::mask, bufr2tac_subset_state::mask, temp_acd_sec1::MMM, temp_b_sec1::MMM, temp_raw_data::n, temp_raw_wind_shear_data::n, temp_acd_sec1::Qc, temp_b_sec1::Qc, bufr2tac_subset_state::r, temp_raw_data::raw, temp_raw_wind_shear_data::raw, bufr2tac_subset_state::rep, temp_a::s1, temp_b::s1, temp_c::s1, temp_d::s1, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, temp_acd_sec1::Ulo, temp_b_sec1::Ulo, bufr2tac_subset_state::val, bufr2tac_subset_state::w, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 06 001 . Longitude (High accuracy)
     case 2: // 0 06 002 . Longitude (Coarse)
       if ( s->val < 0.0 )
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = ( int ) ( fabs ( s->val ) * 10.0 + 0.5 );
       sprintf ( t->a.s1.LoLoLoLo, "%04d",ia );
       sprintf ( t->b.s1.LoLoLoLo, "%04d",ia );
       sprintf ( t->c.s1.LoLoLoLo, "%04d",ia );
       sprintf ( t->d.s1.LoLoLoLo, "%04d",ia );
       t->a.s1.Ulo[0] = t->a.s1.LoLoLoLo[2];
       t->b.s1.Ulo[0] = t->b.s1.LoLoLoLo[2];
       t->c.s1.Ulo[0] = t->c.s1.LoLoLoLo[2];
       t->d.s1.Ulo[0] = t->d.s1.LoLoLoLo[2];
       s->lon = s->val;
       // check if set both LaLaLa and LoLoLoLo to set Qc
       if ( ( t->a.s1.Qc[0] == 0 ) && t->a.s1.LaLaLa[0] && t->a.s1.LoLoLoLo[0] )
         {
           if ( s->mask & SUBSET_MASK_LATITUDE_SOUTH )
             {
               if ( s->mask & SUBSET_MASK_LONGITUDE_WEST )
                 strcpy ( t->a.s1.Qc, "5" );
               else
                 strcpy ( t->a.s1.Qc, "3" );
             }
           else
             {
               if ( s->mask & SUBSET_MASK_LONGITUDE_WEST )
                 strcpy ( t->a.s1.Qc, "7" );
               else
                 strcpy ( t->a.s1.Qc, "1" );
             }
           strcpy ( t->b.s1.Qc, t->a.s1.Qc );
           strcpy ( t->c.s1.Qc, t->a.s1.Qc );
           strcpy ( t->d.s1.Qc, t->a.s1.Qc );
         }
       // check if about MMM
       if ( ( t->a.s1.MMM[0] == 0 ) && t->a.s1.LaLaLa[0] && t->a.s1.LoLoLoLo[0] )
         {
           latlon_to_MMM ( t->a.s1.MMM, s->lat, s->lon );
           strcpy ( t->b.s1.MMM, t->a.s1.MMM );
           strcpy ( t->c.s1.MMM, t->a.s1.MMM );
           strcpy ( t->d.s1.MMM, t->a.s1.MMM );
         }
       break;
     case 15: // 0 06 015. Longitude displacement since launch site (high accuracy)
       if ( s->rep > 0 && s->r->n > 0 )
         {
           s->r->raw[s->r->n - 1].dlon = s->val;
         }
       else if ( s->w->n > 0 )
         {
           s->w->raw[s->w->n - 1].dlon = s->val;
         }
       break;
     default:
       break;
     }
   return 0;
 }