bufr2synop: src/libraries/bufr2syn_x12.c File Reference
bufr2syn_x12.c File Reference
decodes the descriptors with X = 12
#include "bufr2syn.h"
Functions
char * kelvin_to_snTTT (char *target, double T)
converts a kelvin temperature value into a snTTT string
char * kelvin_to_snTT (char *target, double T)
converts a kelvin temperature value into a snTT string
char * kelvin_to_TT (char *target, double T)
converts a kelvin temperature value into a TT string
char * kelvin_to_TTTT (char *target, double T)
converts a kelvin temperature value into a TTTT string
int syn_parse_x12 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 12.
int buoy_parse_x12 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 12.
Detailed Description
decodes the descriptors with X = 12
Definition in file bufr2syn_x12.c.
Function Documentation
int buoy_parse_x12 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 239 of file bufr2syn_x12.c.
References bufr_subset_state::a, BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, kelvin_to_snTTT(), buoy_chunks::mask, bufr_atom_data::mask, buoy_chunks::s1, buoy_sec1::sn1, buoy_sec1::sn2, buoy_sec1::TdTdTd, buoy_sec1::TTT, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 12 001
     case 4: // 0 12 004
     case 101: // 0 12 101
     case 104: // 0 12 104
       if (b->s1.TTT[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               b->s1.sn1[0] = aux[0];
               strcpy ( b->s1.TTT, aux + 1 );
               b->mask |= BUOY_SEC1;
             }
         }
       break;
     case 3: // 0 12 003
     case 5: // 0 12 006
     case 103: // 0 12 103
     case 106: // 0 12 106
       if (b->s1.TdTdTd[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               b->s1.sn2[0] = aux[0];
               strcpy ( b->s1.TdTdTd, aux + 1 );
               b->mask |= BUOY_SEC1;
             }
         }
       break;
       default:
       break;
     }
   return 0;
 }
char* kelvin_to_snTT (char * target, double T)
converts a kelvin temperature value into a snTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 55 of file bufr2syn_x12.c.
Referenced by syn_parse_x12().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   ic /= 100;
   if ( ic < 0 )
     sprintf ( target, "1%02d", -ic );
   else
     sprintf ( target, "%03d", ic );
   return target;
 }
char* kelvin_to_snTTT (char * target, double T)
converts a kelvin temperature value into a snTTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 32 of file bufr2syn_x12.c.
Referenced by buoy_parse_x12(), buoy_parse_x22(), syn_parse_x12(), and syn_parse_x22().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   if ( ic < 0 )
   {
     sprintf ( target, "1%03d",(-ic + 5)/10 );
   }
   else
   {
     sprintf ( target, "%04d", (ic  + 5)/10);
   }
   return target;
 }
char* kelvin_to_TT (char * target, double T)
converts a kelvin temperature value into a TT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 75 of file bufr2syn_x12.c.
Referenced by syn_parse_x12().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   ic /= 100;
   if ( ic < 0 )
     sprintf ( target, "%02d", 50 - ic );
   else
     sprintf ( target, "%02d", ic );
   return target;
 }
char* kelvin_to_TTTT (char * target, double T)
converts a kelvin temperature value into a TTTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 95 of file bufr2syn_x12.c.
Referenced by buoy_parse_x22().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   if (ic < 0)
     ic = 5000 - ic;
   sprintf ( target, "%04d", ic );
   return target;
 }
int syn_parse_x12 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 119 of file bufr2syn_x12.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, guess_WMO_region(), bufr_subset_state::itval, synop_sec3::jjj, kelvin_to_snTT(), kelvin_to_snTTT(), kelvin_to_TT(), bufr_atom_data::mask, synop_chunks::mask, synop_chunks::s1, synop_chunks::s2, synop_chunks::s3, synop_sec1::sn1, synop_sec1::sn2, synop_sec3::snn, synop_sec3::snx, synop_sec2::sw, SYNOP_SEC1, SYNOP_SEC2, SYNOP_SEC3, synop_sec2::TbTbTb, synop_sec1::TdTdTd, synop_sec3::TnTnTn, synop_sec1::TTT, synop_sec3::TxTxTx, bufr_subset_state::val, synop_sec3::XoXoXoXo, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 12 001
     case 4: // 0 12 004
     case 101: // 0 12 101
     case 104: // 0 12 104
       if (syn->s1.TTT[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s1.sn1[0] = aux[0];
               strcpy ( syn->s1.TTT, aux + 1 );
               syn->mask |= SYNOP_SEC1;
             }
         }
       break;
     case 3: // 0 12 003
     case 5: // 0 12 006
     case 103: // 0 12 103
     case 106: // 0 12 106
       if (syn->s1.TdTdTd[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s1.sn2[0] = aux[0];
               strcpy ( syn->s1.TdTdTd, aux + 1 );
               syn->mask |= SYNOP_SEC1;
             }
         }
       break;
     case 11: // 0 12 011
     case 14: // 0 12 014
     case 21: // 0 12 021
     case 111: // 0 12 115
     case 114: // 0 12 114
     case 116: // 0 12 116
       if (syn->s3.TxTxTx[0] == 0 && (s->itval % (3*3600)) == 0) // only for 3, 6 ... hours
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s3.snx[0] = aux[0];
               strcpy ( syn->s3.TxTxTx, aux + 1 );
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     case 12: // 0 12 012
     case 15: // 0 12 015
     case 22: // 0 12 022
     case 112: // 0 12 115
     case 115: // 0 12 115
     case 117: // 0 12 117
       if (syn->s3.TnTnTn[0] == 0 && (s->itval % (3*3600)) == 0) // only for 3, 6 ... hours
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s3.snn[0] = aux[0];
               strcpy ( syn->s3.TnTnTn, aux + 1 );
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     case 2:
     case 6:
     case 102:
     case 105: // 0 12 105 Wet bulb temperature
       if (syn->s2.TbTbTb[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s2.sw[0] = aux[0];
               strcpy ( syn->s2.TbTbTb, aux + 1 );
               syn->mask |= SYNOP_SEC2;
             }
         }
       break;
     case 113:
       if (strcmp("6", guess_WMO_region(syn)) == 0) // region VI
         {
           if (kelvin_to_snTT ( aux, s->val ))
             {
               strcpy ( syn->s3.jjj, aux);
               syn->mask |= SYNOP_SEC3;
             }
         }
       else if (strcmp("1", guess_WMO_region(syn)) == 0)
         {
           if (kelvin_to_TT ( aux, s->val ))
             {
               syn->s3.XoXoXoXo[0] = aux[0];
               syn->s3.XoXoXoXo[1] = aux[1];
               if (syn->s3.XoXoXoXo[2] == 0)
                 syn->s3.XoXoXoXo[2] = '/';
               if (syn->s3.XoXoXoXo[3] == 0)
                 syn->s3.XoXoXoXo[3] = '/';
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     default:
       break;
     }
   return 0;
 }