bufr2synop: src/apps/bufrtotac_io.c File Reference
bufrtotac_io.c File Reference
file with the i/o code for binary bufrtotac
#include "config.h"
#include "bufrtotac.h"
Macros
#define CONFIG_H
Functions
void print_usage (void)
char * bufrtotac_get_version (char *version, char *build, char *builder, int *version_major, int *version_minor, int *version_patch)
Get strings with version information and build date and time.
void print_version ()
int read_args (int _argc, char *_argv[])
read the arguments from stdio
int bufrdeco_parse_subset_sequence (struct metreport *m, struct bufr2tac_subset_state *st, struct bufrdeco *b, char *err)
char * get_bufrfile_path (char *filename, char *err)
Get bufr file names to parse.
Detailed Description
file with the i/o code for binary bufrtotac
Definition in file bufrtotac_io.c.
Macro Definition Documentation
CONFIG_H
#define CONFIG_H
Definition at line 26 of file bufrtotac_io.c.
Function Documentation
bufrdeco_parse_subset_sequence()
int bufrdeco_parse_subset_sequence (struct metreport * m, struct bufr2tac_subset_state * st, struct bufrdeco * b, char * err)
Definition at line 253 of file bufrtotac_io.c.
{
  size_t i;
  int ksec1[40], res;
  int *kdtlst;
  size_t nlst = ( size_t ) b->sec3.ndesc;
  // memory for kdtlst
  if ( ( kdtlst = ( int * ) calloc ( 1, nlst * sizeof ( int ) ) ) == NULL )
    {
      sprintf ( err, "decobufr_parse_subset_sequence(): cannot alloc memory for kdtlst\n" );
      return 1;
    }
  // sets descriptor as integer according to ECMWF
  for ( i = 0; i < nlst ; i++ )
    {
      descriptor_to_integer ( &kdtlst[i], &b->sec3.unexpanded[i] );
    }
  // And now set only used ksec1 elements
  ksec1[5] = b->sec1.category;
  ksec1[6] = b->sec1.subcategory_local;
  // Finaly we call to bufr2tac library
  memset ( m, 0, sizeof ( struct metreport ) );
  m->h = &b->header;
  res = parse_subset_sequence ( m, &b->seq, st, kdtlst, nlst, ksec1, err );
  free ( ( void * ) kdtlst );
  return res;
}
References bufr_sec1::category, descriptor_to_integer(), metreport::h, bufrdeco::header, bufr_sec3::ndesc, parse_subset_sequence(), bufrdeco::sec1, bufrdeco::sec3, bufrdeco::seq, bufr_sec1::subcategory_local, and bufr_sec3::unexpanded.
Referenced by main().
bufrtotac_get_version()
char * bufrtotac_get_version (char * version, char * build, char * builder, int * version_major, int * version_minor, int * version_patch)
Get strings with version information and build date and time.
Parameters
version pointer to string with version as result if not NULL
build pointer to string with compiler and compilation date and time if not NULL
builder pointer to string with builder utility. 'cmake' or 'autotools' if not NULL
version_major pointer to string with version_major component if not NULL
version_minor pointer to string with version_minor component if not NULL
version_patch pointer to string with version_patch component if not NULL
Retuns string pointer version.
Definition at line 68 of file bufrtotac_io.c.
{
  int major = 0, minor = 0, patch = 0;
  char *c;
  if (version == NULL)
    return NULL;
  sprintf(version, "%s", VERSION);
  // default values
  sscanf(version, "%d.%d.%d", &major, &minor, &patch);
  if (build)
    {
       c = build;
#if defined(__INTEL_COMPILER)
       c += sprintf(build, "using INTEL C compiler icc %d.%d ", __INTEL_COMPILER, __INTEL_COMPILER_UPDATE);
#elif defined(__GNUC__)
       c += sprintf(build, "using GNU C compiler gcc %d.%d.%d ", __GNUC__ , __GNUC_MINOR__ , __GNUC_PATCHLEVEL__);
#endif
       sprintf(c,"at %s %s",__DATE__,__TIME__);
    }
  if (builder)
#ifdef BUILD_USING_CMAKE
    strcpy(builder, "cmake");
#else
    strcpy(builder, "autotools");
#endif
  if (version_major)
    *version_major = major;
  if (version_minor)
    *version_minor = minor;
  if (version_patch)
    *version_patch = patch;
  return version;
}
References VERSION.
Referenced by print_version().
get_bufrfile_path()
char * get_bufrfile_path (char * filename, char * err)
Get bufr file names to parse.
Parameters
filename string where the file is on output
err string where to set the error if any
If success, it returns a pointer to filename. If there is no more files to parse, or error returns NULL.
This routine is also opens the file with file list and close it when no more file available in list
The content format in LISTOFFILES is compatible with 'ls -1'. Example assume we want to parse all *.bufr files in current directory, we can do
ls -1 *.bufr > list_file && bufrtotac -I list_file
Definition at line 305 of file bufrtotac_io.c.
{
  char aux[256], *c;
  if ( LISTOFFILES[0] == 0 )
    {
      if ( NFILES == 0 )
        {
          if ( filename != INPUTFILE )
            strcpy ( filename, INPUTFILE );
          return filename;
        }
      else
        return 0;
    }
  else if ( NFILES == 0 )
    {
      if ( ( FL = fopen ( LISTOFFILES,"r" ) ) == NULL )
        {
          sprintf ( err,"Cannot open '%s'", LISTOFFILES );
          return NULL;
        }
    }
  if ( fgets ( aux, 256, FL ) )
    {
      c =  strrchr ( aux,'\n' );
      if ( c )
        *c = 0;
      strcpy ( filename, aux );
      return filename;
    }
  else
    {
      fclose ( FL );
      return NULL;
    }
}
References FL, INPUTFILE, LISTOFFILES, and NFILES.
Referenced by main().
print_usage()
void print_usage (void)
Definition at line 31 of file bufrtotac_io.c.
{
  print_version ();
  printf ( "\nUsage: \n" );
  printf ( "%s -i input_file [-i input] [-I list_of_files] [-t bufrtable_dir] [-o output] [-s] [-v][-j][-x][-X][-c][-h]\n" , SELF );
  printf ( "       -c. The output is in csv format\n" );
  printf ( "       -D. Print some debug info\n" );
#ifdef USE_BUFRDC
  printf ( "       -E. Use ECMWF package tables. Default is WMO csv tables\n" );
#endif
  printf ( "       -h Print this help\n" );
  printf ( "       -i Input file. Complete input path file for bufr file\n" );
  printf ( "       -I list_of_files. Pathname of a file with the list of files to parse, one filename per line\n" );
  printf ( "       -j. The output is in json format\n" );
  printf ( "       -n. Do not try to decode to TAC, just parse BUFR report\n" );
  printf ( "       -o output. Pathname of output file. Default is standar output\n" );
  printf ( "       -s prints a long output with explained sequence of descriptors\n" );
  printf ( "       -S first..last . Print only results for subsets in range first..last (First subset available is 0). Default is all subsets\n" );
  printf ( "       -t bufrtable_dir. Pathname of bufr tables directory. Ended with '/'\n" );
  printf ( "       -V. Verbose output\n" );
  printf ( "       -v. Print version\n" );
  printf ( "       -x. The output is in xml format\n" );
  printf ( "       -X. Try to extract an embebed bufr in a file seraching for a first '7777' after first 'BUFR'\n");
}
References print_version(), and SELF.
Referenced by read_args().
print_version()
void print_version (void)
Definition at line 105 of file bufrtotac_io.c.
{
   char version[16], build[128], builder[32];
   bufrtotac_get_version(version, build, builder, NULL, NULL, NULL);
   printf ("%s: Version '%s' built %s and %s.\n" , SELF, VERSION, build, builder);
   bufr2tac_get_version(version, build, builder, NULL, NULL, NULL);
   printf ("Linked to bufr2tac library version '%s' built %s and %s.\n", version, build, builder);
   bufrdeco_get_version(version, build, builder, NULL, NULL, NULL);
   printf ("Linked to bufrdeco library version '%s' built %s and %s.\n", version, build, builder);
}
References bufr2tac_get_version(), bufrdeco_get_version(), bufrnoaa_get_version(), bufrtotac_get_version(), OWN, SELF, and VERSION.
Referenced by print_usage(), and read_args().
read_args()
int read_args (int _argc, char * _argv[])
read the arguments from stdio
Parameters
_argc number of arguments passed
_argv array of arguments
Returns 1 if succcess, -1 othewise
Definition at line 126 of file bufrtotac_io.c.
{
  int iopt;
  char *c;
  char aux[128];
  // Initial and default values
  INPUTFILE[0] = '\0';
  OUTPUTFILE[0] = '\0';
  LISTOFFILES[0] = '\0';
  BUFRTABLES_DIR[0] = '\0';
  VERBOSE = 0;
  SHOW_SEQUENCE = 0;
  DEBUG = 0;
  NFILES = 0;
  XML = 0;
  JSON = 0;
  CSV= 0;
  EXTRACT = 0;
  ECMWF = 0;
  HTML = 0;
  NOTAC = 0;
  FIRST_SUBSET = 0;
  LAST_SUBSET = BUFR_LEN;
  /*
     Read input options
  */
  while ( ( iopt = getopt ( _argc, _argv, "cDEhi:jHI:no:S:st:vVxX" ) ) !=-1 )
    switch ( iopt )
      {
      case 'i':
        if ( strlen ( optarg ) < 256 )
          strcpy ( INPUTFILE, optarg );
        break;
      case 'j':
        JSON = 1;
        break;
      case 'I':
        if ( strlen ( optarg ) < 256 )
          strcpy ( LISTOFFILES, optarg );
        break;
      case 'n':
        NOTAC = 1;
        break;
      case 'o':
        if ( strlen ( optarg ) < 256 )
          strcpy ( OUTPUTFILE, optarg );
        break;
      case 't':
        if ( strlen ( optarg ) < 256 )
          {
            strcpy ( BUFRTABLES_DIR, optarg );
          }
        break;
      case 'D':
        DEBUG = 1;
        break;
      case 'E':
#ifdef USE_BUFRDC
        ECMWF = 1;
#endif
        break;
      case 'H':
        HTML = 1;
        break;
      case 'V':
        VERBOSE = 1;
        break;
      case 'v':
        print_version();
        exit ( EXIT_SUCCESS );
        break;
      case 's':
        SHOW_SEQUENCE = 1;
        break;
      case 'S':
        // Process subset sequence to show
        if ( strlen ( optarg ) < 128 &&
             strspn ( optarg, "0123456789." ) == strlen ( optarg ) )
          {
            if ( strstr ( optarg, ".." ) != NULL )
              {
                strcpy ( aux, optarg );
                c = strstr ( aux, ".." );
                if ( strlen ( c ) > 2 )
                  {
                    LAST_SUBSET = atoi ( c + 2 );
                  }
                *c = '\0';
                if ( aux[0] )
                  {
                    FIRST_SUBSET = atoi ( aux );
                  }
              }
            else
              {
                FIRST_SUBSET = atoi ( optarg );
                LAST_SUBSET = FIRST_SUBSET;
              }
          }
        break;
      case 'x':
        XML = 1;
        break;
      case 'c':
        CSV = 1;
        break;
      case 'X':
        EXTRACT = 1;
        break;
      case 'h':
      default:
        print_usage();
        exit ( EXIT_SUCCESS );
      }
  if ( INPUTFILE[0] == 0 && LISTOFFILES[0] == 0 )
    {
      printf ( "read_args(): It is needed an input file. Use -i or -I option\n" );
      print_usage();
      return -1;
    }
  return 1;
}
References BUFR_LEN, BUFRTABLES_DIR, CSV, DEBUG, ECMWF, EXTRACT, FIRST_SUBSET, HTML, INPUTFILE, JSON, LAST_SUBSET, LISTOFFILES, NFILES, NOTAC, OUTPUTFILE, print_usage(), print_version(), SHOW_SEQUENCE, VERBOSE, and XML.