bufr2synop: src/bufrdeco/bufrdeco_json.c File Reference
bufrdeco_json.c File Reference
This file has the code which functions to print BUFR data in json format.
#include "bufrdeco.h"
Functions
buf_t bufrdeco_print_json_scape_string_cvals (FILE *out, char *source)
prints a descriptor string value scaping the '"' for a json format
buf_t bufrdeco_print_json_subset_data_prologue (FILE *out, struct bufrdeco *b)
buf_t bufrdeco_print_json_subset_data_epilogue (FILE *out)
buf_t bufrdeco_print_json_sequence_descriptor_header (FILE *out, struct bufr_sequence *seq)
Print the header of a sequence descriptor (f == 3)
buf_t bufrdeco_print_json_sequence_descriptor_final (FILE *out)
buf_t bufrdeco_print_json_object_atom_data (FILE *out, struct bufr_atom_data *a, char *add)
Print an json object with a descriptor data.
buf_t bufrdeco_print_json_object_operator_descriptor (FILE *out, struct bufr_descriptor *d, char *add)
print an operator desciptor as a json object
buf_t bufrdeco_print_json_object_replicator_descriptor (FILE *out, struct bufr_descriptor *d, char *add)
print an operator desciptor as a json object
buf_t bufrdeco_print_json_separator (FILE *out)
Print the comma ',' separator in an output.
buf_t bufrdeco_print_json_sec0 (FILE *out, struct bufrdeco *b)
buf_t bufrdeco_print_json_sec1 (FILE *out, struct bufrdeco *b)
Print info form sec 1 in json format.
buf_t bufrdeco_print_json_sec2 (FILE *out, struct bufrdeco *b)
Print info form optional sec 2 in json format.
buf_t bufrdeco_print_json_sec3 (FILE *out, struct bufrdeco *b)
Print info form sec 3 in json format.
buf_t bufrdeco_print_json_tree_recursive (FILE *out, struct bufrdeco *b, struct bufr_sequence *seq)
Print a tree of descriptors to a file in a recursive way in json format.
buf_t bufrdeco_print_json_tree (struct bufrdeco *b)
Detailed Description
This file has the code which functions to print BUFR data in json format.
Definition in file bufrdeco_json.c.
Function Documentation
bufrdeco_print_json_object_atom_data()
buf_t bufrdeco_print_json_object_atom_data (FILE * out, struct bufr_atom_data * a, char * add)
Print an json object with a descriptor data.
Parameters
out output stream opened by caller
a pointer to target struct bufr_atom_data
add adtional optional info
Returns
The amount of bytes sent to out
There are four cases of objects, depending of data type { "descriptor":"f xx yyy", "name":"name_of_descriptor" , "unit":"name_of_unit", "value":"string_value"} { "descriptor":"f xx yyy", "name":"name_of_descriptor" , "unit":"Code table", "value":"numeric_value", "meaning":"explanation_string} { "descriptor":"f xx yyy", "name":"name_of_descriptor" , "unit":"Flag value", "value":"numeric_value", "meaning":"explanation_string} { "descriptor":"f xx yyy", "name":"name_of_descriptor" , "unit":"name_of_unit", "value":"numeric_value"}
Definition at line 134 of file bufrdeco_json.c.
{
  char aux[256];
  buf_t used = 0;
  used += fprintf ( out,  "{\"Descriptor\":\"%u %02u %03u\",\"Name\":\"%s\",", a->desc.f, a->desc.x, a->desc.y, bufr_adjust_string ( a->name ) );
  // add aditional info keys
  if ( add != NULL && add[0] )
    used += fprintf ( out, "%s,", add );
  if ( a->mask & DESCRIPTOR_HAVE_STRING_VALUE )
    {
      // string data case
      if ( a->mask & DESCRIPTOR_VALUE_MISSING )
        used += fprintf ( out, "\"Unit\":\"CCITT5\",\"Value\":\"MISSING\"}" ) ;
      else
        {
          used += fprintf ( out, "\"Unit\":\"CCITT5\",\"Value\":\"" ) ;
          used += bufrdeco_print_json_scape_string_cvals ( out, a->cval );
          used += fprintf ( out, "\"}" );
        }
    }
  else if ( a->mask & DESCRIPTOR_IS_CODE_TABLE )
    {
      // code table case
      if ( a->mask & DESCRIPTOR_VALUE_MISSING )
        used += fprintf ( out, "\"Unit\":\"Code table\",\"Value\":\"MISSING\"}" ) ;
      else
        {
          used += fprintf ( out, "\"Unit\":\"Code table\",\"Value\":%u,", ( uint32_t ) ( a->val + 0.5 ) ) ;
          used += fprintf ( out, "\"Meaning\":\"%s\"}", bufr_adjust_string ( a->ctable ) );
        }
    }
  else if ( a->mask & DESCRIPTOR_IS_FLAG_TABLE )
    {
      // flag table case
      if ( a->mask & DESCRIPTOR_VALUE_MISSING )
        used += fprintf ( out, "\"Unit\":\"Flag table\",\"Value\":\"MISSING\"}" ) ;
      else
        {
          used += fprintf ( out, "\"Unit\":\"Flag table\",\"Value\":\"0x%08X\",", ( uint32_t ) ( a->val ) ) ;
          used += fprintf ( out, "\"Meaning\":\"%s\"}", bufr_adjust_string ( a->ctable ) );
        }
    }
  else
    {
      // numeric data case
      if ( a->mask & DESCRIPTOR_VALUE_MISSING )
        used += fprintf ( out, "\"Unit\":\"%s\",\"Value\":\"MISSING\"}", a->unit ) ;
      else
        {
          used += fprintf ( out, "\"Unit\":\"%s\",\"Value\":%s}", a->unit,
                            get_formatted_value_from_escale2 ( aux, sizeof ( aux ), a->escale, a->val ) );
        }
    }
  return used;
}
References bufr_adjust_string(), bufrdeco_print_json_scape_string_cvals(), bufr_atom_data::ctable, bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_HAVE_STRING_VALUE, DESCRIPTOR_IS_CODE_TABLE, DESCRIPTOR_IS_FLAG_TABLE, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::escale, bufr_descriptor::f, get_formatted_value_from_escale2(), bufr_atom_data::mask, bufr_atom_data::name, bufr_atom_data::unit, bufr_atom_data::val, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufr_decode_subset_data_compressed(), bufrdeco_decode_replicated_subsequence(), bufrdeco_decode_subset_data_recursive(), and bufrdeco_parse_f2_descriptor().
bufrdeco_print_json_object_operator_descriptor()
buf_t bufrdeco_print_json_object_operator_descriptor (FILE * out, struct bufr_descriptor * d, char * add)
print an operator desciptor as a json object
Parameters
out output stream opened by caller
d pointer to operator descriptor
add adtional optional info
Returns
The amount of bytes sent to out
Definition at line 203 of file bufrdeco_json.c.
{
  buf_t used = 0;
  char explanation[256];
  if ( d->f == 2 )
    {
      // only prints if f == 2
      used += fprintf ( out, "{\"Descriptor\":\"%u %02u %03u\",", d->f, d->x, d->y );
      // add aditional info keys
      if ( add != NULL && add[0] )
        used += fprintf ( out, "%s,", add );
      used += fprintf ( out, "\"Operator\": \"%s\"}", bufrdeco_get_f2_descriptor_explanation ( explanation, sizeof ( explanation ), d ) );
    }
  return used;
}
References bufrdeco_get_f2_descriptor_explanation(), bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufr_decode_subset_data_compressed(), bufrdeco_decode_replicated_subsequence(), and bufrdeco_decode_subset_data_recursive().
bufrdeco_print_json_object_replicator_descriptor()
buf_t bufrdeco_print_json_object_replicator_descriptor (FILE * out, struct bufr_descriptor * d, char * add)
print an operator desciptor as a json object
Parameters
out string where to print
d pointer to operator descriptor
add additional info
Returns
The amount of bytes sent to out
Definition at line 230 of file bufrdeco_json.c.
{
  buf_t used = 0;
  if ( d->f == 1 )
    {
      used += fprintf ( out, "{\"Descriptor\":\"%u %02u %03u\",", d->f, d->x, d->y );
      // add aditional info keys
      if ( add != NULL && add[0] )
        used += fprintf ( out, "%s,", add );
      if ( d->y == 0 )
        {
          if ( d->x == 1 )
            used += fprintf ( out, "\"Replicator\":\"Replicator for %d descriptor after next delayed descriptor which set the number of replications.\"}", d->x );
          else
            used += fprintf ( out, "\"Replicator\":\"Replicator for %d descriptors after next delayed descriptor which set the number of replications.\"}", d->x );
        }
      else
        {
          if ( d->x == 1 )
            used += fprintf ( out, "\"Replicator\":\"Replicator for next descriptor %d times.\"}", d->y );
          else
            used += fprintf ( out, "\"Replicator\":\"Replicator for next %d descriptors %d times\"}", d->x, d->y );
        }
    }
  return used;
}
References bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufr_decode_subset_data_compressed(), bufrdeco_decode_replicated_subsequence(), and bufrdeco_decode_subset_data_recursive().
bufrdeco_print_json_scape_string_cvals()
buf_t bufrdeco_print_json_scape_string_cvals (FILE * out, char * source)
prints a descriptor string value scaping the '"' for a json format
Parameters
out output stream
source source string
Returns
The amount of bytes sent to out
Definition at line 33 of file bufrdeco_json.c.
{
  buf_t i = 0, used = 0;
  while ( source[i] )
    {
      switch ( source[i] )
        {
        case '"':
          used += fprintf ( out, "%c%c", '\\', source[i++] );
          break;
        default:
          used += fprintf ( out, "%c", source[i++] );
          break;
        }
    }
  return used;
}
Referenced by bufrdeco_print_json_object_atom_data().
bufrdeco_print_json_sec0()
buf_t bufrdeco_print_json_sec0 (FILE * out, struct bufrdeco * b)
Definition at line 280 of file bufrdeco_json.c.
{
  size_t used = 0;
  bufrdeco_assert ( b != NULL );
  used += fprintf ( out, "{\"Sec 0\":{" );
  used += fprintf ( out, "\"Bufr length\":%u,", b->sec0.bufr_length );
  used += fprintf ( out, "\"Bufr edition\":%u}}", b->sec0.edition );
  return used;
}
References bufr_sec0::bufr_length, bufrdeco_assert, bufr_sec0::edition, and bufrdeco::sec0.
Referenced by bufrdeco_read_buffer().
bufrdeco_print_json_sec1()
buf_t bufrdeco_print_json_sec1 (FILE * out, struct bufrdeco * b)
Print info form sec 1 in json format.
Parameters
out string where to print
b actuve struct bufrdeco
Returns
The amount of bytes sent to out
Definition at line 300 of file bufrdeco_json.c.
{
  size_t used = 0;
  bufrdeco_assert ( b != NULL );
  used += fprintf ( out, "{\"Sec 1\":{" );
  used += fprintf ( out, "\"Length\":%u", b->sec1.length );
  used += fprintf ( out, ",\"Bufr master table\":%u", b->sec1.master );
  used += fprintf ( out, ",\"Centre\":%u", b->sec1.centre );
  used += fprintf ( out, ",\"Sub-Centre\":%u", b->sec1.subcentre );
  used += fprintf ( out, ",\"Update sequence\":%u", b->sec1.update );
  used += fprintf ( out, ",\"Options\":\"0x%x\"", b->sec1.options );
  used += fprintf ( out, ",\"Category\":%u", b->sec1.category );
  used += fprintf ( out, ",\"Subcategory\":%u", b->sec1.subcategory );
  used += fprintf ( out, ",\"Sub-category local\":%u", b->sec1.subcategory_local );
  used += fprintf ( out, ",\"Master table version\":%u", b->sec1.master_version );
  used += fprintf ( out, ",\"Master table local\":%u", b->sec1.master_local );
  used += fprintf ( out, ",\"Year\":%u", b->sec1.year );
  used += fprintf ( out, ",\"Month\":%u", b->sec1.month );
  used += fprintf ( out, ",\"Day\":%u", b->sec1.day );
  used += fprintf ( out, ",\"Hour\":%u", b->sec1.hour );
  used += fprintf ( out, ",\"Minute\":%u", b->sec1.minute );
  used += fprintf ( out, ",\"Second\":%u", b->sec1.second );
  if ( b->sec0.edition == 3 )
    used += fprintf ( out, ",\"Aditional space\":%u", b->sec1.length - 17 );
  else
    used += fprintf ( out, ",\"Aditional space\":%u", b->sec1.length - 22 );
  used += fprintf ( out, "}" );
  if ( b->tables->b.path[0] )
    {
      used += fprintf ( out, ",{\"Used tables\":{" );
      used += fprintf ( out, ",\"TableB file\":\"%s\"", b->tables->b.path );
      used += fprintf ( out, ",\"tableC file\":\"%s\"", b->tables->c.path );
      used += fprintf ( out, ",\"tableD file\":\"%s\"", b->tables->d.path );
      used += fprintf ( out, "}" );
    }
  used += fprintf ( out, "}" );
  return used;
}
References bufr_tables::b, bufrdeco_assert, bufr_tables::c, bufr_sec1::category, bufr_sec1::centre, bufr_tables::d, bufr_sec1::day, bufr_sec0::edition, bufr_sec1::hour, bufr_sec1::length, bufr_sec1::master, bufr_sec1::master_local, bufr_sec1::master_version, bufr_sec1::minute, bufr_sec1::month, bufr_sec1::options, bufr_tableB::path, bufr_tableC::path, bufr_tableD::path, bufrdeco::sec0, bufrdeco::sec1, bufr_sec1::second, bufr_sec1::subcategory, bufr_sec1::subcategory_local, bufr_sec1::subcentre, bufrdeco::tables, bufr_sec1::update, and bufr_sec1::year.
Referenced by bufrdeco_read_buffer().
bufrdeco_print_json_sec2()
buf_t bufrdeco_print_json_sec2 (FILE * out, struct bufrdeco * b)
Print info form optional sec 2 in json format.
Parameters
out string where to print
b actuve struct bufrdeco
Returns
The amount of bytes sent to out
Definition at line 350 of file bufrdeco_json.c.
{
  size_t used = 0;
  bufrdeco_assert ( b != NULL );
  used += fprintf ( out, "{\"Sec 2\":{" );
  if ( b->sec1.options & 0x80 )
    used += fprintf ( out, "\"Length\":%u}}", b->sec2.length );
  else
    used += fprintf ( out, "\"Length\":0}}" );
  return used;
}
References bufrdeco_assert, bufr_sec2::length, bufr_sec1::options, bufrdeco::sec1, and bufrdeco::sec2.
Referenced by bufrdeco_read_buffer().
bufrdeco_print_json_sec3()
buf_t bufrdeco_print_json_sec3 (FILE * out, struct bufrdeco * b)
Print info form sec 3 in json format.
Parameters
out string where to print
b actuve struct bufrdeco
Returns
The amount of bytes sent to out
Definition at line 372 of file bufrdeco_json.c.
{
  buf_t used = 0, i;
  bufrdeco_assert ( b != NULL );
  used += fprintf ( out, "{\"Sec 3\":{" );
  used += fprintf ( out, "\"Sec3 length\":%u", b->sec3.length );
  used += fprintf ( out, ",\"Subsets\":%u", b->sec3.subsets );
  used += fprintf ( out, ",\"Observed\":%u", b->sec3.observed );
  used += fprintf ( out, ",\"Compressed\":%u", b->sec3.compressed );
  used += fprintf ( out, ",\"Unexpanded descriptors\":%u", b->sec3.ndesc );
  used += fprintf ( out, ",\"Unexpanded array\":" );
  used += fprintf ( out,"[" );
  for ( i = 0; i < b->sec3.ndesc; i++ )
    {
      if ( i )
        used += fprintf ( out,"," );
      used += fprintf ( out, "{\"%u\":\"%u %02u %03u\"}", i, b->sec3.unexpanded[i].f, b->sec3.unexpanded[i].x, b->sec3.unexpanded[i].y );
    }
  used += fprintf ( out,"]}}" );
  return used;
}
References bufrdeco_assert, bufr_sec3::compressed, bufr_descriptor::f, bufr_sec3::length, bufr_sec3::ndesc, bufr_sec3::observed, bufrdeco::sec3, bufr_sec3::subsets, bufr_sec3::unexpanded, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufrdeco_read_buffer().
bufrdeco_print_json_separator()
buf_t bufrdeco_print_json_separator (FILE * out)
Print the comma ',' separator in an output.
Parameters
out string where to print
Returns
The amount of bytes sent to out
Definition at line 267 of file bufrdeco_json.c.
{
  return fprintf ( out, "," );
}
Referenced by bufr_decode_subset_data_compressed(), bufrdeco_decode_replicated_subsequence(), bufrdeco_decode_subset_data_recursive(), and bufrdeco_parse_f2_descriptor().
bufrdeco_print_json_sequence_descriptor_final()
buf_t bufrdeco_print_json_sequence_descriptor_final (FILE * out)
Definition at line 110 of file bufrdeco_json.c.
{
  buf_t used = 0;
  // print final
  used += fprintf ( out,  "]}" );
  return used;
}
Referenced by bufr_decode_subset_data_compressed(), and bufrdeco_decode_subset_data_recursive().
bufrdeco_print_json_sequence_descriptor_header()
buf_t bufrdeco_print_json_sequence_descriptor_header (FILE * out, struct bufr_sequence * seq)
Print the header of a sequence descriptor (f == 3)
Parameters
out output stream opened by caller
seq pointer to a bufr_sequence bufr_sequence
Returns
The amount of bytes sent to out
Definition at line 94 of file bufrdeco_json.c.
{
  buf_t used = 0;
  used += fprintf ( out, "{\"Descriptor\":\"%c %c%c %c%c%c\",", seq->key[0], seq->key[1], seq->key[2], seq->key[3], seq->key[4], seq->key[5] );
  used += fprintf ( out, "\"Sequence description\":\"%s\",\"Expanded sequence\":[", seq->name );
  return used;
}
References bufr_sequence::key, and bufr_sequence::name.
Referenced by bufr_decode_subset_data_compressed(), and bufrdeco_decode_subset_data_recursive().
bufrdeco_print_json_subset_data_epilogue()
buf_t bufrdeco_print_json_subset_data_epilogue (FILE * out)
Definition at line 77 of file bufrdeco_json.c.
{
  buf_t used = 0;
  // print prologue
  used += fprintf ( out, "}\n" );
  return used;
}
Referenced by bufr_decode_subset_data_compressed(), and bufrdeco_decode_subset_data_recursive().
bufrdeco_print_json_subset_data_prologue()
buf_t bufrdeco_print_json_subset_data_prologue (FILE * out, struct bufrdeco * b)
Definition at line 58 of file bufrdeco_json.c.
{
  buf_t used = 0;
  bufrdeco_assert ( b != NULL );
  // print prologue
  used += fprintf ( out, "{\"BUFR File\":\"%s\",\"Subset\":%u,\"Decoded data\":",b->header.filename, b->seq.ss );
  return used;
}
References bufrdeco_assert, gts_header::filename, bufrdeco::header, bufrdeco::seq, and bufrdeco_subset_sequence_data::ss.
Referenced by bufr_decode_subset_data_compressed(), and bufrdeco_decode_subset_data_recursive().
bufrdeco_print_json_tree()
buf_t bufrdeco_print_json_tree (struct bufrdeco * b)
Definition at line 508 of file bufrdeco_json.c.
{
  buf_t used = 0;
  bufrdeco_assert ( b != NULL );
  if ( b->mask & BUFRDECO_OUTPUT_JSON_EXPANDED_TREE )
    used += bufrdeco_print_json_tree_recursive ( b->out, b, NULL );
  return used;
};
References bufrdeco_assert, BUFRDECO_OUTPUT_JSON_EXPANDED_TREE, bufrdeco_print_json_tree_recursive(), bufrdeco::mask, and bufrdeco::out.
Referenced by main().
bufrdeco_print_json_tree_recursive()
buf_t bufrdeco_print_json_tree_recursive (FILE * out, struct bufrdeco * b, struct bufr_sequence * seq)
Print a tree of descriptors to a file in a recursive way in json format.
Parameters
out stream opened by caller
b pointer to the basic container struct bufrdeco
seq pointer to the struct bufr_sequence to print
Returns
The amount of bytes sent to out
Definition at line 405 of file bufrdeco_json.c.
{
  buf_t i, k, used = 0;
  struct bufr_sequence *l;
  char explanation[256];
  bufrdeco_assert ( out != NULL && b != NULL );
  if ( seq == NULL )
    {
      l = & ( b->tree->seq[0] );
    }
  else
    {
      l = seq;
    }
  // begins the array
  for ( i = 0; i < l->ndesc; i++ )
    {
      if ( i )
        used += fprintf ( out, "," );
      fprintf ( out,  "{\"%u %02u %03u\"", l->lseq[i].f, l->lseq[i].x,l->lseq[i].y );
      if ( l->lseq[i].f != 3 )
        {
          if ( l->lseq[i].f == 0 )
            {
              if ( bufr_find_tableB_index ( &k, & ( b->tables->b ), l->lseq[i].c ) )
                used += fprintf ( out, "\"Not found in tables\"}" );
              else
                {
                  used += fprintf ( out, ":\"" );
                  if ( l->replicated[i] )
                    {
                      if ( l->replicated[i] )
{
                          if ( l->replicated[i] == 1 )
                            used += fprintf ( out, "Replicated | " );
                          else
                            used += fprintf ( out, "Replicated depth %u | ", l->replicated[i] );
                        }
                    }
                  if ( is_a_delayed_descriptor ( & l->lseq[i] ) ||
                       is_a_short_delayed_descriptor ( & l->lseq[i] ) )
                    used += fprintf ( out, "* %s\"}", b->tables->b.item[k].name );
                  else
                    used += fprintf ( out, "%s\"}", b->tables->b.item[k].name );
                }
            }
          else if ( l->lseq[i].f == 2 )
            {
              used += fprintf ( out, ":\"%s\"}", bufrdeco_get_f2_descriptor_explanation ( explanation, sizeof ( explanation ), & ( l->lseq[i] ) ) );
            }
          else if ( l->lseq[i].f == 1 )
            {
              if ( l->lseq[i].y == 0 )
                {
                  if ( l->lseq[i].x == 1 )
                    used += fprintf ( out, ":\"* Replicator for %d descriptor after next delayed descriptor which set the number of replications.\"}", l->lseq[i].x );
                  else
                    used += fprintf ( out, ":\"* Replicator for %d descriptors after next delayed descriptor which set the number of replications.\"}", l->lseq[i].x );
                }
              else
                {
                  if ( l->lseq[i].x == 1 )
                    used += fprintf ( out, ":\"* Replicator for next descriptor %d times\"}", l->lseq[i].y );
                  else
                    used += fprintf ( out, ":\"* Replicator for next %d descriptors %d times\"}", l->lseq[i].x, l->lseq[i].y );
                }
            }
          else
            used += fprintf ( out, "\n" );
          continue;
        }
      else
        {
          // f == 3
          used += fprintf ( out, ":\"" );
          if ( l->replicated[i] )
            {
              if ( l->replicated[i] == 1 )
                used += fprintf ( out, "Replicated | " );
              else
                used += fprintf ( out, "Replicated depth %u | ", l->replicated[i] );
            }
          used += fprintf ( out, "%s\"", bufr_adjust_string ( l->name ) );
          used += fprintf ( out, ",\"Expanded\":[" );
          // parse de son
          used += bufrdeco_print_json_tree_recursive ( out, b, l->sons[i] );
          used += fprintf ( out, "]}" );
          // we then recursively parse the son
        }
    }
  return used;
}
References bufr_tables::b, bufr_adjust_string(), bufr_find_tableB_index(), bufrdeco_assert, bufrdeco_get_f2_descriptor_explanation(), bufrdeco_print_json_tree_recursive(), bufr_descriptor::c, bufr_descriptor::f, is_a_delayed_descriptor(), is_a_short_delayed_descriptor(), bufr_tableB::item, bufr_sequence::lseq, bufr_sequence::name, bufr_tableB_decoded_item::name, bufr_sequence::ndesc, bufr_sequence::replicated, bufrdeco_expanded_tree::seq, bufr_sequence::sons, bufrdeco::tables, bufrdeco::tree, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufrdeco_print_json_tree(), and bufrdeco_print_json_tree_recursive().