bufr2synop: src/libraries/bufr2tac_mrproper.c File Reference
bufr2tac_mrproper.c File Reference
file with the code to clean and init structures
#include "bufr2tac.h"
Functions
void clean_syn_sec0 (struct synop_sec0 *s)
clean a synop_sec0 struct
void clean_syn_sec1 (struct synop_sec1 *s)
clean a synop_sec1 struct
void clean_syn_sec2 (struct synop_sec2 *s)
clean a synop_sec2 struct
void clean_syn_sec3 (struct synop_sec3 *s)
clean a synop_sec3 struct
void clean_syn_sec4 (struct synop_sec4 *s)
clean a synop_sec4 struct
void clean_syn_sec5 (struct synop_sec5 *s)
clean a synop_sec5 struct
void clean_report_date_ext (struct report_date_ext *s)
clean a synop_ext struct
void clean_wigos_id (struct wigos_id *w)
clean a synop_ext struct
void bufr2tac_clean_synop_chunks (struct synop_chunks *syn)
void clean_buoy_sec0 (struct buoy_sec0 *s)
clean a buoy_sec0 struct
void clean_buoy_sec1 (struct buoy_sec1 *s)
clean a buoy_sec1 struct
void clean_buoy_sec2 (struct buoy_sec2 *s)
clean a buoy_sec2 struct
void clean_buoy_sec3 (struct buoy_sec3 *s)
clean a buoy_sec3 struct
void clean_buoy_sec4 (struct buoy_sec4 *s)
clean a buoy_sec4 struct
void bufr2tac_clean_buoy_chunks (struct buoy_chunks *b)
cleans a buoy_chunks struct
void bufr2tac_clean_temp_chunks (struct temp_chunks *t)
cleans a buoy_chunks struct
void clean_climat_sec0 (struct climat_sec0 *s)
clean a climat_sec0 struct
void clean_climat_sec1 (struct climat_sec1 *s)
clean a climat_sec1 struct
void clean_climat_sec2 (struct climat_sec2 *s)
clean a climat_sec2 struct
void clean_climat_sec3 (struct climat_sec3 *s)
clean a climat_sec3 struct
void clean_climat_sec4 (struct climat_sec4 *s)
clean a climat_sec4 struct
void clean_climat_old (struct climat_old *s)
clean a climat_sec4 struct
void bufr2tac_clean_climat_chunks (struct climat_chunks *c)
cleans a climat_chunks struct
void bufr2tac_clean_metreport (struct metreport *m)
Detailed Description
file with the code to clean and init structures
Definition in file bufr2tac_mrproper.c.
Function Documentation
bufr2tac_clean_buoy_chunks()
void bufr2tac_clean_buoy_chunks (struct buoy_chunks * b)
cleans a buoy_chunks struct
Parameters
b pointer to the struct to clean
Definition at line 178 of file bufr2tac_mrproper.c.
{
  b->mask = 0;
  clean_report_date_ext ( & ( b->e ) );
  clean_wigos_id ( & ( b->wid ) );
  clean_buoy_sec0 ( & ( b->s0 ) );
  clean_buoy_sec1 ( & ( b->s1 ) );
  clean_buoy_sec2 ( & ( b->s2 ) );
  clean_buoy_sec3 ( & ( b->s3 ) );
  clean_buoy_sec4 ( & ( b->s4 ) );
  b->error[0] = '\0';
}
References clean_buoy_sec0(), clean_buoy_sec1(), clean_buoy_sec2(), clean_buoy_sec3(), clean_buoy_sec4(), clean_report_date_ext(), clean_wigos_id(), buoy_chunks::e, buoy_chunks::error, buoy_chunks::mask, buoy_chunks::s0, buoy_chunks::s1, buoy_chunks::s2, buoy_chunks::s3, buoy_chunks::s4, and buoy_chunks::wid.
Referenced by parse_subset_as_buoy().
bufr2tac_clean_climat_chunks()
void bufr2tac_clean_climat_chunks (struct climat_chunks * c)
cleans a climat_chunks struct
Parameters
c pointer to the struct to clean
Definition at line 262 of file bufr2tac_mrproper.c.
{
  c->mask = 0;
  clean_report_date_ext ( & ( c->e ) );
  clean_wigos_id ( & ( c->wid ) );
  clean_climat_sec0 ( & ( c->s0 ) );
  clean_climat_sec1 ( & ( c->s1 ) );
  clean_climat_sec2 ( & ( c->s2 ) );
  clean_climat_sec3 ( & ( c->s3 ) );
  clean_climat_sec4 ( & ( c->s4 ) );
  clean_climat_old ( & ( c->o ) );
  c->error[0] = '\0';
}
References clean_climat_old(), clean_climat_sec0(), clean_climat_sec1(), clean_climat_sec2(), clean_climat_sec3(), clean_climat_sec4(), clean_report_date_ext(), clean_wigos_id(), climat_chunks::e, climat_chunks::error, climat_chunks::mask, climat_chunks::o, climat_chunks::s0, climat_chunks::s1, climat_chunks::s2, climat_chunks::s3, climat_chunks::s4, and climat_chunks::wid.
Referenced by parse_subset_as_climat().
bufr2tac_clean_metreport()
void bufr2tac_clean_metreport (struct metreport * m)
Definition at line 276 of file bufr2tac_mrproper.c.
{
  if (m != NULL)
    memset(m, 0, sizeof (struct metreport));
}
Referenced by bufrtotac_parse_subset_sequence().
bufr2tac_clean_synop_chunks()
void bufr2tac_clean_synop_chunks (struct synop_chunks * syn)
Definition at line 104 of file bufr2tac_mrproper.c.
{
  syn->mask = 0;
  clean_report_date_ext ( & ( syn->e ) );
  clean_wigos_id ( & ( syn->wid ) );
  clean_syn_sec0 ( & ( syn->s0 ) );
  clean_syn_sec1 ( & ( syn->s1 ) );
  clean_syn_sec2 ( & ( syn->s2 ) );
  clean_syn_sec3 ( & ( syn->s3 ) );
  clean_syn_sec5 ( & ( syn->s5 ) );
  // default
  strcpy ( syn->s0.iw,"/" );
  strcpy ( syn->s1.ir,"/" );
  strcpy ( syn->s1.ix,"/" );
  strcpy ( syn->s1.h,"/" );
  strcpy ( syn->s1.VV,"//" );
  strcpy ( syn->s1.N,"/" );
  strcpy ( syn->s1.dd,"//" );
  strcpy ( syn->s1.ff,"//" );
  syn->error[0] = '\0';
}
References clean_report_date_ext(), clean_syn_sec0(), clean_syn_sec1(), clean_syn_sec2(), clean_syn_sec3(), clean_syn_sec5(), clean_wigos_id(), synop_sec1::dd, synop_chunks::e, synop_chunks::error, synop_sec1::ff, synop_sec1::h, synop_sec1::ir, synop_sec0::iw, synop_sec1::ix, synop_chunks::mask, synop_sec1::N, synop_chunks::s0, synop_chunks::s1, synop_chunks::s2, synop_chunks::s3, synop_chunks::s5, synop_sec1::VV, and synop_chunks::wid.
Referenced by parse_subset_as_synop().
bufr2tac_clean_temp_chunks()
void bufr2tac_clean_temp_chunks (struct temp_chunks * t)
cleans a buoy_chunks struct
Parameters
t pointer to the struct to clean
Definition at line 197 of file bufr2tac_mrproper.c.
{
  memset ( t, 0, sizeof ( struct temp_chunks ) );
}
Referenced by parse_subset_as_temp().
clean_buoy_sec0()
void clean_buoy_sec0 (struct buoy_sec0 * s)
clean a buoy_sec0 struct
Parameters
s pointer to the buoy_sec0 struct
Definition at line 132 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct buoy_sec0 ) );
}
Referenced by bufr2tac_clean_buoy_chunks().
clean_buoy_sec1()
void clean_buoy_sec1 (struct buoy_sec1 * s)
clean a buoy_sec1 struct
Parameters
s pointer to the buoy_sec1 struct
Definition at line 141 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct buoy_sec1 ) );
}
Referenced by bufr2tac_clean_buoy_chunks().
clean_buoy_sec2()
void clean_buoy_sec2 (struct buoy_sec2 * s)
clean a buoy_sec2 struct
Parameters
s pointer to the buoy_sec2 struct
Definition at line 150 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct buoy_sec2 ) );
}
Referenced by bufr2tac_clean_buoy_chunks().
clean_buoy_sec3()
void clean_buoy_sec3 (struct buoy_sec3 * s)
clean a buoy_sec3 struct
Parameters
s pointer to the buoy_sec3 struct
Definition at line 159 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct buoy_sec3 ) );
}
Referenced by bufr2tac_clean_buoy_chunks().
clean_buoy_sec4()
void clean_buoy_sec4 (struct buoy_sec4 * s)
clean a buoy_sec4 struct
Parameters
s pointer to the buoy_sec3 struct
Definition at line 168 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct buoy_sec4 ) );
}
Referenced by bufr2tac_clean_buoy_chunks().
clean_climat_old()
void clean_climat_old (struct climat_old * s)
clean a climat_sec4 struct
Parameters
s pointer to the climat_old struct
Definition at line 251 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct climat_old ) );
}
Referenced by bufr2tac_clean_climat_chunks().
clean_climat_sec0()
void clean_climat_sec0 (struct climat_sec0 * s)
clean a climat_sec0 struct
Parameters
s pointer to the climat_sec0 struct
Definition at line 206 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct climat_sec0 ) );
}
Referenced by bufr2tac_clean_climat_chunks().
clean_climat_sec1()
void clean_climat_sec1 (struct climat_sec1 * s)
clean a climat_sec1 struct
Parameters
s pointer to the climat_sec1 struct
Definition at line 215 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct climat_sec1 ) );
}
Referenced by bufr2tac_clean_climat_chunks().
clean_climat_sec2()
void clean_climat_sec2 (struct climat_sec2 * s)
clean a climat_sec2 struct
Parameters
s pointer to the climat_sec2 struct
Definition at line 224 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct climat_sec2 ) );
}
Referenced by bufr2tac_clean_climat_chunks().
clean_climat_sec3()
void clean_climat_sec3 (struct climat_sec3 * s)
clean a climat_sec3 struct
Parameters
s pointer to the climat_sec3 struct
Definition at line 233 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct climat_sec3 ) );
}
Referenced by bufr2tac_clean_climat_chunks().
clean_climat_sec4()
void clean_climat_sec4 (struct climat_sec4 * s)
clean a climat_sec4 struct
Parameters
s pointer to the climat_sec4 struct
Definition at line 242 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct climat_sec4 ) );
}
Referenced by bufr2tac_clean_climat_chunks().
clean_report_date_ext()
void clean_report_date_ext (struct report_date_ext * s)
clean a synop_ext struct
Parameters
s pointer to the synop_ext struct
Definition at line 85 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct report_date_ext ) );
}
Referenced by bufr2tac_clean_buoy_chunks(), bufr2tac_clean_climat_chunks(), and bufr2tac_clean_synop_chunks().
clean_syn_sec0()
void clean_syn_sec0 (struct synop_sec0 * s)
clean a synop_sec0 struct
Parameters
s pointer to the synop_sec0 struct
Definition at line 30 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec0 ) );
}
Referenced by bufr2tac_clean_synop_chunks().
clean_syn_sec1()
void clean_syn_sec1 (struct synop_sec1 * s)
clean a synop_sec1 struct
Parameters
s pointer to the synop_sec1 struct
Definition at line 39 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec1 ) );
}
Referenced by bufr2tac_clean_synop_chunks().
clean_syn_sec2()
void clean_syn_sec2 (struct synop_sec2 * s)
clean a synop_sec2 struct
Parameters
s pointer to the synop_sec2 struct
Definition at line 48 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec2 ) );
}
Referenced by bufr2tac_clean_synop_chunks().
clean_syn_sec3()
void clean_syn_sec3 (struct synop_sec3 * s)
clean a synop_sec3 struct
Parameters
s pointer to the synop_sec3 struct
Definition at line 57 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec3 ) );
}
Referenced by bufr2tac_clean_synop_chunks().
clean_syn_sec4()
void clean_syn_sec4 (struct synop_sec4 * s)
clean a synop_sec4 struct
Parameters
s pointer to the synop_sec4 struct
Definition at line 66 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec4 ) );
}
clean_syn_sec5()
void clean_syn_sec5 (struct synop_sec5 * s)
clean a synop_sec5 struct
Parameters
s pointer to the synop_sec5 struct
Definition at line 75 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec5 ) );
}
Referenced by bufr2tac_clean_synop_chunks().
clean_wigos_id()
void clean_wigos_id (struct wigos_id * w)
clean a synop_ext struct
Parameters
w pointer to the wigos_id struct
Definition at line 94 of file bufr2tac_mrproper.c.
{
  memset ( w, 0, sizeof ( struct wigos_id ) );
}
Referenced by bufr2tac_clean_buoy_chunks(), bufr2tac_clean_climat_chunks(), and bufr2tac_clean_synop_chunks().