bufr2synop: src/libraries/bufr2syn_sqparse.c File Reference
bufr2syn_sqparse.c File Reference
file with the code to parse a sequence of descriptors for a subset
#include "bufr2syn.h"
Functions
int find_descriptor (int *haystack, size_t nlst, int needle)
Try to find a descriptor in an array.
int find_descriptor_interval (int *haystack, size_t nlst, int needlemin, int needlemax)
int parse_subset_sequence (struct metreport *m, struct bufr_subset_sequence_data *sq, struct bufr_subset_state *st, struct synop_chunks *synop, struct buoy_chunks *buoy, int *kdtlst, size_t nlst, int *ksec1, char *err)
Detailed Description
file with the code to parse a sequence of descriptors for a subset
Definition in file bufr2syn_sqparse.c.
Function Documentation
int find_descriptor (int * haystack, size_t nlst, int needle)
Try to find a descriptor in an array.
Parameters
haystack array of integers as descriptors
nlst number of descriptors in array
needle descriptor to find
it returns 1 if found, 0 otherwise.
Definition at line 35 of file bufr2syn_sqparse.c.
Referenced by parse_subset_sequence().
 {
   size_t i = 0;
   while (haystack[i] != needle && i < nlst)
     i++;
   return (i < nlst);
 }
int find_descriptor_interval (int * haystack, size_t nlst, int needlemin, int needlemax)
Definition at line 57 of file bufr2syn_sqparse.c.
Referenced by parse_subset_sequence().
 {
   size_t i = 0;
   while ((haystack[i] > needlemax || haystack[i] < needlemin) && i < nlst)
     i++;
   return (i < nlst);
 }
int parse_subset_sequence (struct metreport * m, struct bufr_subset_sequence_data * sq, struct bufr_subset_state * st, struct synop_chunks * synop, struct buoy_chunks * buoy, int * kdtlst, size_t nlst, int * ksec1, char * err)
Definition at line 76 of file bufr2syn_sqparse.c.
References metreport::alphanum, find_descriptor(), find_descriptor_interval(), parse_subset_as_buoy(), parse_subset_as_synop(), print_buoy(), print_synop(), and bufr_subset_state::type_report.
Referenced by main().
 {
   /* Clean the state */
   memset(st, 0, sizeof(struct bufr_subset_state));
   /* First task to do is figure out the type of report */
   switch (ksec1[5])
     {
     case 0:
       if (find_descriptor_interval(kdtlst, nlst, 307079, 307086) ||
           find_descriptor(kdtlst, nlst,307091) ||
           find_descriptor(kdtlst, nlst,307096) ||
           ksec1[6] == 0 || ksec1[6] == 1 || ksec1[6] == 2)
         strcpy(st->type_report,"AAXX"); // FM-12 synop
       else if (find_descriptor(kdtlst, nlst,307090)
          || ksec1[6] == 3 || ksec1[6] == 4 || ksec1[6] == 5 )
         strcpy(st->type_report,"OOXX"); // FM-14 synop-mobil
       break;
     case 1:
       if (find_descriptor_interval(kdtlst, nlst, 308004, 308005) ||
           find_descriptor(kdtlst, nlst,308009) || find_descriptor(kdtlst, nlst,1011))
         strcpy(st->type_report,"BBXX"); // FM-13 ship
       else if (find_descriptor_interval(kdtlst, nlst, 308001, 308003) ||
         find_descriptor(kdtlst, nlst,1005) ||
         find_descriptor(kdtlst, nlst,2036) ||
         find_descriptor(kdtlst, nlst,2149) ||
         ksec1[6] == 25)
         strcpy(st->type_report,"ZZYY"); // FM-18 buoy
       break;
     case 2:
       if (find_descriptor_interval(kdtlst, nlst, 309050, 309052))
         strcpy(st->type_report,"TTXX"); // FM-13 ship
       break;
     default:
       sprintf(err, "The data category %d is not parsed at the moment", ksec1[5]);
       return 1;
     }
   if (st->type_report[0] == '\0')
   {
     sprintf(err, "Cannot find the report type\n");
     return 1;
   }
   //if(DEBUG)
   //  printf("Going to parse a %s report\n", st->type_report);
   // Parse FM-12, FM-13 and FM-14
   if (strcmp(st->type_report,"AAXX") == 0 || strcmp(st->type_report,"BBXX") == 0 || strcmp(st->type_report,"OOXX") == 0)
   {
     if (parse_subset_as_synop(m, synop, st, sq, err) == 0)
       return print_synop(m->alphanum, 2048, synop);
   }
   else if (strcmp(st->type_report,"ZZYY") == 0)
   {
     if (parse_subset_as_buoy(m, buoy, st, sq, err) == 0)
       return print_buoy(m->alphanum, 2048, buoy);
   }
   // when reached this point we have han error
   return 1;
 }