bufr2synop: src/bufrdeco/bufrdeco_csv.c File Reference
bufrdeco_csv.c File Reference
This file has the code of useful routines for read or write csv formatted lines.
#include "bufrdeco.h"
Macros
#define CSV_WAIT_ITEM 1
#define CSV_FINISHED_ITEM 2
#define CSV_IS_ITEM 4
#define CSV_IS_SEPARATOR 8
#define CSV_IS_CITED 16
#define CSV_WAIT_SEPARATOR 32
#define CSV_IS_DOUBLE_QUOTED 64
Functions
char * csv_quoted_string (char *out, char *in)
Transform a string to a quoted string to be inserted in a csv file.
int parse_csv_line (int *nt, char *tk[], char *lin)
Parse a csv line.
Variables
const char CSV_SPACE [] = " \t\r"
const char CSV_SEPARATOR = ','
const char CSV_CITE = '\"'
const char CSV_FINAL = '\n'
Detailed Description
This file has the code of useful routines for read or write csv formatted lines.
Definition in file bufrdeco_csv.c.
Macro Definition Documentation
#define CSV_FINISHED_ITEM 2
Definition at line 27 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
#define CSV_IS_CITED 16
Definition at line 30 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
#define CSV_IS_DOUBLE_QUOTED 64
Definition at line 32 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
#define CSV_IS_ITEM 4
Definition at line 28 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
#define CSV_IS_SEPARATOR 8
Definition at line 29 of file bufrdeco_csv.c.
#define CSV_WAIT_ITEM 1
Definition at line 26 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
#define CSV_WAIT_SEPARATOR 32
Definition at line 31 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
Function Documentation
char* csv_quoted_string (char * out, char * in)
Transform a string to a quoted string to be inserted in a csv file.
Parameters
out resulting string
in input string
If problem returns NULL
Definition at line 48 of file bufrdeco_csv.c.
References CSV_MAXL.
Referenced by main().
 {
    size_t i = 0, j = 0;
    if ( in[0] == 0)
      return NULL;
    out[j++] = '\"';
    while (in[i] && j < (CSV_MAXL - 1)  && i < CSV_MAXL)
    {
        if (in[i] == '\"')
        {
            out[j++] = '\"';
            out[j++] = '\"';
            i++;
        }
        else
          out[j++] = in[i++];
    }
    out[j++] = '\"';
    out[j] = 0; // end of string
    return out;
 }
int parse_csv_line (int * nt, char * tk[], char * lin)
Parse a csv line.
Parameters
nt pointer to a integer. On success is the number of items found
tk array of pointers. Every pointer is a item on success
lin input line which is modified in this routine to be splitted into items
NOTE that input line is modified On success return 0, otherwise -1
Definition at line 83 of file bufrdeco_csv.c.
References CSV_CITE, CSV_FINAL, CSV_FINISHED_ITEM, CSV_IS_CITED, CSV_IS_DOUBLE_QUOTED, CSV_IS_ITEM, CSV_MAXL, CSV_SEPARATOR, CSV_SPACE, CSV_WAIT_ITEM, and CSV_WAIT_SEPARATOR.
Referenced by bufr_read_tableb_csv(), bufr_read_tablec_csv(), bufr_read_tabled_csv(), and main().
 {
   size_t i, j, k = 0, l, latest_char = 0;
   int flag;
   char c, caux[CSV_MAXL];
   l = strlen ( lin );
   if ( l > CSV_MAXL || l == 0 )
     return -1;
   // copy original string
   strcpy ( caux, lin );
   flag = CSV_WAIT_ITEM;
   for ( i = 0, j = 0, k = 0; i < l; i++ )
     {
       c = caux[i]; // original char
       if ( ( flag & CSV_IS_CITED ) == 0 )
         {
           if ( flag & CSV_WAIT_ITEM )
             {
               if ( strchr ( CSV_SPACE, c ) != NULL )
                 {
                   lin[j++] = c; // copy to target
                   continue;
                 }
               else if ( c == CSV_CITE )
                 {
                   lin[j++] = '\0'; // copy to target
                   flag |= CSV_IS_CITED;
                   continue;
                 }
               else if ( c == CSV_SEPARATOR )
                 {
                   /* item vacio */
                   tk[k++] = lin + j;
                   lin[j++] = '\0';
                   flag = CSV_WAIT_ITEM;
                   continue;
                 }
               else if ( c == CSV_FINAL )
                 {
                   if ( flag & CSV_FINISHED_ITEM )
                     {
                       *nt = k;
                       return 0;
                     }
                   /* al menos un token, vacio */
                   tk[k++] = lin + j;
                   lin[j] = '\0';
                   *nt = k;
                   return 0;
                 }
               else
                 {
                   latest_char = j;
                   tk[k] = lin + j;
                   lin[j++] = c;
                   flag = CSV_IS_ITEM;
                   continue;
                 }
             }
           else if ( flag & CSV_IS_ITEM )
             {
               if ( strchr ( CSV_SPACE, c ) != NULL )
                 {
                   lin[j++] = c;
                   continue;
                 }
               else if ( c == CSV_SEPARATOR )
                 {
                   lin[latest_char + 1] = '\0';
                   j = latest_char + 2;
                   k++;
                   flag = CSV_WAIT_ITEM | CSV_FINISHED_ITEM;
                   continue;
                 }
               else if ( c == CSV_FINAL )
                 {
                   lin[latest_char + 1] = '\0';
                   k++;
                   *nt = k;
                   return 0;
                 }
               else
                 {
                   latest_char = j++;
                 }
             }
           else if ( flag & CSV_WAIT_SEPARATOR )
             {
               if ( c == CSV_SEPARATOR )
                 {
                   lin[j++] = '\0';
                   k++;
                   flag = CSV_WAIT_ITEM;
                 }
               else if ( c == CSV_FINAL )
                 {
                   lin[j++] = '\0';
                   *nt = k + 1;
                   return 0;
                 }
               continue;
             }
         }
       else /* CITED */
         {
           if ( flag & CSV_WAIT_ITEM )
             {
               tk[k] = lin + j;
               flag &= ( ~CSV_WAIT_ITEM ); // Clean wait item bit
             }
           if ( c == CSV_CITE )
             {
               if ( caux[i + 1] == CSV_CITE )
                 {
                   if ( flag & CSV_IS_DOUBLE_QUOTED )
                     {
                       flag &= ( ~CSV_IS_DOUBLE_QUOTED ) ; // Clean double quoted bit
                       lin[j++] = '"';
                       i++;
                     }
                   else
                     {
                       flag |= CSV_IS_DOUBLE_QUOTED;
                       lin[j++] = '"';
                       i++;
                     }
                     continue;
                 }
               else
                 {
                   lin[j++] = '\0';
                   flag = CSV_WAIT_SEPARATOR;
                 }
             }
           else if ( c == CSV_FINAL )
             {
               lin[j++] = '\0';
               *nt = k + 1;
               return 0;
             }
           else
             {
               lin[j++] = c;
             }
           continue;
         }
     }
   return -1;
 }
Variable Documentation
const char CSV_CITE = '\"'
Definition at line 36 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
const char CSV_FINAL = '\n'
Definition at line 37 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
const char CSV_SEPARATOR = ','
Definition at line 35 of file bufrdeco_csv.c.
Referenced by parse_csv_line().
const char CSV_SPACE[] = " \t\r"
Definition at line 34 of file bufrdeco_csv.c.
Referenced by parse_csv_line().