bufr2synop: src/apps/bufrnoaa.h File Reference
bufrnoaa.h File Reference
inclusion file for binary bufrnoaa
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <time.h>
#include <utime.h>
#include <sys/time.h>
#include <sys/stat.h>
Macros
#define BLEN 1024
#define BUFRLEN 8388608
Functions
int is_bufr (unsigned char *b)
checks if an unsigned char from an array is the first char of 'BUFR'
int is_endb (unsigned char *b)
checks if an unsigned char from an array is the first char of '7777'
int is_head (unsigned char *b)
checks if an unsigned char from an array is the first char of '****'
int is_head_custom (unsigned char *b, char mark)
checks if an unsigned char from an array is the first char of repeated mark char four times
int timeval_substract (struct timeval *result, struct timeval *x, struct timeval *y)
Subtract the ‘struct timeval’ values X and Y, storing the result in RESULT.
int read_args (int _argc, char *_argv[])
read the arguments from stdio
void print_usage (void)
void print_version (void)
int bufr_is_selected (char *name)
returns 1 if selected message 0 otherwise
int date_mtime_from_stat (char *date, struct stat *st)
get a string with date and time from a struct stat
int mtime_from_stat (char *filename, struct stat *st)
modifies a file update time from a struct stat
Variables
int STAGE
int SELECT
int INDIVIDUAL
int COLECT
int VERBOSE
int LISTF
unsigned char BUFR [BUFRLEN]
unsigned char BUF [BLEN]
char ENTRADA [256]
char PREFIX [64]
struct stat INSTAT
char SEL [64]
char SELS [64]
char SELO [64]
char SELU [64]
char OWN []
char HEADER_MARK
char FINAL_SEP [4]
char SEP []
Detailed Description
inclusion file for binary bufrnoaa
Definition in file bufrnoaa.h.
Macro Definition Documentation
BLEN
#define BLEN 1024
Definition at line 34 of file bufrnoaa.h.
BUFRLEN
#define BUFRLEN 8388608
Definition at line 36 of file bufrnoaa.h.
Function Documentation
bufr_is_selected()
int bufr_is_selected (char * name)
returns 1 if selected message 0 otherwise
Parameters
name string with name to check
Definition at line 124 of file bufrnoaa_utils.c.
{
  if ( strlen ( SEL ) == 0 )
    return 0;
  if ( strchr ( SEL, name[1] ) == NULL )
    return 0;
  if ( name[1] == 'S' )
    {
      if ( strlen ( SELS ) == 0 )
        return 1;
      else if ( strchr ( SELS, name[2] ) == NULL )
        return 0;
    }
  if ( name[1] == 'O' )
    {
      if ( strlen ( SELO ) == 0 )
        return 1;
      else if ( strchr ( SELO, name[2] ) == NULL )
        return 0;
    }
  if ( name[1] == 'U' )
    {
      if ( strlen ( SELU ) == 0 )
        return 1;
      else if ( strchr ( SELU, name[2] ) == NULL )
        return 0;
    }
  return 1;
}
References SELO, SELS, and SELU.
Referenced by main().
date_mtime_from_stat()
nt date_mtime_from_stat (char * date, struct stat * st)
get a string with date and time from a struct stat
Parameters
date string wuth the result
st pointer to a strucr stat
Definition at line 163 of file bufrnoaa_utils.c.
{
  struct tm tim;
  memset ( &tim, 0, sizeof ( tim ) );
  gmtime_r ( & ( st->st_mtime ), &tim );
  strftime ( date, 16, "%Y%m%d%H%M%S", &tim );
  return 1;
}
Referenced by main().
is_bufr()
int is_bufr (unsigned char * b)
checks if an unsigned char from an array is the first char of 'BUFR'
Parameters
b pointer to unsigned char to check
Returns 1 if success, 0 othewise
Definition at line 33 of file bufrnoaa_utils.c.
{
  if ( b[0] == 'R' && b[1] == 'F' && b[2] == 'U' && b[3] == 'B' )
    return 1;
  return 0;
}
Referenced by main().
is_endb()
int is_endb (unsigned char * b)
checks if an unsigned char from an array is the first char of '7777'
Parameters
b pointer to unsigned char to check
Returns 1 if success, 0 othewise
Definition at line 76 of file bufrnoaa_utils.c.
{
  if ( b[0] == '7' && b[1] == '7' && b[2] == '7' && b[3] == '7' )
    return 1;
  return 0;
}
Referenced by main().
is_head()
int is_head (unsigned char * b)
checks if an unsigned char from an array is the first char of '****'
Parameters
b pointer to unsigned char to check
Returns 1 if success, 0 othewise
Definition at line 47 of file bufrnoaa_utils.c.
{
  if ( b[0] == '*' && b[1] == '*' && b[2] == '*' && b[3] == '*' )
    return 1;
  return 0;
}
is_head_custom()
int is_head_custom (unsigned char * b, char mark)
checks if an unsigned char from an array is the first char of repeated mark char four times
Parameters
b pointer to unsigned char to check
mark char to be found repeated four times since b Returns 1 if success, 0 othewise
Definition at line 61 of file bufrnoaa_utils.c.
{
  if ( b[0] == mark && b[1] == mark && b[2] == mark && b[3] == mark )
    return 1;
  return 0;
}
Referenced by main().
mtime_from_stat()
int mtime_from_stat (char * filename, struct stat * st)
modifies a file update time from a struct stat
Parameters
filename string with the pathname of file to modify
st pointer to a struct stat as reference
Definition at line 178 of file bufrnoaa_utils.c.
{
  struct utimbuf ut;
  ut.modtime = st->st_mtime;
  ut.actime = st->st_mtime;
  utime ( filename, &ut );
  return 1;
}
Referenced by main().
print_usage()
void print_usage (void)
Definition at line 37 of file bufrdeco_json.c.
{
  printf ( "Usage: \n" );
  printf ( "bufrdeco_test -i input_file [-h][more optional args...]\n" );
  printf ( "   -h Print this help\n" );
  printf ( "   -i Input file. Complete input path file for bufr file\n" );
  printf ( "   -J. Information, tree and data in json format. Equivalent to option -E01234\n" );
  printf ( "   -S first..last . Print only results for subsets in range first..last (First subset available is 0). Default is all subsets\n" );
  printf ( "   -T. Print expanded tree in json format\n" );
  printf ( "   -X. Extract first BUFR buffer found in input file (from first 'BUFR' item to next '7777')\n" );
  printf ( "   -0. Prints BUFR Sec 0 information in json format\n" );
  printf ( "   -1. Prints BUFR Sec 1 information in json format\n" );
  printf ( "   -2. Prints BUFR Sec 2 information in json format\n" );
  printf ( "   -3. Prints BUFR Sec 3 information in json format\n" );
  printf ( "   -4. Prints BUFR data in json format\n" );
}
References OWN, PACKAGE_VERSION, print_version(), and SELF.
Referenced by main(), and read_args().
print_version()
void print_version (void)
Definition at line 114 of file bufrnoaa_io.c.
{
   char version[16], build[64], builder[32];
   bufrnoaa_get_version(version, build, builder, NULL, NULL, NULL);
   printf ("%s: Version '%s' built %s and %s.\n" , OWN, VERSION, build, builder);
}
References bufrnoaa_get_version(), OWN, and VERSION.
Referenced by print_usage(), and read_args().
read_args()
int read_args (int _argc, char * _argv[])
read the arguments from stdio
Parameters
_argc number of arguments passed
_argv array of arguments
Returns 1 if succcess, -1 othewise
Definition at line 63 of file bufrdeco_json.c.
{
  int iopt;
  char *c, aux[128];
  // Default values
  EXTRACT = 0;
  PRINT_JSON_SEC0 = 0;
  PRINT_JSON_SEC1 = 0;
  PRINT_JSON_SEC2 = 0;
  PRINT_JSON_SEC3 = 0;
  PRINT_JSON_EXPANDED_TREE = 0;
  /*
     Read input options
  */
  while ( ( iopt = getopt ( _argc, _argv, "hi:JXT01234" ) ) !=-1 )
    switch ( iopt )
      {
      case 'X':
        EXTRACT = 1;
        break;
      case '0':
        PRINT_JSON_SEC0 = 1;
        break;
      case '1':
        PRINT_JSON_SEC1 = 1;
        break;
      case '2':
        PRINT_JSON_SEC2 = 1;
        break;
      case '3':
        PRINT_JSON_SEC3 = 1;
        break;
      case '4':
        PRINT_JSON_SEC4 = 1;
        break;
      case 'T':
        PRINT_JSON_EXPANDED_TREE = 1;
        break;
      case 'J':
        PRINT_JSON_SEC0 = 1;
        PRINT_JSON_SEC1 = 1;
        PRINT_JSON_SEC2 = 1;
        PRINT_JSON_SEC3 = 1;
        PRINT_JSON_SEC4 = 1;
        PRINT_JSON_EXPANDED_TREE = 1;
        break;
      case 'S':
        // Process subset sequence to show
        if ( strlen ( optarg ) < 128 &&
             strspn ( optarg, "0123456789." ) == strlen ( optarg ) )
          {
            if ( strstr ( optarg, ".." ) != NULL )
              {
                strcpy ( aux, optarg );
                c = strstr ( aux, ".." );
                if ( strlen ( c ) > 2 )
                  {
                    LAST_SUBSET = atoi ( c + 2 );
                  }
                *c = '\0';
                if ( aux[0] )
                  {
                    FIRST_SUBSET = atoi ( aux );
                  }
              }
            else
              {
                FIRST_SUBSET = atoi ( optarg );
                LAST_SUBSET = FIRST_SUBSET;
              }
          }
        break;
      case 'i':
        if ( strlen ( optarg ) < 256 )
          strcpy ( ENTRADA, optarg );
        break;
      case 'h':
      default:
        print_usage();
        exit ( EXIT_SUCCESS );
      }
  if ( ENTRADA[0] == '\0' )
    {
      printf ( "read_args(): It is needed an input file. Use -i option\n" );
      return -1;
    }
  return 1;
}
References COLECT, ENTRADA, EXTRACT, FINAL_SEP, FIRST_SUBSET, HEADER_MARK, INDIVIDUAL, LAST_SUBSET, LISTF, OWN, PREFIX, PRINT_JSON_EXPANDED_TREE, PRINT_JSON_SEC0, PRINT_JSON_SEC1, PRINT_JSON_SEC2, PRINT_JSON_SEC3, PRINT_JSON_SEC4, print_usage(), print_version(), SELECT, SELO, SELS, SELU, SEP, and VERBOSE.
Referenced by main().
timeval_substract()
int timeval_substract (struct timeval * result, struct timeval * x, struct timeval * y)
Subtract the ‘struct timeval’ values X and Y, storing the result in RESULT.
Parameters
result pointer to a struct timeval where to set the result
x pointer to struct timeval as X in (X - Y)
y pointer to struct timeval as Y in (X - Y)
Return 1 if the difference is negative, otherwise 0.
Definition at line 93 of file bufrnoaa_utils.c.
{
  /* Perform the carry for the later subtraction by updating Y. */
  if ( x->tv_usec < y->tv_usec )
    {
      int nsec = ( y->tv_usec - x->tv_usec ) / 1000000 + 1;
      y->tv_usec -= 1000000 * nsec;
      y->tv_sec += nsec;
    }
  if ( x->tv_usec - y->tv_usec > 1000000 )
    {
      int nsec = ( x->tv_usec - y->tv_usec ) / 1000000;
      y->tv_usec += 1000000 * nsec;
      y->tv_sec -= nsec;
    }
  /* Compute the time remaining to wait.
     `tv_usec' is certainly positive. */
  result->tv_sec = x->tv_sec - y->tv_sec;
  result->tv_usec = x->tv_usec - y->tv_usec;
  /* Return 1 if result is negative. */
  return x->tv_sec < y->tv_sec;
}
Referenced by main().
Variable Documentation
BUF
unsigned char BUF[BLEN] extern
Definition at line 195 of file bufrnoaa.c.
Referenced by main().
BUFR
unsigned char BUFR[BUFRLEN] extern
Definition at line 25 of file bufrdeco_json.c.
COLECT
int COLECT
Definition at line 38 of file bufrnoaa.h.
ENTRADA
char ENTRADA[256] extern
Definition at line 27 of file bufrdeco_json.c.
Referenced by main(), and read_args().
FINAL_SEP
char FINAL_SEP[4] extern
Definition at line 207 of file bufrnoaa.c.
Referenced by main(), and read_args().
HEADER_MARK
char HEADER_MARK extern
Header mark character who is repeated four times at the begining
Definition at line 202 of file bufrnoaa.c.
Referenced by main(), and read_args().
INDIVIDUAL
int INDIVIDUAL
Definition at line 38 of file bufrnoaa.h.
INSTAT
struct stat INSTAT extern
Definition at line 204 of file bufrnoaa.c.
Referenced by main().
LISTF
int LISTF extern
if != then a list of messages in bin file is generated
Definition at line 193 of file bufrnoaa.c.
Referenced by main(), and read_args().
OWN
char OWN[] extern
Definition at line 205 of file bufrnoaa.c.
Referenced by main(), print_usage(), print_version(), and read_args().
PREFIX
char PREFIX[64]
Definition at line 42 of file bufrnoaa.h.
SEL
char SEL[64] extern
Selection string for argument -T according with T1
Definition at line 197 of file bufrnoaa.c.
SELECT
int SELECT
Definition at line 38 of file bufrnoaa.h.
SELO
char SELO[64]
Definition at line 44 of file bufrnoaa.h.
SELS
char SELS[64]
Definition at line 44 of file bufrnoaa.h.
SELU
char SELU[64]
Definition at line 44 of file bufrnoaa.h.
SEP
char SEP[] extern
Definition at line 206 of file bufrnoaa.c.
Referenced by read_args().
STAGE
int STAGE extern
Definition at line 192 of file bufrnoaa.c.
Referenced by main().
VERBOSE
int VERBOSE
Definition at line 38 of file bufrnoaa.h.