bufr2synop: src/libraries/bufr2tac_x07.c File Reference
bufr2tac_x07.c File Reference
decodes the descriptors with X = 07 (Vertical Position)
#include "bufr2tac.h"
Functions
char * grad_to_ec (char *target, double grad)
Converts elevation in grads to ec (code table 1004)
int syn_parse_x07 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 07.
int buoy_parse_x07 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 07.
int climat_parse_x07 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
int temp_parse_x07 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Detailed Description
decodes the descriptors with X = 07 (Vertical Position)
Definition in file bufr2tac_x07.c.
Function Documentation
buoy_parse_x07()
int buoy_parse_x07 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 07.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 164 of file bufr2tac_x07.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  if ( b == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 62: // 0 07 062 Depth below sea/water surface
    case 63: // 0 07 063 Profundity below sea/water level
      if ( s->k_rep == ( s->i - 1 ) ) // Case of first layer after a replicator
        {
          s->layer = 0;
        }
      else
        {
          ( s->layer ) ++;
        }
      s->deep = ( int ) ( s->val + 0.5 );
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x07()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr2tac_subset_state::deep, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::i, bufr2tac_subset_state::k_rep, bufr2tac_subset_state::layer, bufr_atom_data::mask, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
climat_parse_x07()
int climat_parse_x07 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Definition at line 208 of file bufr2tac_x07.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  // this is to avoid warning
  if ( c == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 07 001 . Heigh of station
    case 30: // 0 07 030 . Height of station ground above msl
    case 31: // 0 07 031 . Height of barometer above msl
      s->alt = s->val;
      break;
    case 32: // 0 07 032 . Pressure of standard level
      // Not a useful value for alphanumeric climat
      if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x07()", "Descriptor not parsed" );
      break;
    case 4: // Pressure of standard level
      // Not a useful value for alphanumeric climat
      if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x07()", "Descriptor not parsed" );
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x07()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, bufr2tac_subset_state::alt, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::mask, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_climat().
grad_to_ec()
char * grad_to_ec (char * target, double grad)
Converts elevation in grads to ec (code table 1004)
Parameters
grad the elevation angle (degrees)
target the resulting code
Definition at line 32 of file bufr2tac_x07.c.
{
  if ( grad < 5.0 )
    strcpy ( target, "9" );
  else if ( grad < 6.5 )
    strcpy ( target, "8" );
  else if ( grad < 8.0 )
    strcpy ( target, "7" );
  else if ( grad < 10.5 )
    strcpy ( target, "6" );
  else if ( grad < 13.5 )
    strcpy ( target, "5" );
  else if ( grad < 17.5 )
    strcpy ( target, "4" );
  else if ( grad < 25.0 )
    strcpy ( target, "3" );
  else if ( grad < 40.0 )
    strcpy ( target, "2" );
  else if ( grad >= 45.0 )
    strcpy ( target, "1" );
  else
    strcpy ( target, "0" );
  return target;
}
Referenced by syn_parse_x07().
syn_parse_x07()
int syn_parse_x07 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 07.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 65 of file bufr2tac_x07.c.
{
  // this is to avoid warning
  if ( syn == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 07 001 . Heigh of station
    case 30: // 0 07 030 . Height of station ground above msl
    case 31: // 0 07 031 . Height of barometer above msl
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( syn->s0.h0h0h0h0[0] == 0 )
        {
          if (s->ival > 9999 || s->ival < -9999)
            return 1;
          sprintf ( syn->s0.h0h0h0h0, "%04d", s->ival );
          syn->s0.im[0] = '1';// set unit as m
          s->mask |= SUBSET_MASK_HAVE_ALTITUDE;
        }
      s->alt = s->val;
      break;
    case 4: // 0 07 004 . Pressure at standard level
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( s->ival == 100000 )
        {
          strcpy ( syn->s1.a3, "1" );
        }
      else if ( s->ival == 92500 )
        {
          strcpy ( syn->s1.a3, "2" );
        }
      else if ( s->ival == 85000 )
        {
          strcpy ( syn->s1.a3, "8" );
        }
      else if ( s->ival == 70000 )
        {
          strcpy ( syn->s1.a3, "7" );
        }
      else if ( s->ival == 50000 )
        {
          strcpy ( syn->s1.a3, "5" );
        }
      break;
    case 21: // 0 07 021 . Elevation angle
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      grad_to_ec ( syn->s3.ec, s->val );
      syn->mask |= SYNOP_SEC3;
      break;
    case 32: // 0 07 032 Height of sensor above local ground
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->hsensor = -999.9; // clean value
          return 0;
        }
      s->hsensor = s->val;
      break;
    case 33: // 0 07 033 Height of sensor above water surface
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->hwsensor = -999.9; // clean value
          return 0;
        }
      s->hwsensor = s->val;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x07()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, synop_sec1::a3, bufr2tac_subset_state::alt, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec3::ec, grad_to_ec(), synop_sec0::h0h0h0h0, bufr2tac_subset_state::hsensor, bufr2tac_subset_state::hwsensor, synop_sec0::im, bufr2tac_subset_state::ival, bufr_atom_data::mask, bufr2tac_subset_state::mask, synop_chunks::mask, synop_chunks::s0, synop_chunks::s1, synop_chunks::s3, SUBSET_MASK_HAVE_ALTITUDE, SYNOP_SEC3, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x07()
int temp_parse_x07 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Definition at line 258 of file bufr2tac_x07.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
// this is to avoid warning
  if ( t == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 4:  // 0 07 004 . Pressure
      if ( s->rep > 0 && s->r->n > 0 )
        {
          s->r->raw[s->r->n - 1].p = s->val;
        }
      else if ( s->w->n > 0 )
        {
          s->w->raw[s->w->n - 1].p = s->val;
        }
      break;
    case 30: // 0 07 030 . Height of station ground above msl
      sprintf ( t->a.s1.h0h0h0h0, "%04.0lf" , s->val );
      sprintf ( t->b.s1.h0h0h0h0, "%04.0lf" , s->val );
      sprintf ( t->c.s1.h0h0h0h0, "%04.0lf" , s->val );
      sprintf ( t->d.s1.h0h0h0h0, "%04.0lf" , s->val );
      break;
    case 31: // 0 07 031 . Height of barometer above msl
      s->alt = s->val;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x07()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, temp_chunks::a, bufr2tac_subset_state::alt, temp_chunks::b, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), temp_chunks::c, temp_chunks::d, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_acd_sec1::h0h0h0h0, temp_b_sec1::h0h0h0h0, bufr_atom_data::mask, temp_raw_data::n, temp_raw_wind_shear_data::n, temp_raw_point_data::p, temp_raw_wind_shear_point::p, bufr2tac_subset_state::r, temp_raw_data::raw, temp_raw_wind_shear_data::raw, bufr2tac_subset_state::rep, temp_a::s1, temp_b::s1, temp_c::s1, temp_d::s1, bufr2tac_subset_state::val, bufr2tac_subset_state::w, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().