bufr2synop: src/libraries/bufr2syn_print.c File Reference
bufr2syn_print.c File Reference
file with the code to print the results
#include "bufr2syn.h"
Macros
#define check_len(ori, inc) (c - *ori + inc < (int)lmax)
cheks if there still memory enough to add inc chars
Functions
char * print_synop_sec0 (char **sec0, size_t lmax, struct synop_chunks *syn)
Prints the synop section 0 (header)
char * print_synop_sec1 (char **sec1, size_t lmax, struct synop_chunks *syn)
Prints the synop section 1.
char * print_synop_sec2 (char **sec2, size_t lmax, struct synop_chunks *syn)
Prints the synop section 2.
char * print_synop_sec3 (char **sec3, size_t lmax, struct synop_chunks *syn)
Prints the synop section 3.
char * print_synop_sec5 (char **sec5, size_t lmax, struct synop_chunks *syn)
Prints the synop section 5.
int print_synop (char *report, size_t lmax, struct synop_chunks *syn)
prints a synop into a string
char * print_buoy_sec0 (char **sec0, size_t lmax, struct buoy_chunks *b)
Prints the buoy section 1.
char * print_buoy_sec1 (char **sec1, size_t lmax, struct buoy_chunks *b)
Prints the buoy section 1.
char * print_buoy_sec2 (char **sec2, size_t lmax, struct buoy_chunks *b)
Prints the buoy section 1.
char * print_buoy_sec3 (char **sec3, size_t lmax, struct buoy_chunks *b)
Prints the buoy section 3.
int print_buoy (char *report, size_t lmax, struct buoy_chunks *b)
prints a buoy into a string
Detailed Description
file with the code to print the results
Definition in file bufr2syn_print.c.
Macro Definition Documentation
#define check_len (ori, inc) (c - *ori + inc < (int)lmax)
cheks if there still memory enough to add inc chars
Definition at line 30 of file bufr2syn_print.c.
Referenced by print_buoy_sec0(), print_buoy_sec1(), print_buoy_sec2(), print_buoy_sec3(), print_synop_sec0(), print_synop_sec1(), print_synop_sec2(), print_synop_sec3(), and print_synop_sec5().
Function Documentation
int print_buoy (char * report, size_t lmax, struct buoy_chunks * b)
prints a buoy into a string
Parameters
report target string
lmax max size of string
b pointer to a struct buoy_chunks with the result of parse tasks
returns 0 if all went right
Definition at line 754 of file bufr2syn_print.c.
References BUOY_SEC1, BUOY_SEC2, BUOY_SEC3, buoy_chunks::e, buoy_chunks::mask, print_buoy_sec0(), print_buoy_sec1(), print_buoy_sec2(), print_buoy_sec3(), and report_date_ext::YYYY.
Referenced by parse_subset_sequence().
 {
   char *c;
   c = report;
   // Needs time extension
   if (b->e.YYYY[0] == 0)
     return 1;
   print_buoy_sec0(&c, lmax, b);
   if (b->mask & (BUOY_SEC1 | BUOY_SEC2 | BUOY_SEC3))
     {
       print_buoy_sec1(&c, lmax - strlen(report), b);
       print_buoy_sec2(&c, lmax - strlen(report), b);
       print_buoy_sec3(&c, lmax - strlen(report), b);
     }
   else
     c+= sprintf(c, " NIL");
   c += sprintf ( c, "=" );
   return 0;
 }
char* print_buoy_sec0 (char ** sec0, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 1.
Parameters
sec0 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 493 of file bufr2syn_print.c.
References buoy_sec0::A1, buoy_sec0::bw, check_len, buoy_sec0::D_D, report_date_ext::DD, buoy_chunks::e, buoy_sec0::GG, buoy_sec0::gg, report_date_ext::HH, buoy_sec0::iw, buoy_sec0::J, buoy_sec0::LaLaLaLaLa, buoy_sec0::LoLoLoLoLoLo, buoy_sec0::MiMi, buoy_sec0::MjMj, buoy_sec0::MM, report_date_ext::MM, report_date_ext::mm, buoy_sec0::nbnbnb, buoy_sec0::QA, buoy_sec0::Qc, buoy_sec0::Ql, buoy_sec0::Qt, buoy_chunks::s0, buoy_sec0::YY, and report_date_ext::YYYY.
Referenced by print_buoy().
 {
   char *c = *sec0;
   if (check_len(sec0,12))
     c += sprintf ( c, "%s%s%s%s%s", b->e.YYYY, b->e.MM, b->e.DD, b->e.HH, b->e.mm );
   // Print type
   if (check_len(sec0,5))
     c += sprintf ( c, " %s%s", b->s0.MiMi, b->s0.MjMj );
   if (check_len(sec0,6) && b->s0.A1[0] && b->s0.bw[0] && b->s0.nbnbnb[0])
     {
       c += sprintf ( c, " %s%s%s", b->s0.A1, b->s0.bw, b->s0.nbnbnb);
     }
   else if (check_len(sec0, 10) && b->s0.D_D)
     c += sprintf ( c, " %s", b->s0.D_D );
   if (check_len(sec0,6))
     c += sprintf(c, " %s%s%s", b->s0.YY, b->s0.MM, b->s0.J);
   if (check_len(sec0,6))
     {
       if (  b->s0.iw[0])
         c += sprintf(c, " %s%s%s", b->s0.GG, b->s0.gg, b->s0.iw);
       else
         c += sprintf(c, " %s%s/", b->s0.GG, b->s0.gg);
     }
   if (check_len(sec0,7))
     c += sprintf(c, " %s%s", b->s0.Qc, b->s0.LaLaLaLaLa);
   if (check_len(sec0,7))
     c += sprintf(c, " %s", b->s0.LoLoLoLoLoLo);
   if (b->s0.QA[0] || b->s0.Ql[0] || b->s0.Qt[0])
     {
       if (b->s0.Ql[0])
         c +=sprintf(c, " 6%s", b->s0.Ql);
       else
         c +=sprintf(c, " 6/");
       if (b->s0.Qt[0])
         c +=sprintf(c, "%s", b->s0.Qt);
       else
         c +=sprintf(c, "/");
       if (b->s0.QA[0])
         c +=sprintf(c, "%s/", b->s0.QA);
       else
         c +=sprintf(c, "//");
     }
   *sec0 = c;
   return *sec0;
 }
char* print_buoy_sec1 (char ** sec1, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 1.
Parameters
sec1 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 559 of file bufr2syn_print.c.
References buoy_sec1::a, BUOY_SEC1, check_len, buoy_sec1::dd, buoy_sec1::ff, buoy_chunks::mask, buoy_sec1::PoPoPoPo, buoy_sec1::ppp, buoy_sec1::PPPP, buoy_sec1::Qd, buoy_sec1::Qx, buoy_chunks::s1, buoy_sec1::sn1, buoy_sec1::sn2, buoy_sec1::TdTdTd, and buoy_sec1::TTT.
Referenced by print_buoy().
 {
   char *c = *sec1;
   if ( b->mask & BUOY_SEC1)
     {
       // 111QdQx
       c += sprintf(c," 111");
       if (b->s1.Qd[0])
         c += sprintf(c,"%s", b->s1.Qd);
       else
         c += sprintf(c,"/");
       if (b->s1.Qx[0])
         c += sprintf(c,"%s", b->s1.Qx);
       else
         c += sprintf(c,"/");
       // 0ddff
       if (check_len(sec1,6))
         {
           if (b->s1.dd[0] || b->s1.ff[0])
             {
               c += sprintf(c, " 0");
               if (b->s1.dd[0])
                 c += sprintf ( c, "%s", b->s1.dd);
               else
                 c += sprintf ( c, "//");
               if (b->s1.ff[0])
                 c += sprintf ( c, "%s", b->s1.ff);
               else
                 c += sprintf ( c, "//");
             }
         }
       // 1snTTT
       if (check_len(sec1,6) && b->s1.TTT[0])
         c += sprintf(c, " 1%s%s", b->s1.sn1, b->s1.TTT);
       // 2snTdTdTd
       if (check_len(sec1,6) && b->s1.TdTdTd[0])
         c += sprintf(c, " 2%s%s", b->s1.sn2, b->s1.TdTdTd);
       // 3PoPoPoPo
       if (check_len(sec1,6) && b->s1.PoPoPoPo[0])
         c += sprintf(c, " 3%s", b->s1.PoPoPoPo);
       // printf 4PPPP
       if ( check_len(sec1,6) && b->s1.PPPP[0] )
         c += sprintf ( c, " 4%s", b->s1.PPPP );
       // printf 5appp
       if ( check_len(sec1,6) && (b->s1.a[0] || b->s1.ppp[0]))
         {
           if ( b->s1.a[0] == 0 )
             b->s1.a[0] = '/';
           if ( b->s1.ppp[0] == 0 )
             strcpy ( b->s1.ppp, "///" );
           c += sprintf ( c, " 5%s%s", b->s1.a, b->s1.ppp );
         }
     }
   *sec1 = c;
   return *sec1;
 }
char* print_buoy_sec2 (char ** sec2, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 1.
Parameters
sec2 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 634 of file bufr2syn_print.c.
References BUOY_SEC2, check_len, buoy_sec2::HwaHwa, buoy_sec2::HwaHwaHwa, buoy_chunks::mask, buoy_sec2::PwaPwa, buoy_sec2::PwaPwaPwa, buoy_sec2::Qd, buoy_sec2::Qx, buoy_chunks::s2, buoy_sec2::sn, and buoy_sec2::TwTwTw.
Referenced by print_buoy().
 {
   char *c = *sec2;
   if (b->mask & BUOY_SEC2)
     {
       // 222QdQx
       c += sprintf(c," 222");
       if (b->s2.Qd[0])
         c += sprintf(c,"%s", b->s2.Qd);
       else
         c += sprintf(c,"/");
       if (b->s2.Qx[0])
         c += sprintf(c,"%s", b->s2.Qx);
       else
         c += sprintf(c,"/");
       // 0snTwTwTw
       if (check_len(sec2,6) && b->s2.TwTwTw[0] )
         c += sprintf ( c, " 0%s%s", b->s2.sn, b->s2.TwTwTw );
       // 1PwaPwaHwaHwa
       if (check_len(sec2,6) && (b->s2.PwaPwa[0] || b->s2.HwaHwa[0]))
         {
           c += sprintf(c, " 1");
           if (b->s2.PwaPwa[0])
             c += sprintf(c,"%s", b->s2.PwaPwa);
           else
             c += sprintf(c,"//");
           if (b->s2.HwaHwa[0])
             c += sprintf(c,"%s", b->s2.HwaHwa);
           else
             c += sprintf(c,"//");
         }
       // 20PwaPwaPwa
       if (check_len(sec2,6) && b->s2.PwaPwaPwa[0])
         c += sprintf(c, " 20%s", b->s2.PwaPwaPwa);
       // 21HwaHwaHwa
       if (check_len(sec2,6) && b->s2.HwaHwaHwa[0])
         c += sprintf(c, " 21%s", b->s2.HwaHwaHwa);
     }
   *sec2 = c;
   return *sec2;
 }
char* print_buoy_sec3 (char ** sec3, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 3.
Parameters
sec3 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 694 of file bufr2syn_print.c.
References BUOY_SEC3, b_sec3_layer2::ccc, check_len, b_sec3_layer2::dd, buoy_sec3::k2, buoy_sec3::k3, buoy_sec3::k6, buoy_sec3::l1, buoy_sec3::l2, buoy_chunks::mask, buoy_sec3::Qd1, buoy_sec3::Qd2, buoy_chunks::s3, b_sec3_layer1::SSSS, b_sec3_layer1::TTTT, b_sec3_layer1::zzzz, and b_sec3_layer2::zzzz.
Referenced by print_buoy().
 {
   char *c = *sec3;
   size_t l;
   if (check_len(sec3,6) && (b->mask & BUOY_SEC3))
     {
       c += sprintf(c, " 333%s%s", b->s3.Qd1, b->s3.Qd2);
       // check if has 8887k2
       l = 0;
       while (b->s3.l1[l].zzzz[0] && l < 32)
         {
           if (l == 0)
             c += sprintf(c, " 8887%s", b->s3.k2);
           c += sprintf(c,  " 2%s", b->s3.l1[l].zzzz);
           if (b->s3.l1[l].TTTT[0])
             c += sprintf(c,  " 3%s", b->s3.l1[l].TTTT);
           if (b->s3.l1[l].SSSS[0])
             c += sprintf(c,  " 4%s", b->s3.l1[l].SSSS);
           l++;
         }
       l = 0;
       while (b->s3.l2[l].zzzz[0] && l < 32)
         {
           if (l == 0)
             c += sprintf(c, " 66%s9%s", b->s3.k6, b->s3.k3);
           c += sprintf(c,  " 2%s", b->s3.l2[l].zzzz);
           if (b->s3.l2[l].dd[0] || b->s3.l2[l].ccc[0])
             {
               if (b->s3.l2[l].dd[0])
                 c += sprintf(c,  " %s", b->s3.l2[l].dd);
               else
                 c += sprintf(c,  " //");
               if (b->s3.l2[l].ccc[0])
                 c += sprintf(c,  "%s", b->s3.l2[l].ccc);
               else
                 c += sprintf(c,  "///");
             }
           l++;
         }
     }
   *sec3 = c;
   return *sec3;
 }
int print_synop (char * report, size_t lmax, struct synop_chunks * syn)
prints a synop into a string
Parameters
report target string
lmax max size of string
syn pointer to a struct synop_chunks with the result of parse tasks
returns 0 if all went right
Definition at line 456 of file bufr2syn_print.c.
References synop_chunks::e, synop_chunks::mask, print_synop_sec0(), print_synop_sec1(), print_synop_sec2(), print_synop_sec3(), print_synop_sec5(), SYNOP_SEC1, SYNOP_SEC2, SYNOP_SEC3, SYNOP_SEC5, and report_date_ext::YYYY.
Referenced by parse_subset_sequence().
 {
   char *c;
   c = report;
   // Needs time extension
   if (syn->e.YYYY[0] == 0)
     return 1;
   print_synop_sec0(&c, lmax, syn);
   if (syn->mask & (SYNOP_SEC1 | SYNOP_SEC2 | SYNOP_SEC3 | SYNOP_SEC5))
     {
       print_synop_sec1(&c, lmax - strlen(report), syn);
       print_synop_sec2(&c, lmax - strlen(report), syn);
       print_synop_sec3(&c, lmax - strlen(report), syn);
       print_synop_sec5(&c, lmax - strlen(report), syn);
     }
   else
     c += sprintf(c, " NIL");
   c += sprintf ( c, "=" );
   return 0;
 }
char* print_synop_sec0 (char ** sec0, size_t lmax, struct synop_chunks * syn)
Prints the synop section 0 (header)
Parameters
sec0 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 39 of file bufr2syn_print.c.
References synop_sec0::A1, synop_sec0::bw, check_len, synop_sec0::D_D, report_date_ext::DD, synop_chunks::e, synop_sec0::GG, synop_sec0::h0h0h0h0, report_date_ext::HH, synop_sec0::II, synop_sec0::iii, synop_sec0::im, synop_sec0::iw, synop_sec0::LaLaLa, synop_sec0::LoLoLoLo, synop_sec0::MiMi, synop_sec0::MjMj, report_date_ext::MM, report_date_ext::mm, synop_sec0::MMM, synop_sec0::nbnbnb, synop_sec0::Qc, synop_chunks::s0, synop_sec0::Ula, synop_sec0::Ulo, synop_sec0::YY, and report_date_ext::YYYY.
Referenced by print_synop().
 {
   char *c = *sec0;
   if (check_len(sec0,12))
     c += sprintf ( c, "%s%s%s%s%s", syn->e.YYYY, syn->e.MM, syn->e.DD, syn->e.HH, syn->e.mm );
   // Print type
   if (check_len(sec0,5))
     c += sprintf ( c, " %s%s", syn->s0.MiMi, syn->s0.MjMj );
   if (check_len(sec0,6))
     {
       if (syn->s0.D_D[0])
         c += sprintf ( c, " %s", syn->s0.D_D);
       else if (syn->s0.A1[0] && syn->s0.bw[0] && syn->s0.nbnbnb[0])
         c += sprintf ( c, " %s%s%s", syn->s0.A1, syn->s0.bw, syn->s0.nbnbnb);
     }
   // print YYGGiw
   if (check_len(sec0,6))
     c += sprintf ( c, " %s%s%s", syn->s0.YY, syn->s0.GG, syn->s0.iw );
   // print IIiii
   if (check_len(sec0,6) && syn->s0.II[0])
     c += sprintf ( c, " %s%s", syn->s0.II, syn->s0.iii );
   else
     {
       if (syn->s0.LaLaLa[0])
         c += sprintf ( c, " 99%s", syn->s0.LaLaLa );
       else
         c += sprintf ( c, " 99///");
       if (syn->s0.Qc[0] && syn->s0.LoLoLoLo[0])
         c += sprintf ( c, " %s%s", syn->s0.Qc, syn->s0.LoLoLoLo);
       else
         c += sprintf ( c, " /////");
     }
   if (strcmp(syn->s0.MiMi, "OO") == 0)
     {
       if (syn->s0.MMM[0] && syn->s0.Ula && syn->s0.Ulo)
         c += sprintf ( c, " %s%s%s", syn->s0.MMM, syn->s0.Ula, syn->s0.Ulo);
       if (syn->s0.h0h0h0h0[0])
         c += sprintf ( c, " %s%s", syn->s0.h0h0h0h0, syn->s0.im);
     }
   *sec0 = c;
   return *sec0;
 }
char* print_synop_sec1 (char ** sec1, size_t lmax, struct synop_chunks * syn)
Prints the synop section 1.
Parameters
sec1 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 99 of file bufr2syn_print.c.
References synop_sec1::a, synop_sec1::Ch, check_len, synop_sec1::Cl, synop_sec1::Cm, synop_sec1::dd, synop_sec1::ff, synop_sec1::fff, synop_sec1::GG, synop_sec1::gg, synop_sec1::h, synop_sec1::ir, synop_sec1::ix, synop_chunks::mask, synop_sec1::N, synop_sec1::Nh, synop_sec1::PoPoPoPo, synop_sec1::ppp, synop_sec1::PPPP, synop_sec1::RRR, synop_chunks::s1, synop_sec1::sn1, synop_sec1::sn2, SYNOP_SEC1, synop_sec1::TdTdTd, synop_sec1::tr, synop_sec1::TTT, synop_sec1::VV, synop_sec1::W1, synop_sec1::W2, and synop_sec1::ww.
Referenced by print_synop().
 {
   char *c = *sec1;
   if (syn->mask & SYNOP_SEC1)
     {
       // printf irixhVV
       if (check_len(sec1,6))
         c += sprintf ( c, " %s%s%s%s", syn->s1.ir, syn->s1.ix, syn->s1.h, syn->s1.VV );
       // printf Nddff
       if (check_len(sec1,6))
         c += sprintf ( c, " %s%s%s", syn->s1.N, syn->s1.dd, syn->s1.ff );
       if (check_len(sec1,6) && strlen ( syn->s1.fff ) )
         c += sprintf ( c, " 00%s", syn->s1.fff );
       // printf 1snTTT
       if (check_len(sec1,6) && syn->s1.TTT[0] )
         c += sprintf ( c, " 1%s%s", syn->s1.sn1, syn->s1.TTT );
       // printf 2snTdTdTd
       if ( check_len(sec1,6) && syn->s1.TdTdTd[0] )
         c += sprintf ( c, " 2%s%s", syn->s1.sn2, syn->s1.TdTdTd );
       // printf 3PoPoPoPo
       if ( check_len(sec1,6) && syn->s1.PoPoPoPo[0] )
         c += sprintf ( c, " 3%s", syn->s1.PoPoPoPo );
       // printf 4PPPP
       if ( check_len(sec1,6) && syn->s1.PPPP[0] )
         c += sprintf ( c, " 4%s", syn->s1.PPPP );
       // printf 5appp
       if ( check_len(sec1,6) && (syn->s1.a[0] || syn->s1.ppp[0]))
         {
           if ( syn->s1.a[0] == 0 )
             syn->s1.a[0] = '/';
           if ( syn->s1.ppp[0] == 0 )
             strcpy ( syn->s1.ppp, "///" );
           c += sprintf ( c, " 5%s%s", syn->s1.a, syn->s1.ppp );
         }
       // printf 6RRRtr
       if ( check_len(sec1,6) && (syn->s1.tr[0] || syn->s1.RRR[0]))
         {
           if ( syn->s1.tr[0] == 0 )
             syn->s1.tr[0] = '/';
           if ( syn->s1.RRR[0] == 0 )
             strcpy ( syn->s1.RRR, "///" );
           c += sprintf ( c, " 6%s%s", syn->s1.RRR, syn->s1.tr);
         }
       if ( check_len(sec1,6) && (syn->s1.ww[0] || syn->s1.W1[0] || syn->s1.W2[0]))
         {
           if ( syn->s1.ww[0] == 0 )
             strcpy ( syn->s1.ww, "//" );
           if ( syn->s1.W1[0] == 0 )
             strcpy ( syn->s1.W1, "/" );
           if ( syn->s1.W2[0] == 0 )
             strcpy ( syn->s1.W2, "/" );
           c += sprintf ( c, " 7%s%s%s", syn->s1.ww, syn->s1.W1, syn->s1.W2 );
         }
       if ( check_len(sec1,6) && ((syn->s1.Nh[0] && syn->s1.Nh[0] != '0' && syn->s1.Nh[0] != '/') ||
                                  (syn->s1.Cl[0] && syn->s1.Cl[0] != '0' && syn->s1.Cl[0] != '/') ||
                                  (syn->s1.Cm[0] && syn->s1.Cm[0] != '0' && syn->s1.Cm[0] != '/') ||
                                  (syn->s1.Ch[0] && syn->s1.Ch[0] != '0' && syn->s1.Ch[0] != '/')))
         {
           if ( syn->s1.Nh[0] == 0 )
             strcpy ( syn->s1.Nh, "/" );
           if ( syn->s1.Cl[0] == 0 )
             strcpy ( syn->s1.Cl, "/" );
           if ( syn->s1.Cm[0] == 0 )
             strcpy ( syn->s1.Cm, "/" );
           if ( syn->s1.Ch[0] == 0 )
             strcpy ( syn->s1.Ch, "/" );
           c += sprintf(c, " 8%s%s%s%s", syn->s1.Nh, syn->s1.Cl, syn->s1.Cm, syn->s1.Ch);
         }
       if ( check_len(sec1,6) && syn->s1.GG[0] )
         c+= sprintf ( c, " 9%s%s", syn->s1.GG, syn->s1.gg );
     }
   *sec1 = c;
   return *sec1;
 }
char* print_synop_sec2 (char ** sec2, size_t lmax, struct synop_chunks * syn)
Prints the synop section 2.
Parameters
sec2 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 195 of file bufr2syn_print.c.
References check_len, synop_sec2::Ds, synop_sec2::dw1dw1, synop_sec2::dw2dw2, synop_sec2::Hw1Hw1, synop_sec2::Hw2Hw2, synop_sec2::HwaHwa, synop_sec2::HwaHwaHwa, synop_sec2::HwHw, synop_chunks::mask, synop_sec2::Pw1Pw1, synop_sec2::Pw2Pw2, synop_sec2::PwaPwa, synop_sec2::PwPw, synop_chunks::s2, synop_sec2::ss, synop_sec2::sw, SYNOP_SEC2, synop_sec2::TbTbTb, synop_sec2::TwTwTw, and synop_sec2::vs.
Referenced by print_synop().
 {
   char *c = *sec2;
   if ( syn->mask & SYNOP_SEC2 )
     {
       // 222Dsvs
       if (check_len(sec2,46))
         {
           c += sprintf ( c, " 222");
           if (syn->s2.Ds[0])
             c += sprintf ( c, "%s", syn->s2.Ds);
           else
             c += sprintf ( c, "/");
           if (syn->s2.vs[0])
             c += sprintf ( c, "%s", syn->s2.vs);
           else
             c += sprintf ( c, "/");
         }
       // printf 0ssTwTwTw
       if (check_len(sec2,6) && syn->s2.TwTwTw[0] )
         c += sprintf ( c, " 0%s%s", syn->s2.ss, syn->s2.TwTwTw );
       if (check_len(sec2,6) && (syn->s2.PwaPwa[0] || syn->s2.HwaHwa[0]))
         {
           if (syn->s2.PwaPwa[0])
             c += sprintf ( c, " 1%s", syn->s2.PwaPwa);
           else
             c += sprintf ( c, " 1//");
           if (syn->s2.HwaHwa[0])
             c += sprintf ( c, "%s", syn->s2.HwaHwa);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.PwPw[0] || syn->s2.HwHw[0]))
         {
           if (syn->s2.PwPw[0])
             c += sprintf ( c, " 2%s", syn->s2.PwPw);
           else
             c += sprintf ( c, " 2//");
           if (syn->s2.HwHw[0])
             c += sprintf ( c, "%s", syn->s2.HwHw);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.dw1dw1[0] || syn->s2.dw2dw2[0]))
         {
           if (syn->s2.dw1dw1[0])
             c += sprintf ( c, " 3%s", syn->s2.dw1dw1);
           else
             c += sprintf ( c, " 3//");
           if (syn->s2.dw2dw2[0])
             c += sprintf ( c, "%s", syn->s2.dw2dw2);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.Pw1Pw1[0] || syn->s2.Hw1Hw1[0]))
         {
           if (syn->s2.Pw1Pw1[0])
             c += sprintf ( c, " 4%s", syn->s2.Pw1Pw1);
           else
             c += sprintf ( c, " 4//");
           if (syn->s2.Hw1Hw1[0])
             c += sprintf ( c, "%s", syn->s2.Hw1Hw1);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.Pw2Pw2[0] || syn->s2.Hw2Hw2[0]))
         {
           if (syn->s2.Pw2Pw2[0])
             c += sprintf ( c, " 5%s", syn->s2.Pw2Pw2);
           else
             c += sprintf ( c, " 5//");
           if (syn->s2.Hw2Hw2[0])
             c += sprintf ( c, "%s", syn->s2.Hw2Hw2);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && syn->s2.HwaHwaHwa[0])
         {
           c += sprintf(c, " 70%s", syn->s2.HwaHwaHwa);
         }
       if (check_len(sec2,6) && syn->s2.TbTbTb[0] )
         c += sprintf ( c, " 8%s%s", syn->s2.sw, syn->s2.TbTbTb );
     }
   *sec2 = c;
   return *sec2;
 }
char* print_synop_sec3 (char ** sec3, size_t lmax, struct synop_chunks * syn)
Prints the synop section 3.
Parameters
sec3 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 306 of file bufr2syn_print.c.
References nub3::C, check_len, synop_sec3::d9, synop_sec3::E, synop_sec3::FFFF, synop_sec3::FFFF24, nub3::hshs, synop_sec3::j5, synop_sec3::j524, synop_sec3::jjj, synop_chunks::mask, data9::misc, data9::n, nub3::Ns, synop_sec3::nub, synop_sec3::RRR, synop_sec3::RRRR24, synop_chunks::s3, synop_sec3::snn, synop_sec3::snx, misc3::SpSp, misc3::spsp, synop_sec3::SS, synop_sec3::SSS, SYNOP_SEC3, synop_sec3::TnTnTn, synop_sec3::tr, synop_sec3::TxTxTx, and synop_sec3::XoXoXoXo.
Referenced by print_synop().
 {
   size_t i;
   char *c = *sec3, *c0;
   if ( syn->mask & SYNOP_SEC3 )
     {
       if (check_len(sec3,4))
         c += sprintf ( c, " 333" );
       // init point to write info.
       // in case we finally write nothing in this section
       c0 = c;
       // printf 1snxTxTxTx
       if (check_len(sec3,6) && syn->s3.XoXoXoXo[0])
         {
           c += sprintf(c, " 0%s", syn->s3.XoXoXoXo);
         }
       // printf 1snxTxTxTx
       if (check_len(sec3,6) && syn->s3.snx[0])
         {
           c += sprintf(c, " 1%s%s", syn->s3.snx, syn->s3.TxTxTx);
         }
       // printf 1snnTnTnTn
       if (check_len(sec3,6) && syn->s3.snn[0])
         {
           c += sprintf(c, " 2%s%s", syn->s3.snn, syn->s3.TnTnTn);
         }
       // printf 3Ejjj
       if (check_len(sec3,6) && (syn->s3.E[0] || syn->s3.jjj[0]))
         {
           if (syn->s3.E[0] == 0)
             syn->s3.E[0] = '/';
           if (syn->s3.jjj[0] == 0)
             strcpy(syn->s3.jjj, "///");
           c += sprintf(c, " 3%s%s", syn->s3.E, syn->s3.jjj);
         }
       /**** Radiation Sunshine gropus ***/
       // print 55SSS
       if (check_len(sec3,6) && syn->s3.SSS[0] && strcmp(syn->s3.SSS,"///"))
         {
           c += sprintf(c, " 55%s", syn->s3.SSS);
           for (i = 0; i < 7; i++)
             {
               if (syn->s3.j524[i][0])
                 sprintf(c, " %s%s", syn->s3.j524[i], syn->s3.FFFF24[i]);
             }
         }
       // print 553SS
       if (check_len(sec3,6) && syn->s3.SS[0] && strcmp(syn->s3.SS,"//"))
         {
           c += sprintf(c, " 553%s", syn->s3.SS);
           for (i = 0; i < 7; i++)
             {
               if (syn->s3.j5[i][0])
                 sprintf(c, " %s%s", syn->s3.j5[i], syn->s3.FFFF[i]);
             }
         }
       // printf 6RRRtr
       if (check_len(sec3,6) && ( syn->s3.tr[0] || syn->s3.RRR[0]) )
         {
           if ( syn->s3.tr[0] == 0 )
             syn->s3.tr[0] = '/';
           if ( syn->s3.RRR[0] == 0 )
             strcpy ( syn->s3.RRR, "///" );
           c += sprintf ( c, " 6%s%s", syn->s3.RRR ,syn->s3.tr);
         }
       if ( check_len(sec3,6) && syn->s3.RRRR24[0] )
         c += sprintf ( c, " 7%s", syn->s3.RRRR24);
       // additional cloud layers
       i = 0;
       while (i < 4 && syn->s3.nub[i].hshs[0])
       {
         c += sprintf ( c, " 8%s%s%s", syn->s3.nub[i].Ns, syn->s3.nub[i].C, syn->s3.nub[i].hshs);
         i++;
       }
       // additional info
       for (i = 0; i < syn->s3.d9.n ; i++)
       {
         c += sprintf(c, " %s%s", syn->s3.d9.misc[i].SpSp, syn->s3.d9.misc[i].spsp);
       }
       if (c != c0)
         *sec3 = c;
     }
   return *sec3;
 }
char * print_synop_sec5 (char ** sec5, size_t lmax, struct synop_chunks * syn)
Prints the synop section 5.
Parameters
sec5 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 411 of file bufr2syn_print.c.
References check_len, synop_sec5::d9, synop_chunks::mask, data9::misc, data9::n, synop_sec5::RRR, synop_chunks::s5, misc3::SpSp, misc3::spsp, SYNOP_SEC5, and synop_sec5::tr.
Referenced by print_synop().
 {
   size_t i;
   char *c = *sec5, *c0;
   if ( syn->mask & SYNOP_SEC5 )
     {
       if (check_len(sec5,4))
         c += sprintf ( c, " 555" );
       // init point to write info.
       // in case we finally write nothing in this section
       c0 = c;
       // printf 6RRRtr
       if (check_len(sec5,6) && ( syn->s5.tr[0] || syn->s5.RRR[0]) )
         {
           if ( syn->s5.tr[0] == 0 )
             syn->s5.tr[0] = '/';
           if ( syn->s5.RRR[0] == 0 )
             strcpy ( syn->s5.RRR, "///" );
           c += sprintf ( c, " 6%s%s", syn->s5.RRR ,syn->s5.tr);
         }
       // additional info
       for (i = 0; i < syn->s5.d9.n ; i++)
       {
         c += sprintf(c, " %s%s", syn->s5.d9.misc[i].SpSp, syn->s5.d9.misc[i].spsp);
       }
       if (c != c0)
         *sec5 = c;
     }
   return *sec5;
 }