bufr2synop: src/libraries/bufr2tac_x33.c File Reference
bufr2tac_x33.c File Reference
decodes the descriptors with X = 33 (Quality data)
#include "bufr2tac.h"
Functions
int buoy_parse_x33 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 33.
int temp_parse_x33 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 33.
Detailed Description
decodes the descriptors with X = 33 (Quality data)
Definition in file bufr2tac_x33.c.
Function Documentation
buoy_parse_x33()
int buoy_parse_x33 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 33.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2tac_x33.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 20: // 0 33 020. Quality control indication of followinf value
      sprintf ( b->s0.Qt, "%d", s->ival );
      b->mask |= BUOY_SEC1;
      break;
    case 21: // 0 33 021. Quality control of following value
      sprintf ( b->s4.Qp, "%d", s->ival );
      b->mask |= BUOY_SEC1;
      break;
    case 22: // 0 33 022. Quality of buoy satellite transmission
      if ( s->ival == 0 )
        {
          if ( b->s0.Qt[0] == 0 )
            sprintf ( b->s0.Qt, "1" );
          if ( b->s1.Qd[0] == 0 )
            sprintf ( b->s1.Qd, "1" );
          if ( b->s2.Qd[0] == 0 )
            sprintf ( b->s2.Qd, "1" );
        }
      if ( s->ival == 2 )
        {
          if ( b->s0.Qt[0] == 0 )
            sprintf ( b->s0.Qt, "3" );
          if ( b->s1.Qd[0] == 0 )
            sprintf ( b->s1.Qd, "3" );
          if ( b->s2.Qd[0] == 0 )
            sprintf ( b->s2.Qd, "3" );
        }
      break;
    case 23: // 0 33 023 . Quality of buoy location
      sprintf ( b->s0.Ql, "%d", s->ival );
      sprintf ( b->s4.QL, "%d", s->ival );
      break;
    case 27: // 0 33 027. Location quality class (range of ratiuos of 66% confidence)
      sprintf ( b->s0.QA, "%d", s->ival );
      sprintf ( b->s4.QA, "%d", s->ival );
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x33()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::ival, bufr_atom_data::mask, buoy_chunks::mask, buoy_sec0::QA, buoy_sec4::QA, buoy_sec1::Qd, buoy_sec2::Qd, buoy_sec0::Ql, buoy_sec4::QL, buoy_sec4::Qp, buoy_sec0::Qt, buoy_chunks::s0, buoy_chunks::s1, buoy_chunks::s2, buoy_chunks::s4, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
temp_parse_x33()
int temp_parse_x33 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 33.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 100 of file bufr2tac_x33.c.
{
  switch ( s->a->desc.y )
    {
    case 24: // 0 33 024. Station elevation quality mark (for mobile stations)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          strcpy ( t->a.s1.im, "/" );
          strcpy ( t->b.s1.im, "/" );
          strcpy ( t->c.s1.im, "/" );
          strcpy ( t->d.s1.im, "/" );
          return 0;
        }
      if ( s->ival >= 0 && s->ival < 9 )
        {
          sprintf ( t->a.s1.im, "%d", s->ival );
          sprintf ( t->a.s1.im, "%d", s->ival );
          sprintf ( t->a.s1.im, "%d", s->ival );
          sprintf ( t->a.s1.im, "%d", s->ival );
        }
      else
        {
          strcpy ( t->a.s1.im, "/" );
          strcpy ( t->b.s1.im, "/" );
          strcpy ( t->c.s1.im, "/" );
          strcpy ( t->d.s1.im, "/" );
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x33()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, temp_chunks::a, temp_chunks::b, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), temp_chunks::c, temp_chunks::d, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_acd_sec1::im, temp_b_sec1::im, bufr2tac_subset_state::ival, bufr_atom_data::mask, temp_a::s1, temp_b::s1, temp_c::s1, temp_d::s1, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().