bufr2synop: src/libraries/bufr2tac_x10.c File Reference
bufr2tac_x10.c File Reference
decodes the descriptors with X = 10 (air pressure)
#include "bufr2tac.h"
Functions
char * pascal_to_ppp (char *target, double P)
Converts pascal values (variation) into a ppp string.
char * pascal_to_pnpnpn (char *target, double P)
char * pascal_to_PPPP (char *target, double P)
Converts pascal values into a PPPP string.
int syn_parse_x10 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 10.
int buoy_parse_x10 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 10.
int climat_parse_x10 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 10.
int temp_parse_x10 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 10.
Detailed Description
decodes the descriptors with X = 10 (air pressure)
Definition in file bufr2tac_x10.c.
Function Documentation
buoy_parse_x10()
int buoy_parse_x10 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 161 of file bufr2tac_x10.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 4: // 0 10 004 . Pressure
      pascal_to_PPPP ( aux, s->val );
      strcpy ( b->s1.PoPoPoPo, aux );
      b->mask |= BUOY_SEC1;
      break;
    case 51: // 0 10 051 . Pressure reduced to mean sea level
      pascal_to_PPPP ( aux, s->val );
      strcpy ( b->s1.PPPP, aux );
      b->mask |= BUOY_SEC1;
      break;
    case 63: // 0 10 063 . Characteristic of pressure tendency
      sprintf ( b->s1.a, "%1d",s->ival );
      b->mask |= BUOY_SEC1;
      break;
    case 61: // 0 10 061 . 3-hour pressure change
      pascal_to_ppp ( aux, s->val );
      memcpy( b->s1.ppp, aux, 3 );
      b->s1.ppp[3] = 0;
      b->mask |= BUOY_SEC1;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x10()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, buoy_sec1::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::ival, bufr_atom_data::mask, buoy_chunks::mask, pascal_to_ppp(), pascal_to_PPPP(), buoy_sec1::PoPoPoPo, buoy_sec1::ppp, buoy_sec1::PPPP, buoy_chunks::s1, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
climat_parse_x10()
int climat_parse_x10 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
c pointer to a struct climat_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 214 of file bufr2tac_x10.c.
{
  char aux[16];
  if ( c == NULL || s == NULL )
    {
      return 1;
    }
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 4: // 0 10 004 . Pressure
      if ( s->isq_val == 4 )
        {
          pascal_to_PPPP ( aux, s->val );
          if ( s->is_normal == 0 )
            {
              strcpy ( c->s1.PoPoPoPo, aux );
              c->mask |= CLIMAT_SEC1;
            }
          else
            {
              strcpy ( c->s2.PoPoPoPo, aux );
              c->mask |= CLIMAT_SEC2;
            }
        }
      break;
    case 9: // 0 10 009 . Heigh of geopotential
      if ( s->isq_val == 4 )
        {
          if ( s->is_normal == 0 )
            {
              sprintf ( c->s1.PPPP, "%04d", s->ival );
              c->mask |= CLIMAT_SEC1;
            }
          else
            {
              sprintf ( c->s1.PPPP, "%04d", s->ival );
              c->mask |= CLIMAT_SEC2;
            }
        }
      break;
    case 51: // 0 10 051 . Pressure reduced to mean sea level
      if ( s->isq_val == 4 )
        {
          pascal_to_PPPP ( aux, s->val );
          if ( s->is_normal == 0 )
            {
              strcpy ( c->s1.PPPP, aux );
              c->mask |= CLIMAT_SEC1;
            }
          else
            {
              strcpy ( c->s2.PPPP, aux );
              c->mask |= CLIMAT_SEC2;
            }
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x10()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), CLIMAT_SEC1, CLIMAT_SEC2, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::is_normal, bufr2tac_subset_state::isq_val, bufr2tac_subset_state::ival, bufr_atom_data::mask, climat_chunks::mask, pascal_to_PPPP(), climat_sec1::PoPoPoPo, climat_sec2::PoPoPoPo, climat_sec1::PPPP, climat_sec2::PPPP, climat_chunks::s1, climat_chunks::s2, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_climat().
pascal_to_pnpnpn()
char * pascal_to_pnpnpn (char * target, double P)
Definition at line 47 of file bufr2tac_x10.c.
{
  int ic;
  if ( P > 10000.0 )
    {
      ic = ( int ) ( P * 0.01 + 0.5 );
    }
  else
    {
      ic = ( int ) ( P * 0.1 + 0.5 );
    }
  sprintf ( target, "%03d", ic % 1000 );
  return target;
}
Referenced by parse_temp_raw_data().
pascal_to_ppp()
char * pascal_to_ppp (char * target, double P)
Converts pascal values (variation) into a ppp string.
Parameters
P the pressure variation in Pascal units
target string with the result
Definition at line 32 of file bufr2tac_x10.c.
{
  int ic;
  if ( P > 0 )
    {
      ic = ( int ) ( P * 0.1 );
    }
  else
    {
      ic = ( int ) ( -P * 0.1 );
    }
  sprintf ( target, "%03d", ic % 1000 );
  return target;
}
Referenced by buoy_parse_x10(), and syn_parse_x10().
pascal_to_PPPP()
char * pascal_to_PPPP (char * target, double P)
Converts pascal values into a PPPP string.
Parameters
P the pressure variation in Pascal units
target string with the result
Definition at line 69 of file bufr2tac_x10.c.
{
  int ic;
  ic = ( int ) ( P * 0.1 );
  sprintf ( target, "%04d", ic % 10000 );
  return target;
}
Referenced by buoy_parse_x10(), climat_parse_x10(), and syn_parse_x10().
syn_parse_x10()
int syn_parse_x10 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
syn pointer to a s if (BUFR2TAC_DEBUG_LEVEL > 0) bufr2tac_set_error (s, 0, "syn_parse_x08()", "Descriptor not parsed"); truct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 87 of file bufr2tac_x10.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 4: // 0 10 004 . Pressure
      pascal_to_PPPP ( aux, s->val );
      strcpy ( syn->s1.PoPoPoPo, aux );
      syn->mask |= SYNOP_SEC1;
      break;
    case 9: // 0 10 009. Geopotential at standard level
      sprintf ( syn->s1.hhh, "%03d", abs(s->ival) % 1000 );
      syn->mask |= SYNOP_SEC1;
      break;
    case 51: // 0 10 051 . Pressure reduced to mean sea level
      pascal_to_PPPP ( aux, s->val );
      memcpy ( syn->s1.PPPP, aux, 4 );
      syn->s1.PPPP[4] = 0;
      syn->mask |= SYNOP_SEC1;
      break;
    case 61: // 0 10 061 . 3-hour pressure change
      pascal_to_ppp ( aux, s->val );
      memcpy(syn->s1.ppp, aux, 3);
      syn->s1.ppp[3] = 0;
      syn->mask |= SYNOP_SEC1;
      break;
    case 62: // 0 10 062 . 24-hour pressure change
      pascal_to_ppp ( aux, s->val );
      memcpy ( syn->s3.ppp24, aux, 3 );
      syn->s3.ppp24[3] = 0;
      if ( s->val >= 0 )
        {
          strcpy ( syn->s3.snp24, "8" );
        }
      else
        {
          strcpy ( syn->s3.snp24, "9" );
        }
      syn->mask |= SYNOP_SEC3;
      break;
    case 63: // 0 10 063 . Characteristic of pressure tendency
      if ( s->ival > 9 || s->ival < 0)
        return 1;
      sprintf ( syn->s1.a, "%1d",s->ival );
      syn->mask |= SYNOP_SEC1;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x10()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, synop_sec1::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec1::hhh, bufr2tac_subset_state::ival, bufr_atom_data::mask, synop_chunks::mask, pascal_to_ppp(), pascal_to_PPPP(), synop_sec1::PoPoPoPo, synop_sec1::ppp, synop_sec3::ppp24, synop_sec1::PPPP, synop_chunks::s1, synop_chunks::s3, synop_sec3::snp24, SYNOP_SEC1, SYNOP_SEC3, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x10()
int temp_parse_x10 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 297 of file bufr2tac_x10.c.
{
  if ( t == NULL || s == NULL )
    {
      return 1;
    }
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 9: // 0 10 009. geopotential
      if ( s->rep > 0 && s->r->n > 0 )
        {
          s->r->raw[s->r->n - 1].h = s->val;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x10()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_raw_point_data::h, bufr_atom_data::mask, temp_raw_data::n, bufr2tac_subset_state::r, temp_raw_data::raw, bufr2tac_subset_state::rep, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().