bufr2synop: src/libraries/bufr2syn_x05.c File Reference
bufr2syn_x05.c File Reference
decodes the descriptors with X = 05 (Position)
#include "bufr2syn.h"
Functions
int syn_parse_x05 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 05.
int buoy_parse_x05 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 05.
Detailed Description
decodes the descriptors with X = 05 (Position)
Definition in file bufr2syn_x05.c.
Function Documentation
int buoy_parse_x05 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 05.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 103 of file bufr2syn_x05.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec0::LaLaLaLaLa, bufr_subset_state::lat, buoy_sec0::LoLoLoLoLoLo, bufr_subset_state::lon, bufr_atom_data::mask, bufr_subset_state::mask, buoy_chunks::s0, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 05 001
     case 2: // 0 05 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LATITUDE_SOUTH; // Sign for latitude
       s->mask |= SUBSET_MASK_HAVE_LATITUDE;
       ia = (int) (fabs(s->val) * 1000.0 + 0.5);
       sprintf(b->s0.LaLaLaLaLa, "%05d",ia);
       s->lat = s->val;
       break;
     case 11: // 0 05 001
     case 12: // 0 05 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = (int) (fabs(s->val) * 1000.0 + 0.5);
       sprintf(b->s0.LoLoLoLoLoLo, "%06d",ia);
       s->lon = s->val;
     break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x05 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 05.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 35 of file bufr2syn_x05.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::LaLaLa, bufr_subset_state::lat, latlon_to_MMM(), synop_sec0::LoLoLoLo, bufr_subset_state::lon, bufr_atom_data::mask, bufr_subset_state::mask, synop_sec0::MMM, synop_sec0::Qc, synop_chunks::s0, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, synop_sec0::Ula, synop_sec0::Ulo, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 05 001
     case 2: // 0 05 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LATITUDE_SOUTH; // Sign for latitude
       s->mask |= SUBSET_MASK_HAVE_LATITUDE;
       ia = (int) (fabs(s->val) * 10.0 + 0.5);
       sprintf(syn->s0.LaLaLa, "%03d",ia);
       syn->s0.Ula[0] = syn->s0.LaLaLa[1];
       s->lat = s->val;
     break;
     case 11: // 0 05 011
     case 12: // 0 05 012
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = (int) (fabs(s->val) * 10.0 + 0.5);
       sprintf(syn->s0.LoLoLoLo, "%04d",ia);
       syn->s0.Ulo[0] = syn->s0.LoLoLoLo[2];
       s->lon = s->val;
     break;
     default:
       break;
     }
   // check if set both LaLaLa and LoLoLoLo to set Qc
   if ((syn->s0.Qc[0] == 0) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0])
   {
     if (s->mask & SUBSET_MASK_LATITUDE_SOUTH)
     {
        if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
          strcpy(syn->s0.Qc, "5");
        else
          strcpy(syn->s0.Qc, "3");
     }
     else
     {
        if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
          strcpy(syn->s0.Qc, "7");
        else
         strcpy(syn->s0.Qc, "1");
     }
   }
   // check if about MMM
   if ((syn->s0.MMM[0] == 0) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0])
   {
      latlon_to_MMM(syn->s0.MMM, s->lat, s->lon);
   }
   return 0;
 }