bufr2synop: src/bufrdeco/bufrdeco_tablec.c File Reference
bufrdeco_tablec.c File Reference
file with the code to read table C data (code and flag tables)
#include "bufrdeco.h"
Functions
int bufr_read_tablec (struct bufr_tablec *tc, char *error)
Reads a file with table C content according with ECMWF format.
int bufr_find_tablec_index (size_t *index, struct bufr_tablec *tc, const char *key)
Find the index of a line in table C for a given key of a descriptor.
char * bufrdeco_explained_table_val (char *expl, size_t dim, struct bufr_tablec *tc, size_t *index, struct bufr_descriptor *d, uint32_t ival)
char * bufrdeco_explained_flag_val (char *expl, size_t dim, struct bufr_tablec *tc, struct bufr_descriptor *d, uint64_t ival, uint8_t nbits)
Detailed Description
file with the code to read table C data (code and flag tables)
Definition in file bufrdeco_tablec.c.
Function Documentation
int bufr_find_tablec_index (size_t * index, struct bufr_tablec * tc, const char * key)
Find the index of a line in table C for a given key of a descriptor.
Parameters
index pointer where to set the result
tc pointer to a struct bufr_tablec where all table data is stored
key string in the form FXXYYY which is the key of descriptor we want to find out
If the descriptor has been found with success then returns 0, othewise returns 1
Definition at line 99 of file bufrdeco_tablec.c.
References bufr_descriptor::c, bufr_tablec::l, bufr_tablec::num, bufr_descriptor::x, and bufr_tablec::x_start.
Referenced by bufrdeco_explained_table_val().
 {
   size_t i, i0;
   size_t x = 0;
   char *c, aux[8];
   aux[0] = key[1];
   aux[1] = key[2];
   aux[2] = '\0';
   x = strtoul ( aux, &c, 10 );
   i0 = tc->x_start[x];
   for ( i = i0 ; i < i0 + tc->num[x] ; i++ )
     {
       if ( tc->l[i][0] != key[0] ||
            tc->l[i][1] != key[1] ||
            tc->l[i][2] != key[2] ||
            tc->l[i][3] != key[3] ||
            tc->l[i][4] != key[4] ||
            tc->l[i][5] != key[5] )
         {
           continue;
         }
       else
         {
           *index = i;
           return 0;
         }
     }
   return 1; // not found
 }
int bufr_read_tablec (struct bufr_tablec * tc, char * error)
Reads a file with table C content according with ECMWF format.
Parameters
tc pointer to a target struct bufr_tablec
error string where to set error if any
If succeded return 0, otherwise 1
Definition at line 34 of file bufrdeco_tablec.c.
References BUFR_MAXLINES_TABLEC, bufr_descriptor::c, bufr_tablec::l, bufr_tablec::nlines, bufr_tablec::num, bufr_tablec::old_path, bufr_tablec::path, bufr_tablec::wmo_table, and bufr_tablec::x_start.
Referenced by bufr_read_tables_ecmwf().
 {
   char aux[8], *c;
   size_t startx = 0;
   FILE *t;
   size_t i = 0;
   char caux[256];
   if ( tc->path == NULL )
     {
       return 1;
     }
   // If we've already readed this table.
   if ( strcmp ( tc->path, tc->old_path ) == 0 )
     {
       return 0; // all done
     }
   strcpy ( caux, tc->path );
   memset ( tc, 0, sizeof ( struct bufr_tablec ) );
   strcpy ( tc->path,caux );
   if ( ( t = fopen ( tc->path, "r" ) ) == NULL )
     {
       sprintf ( error,"Unable to open table C file '%s'\n", tc->path );
       return 1;
     }
   while ( fgets ( tc->l[i], 96, t ) != NULL && i < BUFR_MAXLINES_TABLEC )
     {
       // supress the newline
       if ( ( c = strrchr ( tc->l[i],'\n' ) ) != NULL )
         {
           *c = '\0';
         }
       if ( tc->l[i][1] != ' ' && tc->l[i][2] != ' ' )
         {
           aux[0] = tc->l[i][1];
           aux[1] = tc->l[i][2];
           aux[2] = '\0';
           startx = strtoul ( aux, &c, 10 );
           if ( tc->x_start[startx] == 0 )
             {
               tc->x_start[startx] = i;  // marc the start
             }
         }
       ( tc->num[startx] ) ++;
       i++;
     }
   fclose ( t );
   tc->nlines = i;
   tc->wmo_table = 0;
   strcpy ( tc->old_path, tc->path ); // store latest path
   return 0;
 }
char* bufrdeco_explained_flag_val (char * expl, size_t dim, struct bufr_tablec * tc, struct bufr_descriptor * d, uint64_t ival, uint8_t nbits)
Definition at line 227 of file bufrdeco_tablec.c.
References bufrdeco_explained_flag_csv_val(), bufr_descriptor::c, bufr_tablec::l, bufr_tablec::nlines, and bufr_tablec::wmo_table.
Referenced by bufrdeco_get_atom_data_from_compressed_data_ref(), and bufrdeco_tableb_val().
 {
   char *c, *s;
   uint64_t test, test0;
   uint64_t nb, nx, v,  nl;
   size_t i, j;
   if ( tc->wmo_table )
     { // WMO case
       return bufrdeco_explained_flag_csv_val ( expl, dim, tc, d, ival, nbits );
     }
   // Find first line for descriptor
   for ( i = 0; i <  tc->nlines; i++ )
     {
       if ( tc->l[i][0] != d->c[0] ||
            tc->l[i][1] != d->c[1] ||
            tc->l[i][2] != d->c[2] ||
            tc->l[i][3] != d->c[3] ||
            tc->l[i][4] != d->c[4] ||
            tc->l[i][5] != d->c[5] )
         {
           continue;
         }
       else
         {
           break;
         }
     }
   if ( i == tc->nlines )
     {
       //printf("Descriptor %s No encontrado\n", d->c);
       return NULL;
     }
   //printf("Descriptor %s en linea %d\n", d->c, i);
   // reads the amount of possible bits
   if ( tc->l[i][7] != ' ' )
     {
       nb = strtoul ( &tc->l[i][7], &c, 10 );
     }
   else
     {
       return NULL;
     }
   // read a value
   s = expl;
   s[0] = '\0';
   for ( j = 0, test0 = 1; j < nb && i < tc->nlines ; i++ )
     {
       if ( tc->l[i][12] != ' ' )
         {
           v = strtol ( &tc->l[i][12], &c, 10 ); // v is the bit number
           j++;
           // case 0 with meaning
           if ( v == 0 )
             {
               test0 = 1;
               if ( ival == 0 )
                 {
                   nl = strtoul ( &tc->l[i][21], &c, 10 );
                   if ( strlen ( expl ) && ( strlen ( expl ) + 1 ) < dim )
                     {
                       s += sprintf ( s, "|" );
                     }
                   s += sprintf ( s,"%s", &tc->l[i][24] );
                   if ( nl > 1 )
                     {
                       for ( nx = 1 ; nx < nl; nx++ )
                         if ( ( strlen ( expl ) + strlen ( &tc->l[i + nx][22] ) )  < dim )
{
                             s += sprintf ( s, "%s", &tc->l[i + nx][22] );
                           }
                     }
                   return expl;
                 }
             }
           test = test0 << ( nbits - v );
           if ( v && ( test & ival ) != 0 )
             {
               // bit match
               // read how many lines for the descriptors
               nl = strtol ( &tc->l[i][21], &c, 10 );
               if ( strlen ( expl ) && ( strlen ( expl ) + 1 ) < dim )
                 {
                   s += sprintf ( s, "|" );
                 }
               s += sprintf ( s,"%s", &tc->l[i][24] );
               if ( nl > 1 )
                 {
                   for ( nx = 1 ; nx < nl; nx++ )
                     if ( ( strlen ( expl ) + strlen ( &tc->l[i + nx][22] ) )  < dim )
                       {
                         s += sprintf ( s, "%s", &tc->l[i + nx][22] );
                       }
                 }
             }
           else
             {
               continue;
             }
         }
     }
   // if match then we have finished the search
   return expl;
 }
char* bufrdeco_explained_table_val (char * expl, size_t dim, struct bufr_tablec * tc, size_t * index, struct bufr_descriptor * d, uint32_t ival)
Definition at line 143 of file bufrdeco_tablec.c.
References bufr_find_tablec_index(), bufrdeco_explained_table_csv_val(), bufr_descriptor::c, bufr_tablec::l, bufr_tablec::nlines, and bufr_tablec::wmo_table.
Referenced by bufrdeco_get_atom_data_from_compressed_data_ref(), and bufrdeco_tableb_val().
 {
   char *c;
   uint32_t nv, v,  nl;
   size_t  i, j;
   if ( tc->wmo_table )
     { // WMO case
       return bufrdeco_explained_table_csv_val ( expl, dim, tc, index, d, ival );
     }
   if ( *index == 0 )
     {
       // here the calling b item learn where to find table C line
       if ( bufr_find_tablec_index ( index, tc, d->c ) )
         {
           //sprintf ( b->error, "bufrdeco_explained_table_val(): descriptor '%s' not found in table D\n", d->c );
           return NULL; // descritor not found
         }
     }
   i = *index;
   // reads the amount of possible values
   if ( tc->l[i][7] != ' ' )
     {
       nv = strtoul ( &tc->l[i][7], &c, 10 );
     }
   else
     {
       return NULL;
     }
   // read a value
   for ( j = 0; j < nv && i < tc->nlines ; i++ )
     {
       if ( tc->l[i][12] != ' ' )
         {
           v = strtoul ( &tc->l[i][12], &c, 10 );
           j++;
           if ( v != ival )
             {
               continue;
             }
           break;
         }
     }
   if ( j == nv || i == tc->nlines )
     {
       return NULL;  // Value not found
     }
   // read how many lines for the descriptors
   nl = strtoul ( &tc->l[i][21], &c, 10 );
   // if match then we have finished the search
   strcpy ( expl, &tc->l[i][24] );
   if ( nl > 1 )
     {
       for ( nv = 1 ; nv < nl; nv++ )
         if ( ( strlen ( expl ) + strlen ( &tc->l[i + nv][22] ) ) < dim )
           {
             strcat ( expl, &tc->l[i + nv][22] );
           }
     }
   return expl;
 }