bufr2synop: src/libraries/bufr2tac_x04.c File Reference
bufr2tac_x04.c File Reference
decodes the descriptors with X = 04 (date and time)
#include "bufr2tac.h"
Functions
int time_period_duration (struct bufr2tac_subset_state *s)
Get time period duration in seconds.
int hour_rounded (struct synop_chunks *syn)
Get the rounded hour of a given date.
int syn_parse_x04 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 04.
int buoy_parse_x04 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 04.
int climat_parse_x04 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 04.
int temp_parse_x04 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 04.
Detailed Description
decodes the descriptors with X = 04 (date and time)
Definition in file bufr2tac_x04.c.
Function Documentation
buoy_parse_x04()
int buoy_parse_x04 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 04.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 248 of file bufr2tac_x04.c.
{
  switch ( s->a->desc.y )
    {
    case 1: // 0 04 001 . Year
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( b->e.YYYY[0] == 0 )
        {
          sprintf ( b->e.YYYY, "%04d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_YEAR;
      break;
    case 2: // 0 04 002 . Month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( b->e.MM[0] == 0 )
        {
          sprintf ( b->e.MM, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_MONTH;
      break;
    case 3: // 0 04 003 . Day of month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( b->e.DD[0] == 0 )
        {
          sprintf ( b->e.DD, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_DAY;
      //sprintf(b->s0.YY, "%02d", (int) sq->sequence[is].val);
      break;
    case 4: // 0 04 004 . Hour
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( b->e.HH[0] == 0 )
        {
          sprintf ( b->e.HH, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_HOUR;
      //sprintf(b->s0.GG, "%02d", (int) sq->sequence[is].val);
      break;
    case 5: // 0 04 005 . Minute
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( b->e.mm[0] == 0 )
        {
          sprintf ( b->e.mm, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_MINUTE;
      break;
    // store latest displacement in seconds
    case 23: // 0 04 023 . Time period of displacement (days)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->k_itval = s->i;
      s->itval = s->ival * 86400;
      break;
    case 24: // 0 04 024 . Time period of displacement (hours)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->k_itval = s->i;
      s->itval = s->ival * 3600;
      break;
    case 25: // 0 04 025 . Time period of displacement (minutes)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->k_itval = s->i;
      s->itval = s->ival * 60;
      break;
    case 26: // 0 04 026 .  Time period of displacement (seconds)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->k_itval = s->i;
      s->itval = s->ival;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x04()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_chunks::e, report_date_ext::HH, bufr2tac_subset_state::i, bufr2tac_subset_state::itval, bufr2tac_subset_state::ival, bufr2tac_subset_state::jtval, bufr2tac_subset_state::k_itval, bufr2tac_subset_state::k_jtval, bufr_atom_data::mask, bufr2tac_subset_state::mask, report_date_ext::MM, report_date_ext::mm, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_MINUTE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_YEAR, bufr_descriptor::y, and report_date_ext::YYYY.
Referenced by parse_subset_as_buoy().
climat_parse_x04()
int climat_parse_x04 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 04.
Parameters
c pointer to a struct climat_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 392 of file bufr2tac_x04.c.
{
  if ( c == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 04 001 .Year
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( s->i && ( s->a1->desc.x == 4 ) && ( s->a1->desc.y == 1 ) )
        {
          // this is the final year of a normal period
          s->is_normal = 1;
          sprintf ( c->s2.YcYc, "%02d", s->ival % 100 );
          // then we fill the begin from tatest descriptor
          sprintf ( c->s2.YbYb, "%02d", ( int ) s->a1->val % 100 );
        }
      else if ( c->e.YYYY[0] == '\0' )
        {
          sprintf ( c->e.YYYY, "%04d", s->ival );
          s->mask |= SUBSET_MASK_HAVE_YEAR;
          sprintf ( c->s0.JJJ, "%03d", abs(s->ival) % 1000 );
          c->mask |= CLIMAT_SEC0;
        }
      break;
    case 2: // 0 04 002 . Month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( c->e.MM, "%02d", s->ival );
      s->mask |= SUBSET_MASK_HAVE_MONTH;
      sprintf ( c->s0.MM, "%02d", s->ival );
      c->mask |= CLIMAT_SEC0;
      break;
    case 3: // 0 04 003 . Day of month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( c->e.DD[0] == 0 )
        {
          sprintf ( c->e.DD, "%02d", s->ival );
        }
      if ( s->a1->desc.x == 8 && s->a1->desc.y == 53 )
        {
          s->more_days = s->isq_val;
        }
      s->day = s->ival;
      s->mask |= SUBSET_MASK_HAVE_DAY;
      break;
    case 4: // 0 04 004 . Hour
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( c->e.HH[0] == 0 )
        {
          sprintf ( c->e.HH, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_HOUR;
      break;
    case 5: // 0 04 005 . Minute
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( c->e.mm[0] == 0 )
        {
          sprintf ( c->e.mm, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_MINUTE;
      break;
    case 22: // 0 04 022 . Num month. Case of sec2 with normals
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      s->month = s->ival;
      break;
    case 23: // 0 04 023 . Num days in month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( s->nday == 0 )
        {
          s->nday = s->ival;
        }
      break;
    case 51: // 0 04 051 . Principal time of daily reading of maximum
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( c->s4.GxGx, "%02d", s->ival );
      s->mask |= CLIMAT_SEC4;
      break;
    case 52: // 0 04 052 . Principal time of daily reading of minimum
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( c->s4.GnGn, "%02d", s->ival );
      s->mask |= CLIMAT_SEC4;
      break;
    case 53: // 0 04 053 . Number of days with precipitation equal to or more than 1 mm
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( s->is_normal == 0 )
        {
          sprintf ( c->s1.nrnr, "%02d", s->ival );
          s->mask |= CLIMAT_SEC1;
        }
      else
        {
          sprintf ( c->s2.nrnr, "%02d", s->ival );
          s->mask |= CLIMAT_SEC2;
        }
      break;
    case 74: // 0 04 074 . (UTC - LST)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      s->dift = s->ival;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x04()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, bufr2tac_subset_state::a1, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), CLIMAT_SEC0, CLIMAT_SEC1, CLIMAT_SEC2, CLIMAT_SEC4, bufr2tac_subset_state::day, report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::dift, climat_chunks::e, climat_sec4::GnGn, climat_sec4::GxGx, report_date_ext::HH, bufr2tac_subset_state::i, bufr2tac_subset_state::is_normal, bufr2tac_subset_state::isq_val, bufr2tac_subset_state::ival, climat_sec0::JJJ, bufr_atom_data::mask, bufr2tac_subset_state::mask, climat_chunks::mask, climat_sec0::MM, report_date_ext::MM, report_date_ext::mm, bufr2tac_subset_state::month, bufr2tac_subset_state::more_days, bufr2tac_subset_state::nday, climat_sec1::nrnr, climat_sec2::nrnr, climat_chunks::s0, climat_chunks::s1, climat_chunks::s2, climat_chunks::s4, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_MINUTE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_YEAR, bufr_atom_data::val, bufr_descriptor::x, bufr_descriptor::y, climat_sec2::YbYb, climat_sec2::YcYc, and report_date_ext::YYYY.
Referenced by parse_subset_as_climat().
hour_rounded()
int hour_rounded (struct synop_chunks * syn)
Get the rounded hour of a given date.
Parameters
syn pointer to the synop_chunks struct
It returns the rounded hour if >= 0. If < 0 problems
Definition at line 78 of file bufr2tac_x04.c.
{
  time_t t;
  struct tm tim;
  char aux[32];
  sprintf ( aux, "%s%s%s%s%s", syn->e.YYYY,syn->e.MM,syn->e.DD,syn->e.HH, syn->e.mm );
  memset ( &tim, 0, sizeof ( struct tm ) );
  if ( strlen ( aux ) == 12 )
    {
      strptime ( aux, "%Y%m%d%H%M", &tim );
      t = mktime ( &tim );
      t += 1800;
      gmtime_r ( &t, &tim );
      return tim.tm_hour;
    }
  else if ( syn->e.mm[0] == 0 && syn->e.HH[0] )
    {
      return atoi ( syn->e.HH );
    }
  else
    return -1;
}
References report_date_ext::DD, synop_chunks::e, report_date_ext::HH, report_date_ext::MM, report_date_ext::mm, and report_date_ext::YYYY.
Referenced by syn_parse_x13().
syn_parse_x04()
int syn_parse_x04 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 04.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 110 of file bufr2tac_x04.c.
{
  switch ( s->a->desc.y )
    {
    case 1: // 0 04 001 .Year
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( syn->e.YYYY, "%04d", s->ival );
      s->mask |= SUBSET_MASK_HAVE_YEAR;
      break;
    case 2: // 0 04 002 . Month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( syn->e.MM, "%02d", s->ival );
      s->mask |= SUBSET_MASK_HAVE_MONTH;
      break;
    case 3: // 0 04 003 . Day of month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( syn->e.DD, "%02d", s->ival );
      s->mask |= SUBSET_MASK_HAVE_DAY;
      break;
    case 4: // 0 04 004 . Hour
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( syn->e.HH, "%02d", s->ival );
      s->mask |= SUBSET_MASK_HAVE_HOUR;
      break;
    case 5: // 0 04 005 . Minute
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      sprintf ( syn->e.mm, "%02d", s->ival );
      s->mask |= SUBSET_MASK_HAVE_MINUTE;
      break;
    // store latest displacement in seconds
    case 23: // 0 04 023 . Time period of displacement (days)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->jtmask = s->itmask;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->jtmask = s->itmask;
      s->k_itval = s->i;
      s->itmask = s->a->mask;
      s->itval = s->ival * 86400;
      break;
    case 24: // 0 04 024 .  Time period of displacement (hours)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->jtmask = s->itmask;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->jtmask = s->itmask;
      s->k_itval = s->i;
      s->itmask = s->a->mask;
      s->itval = s->ival * 3600;
      break;
    case 25: // 0 04 025  Time period of displacement (minutes)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->jtmask = s->itmask;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->jtmask = s->itmask;
      s->k_itval = s->i;
      s->itmask = s->a->mask;
      s->itval = s->ival * 60;
      break;
    case 26: // 0 04 026 .  Time period of displacement (seconds)
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          s->k_jtval = s->k_itval;
          s->jtval = s->itval;
          s->jtmask = s->itmask;
          s->k_itval = s->i;
          s->itval = 0;
          return 0;
        }
      s->k_jtval = s->k_itval;
      s->jtval = s->itval;
      s->jtmask = s->itmask;
      s->k_itval = s->i;
      s->itmask = s->a->mask;
      s->itval = s->ival;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x04()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_chunks::e, report_date_ext::HH, bufr2tac_subset_state::i, bufr2tac_subset_state::itmask, bufr2tac_subset_state::itval, bufr2tac_subset_state::ival, bufr2tac_subset_state::jtmask, bufr2tac_subset_state::jtval, bufr2tac_subset_state::k_itval, bufr2tac_subset_state::k_jtval, bufr_atom_data::mask, bufr2tac_subset_state::mask, report_date_ext::MM, report_date_ext::mm, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_MINUTE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_YEAR, bufr_descriptor::y, and report_date_ext::YYYY.
Referenced by parse_subset_as_synop().
temp_parse_x04()
int temp_parse_x04 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 04.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 555 of file bufr2tac_x04.c.
{
  switch ( s->a->desc.y )
    {
    case 1: // 0 04 001 . Year
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( t->a.e.YYYY[0] == 0 )
        {
          sprintf ( t->a.e.YYYY, "%04d", s->ival );
          sprintf ( t->b.e.YYYY, "%04d", s->ival );
          sprintf ( t->c.e.YYYY, "%04d", s->ival );
          sprintf ( t->d.e.YYYY, "%04d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_YEAR;
      break;
    case 2: // 0 04 002 . Month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( t->a.e.MM[0] == 0 )
        {
          sprintf ( t->a.e.MM, "%02d", s->ival );
          sprintf ( t->b.e.MM, "%02d", s->ival );
          sprintf ( t->c.e.MM, "%02d", s->ival );
          sprintf ( t->d.e.MM, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_MONTH;
      break;
    case 3: // 0 04 003 . Day of month
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( t->a.e.DD[0] == 0 )
        {
          sprintf ( t->a.e.DD, "%02d", s->ival );
          sprintf ( t->b.e.DD, "%02d", s->ival );
          sprintf ( t->c.e.DD, "%02d", s->ival );
          sprintf ( t->d.e.DD, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_DAY;
      //sprintf(t->s0.YY, "%02d", (int) sq->sequence[is].val);
      break;
    case 4: // 0 04 004 . Hour
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( t->a.e.HH[0] == 0 )
        {
          sprintf ( t->a.e.HH, "%02d", s->ival );
          sprintf ( t->b.e.HH, "%02d", s->ival );
          sprintf ( t->c.e.HH, "%02d", s->ival );
          sprintf ( t->d.e.HH, "%02d", s->ival );
          sprintf ( t->a.s7.GG, "%02d", s->ival );
          sprintf ( t->b.s7.GG, "%02d", s->ival );
          sprintf ( t->c.s7.GG, "%02d", s->ival );
          sprintf ( t->d.s7.GG, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_HOUR;
      //sprintf(t->s0.GG, "%02d", (int) sq->sequence[is].val);
      break;
    case 5: // 0 04 005 . Minute
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( t->a.e.mm[0] == 0 )
        {
          sprintf ( t->a.e.mm, "%02d", s->ival );
          sprintf ( t->b.e.mm, "%02d", s->ival );
          sprintf ( t->c.e.mm, "%02d", s->ival );
          sprintf ( t->d.e.mm, "%02d", s->ival );
          sprintf ( t->a.s7.gg, "%02d", s->ival );
          sprintf ( t->b.s7.gg, "%02d", s->ival );
          sprintf ( t->c.s7.gg, "%02d", s->ival );
          sprintf ( t->d.s7.gg, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_MINUTE;
      break;
    case 6: // 0 04 006 . Second
      if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
        {
          return 0;
        }
      if ( t->a.e.ss[0] == 0 )
        {
          sprintf ( t->a.e.ss, "%02d", s->ival );
          sprintf ( t->b.e.ss, "%02d", s->ival );
          sprintf ( t->c.e.ss, "%02d", s->ival );
          sprintf ( t->d.e.ss, "%02d", s->ival );
        }
      s->mask |= SUBSET_MASK_HAVE_SECOND;
      break;
    case 86: // 0 04 086 . Long time period or displacement (since launch time)
      // s->rep is used to check what type of point we are dealing from
      // see repliator 0 31 001 and 0 31 002 to understand it better
      // Because this is the first descriptor in a sequence for a point, we use this
      // descriptor to set properly the current index
      if ( s->rep > 0 )
        {
          // case of Temperature, humidty ... point
          if ( ( int ) s->r->n < s->rep )
            {
              // Because of there are bufr reports with a lot of not significant points
              // we only collect the first one and significant points, i.e. those that flags are non zero
              // When flags are zero we just overwrite points
              if ( s->r->n < ( RAW_TEMP_NMAX_POINTS ) &&
                   ( s->r->n == 0 || s->r->raw[s->r->n - 1].flags ) )
                {
                  s->r->n += 1; // Here we update the index
                }
            }
          s->r->raw[s->r->n - 1].dt = s->ival;
        }
      else
        {
          // case of wind shear point
          if ( ( int ) s->w->n < s->itval )
            {
              s->w->n += 1;
            }
          s->w->raw[s->w->n - 1].dt = s->ival;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x04()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, temp_chunks::a, temp_chunks::b, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), temp_chunks::c, temp_chunks::d, report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_raw_point_data::dt, temp_raw_wind_shear_point::dt, temp_a::e, temp_b::e, temp_c::e, temp_d::e, temp_raw_point_data::flags, temp_sec7::GG, temp_sec7::gg, report_date_ext::HH, bufr2tac_subset_state::itval, bufr2tac_subset_state::ival, bufr_atom_data::mask, bufr2tac_subset_state::mask, report_date_ext::MM, report_date_ext::mm, temp_raw_data::n, temp_raw_wind_shear_data::n, bufr2tac_subset_state::r, temp_raw_data::raw, temp_raw_wind_shear_data::raw, RAW_TEMP_NMAX_POINTS, bufr2tac_subset_state::rep, temp_a::s7, temp_b::s7, temp_c::s7, temp_d::s7, report_date_ext::ss, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_MINUTE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_SECOND, SUBSET_MASK_HAVE_YEAR, bufr2tac_subset_state::w, bufr_descriptor::y, and report_date_ext::YYYY.
Referenced by parse_subset_as_temp().
time_period_duration()
int time_period_duration (struct bufr2tac_subset_state * s)
Get time period duration in seconds.
Parameters
s pinter to struct bufr2tac_subset_state
Returns -1 if no duration is computed. Otherwise returns time duration in seconds
Definition at line 33 of file bufr2tac_x04.c.
{
  if ( s->k_itval == ( s->k_jtval + 1 ) )
    {
      // two consecutive time period displacements
      if ( ( s->itmask & DESCRIPTOR_VALUE_MISSING ) == 0  &&
           ( s->jtmask & DESCRIPTOR_VALUE_MISSING ) == 0 )
        {
          return ( abs ( s->itval - s->jtval ) );
        }
      else if ( ( s->itmask & DESCRIPTOR_VALUE_MISSING )  &&
                ( s->jtmask & DESCRIPTOR_VALUE_MISSING ) )
        {
          return 0;
        }
      else if ( ( s->itmask & DESCRIPTOR_VALUE_MISSING ) == 0 &&
                ( s->jtmask & DESCRIPTOR_VALUE_MISSING ) )
        {
          return ( abs ( s->itval ) );
        }
      else if ( ( s->jtmask & DESCRIPTOR_VALUE_MISSING ) == 0 &&
                ( s->itmask & DESCRIPTOR_VALUE_MISSING ) )
        {
          return -1;
        }
    }
  // just a single time period displacement
  if ( ( s->itmask & DESCRIPTOR_VALUE_MISSING ) == 0 )
    {
      return ( abs ( s->itval ) );
    }
  else
    {
      return 0;
    }
}
References DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::itmask, bufr2tac_subset_state::itval, bufr2tac_subset_state::jtmask, bufr2tac_subset_state::jtval, bufr2tac_subset_state::k_itval, and bufr2tac_subset_state::k_jtval.
Referenced by syn_parse_x12(), syn_parse_x13(), and syn_parse_x14().