bufr2synop: src/libraries/bufr2syn_synop.c File Reference
bufr2syn_synop.c File Reference
file with the code to parse a sequence as a SYNOP FM-12, FM-13 and FM-14
#include "bufr2syn.h"
Functions
int synop_YYYYMMDDHHmm_to_YYGG (struct synop_chunks *syn)
Sets YYGG from YYYYMMDDHHmm extended group.
char * guess_WMO_region (struct synop_chunks *syn)
Try to find WMO region if it is not already set and WMO Block and number index are known.
int parse_subset_as_synop (struct metreport *m, struct synop_chunks *syn, struct bufr_subset_state *s, struct bufr_subset_sequence_data *sq, char *err)
Detailed Description
file with the code to parse a sequence as a SYNOP FM-12, FM-13 and FM-14
Definition in file bufr2syn_synop.c.
Function Documentation
char* guess_WMO_region (struct synop_chunks * syn)
Try to find WMO region if it is not already set and WMO Block and number index are known.
Parameters
syn pointer to the struct synop_chunks with all known data for a synop
It returns a pointer to the string with WMO region
Definition at line 64 of file bufr2syn_synop.c.
References synop_sec0::A1, synop_sec0::II, synop_sec0::iii, synop_sec0::Reg, and synop_chunks::s0.
Referenced by syn_parse_x12().
 {
   char aux[8];
   if (syn->s0.A1[0])
     {
       return syn->s0.A1;
     }
   if (syn->s0.II[0] == 0  || syn->s0.iii[0] == 0)
     return syn->s0.A1;
   sprintf(aux,"%s%s",syn->s0.II, syn->s0.iii);
   if ((syn->s0.II[0] == '0' && (strstr(aux,"042") != aux) && (strstr(aux,"043") != aux)  &&
        (strstr(aux,"044") != aux)  && (strstr(aux,"0858") != aux) &&  (strstr(aux,"0859") != aux)) ||
       syn->s0.II[0] == '1' || (strstr(aux,"201") == aux) ||
       strcmp(syn->s0.II,"22") == 0 || strcmp(syn->s0.II,"26") == 0 || strcmp(syn->s0.II,"27") == 0 ||
       strcmp(syn->s0.II,"33") == 0 || strcmp(syn->s0.II,"34") == 0 || strcmp(syn->s0.II,"22") == 0 ||
       (strstr(aux,"201") == aux))
     {
       // Reg 6. Europe
       syn->s0.A1[0] = '6';
       strcpy(syn->s0.Reg,"VI");
     }
   else if (syn->s0.II[0] == '6' || (strstr(aux,"0858") == aux) ||  (strstr(aux,"0859") == aux))
     {
       // Reg 1. Africa
       syn->s0.A1[0] = '1';
       strcpy(syn->s0.Reg,"I");
     }
   else if (syn->s0.II[0] == '5' || (strcmp(syn->s0.II,"49") == 0) || (strcmp(syn->s0.II,"21") == 0) ||
            (strcmp(syn->s0.II,"23") == 0) || (strcmp(syn->s0.II,"24") == 0) || (strcmp(syn->s0.II,"25") == 0) ||
            (strcmp(syn->s0.II,"28") == 0) || (strcmp(syn->s0.II,"29") == 0) || (strcmp(syn->s0.II,"30") == 0) ||
            (strcmp(syn->s0.II,"31") == 0) || (strcmp(syn->s0.II,"32") == 0) || (strcmp(syn->s0.II,"38") == 0) ||
            (strcmp(syn->s0.II,"35") == 0) || (strcmp(syn->s0.II,"36") == 0) || (strcmp(syn->s0.II,"39") == 0) ||
            (strcmp(aux, "20200") >= 0 && strcmp(aux, "20999") <= 0) ||
            (strcmp(aux, "40000") >= 0 && strcmp(aux, "48599") <= 0) ||
            (strcmp(aux, "48800") >= 0 && strcmp(aux, "49999") <= 0))
     {
       // Reg 2. Asia
       syn->s0.A1[0] = '2';
       strcpy(syn->s0.Reg,"II");
     }
   else if (strcmp(aux, "80000") >= 0 && strcmp(aux, "88999") <= 0)
     {
       // Reg 3. South america
       syn->s0.A1[0] = '3';
       strcpy(syn->s0.Reg,"III");
     }
   else if (syn->s0.II[0] == '7' || strstr(aux,"042") == aux ||
            strstr(aux,"043") == aux  || strstr(aux,"044") == aux)
     {
       // Reg 4. North and central america
       syn->s0.A1[0] = '4';
       strcpy(syn->s0.Reg,"IV");
     }
   else if ((strcmp(aux, "48600") >= 0 && strcmp(aux, "48799") <= 0) ||
            (strcmp(aux, "90000") >= 0 && strcmp(aux, "98999") <= 0))
     {
       // Reg 5. Pacific South
       syn->s0.A1[0] = '4';
       strcpy(syn->s0.Reg,"IV");
     }
   else if (strcmp(syn->s0.II,"89") == 0)
     {
       // Reg 0. Antarctica
       syn->s0.A1[0] = '0';
       strcpy(syn->s0.Reg,"0");
     }
   return syn->s0.A1;
 }
int parse_subset_as_synop (struct metreport * m, struct synop_chunks * syn, struct bufr_subset_state * s, struct bufr_subset_sequence_data * sq, char * err)
Definition at line 149 of file bufr2syn_synop.c.
References bufr_subset_state::a, bufr_subset_state::alt, met_geo::alt, clean_synop_chunks(), bufr_subset_state::country, met_geo::country, synop_sec0::D_D, report_date_ext::DD, bufr_atom_data::desc, synop_chunks::e, synop_sec1::ff, metreport::g, synop_sec1::GG, synop_sec1::gg, report_date_ext::HH, bufr_subset_state::i, synop_sec0::II, synop_sec0::iii, synop_sec0::IIIII, met_geo::index, synop_sec1::ir, bufr_subset_state::isq, bufr_subset_state::ival, synop_sec0::iw, synop_sec1::ix, bufr_subset_state::lat, met_geo::lat, bufr_subset_state::lon, met_geo::lon, synop_chunks::mask, bufr_subset_state::mask, synop_sec0::MiMi, synop_sec0::MjMj, report_date_ext::MM, report_date_ext::mm, bufr_subset_state::name, met_geo::name, bufr_subset_sequence_data::nd, synop_sec1::RRR, synop_sec3::RRR, synop_sec3::RRRR24, synop_chunks::s0, synop_chunks::s1, synop_chunks::s3, bufr_subset_sequence_data::sequence, SUBSET_MASK_HAVE_ALTITUDE, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2, SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW, SUBSET_MASK_HAVE_TYPE_STATION, SUBSET_MASK_HAVE_YEAR, syn_parse_x01(), syn_parse_x02(), syn_parse_x04(), syn_parse_x05(), syn_parse_x06(), syn_parse_x07(), syn_parse_x08(), syn_parse_x10(), syn_parse_x11(), syn_parse_x12(), syn_parse_x13(), syn_parse_x14(), syn_parse_x20(), syn_parse_x22(), syn_parse_x31(), SYNOP_EXT, synop_YYYYMMDDHHmm_to_YYGG(), metreport::t, bufr_subset_state::type, metreport::type, bufr_subset_state::type_report, bufr_atom_data::val, bufr_subset_state::val, bufr_descriptor::x, report_date_ext::YYYY, and YYYYMMDDHHmm_to_met_datetime().
Referenced by parse_subset_sequence().
 {
   int ival; // integer value for a descriptor
   size_t is;
   char aux[16];
   // clean data
   clean_synop_chunks ( syn );
   // reject if still not coded type
   if (strcmp(s->type_report,"AAXX") && strcmp(s->type_report,"BBXX"))
   {
     sprintf(err,"bufr2syn: parse_subset_as_synop(): '%s' reports still not decoded in this software", s->type_report);
     return 1;
   }
   syn->s0.MiMi[0] = s->type_report[0];
   syn->s0.MiMi[1] = s->type_report[1];
   syn->s0.MjMj[0] = s->type_report[2];
   syn->s0.MjMj[1] = s->type_report[3];
   strcpy(m->type, s->type_report);
   /**** First pass, sequential analysis *****/
   for ( is = 0; is < sq->nd; is++ )
     {
       // check if is a significance qualifier
       if (sq->sequence[is].desc.x == 8)
       {
         s->i = is;
         s->a = &sq->sequence[is];
         s->ival = ( int ) sq->sequence[is].val;
         s->val = sq->sequence[is].val;
         syn_parse_x08 ( syn, s);
       }
       if ( s->isq)   // case of an significance qualifier
         continue;
       s->i = is;
       s->ival = ( int ) sq->sequence[is].val;
       ival = ival;
       s->val = sq->sequence[is].val;
       s->a = &sq->sequence[is];
       switch ( sq->sequence[is].desc.x )
         {
         case 1: //localization descriptors
           syn_parse_x01 ( syn, s);
           break;
         case 2: //Date time descriptors
           syn_parse_x02 ( syn, s);
           break;
         case 4: //Date time descriptors
           syn_parse_x04 ( syn, s);
           break;
         case 5: //Position
           syn_parse_x05 ( syn, s);
           break;
         case 6: // Horizontal Position -2
           syn_parse_x06 ( syn, s);
           break;
         case 7: // Vertical position
           syn_parse_x07 ( syn, s);
           break;
         case 10: // Air Pressure descriptors
           syn_parse_x10 ( syn, s);
           break;
         case 11: // wind  data
           syn_parse_x11 ( syn, s);
           break;
         case 12: //Temperature descriptors
           syn_parse_x12 ( syn, s);
           break;
         case 13: // Humidity and precipitation data
           syn_parse_x13 ( syn, s);
           break;
         case 14: // Radiation
           syn_parse_x14 ( syn, s);
           break;
         case 20: // Cloud data
           syn_parse_x20 ( syn, s);
           break;
         case 22: // Oceanographic data
           syn_parse_x22 ( syn, s);
           break;
         case 31: // Replicators
           syn_parse_x31 ( syn, s);
           break;
         default:
           break;
         }
     }
   /* Check about needed descriptors */
   if (((s->mask & SUBSET_MASK_HAVE_LATITUDE) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_LONGITUDE) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_YEAR) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_MONTH) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_DAY) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_HOUR) == 0)
       )
       {
         sprintf(err,"bufr2syn: parse_subset_as_synop(): lack of mandatory descriptor in sequence");
         return 1;
       }
   if (strcmp(s->type_report, "AAXX") == 0 && (syn->s0.II[0] == 0 || syn->s0.iii[0] == 0))
     {
        sprintf(err,"bufr2syn: parse_subset_as_synop(): lack of mandatory index station for AAXX report");
        return 1;
     }
   /****** Second pass. Global results and consistence analysis ************/
   // set ir
   if ( syn->s1.RRR[0] == 0 && syn->s3.RRR[0] == 0 && syn->s3.RRRR24[0] == 0 )
     {
       // no prec data case
       syn->s1.ir[0] = '4';
     }
   else if ( syn->s1.RRR[0] == 0 && syn->s3.RRR[0] != 0 )
     syn->s1.ir[0] = '2';
   else if ( syn->s1.RRR[0] != 0 && syn->s3.RRR[0] == 0 )
     syn->s1.ir[0] = '1';
   else
     syn->s1.ir[0] = '0';
   // adjust iw
   if ( syn->s0.iw[0] == '/' && syn->s1.ff[0] != '/' )
     syn->s0.iw[0] = '1';
   // adjust ix
   if (syn->s1.ix[0] == '/' /*&& syn->s1.ww[0] == 0*/)
     {
       if ((s->mask & SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW) &&
           (s->mask & SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1) &&
           (s->mask & SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2)
          )
         {
           if (s->mask & SUBSET_MASK_HAVE_TYPE_STATION)
             {
               if (s->type == 1 || s->type == 2)
                 strcpy(syn->s1.ix,"2");
               else if (s->type == 0)
                 strcpy(syn->s1.ix,"5");
             }
           else
             strcpy(syn->s1.ix,"6"); //NOTE: here we assume an automatic station without W data
         }
       else if (s->mask & SUBSET_MASK_HAVE_TYPE_STATION)
         {
           if (s->type == 1)
             strcpy(syn->s1.ix,"3");
           else if (s->type == 0)
             strcpy(syn->s1.ix,"6");
         }
       else
         strcpy(syn->s1.ix,"6"); //NOTE: here we assume an automatic station without W data
     }
   /****** Final Adjust ***********/
   // fix YYGG according with YYYYMMDDHHmm
   synop_YYYYMMDDHHmm_to_YYGG ( syn );
   if ( strcmp(syn->e.mm,"00"))
     {
       strcpy ( syn->s1.GG, syn->e.HH );
       strcpy ( syn->s1.gg, syn->e.mm );
     }
   syn->mask |= SYNOP_EXT;
   // Fill some metreport fields
   if (strlen(syn->s0.II))
   {
     strcpy(m->g.index, syn->s0.II);
     strcat(m->g.index, syn->s0.iii);
   }
   else if (strlen(syn->s0.D_D))
   {
     strcpy(m->g.index, syn->s0.D_D);
   }
   else if (strlen(syn->s0.IIIII))
   {
     strcpy(m->g.index, syn->s0.IIIII);
   }
   if (s->mask & SUBSET_MASK_HAVE_LATITUDE)
     m->g.lat = s->lat;
   if (s->mask & SUBSET_MASK_HAVE_LONGITUDE)
     m->g.lon = s->lon;
   if (s->mask & SUBSET_MASK_HAVE_ALTITUDE)
     m->g.alt = s->alt;
   if (s->mask & SUBSET_MASK_HAVE_NAME)
     strcpy(m->g.name, s->name);
   if (s->mask & SUBSET_MASK_HAVE_COUNTRY)
     strcpy(m->g.country, s->country);
   sprintf ( aux,"%s%s%s%s%s", syn->e.YYYY, syn->e.MM, syn->e.DD, syn->e.HH, syn->e.mm );
   YYYYMMDDHHmm_to_met_datetime(&m->t, aux);
   return 0;
 }
int synop_YYYYMMDDHHmm_to_YYGG (struct synop_chunks * syn)
Sets YYGG from YYYYMMDDHHmm extended group.
Parameters
syn pointer to the target struct synop_chunks
Definition at line 31 of file bufr2syn_synop.c.
References report_date_ext::DD, synop_chunks::e, synop_sec0::GG, report_date_ext::HH, report_date_ext::MM, report_date_ext::mm, synop_chunks::s0, synop_sec0::YY, and report_date_ext::YYYY.
Referenced by parse_subset_as_synop().
 {
   char aux[20];
   time_t t;
   struct tm tim;
   if ( strlen ( syn->e.YYYY ) &&
        strlen ( syn->e.MM ) &&
        strlen ( syn->e.DD ) &&
        strlen ( syn->e.HH ) &&
        strlen ( syn->e.mm ) )
     sprintf ( aux,"%s%s%s%s%s", syn->e.YYYY, syn->e.MM, syn->e.DD, syn->e.HH, syn->e.mm );
   if ( strlen ( aux ) != 12 )
     return 1;
   memset ( &tim, 0, sizeof ( struct tm ) );
   strptime ( aux, "%Y%m%d%H%M", &tim );
   t = mktime ( &tim ) + 1799 ; // rounding trick
   gmtime_r ( &t, &tim );
   sprintf ( syn->s0.YY, "%02d", tim.tm_mday );
   sprintf ( syn->s0.GG, "%02d", tim.tm_hour );
   return 0;
 }