bufr2synop: src/bufrdeco/bufrdeco_tablec_csv.c File Reference
bufrdeco_tablec_csv.c File Reference
file with the code to read table C (Code and flag tables from WMO files)
#include "bufrdeco.h"
Functions
int bufr_read_tablec_csv (struct bufr_tablec *tc, char *error)
Reads a file with table C content (Code table and bit flags) according with csv WMO format.
int bufr_find_tablec_csv_index (size_t *index, struct bufr_tablec *tc, const char *key, uint32_t code)
char * bufrdeco_explained_table_csv_val (char *expl, size_t dim, struct bufr_tablec *tc, size_t *index, struct bufr_descriptor *d, uint32_t ival)
char * bufrdeco_explained_flag_csv_val (char *expl, size_t dim, struct bufr_tablec *tc, struct bufr_descriptor *d, uint64_t ival, uint8_t nbits)
Detailed Description
file with the code to read table C (Code and flag tables from WMO files)
Definition in file bufrdeco_tablec_csv.c.
Function Documentation
int bufr_find_tablec_csv_index (size_t * index, struct bufr_tablec * tc, const char * key, uint32_t code)
Definition at line 149 of file bufrdeco_tablec_csv.c.
References bufr_descriptor::c, bufr_tablec::item, bufr_tablec_decoded_item::ival, bufr_tablec::num, uint32_t_to_descriptor(), bufr_descriptor::x, bufr_tablec_decoded_item::x, bufr_tablec::x_start, bufr_descriptor::y, and bufr_tablec_decoded_item::y.
Referenced by bufrdeco_explained_table_csv_val().
 {
   uint32_t ix;
   size_t i, i0;
   char *c;
   struct bufr_descriptor desc;
   ix = strtoul ( key, &c, 10 );
   uint32_t_to_descriptor ( &desc, ix );
   i0 = tc->x_start[desc.x];
   for ( i = i0 ; i < i0 + tc->num[desc.x] ; i++ )
     {
       if ( tc->item[i].x != desc.x )
         {
           return 1; // descriptor not found
         }
       if ( tc->item[i].y == desc.y && tc->item[i].ival == code )
         {
           *index = i;
           return 0; // found
         }
     }
   return 1; // not found
 }
int bufr_read_tablec_csv (struct bufr_tablec * tc, char * error)
Reads a file with table C content (Code table and bit flags) according with csv WMO format.
Parameters
tc pointer to a target struct bufr_tablec
error string where to set error if any
If succeded return 0, otherwise 1
Definition at line 34 of file bufrdeco_tablec_csv.c.
References BUFR_EXPLAINED_LENGTH, BUFR_MAXLINES_TABLEC, bufr_descriptor::c, CSV_MAXL, bufr_tablec_decoded_item::description, bufr_tablec::item, bufr_tablec_decoded_item::ival, bufr_tablec_decoded_item::key, bufr_tablec::nlines, bufr_tablec::num, bufr_tablec::old_path, parse_csv_line(), bufr_tablec::path, uint32_t_to_descriptor(), bufr_tablec::wmo_table, bufr_descriptor::x, bufr_tablec_decoded_item::x, bufr_tablec::x_start, bufr_descriptor::y, bufr_tablec_decoded_item::y, and bufr_tablec::y_ref.
Referenced by bufr_read_tables_wmo().
 {
   char *c;
   FILE *t;
   int nt;
   uint32_t ix;
   size_t i = 0;
   struct bufr_descriptor desc;
   char *tk[16];
   char caux[256], l[CSV_MAXL];
   if ( tc->path[0] == 0 )
     {
       return 1;
     }
   // If we've already readed this table.
   if ( strcmp ( tc->path, tc->old_path ) == 0 )
     {
       return 0; // all done
     }
   strcpy ( caux, tc->path );
   memset ( tc, 0, sizeof ( struct bufr_tablec ) );
   strcpy ( tc->path,caux );
   if ( ( t = fopen ( tc->path, "r" ) ) == NULL )
     {
       sprintf ( error,"Unable to open table C file '%s'\n", tc->path );
       return 1;
     }
   // read first line, it is ignored
   fgets ( l, CSV_MAXL, t );
   while ( fgets ( l, CSV_MAXL, t ) != NULL && i < BUFR_MAXLINES_TABLEC )
     {
       // Parse line
       if ( parse_csv_line ( &nt, tk, l ) < 0 || nt != 6 )
         {
           sprintf ( error,"Error parsing csv line from table C file '%s'. Found %d fields in line %lu \n", tc->path, nt, i );
           return 1;
         }
       // Check if code contains other than non-numeric i.e. 'All' or '-'
       // In this case, the line is ignored
       if ( tk[1][0] == 0 || strchr ( tk[1], '-' ) != NULL || strstr ( tk[1], "All" ) != NULL )
         continue;
       // Key
       // First we build the descriptor
       ix = strtoul ( tk[0], &c, 10 );
       uint32_t_to_descriptor ( &desc, ix );
       strcpy ( tc->item[i].key, tk[0] );
       tc->item[i].x = desc.x;
       tc->item[i].y = desc.y;
       // Integer value
       tc->item[i].ival = strtoul ( tk[1], &c, 10 );
       // Description
       c = & tc->item[i].description[0];
       if ( strlen ( tk[2] ) < BUFR_EXPLAINED_LENGTH )
         {
           c += sprintf ( c,"%s", tk[2] );
           if ( tk[3][0] && ( strlen ( tk[3] ) + strlen ( tc->item[i].description ) ) < BUFR_EXPLAINED_LENGTH )
             {
               c += sprintf ( c," %s", tk[3] );
               if ( tk[4][0] && ( strlen ( tk[4] ) + strlen ( tc->item[i].description ) ) < BUFR_EXPLAINED_LENGTH )
                 {
                   c += sprintf ( c, " %s", tk[4] );
                 }
             }
         }
       else
         {
           tk[2][BUFR_EXPLAINED_LENGTH - 1] = '\0';
           c += sprintf ( c,"%s", tk[2] );
         }
       if ( tk[5][0] && ( strlen ( tk[5] ) + strlen ( tc->item[i].description ) ) < BUFR_EXPLAINED_LENGTH )
         {
           c += sprintf ( c,"%s", tk[5] );
         }
       if ( tc->num[desc.x] == 0 )
         {
           tc->x_start[desc.x] = i;  // marc the start
         }
       if ( tc->y_ref[desc.x][desc.y] == 0 )
         {
           tc->y_ref[desc.x][desc.y] = i - tc->x_start[desc.x]; // marc the position from start of first x
         }
       ( tc->num[desc.x] ) ++;
       //printf("%ld %s %d %d, %ld %ld\n", i, tc->item[i].key, tc->item[i].x, tc->item[i].y, tc->x_start[desc.x], tc->y_ref[desc.x][desc.y]);
       i++;
     }
   fclose ( t );
   tc->nlines = i;
   tc->wmo_table = 1;
   strcpy ( tc->old_path, tc->path ); // store latest path
   return 0;
 }
char* bufrdeco_explained_flag_csv_val (char * expl, size_t dim, struct bufr_tablec * tc, struct bufr_descriptor * d, uint64_t ival, uint8_t nbits)
Definition at line 223 of file bufrdeco_tablec_csv.c.
References bufr_tablec_decoded_item::description, bufr_tablec::item, bufr_tablec_decoded_item::ival, bufr_tablec::num, bufr_descriptor::x, bufr_tablec_decoded_item::x, bufr_tablec::x_start, bufr_descriptor::y, bufr_tablec_decoded_item::y, and bufr_tablec::y_ref.
Referenced by bufrdeco_explained_flag_val().
 {
   char *s;
   uint64_t test, test0;
   uint64_t v;
   size_t i, j;
   if ( tc->num[d->x] == 0 )
     {
       //printf("Descriptor %s No encontrado\n", d->c);
       return NULL;
     }
   // First line for descriptor
   i = tc->x_start[d->x] + tc->y_ref[d->x][d->y];
   // init description
   s = expl;
   s[0] = '\0';
   //printf ( "%ld %s %d %d %d %d\n", i, tc->item[i].key, tc->item[i].x, tc->item[i].y, d->x , d->y );
   for ( j = 0, test0 = 1 ; j < nbits && ( tc->item[i].x == d->x ) && ( tc->item[i].y == d->y ) ; i++ )
     {
       v = tc->item[i].ival; // v is the bit number
       j++;
       // case 0 with meaning
       if ( v == 0 )
         {
           test0 = 1;
           if ( ival == 0 )
             {
               if ( strlen ( expl ) && ( strlen ( expl ) + 1 ) < dim )
                 {
                   s += sprintf ( s, "|" );
                 }
               if ( strlen ( expl ) + strlen ( tc->item[i].description ) < dim )
                 {
                   s += sprintf ( s,"%s", tc->item[i].description );
                 }
               return expl;
             }
         }
       test = test0 << ( nbits - v );
       if ( v && ( test & ival ) != 0 )
         {
           if ( strlen ( expl ) && ( strlen ( expl ) + 1 ) < dim )
             {
               s += sprintf ( s, "|" );
             }
           if ( strlen ( expl ) + strlen ( tc->item[i].description ) < dim )
             {
               s += sprintf ( s,"%s", tc->item[i].description );
             }
         }
       else
         {
           continue;
         }
       //printf ( "%s\n", expl );
     }
   // if match then we have finished the search
   return expl;
 }
char* bufrdeco_explained_table_csv_val (char * expl, size_t dim, struct bufr_tablec * tc, size_t * index, struct bufr_descriptor * d, uint32_t ival)
Definition at line 186 of file bufrdeco_tablec_csv.c.
References bufr_find_tablec_csv_index(), bufr_descriptor::c, bufr_tablec_decoded_item::description, bufr_tablec::item, bufr_descriptor::x, bufr_tablec::x_start, bufr_descriptor::y, and bufr_tablec::y_ref.
Referenced by bufrdeco_explained_table_val().
 {
   size_t  i;
   if ( bufr_find_tablec_csv_index ( &i, tc, d->c, ival ) )
     {
       return NULL; // descritor not found
     }
   // here the calling b item learn where to find first table C struct for a given x and y.
   *index = tc->x_start[d->x] + tc->y_ref[d->x][d->y];
   if ( strlen ( tc->item[i].description ) < dim )
     {
       strcpy ( expl, tc->item[i].description );
       return expl;
     }
   else
     {
       return NULL;
     }
 }