bufr2synop: src/libraries/bufr2tac_xml.c File Reference
bufr2tac_xml.c File Reference
Output a struct metreport in xml form.
#include "bufr2tac.h"
Functions
int print_xml_alphanum (FILE *f, char *type, char *alphanum, struct metreport *m)
int print_xml (FILE *f, struct metreport *m)
prints a struct metreport in xml format
Detailed Description
Output a struct metreport in xml form.
Definition in file bufr2tac_xml.c.
Function Documentation
print_xml()
int print_xml (FILE * f, struct metreport * m)
prints a struct metreport in xml format
Parameters
f pointer to a file already open by caller routine
m pointer to a struct metreport containing the data to print
Definition at line 71 of file bufr2tac_xml.c.
{
  // Single report
  if ( m->alphanum[0] )
    {
      print_xml_alphanum ( f, m->type, m->alphanum, m );
    }
  if ( m->alphanum2[0] ) //TTBB
    {
      print_xml_alphanum ( f, m->type2, m->alphanum2, m );
    }
  if ( m->alphanum3[0] ) //TTCC
    {
      print_xml_alphanum ( f, m->type3, m->alphanum3, m );
    }
  if ( m->alphanum4[0] ) //TTDD
    {
      print_xml_alphanum ( f, m->type4, m->alphanum4, m );
    }
  return 0;
}
References metreport::alphanum, metreport::alphanum2, metreport::alphanum3, metreport::alphanum4, print_xml_alphanum(), metreport::type, metreport::type2, metreport::type3, and metreport::type4.
Referenced by main().
print_xml_alphanum()
int print_xml_alphanum (FILE * f, char * type, char * alphanum, struct metreport * m)
Definition at line 28 of file bufr2tac_xml.c.
{
  // prints header
  fprintf ( f, "<metreport type=%s>\n", type );
  // print GTS_HEADER
  if ( m->h != NULL )
    {
      fprintf ( f, "<bufrfile>%s</bufrfile>\n",m->h->filename );
      fprintf ( f, " <gts_header>%s %s %s %s</gts_header>\n",m->h->bname, m->h->center, m->h->dtrel, m->h->order );
    }
  // print DATE AND TIME
  fprintf ( f, " <observation_datetime>%s</observation_datetime>\n",m->t.datime );
  // Geo data
  fprintf ( f, " <geo>\n" );
  if ( strlen ( m->g.index ) )
    {
      fprintf ( f, "  <index>%s</index>\n", m->g.index );
    }
  if ( strlen ( m->g.name ) )
    {
      fprintf ( f, "  <name>%s</name>\n", m->g.name );
    }
  if ( strlen ( m->g.country ) )
    {
      fprintf ( f, "  <country>%s</country>\n", m->g.country );
    }
  fprintf ( f, "  <latitude>%.6lf</latitude>\n", m->g.lat );
  fprintf ( f, "  <longitude>%.6lf</longitude>\n", m->g.lon );
  fprintf ( f, "  <altitude>%.1lf</altitude>\n", m->g.alt );
  fprintf ( f, " </geo>\n" );
  fprintf ( f, " <report>%s=</report>\n", alphanum );
  fprintf ( f, "</metreport>\n" );
  return 0;
}
References met_geo::alt, gts_header::bname, gts_header::center, met_geo::country, met_datetime::datime, gts_header::dtrel, gts_header::filename, metreport::g, metreport::h, met_geo::index, met_geo::lat, met_geo::lon, met_geo::name, gts_header::order, and metreport::t.
Referenced by print_xml().