bufr2synop: src/apps/bufr2synop_io.c File Reference
bufr2synop_io.c File Reference
#include "bufr2synop.h"
Functions
void print_usage (void)
int read_arguments (int _argc, char *_argv[])
read input arguments with the aid of getopt
char * get_bufrfile_path (char *filename, char *err)
Get bufr file names to parse.
Function Documentation
char* get_bufrfile_path (char * filename, char * err)
Get bufr file names to parse.
Parameters
filename string where the file is on output
err string where to set the error if any
If success, it returns a pointer to filename. If there is no more files to parse, or error returns NULL.
This routine is also opens the file with file list and close it when no more file available in list
The content format in LISTOFFILES is compatible with 'ls -1'. Example assume we want to parse all *.bufr files in current directory, we can do
ls -1 *.bufr > list_file && bufr2synop -I list_file
Definition at line 146 of file bufr2synop_io.c.
References FL, INPUTFILE, LISTOFFILES, and NFILES.
Referenced by main().
 {
    char aux[256], *c;
    if (LISTOFFILES[0] == 0)
    {
       if (NFILES == 0)
       {
          strcpy(filename, INPUTFILE);
          return filename;
       }
       else
          return 0;
    }
    else if (NFILES == 0)
    {
      if ((FL = fopen(LISTOFFILES,"r")) == NULL)
      {
         sprintf(err,"Cannot open '%s'", LISTOFFILES);
         return NULL;
      }
    }
    if (fgets(aux, 256, FL))
    {
       c =  strrchr(aux,'\n');
       if (c)
        *c = 0;
       strcpy(filename, aux);
       return filename;
    }
    else
    {
       fclose(FL);
       return NULL;
    }
 }
void print_usage (void)
Definition at line 27 of file bufr2synop_io.c.
 {
   printf("Usage: \n");
   printf("  bufr2synop [-i input] [-I list_of_files] [-t bufrtable_dir][-o output][-s][-v][-j][-x][-c]\n");
   printf("       -e Print some original output from ECMWF library\n");
   printf("       -h. Show this help\n");
   printf("       -i input. Pathname of the file with the bufr message to parse\n");
   printf("       -j. The output is in json format\n");
   printf("       -c. The output is in csv format\n");
   printf("       -I list_of_files. Pathname of a file with the list of files to parse, one filename per line\n");
   printf("       -o output. Pathname of output file. Default is standar output\n");
   printf("       -s prints a long output with explained sequence of descriptors\n");
   printf("       -t bufrtable_dir. Pathname of bufr tables directory. Ended with '/'\n");
   printf("       -v. Verbose output\n");
   printf("       -x. The output is in xml format\n");
 }
int read_arguments (int _argc, char * _argv[])
read input arguments with the aid of getopt
Definition at line 49 of file bufr2synop_io.c.
References BUFRTABLES_DIR, CSV, DEBUG, INPUTFILE, JSON, LISTOFFILES, NFILES, OUTPUTFILE, print_usage(), SHOW_ECMWF_OUTPUT, SHOW_SEQUENCE, VERBOSE, and XML.
Referenced by main().
 {
   int iopt;
   // Initial and default values
   INPUTFILE[0] = '\0';
   OUTPUTFILE[0] = '\0';
   LISTOFFILES[0] = '\0';
   BUFRTABLES_DIR[0] = '\0';
   VERBOSE = 0;
   SHOW_SEQUENCE = 0;
   SHOW_ECMWF_OUTPUT = 0;
   DEBUG = 0;
   NFILES = 0;
   XML = 0;
   JSON = 0;
   CSV= 0;
   /*
    Read input arguments using getop library
    */
   while ((iopt = getopt(_argc, _argv, "cDehi:jI:o:st:vx")) != -1)
     switch (iopt)
       {
       case 'i':
         if (strlen(optarg) < 256)
           strcpy(INPUTFILE, optarg);
         break;
       case 'j':
         JSON = 1;
         break;
       case 'I':
         if (strlen(optarg) < 256)
           strcpy(LISTOFFILES, optarg);
         break;
       case 'o':
         if (strlen(optarg) < 256)
           strcpy(OUTPUTFILE, optarg);
         break;
       case 't':
         if (strlen(optarg) < 256)
           {
             strcpy(BUFRTABLES_DIR, optarg);
           }
         break;
       case 'D':
         DEBUG = 1;
         break;
       case 'e':
         SHOW_ECMWF_OUTPUT = 1;
         break;
       case 'v':
         VERBOSE = 1;
         break;
       case 's':
         SHOW_SEQUENCE = 1;
         break;
       case 'x':
         XML = 1;
         break;
       case 'c':
         CSV = 1;
         break;
       case 'h':
       default:
         print_usage();
         exit(EXIT_SUCCESS);
       }
   if (INPUTFILE[0] == 0 && LISTOFFILES[0] == 0)
     {
       print_usage();
       return 1;
     }
   return 0;
 }