bufr2synop: src/libraries/bufr2syn_x11.c File Reference
bufr2syn_x11.c File Reference
decodes the descriptors with X = 11
#include "bufr2syn.h"
Functions
char * secs_to_tt (char *tt, int secs)
int syn_parse_x11 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 11.
int buoy_parse_x11 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 11.
Detailed Description
decodes the descriptors with X = 11
Definition in file bufr2syn_x11.c.
Function Documentation
int buoy_parse_x11 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 164 of file bufr2syn_x11.c.
References bufr_subset_state::a, BUOY_SEC1, buoy_sec1::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec1::ff, buoy_sec1::fff, bufr_subset_state::ival, buoy_sec0::iw, buoy_chunks::mask, bufr_atom_data::mask, buoy_chunks::s0, buoy_chunks::s1, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 11 001
     case 11: // 0 11 011
       sprintf ( b->s1.dd, "%02d", ( s->ival + 5 ) / 10 );
       b->mask |= BUOY_SEC1;
       break;
     case 2: // 0 11 002
     case 12: // 0 11 012
       if ( b->s0.iw[0] == '4' )
         s->val *= 1.94384449;
       if ( s->val < 100.0 )
         sprintf ( b->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
       else
         {
           sprintf ( b->s1.ff,"99" );
           sprintf ( b->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
         }
       b->mask |= BUOY_SEC1;
       break;
     default:
       break;
     }
   return 0;
 }
char* secs_to_tt (char * tt, int secs)
Definition at line 26 of file bufr2syn_x11.c.
Referenced by syn_parse_x11().
 {
   int i;
   i = (-secs) / 360;
   if (i <= 60)
     sprintf(tt, "%02d", i);
   else if (i < 700)
     sprintf(tt, "61");
   else if (i < 800)
     sprintf(tt, "62");
   else if (i < 900)
     sprintf(tt, "63");
   else if (i < 1000)
     sprintf(tt, "64");
   else if (i < 1100)
     sprintf(tt, "65");
   else if (i < 1200)
     sprintf(tt, "66");
   else if (i < 1800)
     sprintf(tt, "67");
   else
     sprintf(tt, "68");
   return tt;
 }
int syn_parse_x11 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 60 of file bufr2syn_x11.c.
References bufr_subset_state::a, synop_sec3::d9, synop_sec5::d9, synop_sec1::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec1::ff, synop_sec1::fff, bufr_subset_state::itval, bufr_subset_state::ival, synop_sec0::iw, bufr_atom_data::mask, synop_chunks::mask, bufr_subset_state::mask, data9::misc, data9::n, synop_chunks::s0, synop_chunks::s1, synop_chunks::s3, synop_chunks::s5, secs_to_tt(), misc3::SpSp, misc3::spsp, SUBSET_MASK_HAVE_GUST, SYNOP_SEC1, SYNOP_SEC3, SYNOP_SEC5, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 11 001
     case 11: // 0 11 011
       sprintf ( syn->s1.dd, "%02d", ( s->ival + 5 ) / 10 );
       syn->mask |= SYNOP_SEC1;
       break;
     case 2: // 0 11 002
     case 12: // 0 11 012
       if ( syn->s0.iw[0] == '4' )
         s->val *= 1.94384449;
       if ( s->val < 100.0 )
         sprintf ( syn->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
       else
         {
           sprintf ( syn->s1.ff,"99" );
           sprintf ( syn->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
         }
       syn->mask |= SYNOP_SEC1;
       break;
     case 41: // max wind gust speed
       if (s->itval == -600)
         {
           sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "910");
           if ( syn->s0.iw[0] == '4' )
             s->val *= 1.94384449;
           if ( s->val < 100.0 )
             sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
           else
             {
               sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
               syn->s3.d9.n++;
               sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00");
               sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
             }
           syn->s3.d9.n++;
         }
       else if (s->itval)
         {
           if (s->mask & SUBSET_MASK_HAVE_GUST)
             {
               sprintf( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "907");
               secs_to_tt(syn->s5.d9.misc[syn->s5.d9.n].spsp, s->itval);
               syn->s5.d9.n++;
               sprintf( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "911");
               if ( syn->s0.iw[0] == '4' )
                 s->val *= 1.94384449;
               if ( s->val < 100.0 )
                 sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
               else
                 {
                   sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp,"99" );
                   syn->s5.d9.n++;
                   sprintf( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "00");
                   sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                 }
               syn->s5.d9.n++;
               syn->mask |= SYNOP_SEC5;
             }
           else
             {
               sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "907");
               secs_to_tt(syn->s3.d9.misc[syn->s3.d9.n].spsp, s->itval);
               syn->s3.d9.n++;
               sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "911");
               if ( syn->s0.iw[0] == '4' )
                 s->val *= 1.94384449;
               if ( s->val < 100.0 )
                 sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
               else
                 {
                   sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
                   syn->s3.d9.n++;
                   sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00");
                   sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                 }
               syn->s3.d9.n++;
               syn->mask |= SYNOP_SEC3;
               s->mask |= SUBSET_MASK_HAVE_GUST;
             }
         }
       break;
     case 43: // max wind gust direction
       break;
     default:
       break;
     }
   return 0;
 }