bufr2synop: src/apps/bufrdeco_test.c File Reference
bufrdeco_test.c File Reference
This file includes the code to debug and test bufrdeco library.
#include "bufrdeco.h"
Functions
void print_usage (void)
int read_args (int _argc, char *_argv[])
read the arguments from stdio
int main (int argc, char *argv[])
Variables
struct bufrdeco BUFR
int EXTRACT
char ENTRADA [256]
Detailed Description
This file includes the code to debug and test bufrdeco library.
Definition in file bufrdeco_test.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 80 of file bufrdeco_test.c.
{
  size_t subset;
  struct bufrdeco_subset_sequence_data *seq;
  if ( read_args ( argc, argv ) < 0 )
    exit ( EXIT_FAILURE );
  bufrdeco_init ( &BUFR );
  // Check read file
  if ( EXTRACT )
    {
      if ( bufrdeco_extract_bufr ( &BUFR, ENTRADA ) )
        {
          printf ( "%s", BUFR.error );
          exit ( EXIT_FAILURE );
        }
    }
  else if ( bufrdeco_read_bufr ( &BUFR, ENTRADA ) )
    {
      printf ( "%s", BUFR.error );
      exit ( EXIT_FAILURE );
    }
  print_sec0_info ( &BUFR );
  print_sec1_info ( &BUFR );
  print_sec3_info ( &BUFR );
  print_sec4_info ( &BUFR );
  if ( bufrdeco_parse_tree ( &BUFR ) )
    {
      printf ( "# %s", BUFR.error );
      bufrdeco_close ( &BUFR );
      exit ( EXIT_FAILURE );
    }
  bufrdeco_print_tree ( &BUFR );
  for ( subset = 0; subset < BUFR.sec3.subsets ; subset++ )
    {
      if ( ( seq = bufrdeco_get_subset_sequence_data ( &BUFR ) ) == NULL )
        {
          printf ( "# %s", BUFR.error );
          bufrdeco_close ( &BUFR );
          exit ( EXIT_FAILURE );
        }
      bufrdeco_print_subset_sequence_data ( seq );
    }
  printf ( "So far so good !!\n" );
  bufrdeco_close ( &BUFR );
  exit ( EXIT_SUCCESS );
}
References BUFR, bufrdeco_close(), bufrdeco_extract_bufr(), bufrdeco_get_subset_sequence_data(), bufrdeco_init(), bufrdeco_parse_tree(), bufrdeco_print_subset_sequence_data(), bufrdeco_print_tree(), bufrdeco_read_bufr(), ENTRADA, bufrdeco::error, EXTRACT, print_sec0_info(), print_sec1_info(), print_sec3_info(), print_sec4_info(), read_args(), bufrdeco::sec3, and bufr_sec3::subsets.
print_usage()
void print_usage (void)
Definition at line 29 of file bufrdeco_test.c.
{
  printf ( "Usage: \n" );
  printf ( "bufrdeco_test -i input_file [-h][-X]\n" );
  printf ( "   -h Print this help\n" );
  printf ( "   -i Input file. Complete input path file for bufr file\n" );
  printf ( "   -X. Extract first BUFR buffer found in input file (from first 'BUFR' item to next '7777')\n" );
}
Referenced by read_args().
read_args()
int read_args (int _argc, char * _argv[])
read the arguments from stdio
Parameters
_argc number of arguments passed
_argv array of arguments
Returns 1 if succcess, -1 othewise
Definition at line 46 of file bufrdeco_test.c.
{
  int iopt;
  // Default values
  EXTRACT = 0;
  /*
     Read input options
  */
  while ( ( iopt = getopt ( _argc, _argv, "hi:X" ) ) !=-1 )
    switch ( iopt )
      {
      case 'X':
        EXTRACT = 1;
        break;
      case 'i':
        if ( strlen ( optarg ) < 256 )
          strcpy ( ENTRADA, optarg );
        break;
      case 'h':
      default:
        print_usage();
        exit ( EXIT_SUCCESS );
      }
  if ( ENTRADA[0] == '\0' )
    {
      printf ( "read_args(): It is needed an input file. Use -i option\n" );
      return -1;
    }
  return 1;
}
References ENTRADA, EXTRACT, and print_usage().
Referenced by main().
Variable Documentation
BUFR
struct bufrdeco BUFR
Definition at line 25 of file bufrdeco_test.c.
Referenced by main().
ENTRADA
char ENTRADA[256]
Definition at line 27 of file bufrdeco_test.c.
Referenced by main(), and read_args().
EXTRACT
int EXTRACT
Definition at line 26 of file bufrdeco_test.c.
Referenced by bufrtotac_read_args(), main(), and read_args().