bufr2synop: src/apps/bufrtotac.c File Reference
bufrtotac.c File Reference
This file includes the code to test bufr to TAC libraries using bufrdeco library to decode bufr.
#include "bufrtotac.h"
Functions
int main (int argc, char *argv[])
Variables
struct bufrdeco BUFR
struct metreport REPORT
struct bufr2tac_subset_state STATE
const char SELF [] = "bufrtotac"
char ERR [256]
char BUFRTABLES_DIR [256]
char LISTOFFILES [256]
char INPUTFILE [256]
char OUTPUTFILE [256]
int VERBOSE
int SHOW_SEQUENCE
int DEBUG
int NFILES
int GTS_HEADER
int XML
int JSON
int CSV
int EXTRACT
int ECMWF
int HTML
int NOTAC
int FIRST_SUBSET
int LAST_SUBSET
FILE * FL
Detailed Description
This file includes the code to test bufr to TAC libraries using bufrdeco library to decode bufr.
Definition in file bufrtotac.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 115 of file bufrtotac.c.
{
  size_t subset;
  char subset_id[32];
  struct bufrdeco_subset_sequence_data *seq;
  if ( read_args ( argc, argv ) < 0 )
    exit ( EXIT_FAILURE );
  // init bufr struct
  if ( bufrdeco_init ( &BUFR ) )
    {
      printf ( "%s(): Cannot init bufr struct\n", SELF );
      return 1;
    }
  // If needed mark to use ECMWF tables
  if ( ECMWF )
    BUFR.mask |= BUFRDECO_USE_ECMWF_TABLES;
  if ( HTML )
    BUFR.mask |= BUFRDECO_OUTPUT_HTML;
  /**** Set bufr tables dir ****/
  strcpy(BUFR.bufrtables_dir , BUFRTABLES_DIR);
  /**** Big loop. a cycle per file ****/
  while ( get_bufrfile_path ( INPUTFILE, ERR ) )
    {
      //printf ( "%s\n", INPUTFILE );
      if ( DEBUG )
        printf ( "# %s\n", INPUTFILE );
      // The following call to bufrdeco_read_bufr() does the folowing tasks:
      // - Read the file and checks the marks at the begining and end to see wheter is a BUFR file
      // - Init the structs and allocate the needed memory if not done previously
      // - Splits and parse the BUFR sections (without expanding descriptors nor parsing data)
      // - Reads the needed Table files and store them in memory.
      //
      // If EXTRACT != 0 then the function bufrdeco_extract_bufr() is used instead of bufrdeco_read_bufr()
      // This act in the same way, but search and extract the first BUFR embebed in a file.
      if ( ( EXTRACT && bufrdeco_extract_bufr ( &BUFR, INPUTFILE ) ) ||
           ( EXTRACT == 0 && bufrdeco_read_bufr ( &BUFR, INPUTFILE ) ) )
        {
          if ( DEBUG )
            printf ( "# %s\n", BUFR.error );
          NFILES++;
          bufrdeco_reset ( &BUFR );
          continue;
        }
      /* Try to guess a GTS header from filename*/
      GTS_HEADER = guess_gts_header ( &BUFR.header , INPUTFILE );  // GTS_HEADER = 1 if succeeded
      if ( GTS_HEADER && DEBUG )
        printf ( "#%s %s %s %s %s\n", BUFR.header.timestamp, BUFR.header.bname, BUFR.header.center,
                 BUFR.header.dtrel, BUFR.header.order );
      /* Prints sections if verbose */
      if ( VERBOSE )
        {
          print_sec0_info ( &BUFR );
          print_sec1_info ( &BUFR );
          print_sec3_info ( &BUFR );
          print_sec4_info ( &BUFR );
        }
      if ( bufrdeco_parse_tree ( &BUFR ) )
        {
          if ( DEBUG )
            printf ( "# %s", BUFR.error );
          NFILES++;
          bufrdeco_reset ( &BUFR );
          continue;
        }
      if ( VERBOSE )
        bufrdeco_print_tree ( &BUFR );
      for ( subset = 0; subset < BUFR.sec3.subsets ; subset++ )
        {
          // Here we get all subsets since 0. FIRST_SUBSET here is not significant
          if ( subset > (size_t) LAST_SUBSET)
              break;
          if ( ( seq = bufrdeco_get_subset_sequence_data ( &BUFR ) ) == NULL )
            {
              if ( DEBUG )
                printf ( "# %s", BUFR.error );
              goto fin;
            }
          // But here we filter the subset array to show since FIRST_SUBSET
          if (subset < (size_t) FIRST_SUBSET)
              continue;
          if ( VERBOSE )
            {
              if ( ( subset == 0 ) && BUFR.sec3.compressed )
                print_bufrdeco_compressed_data_references ( & ( BUFR.refs ) );
              if ( BUFR.mask & BUFRDECO_OUTPUT_HTML )
              {
                sprintf(subset_id, "subset_%lu", subset);
                bufrdeco_print_subset_sequence_data_tagged_html ( seq, subset_id );
              }
              else
                bufrdeco_print_subset_sequence_data ( seq );
            }
          if ( ! NOTAC )
            {
              // Here we perform the decode to TAC
              if ( BUFR.sec3.ndesc &&  bufrdeco_parse_subset_sequence ( &REPORT, &STATE, &BUFR, ERR ) )
                {
                  if ( DEBUG )
                    fprintf ( stderr, "# %s\n", ERR );
                }
              // And here print the results
              if ( XML )
                {
                  if ( subset == 0 )
                    fprintf ( stdout, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" );
                  print_xml ( stdout, &REPORT );
                }
              else if ( JSON )
                {
                  print_json ( stdout, &REPORT );
                }
              else if ( CSV )
                {
                  if ( subset == 0 )
                    fprintf ( stdout, "TYPE,FILE,DATETIME,INDEX,NAME,COUNTRY,LATITUDE,LONGITUDE,ALTITUDE,REPORT\n" );
                  print_csv ( stdout, &REPORT );
                }
              else if ( HTML )
                {
                  print_html ( stdout, &REPORT );
                }
              else
                {
                  print_plain ( stdout, &REPORT );
                }
            }
        }
    fin:
      ;
      bufrdeco_reset ( &BUFR );
      NFILES ++;
    } // End of big loop parsing files
  bufrdeco_close ( &BUFR );
  exit ( EXIT_SUCCESS );
}
References gts_header::bname, BUFR, bufrdeco_close(), bufrdeco_extract_bufr(), bufrdeco_get_subset_sequence_data(), bufrdeco_init(), BUFRDECO_OUTPUT_HTML, bufrdeco_parse_subset_sequence(), bufrdeco_parse_tree(), bufrdeco_print_subset_sequence_data(), bufrdeco_print_subset_sequence_data_tagged_html(), bufrdeco_print_tree(), bufrdeco_read_bufr(), bufrdeco_reset(), BUFRDECO_USE_ECMWF_TABLES, BUFRTABLES_DIR, bufrdeco::bufrtables_dir, gts_header::center, bufr_sec3::compressed, CSV, DEBUG, gts_header::dtrel, ECMWF, ERR, bufrdeco::error, EXTRACT, FIRST_SUBSET, get_bufrfile_path(), GTS_HEADER, guess_gts_header(), bufrdeco::header, HTML, INPUTFILE, JSON, LAST_SUBSET, bufrdeco::mask, bufr_sec3::ndesc, NFILES, NOTAC, gts_header::order, print_bufrdeco_compressed_data_references(), print_csv(), print_html(), print_json(), print_plain(), print_sec0_info(), print_sec1_info(), print_sec3_info(), print_sec4_info(), print_xml(), read_args(), bufrdeco::refs, REPORT, bufrdeco::sec3, SELF, STATE, bufr_sec3::subsets, gts_header::timestamp, VERBOSE, and XML.
Variable Documentation
BUFR
struct bufrdeco BUFR
Definition at line 89 of file bufrtotac.c.
Referenced by main().
BUFRTABLES_DIR
char BUFRTABLES_DIR[256]
Directory for BUFR tables set by user
Definition at line 95 of file bufrtotac.c.
Referenced by main(), and read_args().
CSV
int CSV
If == 1 then output is in csv format
Definition at line 106 of file bufrtotac.c.
Referenced by main(), and read_args().
DEBUG
int DEBUG
Show debug information
Definition at line 101 of file bufrtotac.c.
Referenced by main(), and read_args().
ECMWF
int ECMWF
If == 1 then use tables from ECMWF package
Definition at line 108 of file bufrtotac.c.
Referenced by main(), and read_args().
ERR
char ERR[256]
< the name of this binary string with an error
Definition at line 94 of file bufrtotac.c.
Referenced by main().
EXTRACT
int EXTRACT
if != 0 then the decoder tries to extract an embebed bufr in a file seraching for a first '7777' after first 'BUFR'
Definition at line 107 of file bufrtotac.c.
Referenced by main().
FIRST_SUBSET
int FIRST_SUBSET
First subset index in output. First available is 0
Definition at line 111 of file bufrtotac.c.
Referenced by main(), and read_args().
FL
FILE* FL
Buffer to read the list of files
Definition at line 113 of file bufrtotac.c.
Referenced by get_bufrfile_path().
GTS_HEADER
int GTS_HEADER
If == 1 GTS header have been guessed from filename
Definition at line 103 of file bufrtotac.c.
Referenced by main().
HTML
int HTML
If == 1 then output is in HTML format
Definition at line 109 of file bufrtotac.c.
Referenced by main(), and read_args().
INPUTFILE
char INPUTFILE[256]
The pathname of input file
Definition at line 97 of file bufrtotac.c.
Referenced by get_bufrfile_path(), main(), and read_args().
JSON
int JSON
If == 1 then output is in json format
Definition at line 105 of file bufrtotac.c.
Referenced by main(), and read_args().
LAST_SUBSET
int LAST_SUBSET
Last subset index in output. First available is 0
Definition at line 112 of file bufrtotac.c.
Referenced by main(), and read_args().
LISTOFFILES
char LISTOFFILES[256]
The pathname of a file which includes a list of bufr files to parse
Definition at line 96 of file bufrtotac.c.
Referenced by get_bufrfile_path(), and read_args().
NFILES
int NFILES
The amount of files processed
Definition at line 102 of file bufrtotac.c.
Referenced by get_bufrfile_path(), main(), and read_args().
NOTAC
int NOTAC
if == 1 then do not decode to TAC
Definition at line 110 of file bufrtotac.c.
Referenced by main(), and read_args().
OUTPUTFILE
char OUTPUTFILE[256]
The pathname of output file
Definition at line 98 of file bufrtotac.c.
Referenced by read_args().
REPORT
struct metreport REPORT
stuct to set the parsed report
Definition at line 90 of file bufrtotac.c.
Referenced by main().
SELF
const char SELF[] = "bufrtotac"
Definition at line 93 of file bufrtotac.c.
Referenced by main(), print_usage(), and print_version().
SHOW_SEQUENCE
int SHOW_SEQUENCE
Output explained sequence
Definition at line 100 of file bufrtotac.c.
Referenced by read_args().
STATE
struct bufr2tac_subset_state STATE
Includes the info when parsing a subset sequence
Definition at line 91 of file bufrtotac.c.
Referenced by main().
VERBOSE
int VERBOSE
If != 0 the verbose output
Definition at line 99 of file bufrtotac.c.
Referenced by main().
XML
int XML
If == 1 then output is in xml format
Definition at line 104 of file bufrtotac.c.
Referenced by main(), and read_args().