bufr2synop: src/libraries/bufr2tac_print.c File Reference
bufr2tac_print.c File Reference
file with the code to print the results
#include "bufr2tac.h"
Functions
int print_plain (FILE *f, struct metreport *m)
Print in a file the report decoded to Traditional Alphanumeric Code in plain text format. A line per report.
int print_html (FILE *f, struct metreport *m)
Print in a file the report decoded to Traditional Alphanumeric Code in plain html format. A line per report.
size_t print_geo (char **geo, size_t lmax, struct metreport *m)
size_t print_wigos_id (char **wid, size_t lmax, struct metreport *m)
Detailed Description
file with the code to print the results
Definition in file bufr2tac_print.c.
Function Documentation
print_geo()
size_t print_geo (char ** geo, size_t lmax, struct metreport * m)
Definition at line 71 of file bufr2tac_print.c.
{
  size_t used;
  char sep = '|';
  used = snprintf(*geo, lmax, "%8.4lf %9.4lf %6.1lf%c", m->g.lat, m->g.lon, m->g.alt, sep);
  *geo += used;
  return used;
}
References met_geo::alt, metreport::g, met_geo::lat, and met_geo::lon.
Referenced by print_buoy_report(), print_climat_report(), print_synop_report(), print_temp_a(), print_temp_b(), print_temp_c(), and print_temp_d().
print_html()
int print_html (FILE * f, struct metreport * m)
Print in a file the report decoded to Traditional Alphanumeric Code in plain html format. A line per report.
Parameters
f pointer to file where to write to
m pointer to struct metreport where the decoded report is stored
Definition at line 51 of file bufr2tac_print.c.
{
  fprintf(f, "<pre>");
  if ( m->alphanum[0] )
    fprintf ( f, "%s\n", m->alphanum );
  if ( m->alphanum2[0] )
    fprintf ( f, "%s\n", m->alphanum2 );
  if ( m->alphanum3[0] )
    fprintf ( f, "%s\n", m->alphanum3 );
  if ( m->alphanum4[0] )
    fprintf ( f, "%s\n", m->alphanum4 );
  fprintf(f, "</pre>");
  return 0;
}
References metreport::alphanum, metreport::alphanum2, metreport::alphanum3, and metreport::alphanum4.
Referenced by main().
print_plain()
int print_plain (FILE * f, struct metreport * m)
Print in a file the report decoded to Traditional Alphanumeric Code in plain text format. A line per report.
Parameters
f pointer to file where to write to
m pointer to struct metreport where the decoded report is stored
Definition at line 32 of file bufr2tac_print.c.
{
  if ( m->alphanum[0] )
    fprintf ( f, "%s\n", m->alphanum );
  if ( m->alphanum2[0] )
    fprintf ( f, "%s\n", m->alphanum2 );
  if ( m->alphanum3[0] )
    fprintf ( f, "%s\n", m->alphanum3 );
  if ( m->alphanum4[0] )
    fprintf ( f, "%s\n", m->alphanum4 );
  return 0;
}
References metreport::alphanum, metreport::alphanum2, metreport::alphanum3, and metreport::alphanum4.
Referenced by main().
print_wigos_id()
size_t print_wigos_id (char ** wid, size_t lmax, struct metreport * m)
Definition at line 86 of file bufr2tac_print.c.
{
  char aux[40];
  size_t used;
  char sep = '|';
  if (m->g.wid.series == 0 && m->g.wid.issuer == 0 && m->g.wid.issue == 0 && m->g.wid.local_id[0] == '\0')
    sprintf (aux,"0-0-0-MISSING");
  else
    sprintf (aux,"%d-%d-%d-%s", m->g.wid.series, m->g.wid.issuer, m->g.wid.issue, m->g.wid.local_id );
  used = snprintf (*wid, lmax, "%-32s%c", aux, sep);
  *wid += used;
  return used;
}
References metreport::g, wigos_id::issue, wigos_id::issuer, wigos_id::local_id, wigos_id::series, and met_geo::wid.
Referenced by print_buoy_report(), print_climat_report(), print_synop_report(), print_temp_a(), print_temp_b(), print_temp_c(), and print_temp_d().