bufr2synop: src/libraries/bufr2syn_x20.c File Reference
bufr2syn_x20.c File Reference
decodes the descriptors with X = 20
#include "bufr2syn.h"
Functions
char * percent_to_okta (char *target, double perc)
Converts percent cloud cover into okta.
char * m_to_h (char *target, double h)
converts the altitude of cloud layer into h string code
char * m_to_hh (char *target, double h)
converts the altitude of cloud layer into hh string code
char * vism_to_VV (char *target, double V)
Convert horizontal visibilty in meters to a VV string.
int syn_parse_x20 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 20.
int buoy_parse_x20 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 20.
Detailed Description
decodes the descriptors with X = 20
Definition in file bufr2syn_x20.c.
Function Documentation
int buoy_parse_x20 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 20.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 349 of file bufr2syn_x20.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::mask, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     default:
       break;
     }
   return 0;
 }
char* m_to_h (char * target, double h)
converts the altitude of cloud layer into h string code
Parameters
h the altitude in meters
target the resulting h coded string
Definition at line 63 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   if ( h < 50.0 )
     strcpy ( target,"0" );
   else if ( h < 100.0 )
     strcpy ( target,"1" );
   else if ( h < 200.0 )
     strcpy ( target,"2" );
   else if ( h < 300.0 )
     strcpy ( target,"3" );
   else if ( h < 600.0 )
     strcpy ( target,"4" );
   else if ( h < 1000.0 )
     strcpy ( target,"5" );
   else if ( h < 1500.0 )
     strcpy ( target,"6" );
   else if ( h < 2000.0 )
     strcpy ( target,"7" );
   else if ( h < 2500.0 )
     strcpy ( target,"8" );
   else
     strcpy ( target,"9" );
   return target;
 }
char* m_to_hh (char * target, double h)
converts the altitude of cloud layer into hh string code
Parameters
h the altitude in meters
target the resulting h coded string
Definition at line 95 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   int ih = (int)h;
   if ( ih <= 1500 )
   {
     sprintf(target, "%02d", ih / 30);
   }
   else if ( ih <= 9000 )
   {
     sprintf(target, "%2d", (ih / 300) + 50);
   }
   else if (ih <= 21000 )
   {
     sprintf(target, "%2d", (ih / 500) + 50);
   }
   else
     strcpy ( target,"89" );
   return target;
 }
char* percent_to_okta (char * target, double perc)
Converts percent cloud cover into okta.
Parameters
perc the precent cloud cover
target the resulting okta string
Definition at line 32 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   if ( perc < 12.5 )
     strcpy ( target,"0" );
   else if ( perc < 25.0 )
     strcpy ( target,"1" );
   else if ( perc < 37.5)
     strcpy ( target,"2" );
   else if ( perc < 50.0 )
     strcpy ( target,"3" );
   else if ( perc < 62.5 )
     strcpy ( target,"4" );
   else if ( perc < 75.0 )
     strcpy ( target,"5" );
   else if ( perc < 87.5 )
     strcpy ( target,"6" );
   else if ( perc < 100.0 )
     strcpy ( target,"7" );
   else if ( perc <= 112.5 )
     strcpy ( target,"8" );
   else if ( perc == 113.0 )
     strcpy ( target,"9" );
   return target;
 }
int syn_parse_x20 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 20.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 147 of file bufr2syn_x20.c.
References bufr_subset_state::a, nub3::C, synop_sec1::Ch, synop_sec1::Cl, bufr_subset_state::clayer, synop_sec1::Cm, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec3::E, synop_sec3::E1, synop_sec1::h, nub3::hshs, bufr_subset_state::ival, synop_sec1::ix, m_to_h(), m_to_hh(), bufr_atom_data::mask, synop_chunks::mask, bufr_subset_state::mask, synop_sec1::N, synop_sec1::Nh, nub3::Ns, synop_sec3::nub, percent_to_okta(), synop_chunks::s1, synop_chunks::s3, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2, SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW, SYNOP_SEC1, SYNOP_SEC3, bufr_subset_state::val, vism_to_VV(), synop_sec1::VV, synop_sec1::W1, synop_sec1::W2, synop_sec1::ww, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   switch ( s->a->desc.y )
     {
     case 1: // 0 20 001
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       vism_to_VV ( syn->s1.VV, s->val );
       break;
     case 3: // 0 20 003
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
           {
             s->mask |=  (SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1 | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2);
             return 0;
           }
       if ( s->ival < 100 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"1" );
           sprintf ( syn->s1.ww, "%02d", s->ival );
           syn->mask |= SYNOP_SEC1;
         }
       else if ( s->ival == 100)
         {
           s->mask |=  SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW;
         }
       else if ( s->ival < 200 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"7" );
           sprintf ( syn->s1.ww, "%02d", s->ival % 100 );
           syn->mask |= SYNOP_SEC1;
         }
       else if ( s->ival == 508)
         {
           s->mask |=  (SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1 | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2);
         }
       break;
     case 4: // 0 20 004
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         {
           s->mask |=  SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1;
           return 0;
         }
       if ( s->ival < 10 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"1" );
           sprintf ( syn->s1.W1, "%d", s->ival );
           syn->mask |= SYNOP_SEC1;
         }
       else if (s->ival == 10)
         {
           s->mask |= SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1;
         }
       else
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"7" );
           sprintf ( syn->s1.W1, "%d", s->ival % 10 );
           syn->mask |= SYNOP_SEC1;
         }
       break;
     case 5: // 0 20 005
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         {
           s->mask |=  SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2;
           return 0;
         }
       if ( s->ival < 10 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"1" );
           sprintf ( syn->s1.W2, "%d", s->ival );
           syn->mask |= SYNOP_SEC1;
         }
       else if (s->ival == 10)
         {
           s->mask |= SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2;
         }
       else
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"7" );
           sprintf ( syn->s1.W2, "%d", s->ival % 10 );
           syn->mask |= SYNOP_SEC1;
         }
       break;
     case 10: // 0 20 010
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       percent_to_okta ( syn->s1.N, s->val );
       break;
     case 11: // 0 20 011
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (s->clayer == 0)
         {
           if ( s->ival <= 8 )
             sprintf ( syn->s1.Nh, "%1d", s->ival );
           else if ( s->ival <= 10 )
             sprintf ( syn->s1.Nh, "9");
           else if ( s->ival == 15 )
             sprintf ( syn->s1.Nh, "/");
           syn->mask |= SYNOP_SEC1;
         }
       else
         {
           if ( s->ival <= 8 )
             sprintf ( syn->s3.nub[s->clayer - 1].Ns, "%1d", s->ival );
           else if ( s->ival <= 10 )
             sprintf ( syn->s3.nub[s->clayer - 1].Ns, "9");
           else if ( s->ival == 15 )
             sprintf ( syn->s3.nub[s->clayer - 1].Ns, "/");
           syn->mask |= SYNOP_SEC3;
         }
       break;
     case 12: // 0 20 012
       if (s->clayer == 0)
         {
           if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
             return 0;
           if (s->ival >= 10 && s->ival < 20)
             sprintf( syn->s1.Ch, "%1d", s->ival % 10);
           else if (s->ival >= 20 && s->ival < 30)
             sprintf( syn->s1.Cm, "%1d", s->ival % 10);
           else if (s->ival >= 30 && s->ival < 40)
             sprintf( syn->s1.Cl, "%1d", s->ival % 10);
           else if (s->ival == 59)
             sprintf( syn->s1.Nh, "/");
           else if (s->ival == 60)
             sprintf( syn->s1.Ch, "/");
           else if (s->ival == 61)
             sprintf( syn->s1.Cm, "/");
           else if (s->ival == 62)
             sprintf( syn->s1.Cl, "/");
           syn->mask |= SYNOP_SEC1;
         }
       else
         {
           if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
           {
             sprintf( syn->s3.nub[s->clayer - 1].C, "/");
             return 0;
           }
           if (s->ival == 59)
             sprintf( syn->s3.nub[s->clayer - 1].C, "/");
           else
             sprintf( syn->s3.nub[s->clayer - 1].C, "%1d", s->ival % 10);
           syn->mask |= SYNOP_SEC3;
         }
       break;
     case 13: // 0 20 013
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (s->clayer == 0) // fisrt layer is for sec1
         m_to_h( syn->s1.h, s->val );
       else
         m_to_hh(syn->s3.nub[s->clayer - 1].hshs, s->val);
       break;
     case 62: // 0 20 062
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if ( s->ival < 10)
         sprintf(syn->s3.E,"%d", s->ival);
       else if (s->ival < 20)
         sprintf(syn->s3.E1,"%d", s->ival % 10);
       syn->mask |= SYNOP_SEC3;
       break;
     default:
       break;
     }
   // check about h
   if (syn->s1.h[0] == '/' && syn->s1.N[0] == '0')
     syn->s1.h[0] = '9';
   // Supress 7wwW1W2 if no significant weather
   if ((syn->s1.ww[0] == 0 || (syn->s1.ww[0] && (strcmp(syn->s1.ww,"04") < 0))) &&
       (syn->s1.W1[0] == 0 || (syn->s1.W1[0] && (strcmp(syn->s1.W1,"3") < 0))) &&
       (syn->s1.W2[0] == 0 || (syn->s1.W2[0] && (strcmp(syn->s1.W2,"3") < 0))))
     {
       syn->s1.ww[0] = 0;
       syn->s1.W1[0] = 0;
       syn->s1.W2[0] = 0;
       if (syn->s1.ix[0] == '1')
         syn->s1.ix[0] = '2';
     }
   return 0;
 }
char* vism_to_VV (char * target, double V)
Convert horizontal visibilty in meters to a VV string.
Parameters
V the visibility (m)
target the resulting VV string
Definition at line 124 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   if ( V < 100.0 )
     strcpy ( target, "00" );
   else if ( V <= 5000.0 )
     sprintf ( target, "%02d", ( int ) ( V + 0.1 ) / 100 );
   else if ( V <= 30000.0 )
     sprintf ( target, "%02d", ( int ) ( V + 0.1 ) / 1000 + 50 );
   else if ( V <= 70000.0 )
     sprintf ( target, "%02d", ( int ) ( V - 30000.0 ) / 5000 + 80 );
   else
     strcpy ( target, "89" );
   return target;
 }