bufr2synop: src/libraries/bufr2tac_climat.c File Reference
bufr2tac_climat.c File Reference
file with the code to parse a sequence as a FM-71 XII CLIMAT and FM-72 XII CLIMAT SHIP
#include "bufr2tac.h"
Functions
int parse_subset_as_climat (struct metreport *m, struct bufr2tac_subset_state *s, struct bufr_subset_sequence_data *sq, char *err)
Detailed Description
file with the code to parse a sequence as a FM-71 XII CLIMAT and FM-72 XII CLIMAT SHIP
Definition in file bufr2tac_climat.c.
Function Documentation
parse_subset_as_climat()
int parse_subset_as_climat (struct metreport * m, struct bufr2tac_subset_state * s, struct bufr_subset_sequence_data * sq, char * err)
Definition at line 38 of file bufr2tac_climat.c.
{
  size_t is;
  char aux[32];
  struct climat_chunks *c;
  c = &m->climat;
  // clean data
  bufr2tac_clean_climat_chunks ( c );
  // reject if still not coded type
  if ( strcmp ( s->type_report,"CLIMAT" ) )
    {
      sprintf ( err,"bufr2tac: parse_subset_as_climat(): '%s' reports still not decoded in this software", s->type_report );
      return 1;
    }
  strcpy ( m->type, s->type_report );
  /**** First pass, sequential analysis *****/
  for ( is = 0; is < sq->nd; is++ )
    {
      s->i = is;
      s->ival = ( int ) sq->sequence[is].val;
      s->val = sq->sequence[is].val;
      s->a = &sq->sequence[is];
      if ( is > 0 )
        {
          s->a1 = &sq->sequence[is - 1];
        }
      switch ( sq->sequence[is].desc.x )
        {
        case 1: //localization descriptors
          climat_parse_x01 ( c, s );
          break;
        case 2: //Type of station descriptors
          climat_parse_x02 ( c, s );
          break;
        case 4: //Date and time descriptors
          climat_parse_x04 ( c, s );
          break;
        case 5: // Horizontal position. Latitude
          climat_parse_x05 ( c, s );
          break;
        case 6: // Horizontal position. Longitude
          climat_parse_x06 ( c, s );
          break;
        case 7: // Vertical position
          climat_parse_x07 ( c, s );
          break;
        case 8: // significance qualifier
          climat_parse_x08 ( c, s );
          break;
        case 10: // Air pressure
          climat_parse_x10 ( c, s );
          break;
        case 11: // Wind
          climat_parse_x11 ( c, s );
          break;
        case 12: // Temperature
          climat_parse_x12 ( c, s );
          break;
        case 13: // Humidity and precipitation data
          climat_parse_x13 ( c, s );
          break;
        case 14: // Radiation
          climat_parse_x14 ( c, s );
          break;
        default:
          break;
        }
    }
  // Fill some metreport fields
  if ( strlen ( c->s0.II ) )
    {
      strcpy ( m->g.index, c->s0.II );
      strcat ( m->g.index, c->s0.iii );
    }
  if ( s->mask & SUBSET_MASK_HAVE_LATITUDE )
    {
      m->g.lat = s->lat;
    }
  if ( s->mask & SUBSET_MASK_HAVE_LONGITUDE )
    {
      m->g.lon = s->lon;
    }
  if ( s->mask & SUBSET_MASK_HAVE_ALTITUDE )
    {
      m->g.alt = s->alt;
    }
  if ( s->mask & SUBSET_MASK_HAVE_NAME )
    {
      strcpy ( m->g.name, s->name );
    }
  if ( s->mask & SUBSET_MASK_HAVE_COUNTRY )
    {
      strcpy ( m->g.country, s->country );
    }
  sprintf ( aux,"%s%s%s%s%s", c->e.YYYY, c->e.MM, c->e.DD, c->e.HH, c->e.mm );
  YYYYMMDDHHmm_to_met_datetime ( &m->t, aux );
   // copy WIGOS ID
  memcpy(&m->g.wid, &m->climat.wid, sizeof (struct wigos_id) );
  if ( check_date_from_future ( m ) )
    {
      return 1;  // Bad date/time . Is a report from future!
    }
  return 0;
}
References bufr2tac_subset_state::a, bufr2tac_subset_state::a1, bufr2tac_subset_state::alt, met_geo::alt, bufr2tac_clean_climat_chunks(), check_date_from_future(), metreport::climat, climat_parse_x01(), climat_parse_x02(), climat_parse_x04(), climat_parse_x05(), climat_parse_x06(), climat_parse_x07(), climat_parse_x08(), climat_parse_x10(), climat_parse_x11(), climat_parse_x12(), climat_parse_x13(), climat_parse_x14(), bufr2tac_subset_state::country, met_geo::country, report_date_ext::DD, climat_chunks::e, metreport::g, report_date_ext::HH, bufr2tac_subset_state::i, climat_sec0::II, climat_sec0::iii, met_geo::index, bufr2tac_subset_state::ival, bufr2tac_subset_state::lat, met_geo::lat, bufr2tac_subset_state::lon, met_geo::lon, bufr2tac_subset_state::mask, report_date_ext::MM, report_date_ext::mm, bufr2tac_subset_state::name, met_geo::name, climat_chunks::s0, SUBSET_MASK_HAVE_ALTITUDE, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_HAVE_NAME, metreport::t, metreport::type, bufr2tac_subset_state::type_report, bufr2tac_subset_state::val, met_geo::wid, climat_chunks::wid, report_date_ext::YYYY, and YYYYMMDDHHmm_to_met_datetime().
Referenced by parse_subset_sequence().