bufr2synop: src/apps/bufrnoaa_utils.c File Reference
bufrnoaa_utils.c File Reference
File with some routines for bufrnoaa binary.
#include "bufrnoaa.h"
Functions
int is_bufr (unsigned char *b)
checks if an unsigned char from an array is the first char of 'BUFR'
int is_head (unsigned char *b)
checks if an unsigned char from an array is the first char of '****'
int is_head_custom (unsigned char *b, char mark)
checks if an unsigned char from an array is the first char of repeated mark char four times
int is_endb (unsigned char *b)
checks if an unsigned char from an array is the first char of '7777'
int timeval_substract (struct timeval *result, struct timeval *x, struct timeval *y)
Subtract the ‘struct timeval’ values X and Y, storing the result in RESULT.
int bufr_is_selected (char *name)
returns 1 if selected message 0 otherwise
int date_mtime_from_stat (char *date, struct stat *st)
get a string with date and time from a struct stat
int mtime_from_stat (char *filename, struct stat *st)
modifies a file update time from a struct stat
Detailed Description
File with some routines for bufrnoaa binary.
Definition in file bufrnoaa_utils.c.
Function Documentation
bufr_is_selected()
int bufr_is_selected (char * name)
returns 1 if selected message 0 otherwise
Parameters
name string with name to check
Definition at line 124 of file bufrnoaa_utils.c.
{
  if ( strlen ( SEL ) == 0 )
    return 0;
  if ( strchr ( SEL, name[1] ) == NULL )
    return 0;
  if ( name[1] == 'S' )
    {
      if ( strlen ( SELS ) == 0 )
        return 1;
      else if ( strchr ( SELS, name[2] ) == NULL )
        return 0;
    }
  if ( name[1] == 'O' )
    {
      if ( strlen ( SELO ) == 0 )
        return 1;
      else if ( strchr ( SELO, name[2] ) == NULL )
        return 0;
    }
  if ( name[1] == 'U' )
    {
      if ( strlen ( SELU ) == 0 )
        return 1;
      else if ( strchr ( SELU, name[2] ) == NULL )
        return 0;
    }
  return 1;
}
References SELO, SELS, and SELU.
Referenced by main().
date_mtime_from_stat()
int date_mtime_from_stat (char * date, struct stat * st)
get a string with date and time from a struct stat
Parameters
date string wuth the result
st pointer to a strucr stat
Definition at line 163 of file bufrnoaa_utils.c.
{
  struct tm tim;
  memset ( &tim, 0, sizeof ( tim ) );
  gmtime_r ( & ( st->st_mtime ), &tim );
  strftime ( date, 16, "%Y%m%d%H%M%S", &tim );
  return 1;
}
Referenced by main().
is_bufr()
int is_bufr (unsigned char * b)
checks if an unsigned char from an array is the first char of 'BUFR'
Parameters
b pointer to unsigned char to check
Returns 1 if success, 0 othewise
Definition at line 33 of file bufrnoaa_utils.c.
{
  if ( b[0] == 'R' && b[1] == 'F' && b[2] == 'U' && b[3] == 'B' )
    return 1;
  return 0;
}
Referenced by main().
is_endb()
int is_endb (unsigned char * b)
checks if an unsigned char from an array is the first char of '7777'
Parameters
b pointer to unsigned char to check
Returns 1 if success, 0 othewise
Definition at line 76 of file bufrnoaa_utils.c.
{
  if ( b[0] == '7' && b[1] == '7' && b[2] == '7' && b[3] == '7' )
    return 1;
  return 0;
}
Referenced by main().
is_head()
int is_head (unsigned char * b)
checks if an unsigned char from an array is the first char of '****'
Parameters
b pointer to unsigned char to check
Returns 1 if success, 0 othewise
Definition at line 47 of file bufrnoaa_utils.c.
{
  if ( b[0] == '*' && b[1] == '*' && b[2] == '*' && b[3] == '*' )
    return 1;
  return 0;
}
is_head_custom()
int is_head_custom (unsigned char * b, char mark)
checks if an unsigned char from an array is the first char of repeated mark char four times
Parameters
b pointer to unsigned char to check
mark char to be found repeated four times since b Returns 1 if success, 0 othewise
Definition at line 61 of file bufrnoaa_utils.c.
{
  if ( b[0] == mark && b[1] == mark && b[2] == mark && b[3] == mark )
    return 1;
  return 0;
}
Referenced by main().
mtime_from_stat()
int mtime_from_stat (char * filename, struct stat * st)
modifies a file update time from a struct stat
Parameters
filename string with the pathname of file to modify
st pointer to a struct stat as reference
Definition at line 178 of file bufrnoaa_utils.c.
{
  struct utimbuf ut;
  ut.modtime = st->st_mtime;
  ut.actime = st->st_mtime;
  utime ( filename, &ut );
  return 1;
}
Referenced by main().
timeval_substract()
int timeval_substract (struct timeval * result, struct timeval * x, struct timeval * y)
Subtract the ‘struct timeval’ values X and Y, storing the result in RESULT.
Parameters
result pointer to a struct timeval where to set the result
x pointer to struct timeval as X in (X - Y)
y pointer to struct timeval as Y in (X - Y)
Return 1 if the difference is negative, otherwise 0.
Definition at line 93 of file bufrnoaa_utils.c.
{
  /* Perform the carry for the later subtraction by updating Y. */
  if ( x->tv_usec < y->tv_usec )
    {
      int nsec = ( y->tv_usec - x->tv_usec ) / 1000000 + 1;
      y->tv_usec -= 1000000 * nsec;
      y->tv_sec += nsec;
    }
  if ( x->tv_usec - y->tv_usec > 1000000 )
    {
      int nsec = ( x->tv_usec - y->tv_usec ) / 1000000;
      y->tv_usec += 1000000 * nsec;
      y->tv_sec -= nsec;
    }
  /* Compute the time remaining to wait.
     `tv_usec' is certainly positive. */
  result->tv_sec = x->tv_sec - y->tv_sec;
  result->tv_usec = x->tv_usec - y->tv_usec;
  /* Return 1 if result is negative. */
  return x->tv_sec < y->tv_sec;
}
Referenced by main().