bufr2synop: src/libraries/bufr2tac_x01.c File Reference
bufr2tac_x01.c File Reference
decodes the descriptors with X = 01 (station index, name and country)
#include "bufr2tac.h"
#include <ctype.h>
Functions
int check_wigos_local_id (char *local_id)
int syn_parse_x01 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 01.
int buoy_parse_x01 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 01.
int climat_parse_x01 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 01.
int temp_parse_x01 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 01.
Detailed Description
decodes the descriptors with X = 01 (station index, name and country)
Definition in file bufr2tac_x01.c.
Function Documentation
buoy_parse_x01()
int buoy_parse_x01 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
b pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 205 of file bufr2tac_x01.c.
{
  char aux[80];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 3: // 0 01 003
      if ( s->ival > 0 )
        sprintf ( b->s0.A1, "%d", s->ival % 10 );
      else if ( s->ival == 0 )
        sprintf ( b->s0.A1, "7" );
      break;
    case 4: // 0 01 004
    case 20: // 0 01 004
      sprintf ( b->s0.bw, "%d", s->ival );
      break;
    case 5: // 0 01 005
      if ( s->ival < 1000 )
        sprintf ( b->s0.nbnbnb, "%03d", s->ival % 1000 );
      else
        sprintf ( b->s0.nbnbnb, "%05d", s->ival % 100000 ); // note this is a nnnnn extension
      break;
    case 15: // 0 01 015. Station or site name
      if ( strlen ( s->a->cval ) <= 80 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          strcpy ( s->name, aux );
          s->mask |= SUBSET_MASK_HAVE_NAME;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "buoy_parse_x01()", "Station or site name length > 80. Cannot set s->name" );
        }
      break;
    case 87: // 0 01 087. WMO marine observing platform extended identifier
      // See https://community.wmo.int/rules-allocating-wmo-numbers
      // A1bwnnn is equivalent to A1Bwnnnnn when nnnnn < 1000
      if ( s->a->val < 100000000 )
        {
          sprintf ( aux, "%07.0lf", s->a->val );
          b->s0.A1[0] = aux[0];
          b->s0.A1[1] = 0;
          b->s0.bw[0] = aux[1];
          b->s0.bw[1] = 0;
          if ( ( ( int ) ( s->a->val ) % 100000 ) < 1000 )
            strcpy ( b->s0.nbnbnb, & aux[4] );
          else
            strcpy ( b->s0.nbnbnb, & aux[2] );
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "buoy_parse_x01()",
                               "WMO marine observing platform extended identifier >= 100000000. Cannot set s0.A1, s0.bw, s0.nbnbnb" );
        }
      break;
    case 101: // 0 01 101 . State identifier
      if ( strlen ( s->a->ctable ) <= 256 )
        {
          strcpy ( aux, s->a->ctable );
          adjust_string ( aux );
          strcpy ( s->country, aux );
          s->mask |= SUBSET_MASK_HAVE_COUNTRY;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "buoy_parse_x01()", "State identifier length > 256. Cannot set s->country" );
        }
      break;
    case 125: // 0 01 125 . WIGOS identifier series
      b->wid.series = ( uint8_t ) s->ival;
      break;
    case 126: // 0 01 126 . WIGOS issuer of identifier
      b->wid.issuer = ( uint16_t ) s->ival;
      break;
    case 127: // 0 01 127 , WIGOS issue number
      b->wid.issue = ( uint16_t ) s->ival;
      break;
    case 128: // 0 01 128 . WIGOS local identifier (character)
      if ( strlen ( s->a->cval ) <= 16 )
        {
          adjust_string ( s->a->cval );
          if ( check_wigos_local_id ( s->a->cval ) )
            {
              bufr2tac_set_error ( s, 1, "buoy_parse_x01()","Bad WIGOS Local identifier" );
            }
          strcpy ( b->wid.local_id, s->a->cval );
          s->mask |= SUBSET_MASK_HAVE_WIGOS_ID ;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && ( s->a->mask & DESCRIPTOR_VALUE_MISSING ) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x01()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, buoy_sec0::A1, adjust_string(), BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), buoy_sec0::bw, check_wigos_local_id(), bufr2tac_subset_state::country, bufr_atom_data::ctable, bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, wigos_id::issue, wigos_id::issuer, bufr2tac_subset_state::ival, wigos_id::local_id, bufr_atom_data::mask, bufr2tac_subset_state::mask, bufr2tac_subset_state::name, buoy_sec0::nbnbnb, buoy_chunks::s0, wigos_id::series, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_WIGOS_ID, bufr_atom_data::val, buoy_chunks::wid, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
check_wigos_local_id()
int check_wigos_local_id (char * local_id)
Definition at line 27 of file bufr2tac_x01.c.
{
  char *c = local_id;
  // first char cannot be blank
  if ( ! ( isalpha ( *c ) ) && ! ( isdigit ( *c ) ) )
    return 1;
  c++;
  while ( *c )
    {
      if ( ! ( isalpha ( *c ) ) && ! ( isdigit ( *c ) ) && ! ( isblank ( *c ) ) )
        return 1;
      c++;
    }
  return 0;
}
Referenced by buoy_parse_x01(), climat_parse_x01(), syn_parse_x01(), and temp_parse_x01().
climat_parse_x01()
int climat_parse_x01 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
c pointer to a struct climat_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 324 of file bufr2tac_x01.c.
{
  char aux[80];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 1: // 0 01 001 . WMO block number
      sprintf ( c->s0.II, "%02d", s->ival );
      break;
    case 2: // 0 01 002 . WMO station number
      sprintf ( c->s0.iii, "%03d", s->ival );
      break;
    case 3: // 0 01 003 . WMO Region
      if ( s->ival == 1 )
        strcpy ( c->s0.Reg, "I" );
      else if ( s->ival == 2 )
        strcpy ( c->s0.Reg, "II" );
      else if ( s->ival == 3 )
        strcpy ( c->s0.Reg, "III" );
      else if ( s->ival == 4 )
        strcpy ( c->s0.Reg, "IV" );
      else if ( s->ival == 5 )
        strcpy ( c->s0.Reg, "V" );
      else if ( s->ival == 6 )
        strcpy ( c->s0.Reg, "VI" );
      break;
    case 15: // 0 01 015 . Station or site name
    case 18: // 0 01 018 . Short station or site name
    case 19: // 0 01 019 . Long station or site name
      if ( strlen ( s->a->cval ) <= 80 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          strcpy ( s->name, aux );
          s->mask |= SUBSET_MASK_HAVE_NAME;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "climat_parse_x01()", "Station or site name length > 80. Cannot set s->name" );
        }
      break;
    case 125: // 0 01 125 . WIGOS identifier series
      c->wid.series = ( uint8_t ) s->ival;
      break;
    case 126: // 0 01 126 . WIGOS issuer of identifier
      c->wid.issuer = ( uint16_t ) s->ival;
      break;
    case 127: // 0 01 127 , WIGOS issue number
      c->wid.issue = ( uint16_t ) s->ival;
      break;
    case 128: // 0 01 128 . WIGOS local identifier (character)
      if ( strlen ( s->a->cval ) <= 16 )
        {
          strcpy ( c->wid.local_id, s->a->cval );
          if ( check_wigos_local_id ( s->a->cval ) )
            {
              bufr2tac_set_error ( s, 1, "climat_parse_x01()","Bad WIGOS Local identifier" );
            }
          s->mask |= SUBSET_MASK_HAVE_WIGOS_ID ;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && ( s->a->mask & DESCRIPTOR_VALUE_MISSING ) == 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x01()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, adjust_string(), BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), check_wigos_local_id(), bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, climat_sec0::II, climat_sec0::iii, wigos_id::issue, wigos_id::issuer, bufr2tac_subset_state::ival, wigos_id::local_id, bufr_atom_data::mask, bufr2tac_subset_state::mask, bufr2tac_subset_state::name, climat_sec0::Reg, climat_chunks::s0, wigos_id::series, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_WIGOS_ID, climat_chunks::wid, and bufr_descriptor::y.
Referenced by parse_subset_as_climat().
syn_parse_x01()
int syn_parse_x01 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 54 of file bufr2tac_x01.c.
{
  char aux[80];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 1: // 0 01 001 . WMO block number
      sprintf ( syn->s0.II, "%02d", s->ival );
      break;
    case 2: // 0 01 002 . WMO station number
      sprintf ( syn->s0.iii, "%03d", s->ival );
      break;
    case 3: // 0 01 003 . WMO Region
      sprintf ( syn->s0.A1, "%d", s->ival );
      if ( strcmp ( syn->s0.A1, "1" ) == 0 )
        strcpy ( syn->s0.Reg, "I" );
      else if ( strcmp ( syn->s0.A1, "2" ) == 0 )
        strcpy ( syn->s0.Reg, "II" );
      else if ( strcmp ( syn->s0.A1, "3" ) == 0 )
        strcpy ( syn->s0.Reg, "III" );
      else if ( strcmp ( syn->s0.A1, "4" ) == 0 )
        strcpy ( syn->s0.Reg, "IV" );
      else if ( strcmp ( syn->s0.A1, "5" ) == 0 )
        strcpy ( syn->s0.Reg, "V" );
      else if ( strcmp ( syn->s0.A1, "6" ) == 0 )
        strcpy ( syn->s0.Reg, "VI" );
      break;
    case 4: // 0 01 004 . WMO Subarea
    case 20: // 0 01 020 . WMO region subarea
      sprintf ( syn->s0.bw, "%d", s->ival );
      break;
    case 10: // 0 01 010. Stationary buoy platform identifier
      if ( strlen ( s->a->cval ) < 16 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          if ( aux[0] == '\xff' )
            break;
          if ( strlen ( aux ) < 10 )
            strcpy ( syn->s0.D_D, aux );
          else
            bufr2tac_set_error ( s, 1, "syn_parse_x01()", "Ship or mobile land station index length >= 10. Cannot set s0.D_D" );
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "syn_parse_x01()", "Ship or mobile land station index length >= 16" );
        }
      break;
    case 11: // 0 01 011. Ship or mobile land station index
      if ( strlen ( s->a->cval ) < 16 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          if ( aux[0] == '\xff' )
            break;
          if ( strlen ( aux ) < 10 )
            strcpy ( syn->s0.D_D, aux );
          else
            bufr2tac_set_error ( s, 1, "syn_parse_x01()", "Ship or mobile land station index length >= 10. Cannot set s0.D_D" );
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "syn_parse_x01()", "Ship or mobile land station index length >= 16" );
        }
      break;
    case 15: // 0 01 015 . Station or site name
    case 18: // 0 01 018 . Short station or site name
    case 19: // 0 01 019 . Long station or site name
      if ( strlen ( s->a->cval ) <= 80 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          strcpy ( s->name, aux );
          s->mask |= SUBSET_MASK_HAVE_NAME;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "syn_parse_x01()", "Station or site name length > 80. Cannot set s->name" );
        }
      break;
    case 101: // 0 01 101 . State identifier
      if ( strlen ( s->a->ctable ) <= 256 )
        {
          strcpy ( aux, s->a->ctable );
          adjust_string ( aux );
          strcpy ( s->country, aux );
          s->mask |= SUBSET_MASK_HAVE_COUNTRY;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "syn_parse_x01()", "State identifier length > 256. Cannot set s->country" );
        }
      break;
    case 125: // 0 01 125 . WIGOS identifier series
      syn->wid.series = ( uint8_t ) s->ival;
      break;
    case 126: // 0 01 126 . WIGOS issuer of identifier
      syn->wid.issuer = ( uint16_t ) s->ival;
      break;
    case 127: // 0 01 127 , WIGOS issue number
      syn->wid.issue = ( uint16_t ) s->ival;
      break;
    case 128: // 0 01 128 . WIGOS local identifier (character)
      if ( strlen ( s->a->cval ) <= 16 )
        {
          adjust_string ( s->a->cval );
          if ( check_wigos_local_id ( s->a->cval ) )
            {
              bufr2tac_set_error ( s, 1, "synop_parse_x01()","Bad WIGOS Local identifier" );
            }
          strcpy ( syn->wid.local_id, s->a->cval );
          s->mask |= SUBSET_MASK_HAVE_WIGOS_ID ;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && ( s->a->mask & DESCRIPTOR_VALUE_MISSING ) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x01()", "Descriptor not parsed" );
      break;
    }
  //set WMO region if we know II and iii and still no set A1
  if ( ( syn->s0.A1[0] == 0 ) && syn->s0.II[0] && syn->s0.iii[0] )
    {
      guess_WMO_region ( syn->s0.A1, syn->s0.Reg, syn->s0.II, syn->s0.iii );
    }
  return 0;
}
References bufr2tac_subset_state::a, synop_sec0::A1, adjust_string(), BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), synop_sec0::bw, check_wigos_local_id(), bufr2tac_subset_state::country, bufr_atom_data::ctable, bufr_atom_data::cval, synop_sec0::D_D, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, guess_WMO_region(), synop_sec0::II, synop_sec0::iii, wigos_id::issue, wigos_id::issuer, bufr2tac_subset_state::ival, wigos_id::local_id, bufr_atom_data::mask, bufr2tac_subset_state::mask, bufr2tac_subset_state::name, synop_sec0::Reg, synop_chunks::s0, wigos_id::series, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_WIGOS_ID, synop_chunks::wid, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x01()
int temp_parse_x01 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 415 of file bufr2tac_x01.c.
{
  char aux[80];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 1: // 0 01 001 . WMO block number
      sprintf ( t->a.s1.II, "%02d", s->ival );
      sprintf ( t->b.s1.II, "%02d", s->ival );
      sprintf ( t->c.s1.II, "%02d", s->ival );
      sprintf ( t->d.s1.II, "%02d", s->ival );
      break;
    case 2: // 0 01 002 . WMO station number
      sprintf ( t->a.s1.iii, "%03d", s->ival );
      sprintf ( t->b.s1.iii, "%03d", s->ival );
      sprintf ( t->c.s1.iii, "%03d", s->ival );
      sprintf ( t->d.s1.iii, "%03d", s->ival );
      break;
    case 3: // 0 01 003 . WMO Region
      sprintf ( t->a.s1.A1, "%d", s->ival );
      sprintf ( t->b.s1.A1, "%d", s->ival );
      sprintf ( t->c.s1.A1, "%d", s->ival );
      sprintf ( t->d.s1.A1, "%d", s->ival );
      if ( strcmp ( t->a.s1.A1, "1" ) == 0 )
        {
          strcpy ( t->a.s1.Reg, "I" );
          strcpy ( t->b.s1.Reg, "I" );
          strcpy ( t->c.s1.Reg, "I" );
          strcpy ( t->d.s1.Reg, "I" );
        }
      else if ( strcmp ( t->a.s1.A1, "2" ) == 0 )
        {
          strcpy ( t->a.s1.Reg, "II" );
          strcpy ( t->b.s1.Reg, "II" );
          strcpy ( t->c.s1.Reg, "II" );
          strcpy ( t->d.s1.Reg, "II" );
        }
      else if ( strcmp ( t->a.s1.A1, "3" ) == 0 )
        {
          strcpy ( t->a.s1.Reg, "III" );
          strcpy ( t->b.s1.Reg, "III" );
          strcpy ( t->c.s1.Reg, "III" );
          strcpy ( t->d.s1.Reg, "III" );
        }
      else if ( strcmp ( t->a.s1.A1, "4" ) == 0 )
        {
          strcpy ( t->a.s1.Reg, "IV" );
          strcpy ( t->b.s1.Reg, "IV" );
          strcpy ( t->c.s1.Reg, "IV" );
          strcpy ( t->d.s1.Reg, "IV" );
        }
      else if ( strcmp ( t->a.s1.A1, "5" ) == 0 )
        {
          strcpy ( t->a.s1.Reg, "V" );
          strcpy ( t->b.s1.Reg, "V" );
          strcpy ( t->c.s1.Reg, "V" );
          strcpy ( t->d.s1.Reg, "V" );
        }
      else if ( strcmp ( t->a.s1.A1, "6" ) == 0 )
        {
          strcpy ( t->a.s1.Reg, "VI" );
          strcpy ( t->b.s1.Reg, "VI" );
          strcpy ( t->c.s1.Reg, "VI" );
          strcpy ( t->d.s1.Reg, "VI" );
        }
      break;
    case 4: // 0 01 004 . WMO Subarea
    case 20: // 0 01 020 . WMO region subarea
      sprintf ( t->a.s1.bw, "%d", s->ival );
      sprintf ( t->b.s1.bw, "%d", s->ival );
      sprintf ( t->c.s1.bw, "%d", s->ival );
      sprintf ( t->d.s1.bw, "%d", s->ival );
      break;
    case 11: // 0 01 011. Ship or mobile land station index
      if ( strlen ( s->a->cval ) < 16 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          if ( aux[0] == '\xff' )
            break;
          if ( strlen ( aux ) < 10 )
            {
              strcpy ( t->a.s1.D_D, aux );
              strcpy ( t->b.s1.D_D, aux );
              strcpy ( t->c.s1.D_D, aux );
              strcpy ( t->d.s1.D_D, aux );
            }
        }
      break;
    case 15: // 0 01 015 . Station or site name
    case 18: // 0 01 018 . Short station or site name
    case 19: // 0 01 019 . Long station or site name
      if ( strlen ( s->a->cval ) <= 80 )
        {
          strcpy ( aux, s->a->cval );
          adjust_string ( aux );
          strcpy ( s->name, aux );
          s->mask |= SUBSET_MASK_HAVE_NAME;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "temp_parse_x01()", "Station or site name length > 80. Cannot set s->name" );
        }
      break;
    case 101: // 0 01 101 . State identifier
      if ( strlen ( s->a->ctable ) <= 256 )
        {
          strcpy ( aux, s->a->ctable );
          adjust_string ( aux );
          strcpy ( s->country, aux );
          s->mask |= SUBSET_MASK_HAVE_COUNTRY;
        }
      else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
        {
          bufr2tac_set_error ( s, 1, "temp_parse_x01()", "State identifier length > 256. Cannot set s->country" );
        }
      break;
    case 125: // 0 01 125 . WIGOS identifier series
      t->wid.series = ( uint8_t ) s->ival;
      break;
    case 126: // 0 01 126 . WIGOS issuer of identifier
      t->wid.issuer = ( uint16_t ) s->ival;
      break;
    case 127: // 0 01 127 , WIGOS issue number
      t->wid.issue = ( uint16_t ) s->ival;
      break;
    case 128: // 0 01 128 . WIGOS local identifier (character)
      if ( strlen ( s->a->cval ) <= 16 )
        {
          strcpy ( t->wid.local_id, s->a->cval );
          if ( check_wigos_local_id ( s->a->cval ) )
            {
              bufr2tac_set_error ( s, 1, "temp_parse_x01()","Bad WIGOS Local identifier" );
            }
          s->mask |= SUBSET_MASK_HAVE_WIGOS_ID ;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && ( s->a->mask & DESCRIPTOR_VALUE_MISSING ) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x01()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, temp_chunks::a, temp_acd_sec1::A1, temp_b_sec1::A1, adjust_string(), temp_chunks::b, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), temp_acd_sec1::bw, temp_b_sec1::bw, temp_chunks::c, check_wigos_local_id(), bufr2tac_subset_state::country, bufr_atom_data::ctable, bufr_atom_data::cval, temp_chunks::d, temp_acd_sec1::D_D, temp_b_sec1::D_D, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, temp_acd_sec1::II, temp_b_sec1::II, temp_acd_sec1::iii, temp_b_sec1::iii, wigos_id::issue, wigos_id::issuer, bufr2tac_subset_state::ival, wigos_id::local_id, bufr_atom_data::mask, bufr2tac_subset_state::mask, bufr2tac_subset_state::name, temp_acd_sec1::Reg, temp_b_sec1::Reg, temp_a::s1, temp_b::s1, temp_c::s1, temp_d::s1, wigos_id::series, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_WIGOS_ID, temp_chunks::wid, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().