bufr2synop: src/bufrdeco/bufrdeco_ecmwf.c File Reference
bufrdeco_ecmwf.c File Reference
This file has the code to read bufr files from ECMWF package.
#include "bufrdeco.h"
Functions
int get_ecmwf_tablenames (struct bufrdeco *b, const char *bufrtables_dir)
Get the complete pathnames for EMCWF table files needed by a bufr message.
int bufr_read_tables_ecmwf (struct bufrdeco *b, char *tables_dir)
Read the tables according with bufr file data from a bufr table directory.
Variables
const char DEFAULT_BUFRTABLES_ECMWF_DIR1 [] = "/usr/local/lib/bufrtables/"
const char DEFAULT_BUFRTABLES_ECMWF_DIR2 [] = "/usr/lib/bufrtables/"
Detailed Description
This file has the code to read bufr files from ECMWF package.
Definition in file bufrdeco_ecmwf.c.
Function Documentation
int bufr_read_tables_ecmwf (struct bufrdeco * b, char * tables_dir)
Read the tables according with bufr file data from a bufr table directory.
Parameters
b basic struct with needed data
tables_dir complete path string for directory with ECMWF bufr tables. Must be ended with a '/' . If NULL then is the default
The default directories where to search bufr tables are stored in DEFAULT_BUFRTABLES_ECMWF_DIR1 and DEFAULT_BUFRTABLES_ECMWF_DIR2
Definition at line 165 of file bufrdeco_ecmwf.c.
References bufr_tables::b, bufr_read_tableb(), bufr_read_tablec(), bufr_read_tabled(), bufrdeco_init_tables(), bufr_tables::c, bufr_tables::d, bufrdeco::error, get_ecmwf_tablenames(), and bufrdeco::tables.
Referenced by bufrdeco_read_bufr().
 {
   // get tablenames
   if ( get_ecmwf_tablenames ( b, tables_dir ) )
     {
       sprintf ( b->error, "bufrdeco_read_tables_ecmwf(): Cannot find bufr tebles\n" );
       return 1;
     }
   // If tables still not initialized then do it
   if ( b->tables == NULL && bufrdeco_init_tables ( & ( b->tables ) ) )
     {
       sprintf ( b->error, "bufrdeco_read_tables_ecmwf(): Cannot allocate memory for tables\n" );
       return 1;
     }
   // And now read tables
   if ( bufr_read_tableb ( & ( b->tables->b ), b->error ) )
     {
       return 1;
     }
   if ( bufr_read_tablec ( & ( b->tables->c ), b->error ) )
     {
       return 1;
     }
   if ( bufr_read_tabled ( & ( b->tables->d ), b->error ) )
     {
       return 1;
     }
   return 0;
 }
int get_ecmwf_tablenames (struct bufrdeco * b, const char * bufrtables_dir)
Get the complete pathnames for EMCWF table files needed by a bufr message.
Parameters
bufrtables_dir string with path to bufr file tables dir
b pointer for a struct bufrdeco
In ECMWF library the name of a table file is Kssswwwwwxxxxxyyyzzz.TXT , where
K - type of table, i.e, 'B', 'C', or 'D'
sss - Master table number (zero for WMO meteorological tables)
wwwww - Originating sub-centre
xxxxx - Originating centre
yyy - Version number of master table used
zzz - Version number of local table used
Definition at line 46 of file bufrdeco_ecmwf.c.
References bufr_tables::b, bufr_tables::c, bufr_sec1::centre, bufr_tables::d, DEFAULT_BUFRTABLES_ECMWF_DIR1, DEFAULT_BUFRTABLES_ECMWF_DIR2, bufr_sec1::master, bufr_sec1::master_local, bufr_sec1::master_version, bufr_tableb::path, bufr_tablec::path, bufr_tabled::path, bufrdeco::sec1, bufr_sec1::subcentre, and bufrdeco::tables.
Referenced by bufr_read_tables_ecmwf().
 {
   struct stat st;
   char aux[256];
   if ( bufrtables_dir == NULL )
     {
       // try to guess directory
       if ( stat ( DEFAULT_BUFRTABLES_ECMWF_DIR1, &st ) )
         {
           if ( stat ( DEFAULT_BUFRTABLES_ECMWF_DIR2, &st ) )
             {
               return 1;
             }
           else
             {
               if ( S_ISDIR ( st.st_mode ) )
                 {
                   strcpy ( aux,DEFAULT_BUFRTABLES_ECMWF_DIR2 );
                 }
             }
         }
       else
         {
           if ( S_ISDIR ( st.st_mode ) )
             {
               strcpy ( aux,DEFAULT_BUFRTABLES_ECMWF_DIR1 );
             }
         }
     }
   else
     {
       strcpy ( aux, bufrtables_dir );
     }
   sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
   sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
   sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
   /* check for table b, if problems then we try alternative */
   if ( stat ( b->tables->b.path, &st ) )
     {
       // here we set originating centre xxxxx to 00000 for WMO tables
       if ( b->sec1.master != 0 ) // case of not WMO tables
         {
           sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
                     b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
                     b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d%03d.TXT", aux, b->sec1.master,
                     b->sec1.subcentre, b->sec1.centre, b->sec1.master_version, b->sec1.master_local );
         }
       else
         {
           sprintf ( b->tables->b.path,"%sB000%05d00000%03d%03d.TXT", aux, b->sec1.subcentre,
                     b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->c.path,"%sC000%05d00000%03d%03d.TXT", aux, b->sec1.subcentre,
                     b->sec1.master_version, b->sec1.master_local );
           sprintf ( b->tables->d.path,"%sD000%05d00000%03d%03d.TXT", aux, b->sec1.subcentre,
                     b->sec1.master_version, b->sec1.master_local );
         }
       if ( stat ( b->tables->b.path, &st ) )
         {
           // Another chance. Set local zzz to 000
           if ( b->sec1.master != 0 ) // case of not WMO tables
             {
               sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                         b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
               sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                         b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
               sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                         b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
             }
           else
             {
               sprintf ( b->tables->b.path,"%sB000%05d00000%03d000.TXT", aux, b->sec1.subcentre,
                         b->sec1.master_version );
               sprintf ( b->tables->c.path,"%sC000%05d00000%03d000.TXT", aux, b->sec1.subcentre,
                         b->sec1.master_version );
               sprintf ( b->tables->d.path,"%sD000%05d00000%03d000.TXT", aux, b->sec1.subcentre,
                         b->sec1.master_version );
             }
           if ( stat ( b->tables->b.path, &st ) )
             {
               // Another chance. Set subcentre wwwww to 00000
               if ( b->sec1.master != 0 ) // case of not WMO tables
                 {
                   sprintf ( b->tables->b.path,"%sB%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
                   sprintf ( b->tables->c.path,"%sC%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
                   sprintf ( b->tables->d.path,"%sD%03d%05d%05d%03d000.TXT", aux, b->sec1.master,
                             b->sec1.subcentre, b->sec1.centre, b->sec1.master_version );
                 }
               else
                 {
                   sprintf ( b->tables->b.path,"%sB0000000000000%03d000.TXT", aux, b->sec1.master_version );
                   sprintf ( b->tables->c.path,"%sC0000000000000%03d000.TXT", aux, b->sec1.master_version );
                   sprintf ( b->tables->d.path,"%sD0000000000000%03d000.TXT", aux, b->sec1.master_version );
                 }
             }
         }
     }
   return 0;
 }
Variable Documentation
const char DEFAULT_BUFRTABLES_ECMWF_DIR1[] = "/usr/local/lib/bufrtables/"
These are the default directories where the ECMWF package install bufrtables
Definition at line 29 of file bufrdeco_ecmwf.c.
Referenced by get_ecmwf_tablenames().
const char DEFAULT_BUFRTABLES_ECMWF_DIR2[] = "/usr/lib/bufrtables/"
Definition at line 30 of file bufrdeco_ecmwf.c.
Referenced by get_ecmwf_tablenames().