bufr2synop: src/bufrdeco/bufrdeco_utils.c File Reference
bufrdeco_utils.c File Reference
This file has the code of useful routines for library bufrdeco.
#include "bufrdeco.h"
Functions
buf_t get_bits_as_char_array2 (char *target, uint8_t *has_data, uint8_t *source, buf_t *bit0_offset, buf_t bit_length)
buf_t get_bits_as_char_array (char *target, uint8_t *has_data, uint8_t *source, buf_t *bit0_offset, buf_t bit_length)
uint32_t get_bits_as_uint32_t2 (uint32_t *target, uint8_t *has_data, uint8_t *source, buf_t *bit0_offset, buf_t bit_length)
Read bits from an array of uint8_t and set them as an uint32_t.
uint32_t get_bits_as_uint32_t (uint32_t *target, uint8_t *has_data, uint8_t *source, buf_t *bit0_offset, buf_t bit_length)
int get_table_b_reference_from_uint32_t (int32_t *target, uint8_t bits, uint32_t source)
Get an int32_t from bits according with bufr criteria to change the reference of a descritor. Most significant bit in source is sign.
uint32_t two_bytes_to_uint32 (const uint8_t *source)
returns the uint32_t value from an array of two bytes, most significant first
uint32_t three_bytes_to_uint32 (const uint8_t *source)
returns the uint32_t value from an array of three bytes, most significant first
int uint32_t_to_descriptor (struct bufr_descriptor *d, uint32_t id)
parse an integer with a descriptor fom bufr ECWMF libary
int two_bytes_to_descriptor (struct bufr_descriptor *d, const uint8_t *source)
set a struct bufr_descriptor from two consecutive bytes in bufr file
char * bufr_charray_to_string (char *s, char *buf, size_t size)
get a null termitated c-string from an array of unsigned chars
char * bufr_adjust_string (char *s)
Supress trailing blanks of a string.
int is_a_delayed_descriptor (struct bufr_descriptor *d)
check if a descriptor is a delayed descriptor
int is_a_short_delayed_descriptor (struct bufr_descriptor *d)
check if a descriptor is a short delayed descriptor
int is_a_local_descriptor (struct bufr_descriptor *d)
check if a descriptor is a local descriptor
char * get_formatted_value_from_escale (char *fmt, size_t dim, int32_t escale, double val)
gets a string with formatted value depending of scale
char * get_formatted_value_from_escale2 (char *fmt, size_t dim, int32_t escale, double val)
gets a string with formatted value depending of scale
int bufrdeco_add_to_bitmap (struct bufrdeco_bitmap *bm, buf_t index_to, buf_t index_by)
Push a bitmap element in a bufrdeco_bitmap.
int get_bitmaped_info (struct bufrdeco_bitmap_related_vars *brv, uint32_t target, struct bufrdeco *b)
Get bitmap info searching into bitmaps.
int bufr_write_subset_offset_bits (FILE *f, struct bufrdeco_subset_bit_offsets *off)
Write offset bit array for subsets in a non-compressed bufr.
int bufr_read_subset_offset_bits (FILE *f, struct bufrdeco_subset_bit_offsets *off)
Write offset bit array for subsets in a non-compressed bufr.
Variables
uint8_t bitf [8] = {0x80,0x40,0x20,0x10,0x08,0x04,0x02,0x01}
uint8_t biti [8] = {0xFF,0x7f,0x3f,0x1F,0x0F,0x07,0x03,0x01}
uint8_t bitk [8] = {0x80,0xc0,0xe0,0xf0,0xf8,0xfc,0xfe,0xff}
Detailed Description
This file has the code of useful routines for library bufrdeco.
Definition in file bufrdeco_utils.c.
Function Documentation
bufr_adjust_string()
char * bufr_adjust_string (char * s)
Supress trailing blanks of a string.
Parameters
s string to process
Returns
the resulting s string
Definition at line 333 of file bufrdeco_utils.c.
{
  size_t l;
  //bufrdeco_assert (s != NULL);
  l = strlen ( s );
  while ( l && s[--l] == ' ' )
    s[l] = '\0';
  return s;
}
Referenced by bufrdeco_print_json_object_atom_data(), bufrdeco_print_json_tree_recursive(), and main().
bufr_charray_to_string()
char * bufr_charray_to_string (char * s, char * buf, size_t size)
get a null termitated c-string from an array of unsigned chars
Parameters
s resulting string
buf pointer to first element in array
size number of chars in array
Returns
the resulting s string
Definition at line 316 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (s != NULL && buf != NULL);
  // copy
  memcpy ( s , buf, size );
  // add final string mark
  s[size] = '\0';
  return s;
}
Referenced by main().
bufr_read_subset_offset_bits()
int bufr_read_subset_offset_bits (FILE * f, struct bufrdeco_subset_bit_offsets * off)
Write offset bit array for subsets in a non-compressed bufr.
Parameters
f file pointer opened by caller
off pointer to the struct bufrdeco_subset_bit_offsets with the data to write into file
Returns
if success return 0, otherwise 1
Definition at line 577 of file bufrdeco_utils.c.
{
  size_t readed;
  //bufrdeco_assert (off != NULL && f != NULL );
  readed = fread( &(off->nr), sizeof (buf_t ), 1, f);
  bufrdeco_assert_with_return_val (readed == 1, 1);
  readed = fread( &(off->ofs[0]), sizeof (buf_t ), off->nr, f);
  bufrdeco_assert_with_return_val (readed == off->nr, 1);
  return 0;
}
References bufrdeco_assert_with_return_val, bufrdeco_subset_bit_offsets::nr, and bufrdeco_subset_bit_offsets::ofs.
Referenced by bufrdeco_read_subset_offset_bits().
bufr_write_subset_offset_bits()
int bufr_write_subset_offset_bits (FILE * f, struct bufrdeco_subset_bit_offsets * off)
Write offset bit array for subsets in a non-compressed bufr.
Parameters
f file pointer opened by caller
off pointer to the struct bufrdeco_subset_bit_offsets with the data to write into file
Returns
if success return 0, otherwise 1
Definition at line 555 of file bufrdeco_utils.c.
{
  size_t wrote;
  //bufrdeco_assert (off != NULL && f != NULL );
  wrote = fwrite( &(off->nr), sizeof (buf_t ), 1, f);
  bufrdeco_assert_with_return_val (wrote == 1, 1);
  wrote = fwrite( &(off->ofs[0]), sizeof (buf_t ), off->nr, f);
  bufrdeco_assert_with_return_val (wrote == off->nr, 1);
  return 0;
}
References bufrdeco_assert_with_return_val, bufrdeco_subset_bit_offsets::nr, and bufrdeco_subset_bit_offsets::ofs.
Referenced by bufrdeco_write_subset_offset_bits().
bufrdeco_add_to_bitmap()
int bufrdeco_add_to_bitmap (struct bufrdeco_bitmap * bm, buf_t index_to, buf_t index_by)
Push a bitmap element in a bufrdeco_bitmap.
Parameters
bm target struct bufrdeco_bitmap where to push
index_to index of the bufrdeco_bitmap which this is bitmapping to
index_by index of the bufrdeco_bitmap which this is bitmapped by
Returns
If no space to push returns 1, otherwise 0
Definition at line 461 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (bm != NULL);
  if ( bm->nb < BUFR_MAX_BITMAP_PRESENT_DATA )
    {
      bm->bitmap_to[bm->nb] = index_to;
      bm->bitmaped_by[bm->nb] = index_by;
      ( bm->nb )++;
      return 0;
    }
  return 1;
}
References bufrdeco_bitmap::bitmap_to, bufrdeco_bitmap::bitmaped_by, BUFR_MAX_BITMAP_PRESENT_DATA, and bufrdeco_bitmap::nb.
Referenced by bufrdeco_decode_replicated_subsequence(), and bufrdeco_decode_replicated_subsequence_compressed().
get_bitmaped_info()
int get_bitmaped_info (struct bufrdeco_bitmap_related_vars * brv, uint32_t target, struct bufrdeco * b)
Get bitmap info searching into bitmaps.
Parameters
brv pointer to struct bufrdeco_bitmap_related_vars where to set the results
target The key to find in array of bitmaps
b pointer to the current struct bufrdeco
Returns
If found the target return 0, othewise return 1
Definition at line 484 of file bufrdeco_utils.c.
{
  size_t i, j, k;
  uint32_t delta;
  struct bufrdeco_bitmap *bm;
  //bufrdeco_assert (b != NULL && brv != NULL);
  brv->target = target;
  for ( i = 0; i < b->bitmap.nba ; i++ )
    {
      bm = b->bitmap.bmap[i];
      for ( j = 0; j < bm->nb ; j++ )
        {
          if ( bm->bitmap_to[j] == target )
            {
              brv->nba = i;
              brv->nb = j;
              brv->bitmaped_by = bm->bitmaped_by[j];
              delta = bm->bitmaped_by[j] - bm->bitmaped_by[0];
              // quality data
              if (bm->nq)
              {
                for (k = 0; k < bm->nq; k++)
                {
                   brv->qualified_by[k] = bm->quality[k] + delta;
                }
              }
              // substituded
              if (bm->subs)
                  brv->substituted = bm->subs + delta;
              if (bm->retain )
                  brv->retained = bm->retain + delta;
              if (bm->ns1)
              {
                for (k = 0; k < bm->ns1; k++)
                {
                   brv->stat1[k] = bm->stat1[k] + delta;
                   brv->stat1_desc[k] = bm->stat1[k];
                }
              }
              if (bm->nds)
              {
                for (k = 0; k < bm->nds; k++)
                {
                   brv->dstat[k] = bm->dstat[k] + delta;
                   brv->stat1_desc[k] = bm->dstat[k];
                }
              }
              return 0;
            }
          else if ( b->bitmap.bmap[i]->bitmap_to[j] > target )
            break;
        }
    }
    return 1;
}
References bufrdeco::bitmap, bufrdeco_bitmap::bitmap_to, bufrdeco_bitmap::bitmaped_by, bufrdeco_bitmap_related_vars::bitmaped_by, bufrdeco_bitmap_array::bmap, bufrdeco_bitmap::dstat, bufrdeco_bitmap_related_vars::dstat, bufrdeco_bitmap::nb, bufrdeco_bitmap_related_vars::nb, bufrdeco_bitmap_array::nba, bufrdeco_bitmap_related_vars::nba, bufrdeco_bitmap::nds, bufrdeco_bitmap::nq, bufrdeco_bitmap::ns1, bufrdeco_bitmap_related_vars::qualified_by, bufrdeco_bitmap::quality, bufrdeco_bitmap::retain, bufrdeco_bitmap_related_vars::retained, bufrdeco_bitmap::stat1, bufrdeco_bitmap_related_vars::stat1, bufrdeco_bitmap_related_vars::stat1_desc, bufrdeco_bitmap::subs, bufrdeco_bitmap_related_vars::substituted, and bufrdeco_bitmap_related_vars::target.
get_bits_as_char_array()
buf_t get_bits_as_char_array (char * target, uint8_t * has_data, uint8_t * source, buf_t * bit0_offset, buf_t bit_length)
Definition at line 86 of file bufrdeco_utils.c.
{
  buf_t i, j, k;
  buf_t nc;
  uint8_t *c;
  //bufrdeco_assert (has_data != NULL && source != NULL && target != NULL && bit0_offset != NULL);
  if ( bit_length % 8 )
    return 0; // bit_length needs to be divisible by 8
  //printf("bit_length=%lu\n", bit_length);
  nc = bit_length / 8;
  i = ( *bit0_offset ) % 8;
  k = 8 - i;
  *has_data = 0; // marc if no missing data is present
  for ( j = 0; j < nc ; j++ )
    {
      c = source + ( *bit0_offset )  / 8;
      * ( target + j ) = ( *c & biti[i] );
      if ( i )
        {
          * ( target + j ) <<= i;
          * ( target + j ) |= ( ( * ( c + 1 ) & bitk[i - 1] ) >> k );
        }
      if ( * ( target + j ) != -1 )
        *has_data = 1;
      //printf("%c", * ( target + j ) );
      *bit0_offset += 8; // update bit0_offset
    }
  * ( target + nc ) = '\0';
  return bit_length;
}
References biti, and bitk.
Referenced by bufrdeco_get_atom_data_from_compressed_data_ref(), bufrdeco_parse_f2_compressed(), bufrdeco_parse_f2_descriptor(), bufrdeco_tableB_compressed(), and bufrdeco_tableB_val().
get_bits_as_char_array2()
buf_t get_bits_as_char_array2 (char * target, uint8_t * has_data, uint8_t * source, buf_t * bit0_offset, buf_t bit_length)
Definition at line 40 of file bufrdeco_utils.c.
{
  buf_t i, j;
  buf_t r, d, nc;
  uint8_t *c;
  //bufrdeco_assert (has_data != NULL && source != NULL && target != NULL && bit0_offset != NULL);
  if ( bit_length % 8 )
    return 0; // bit_length needs to be divisible by 8
  nc = bit_length / 8;
  *has_data = 0; // marc if no missing data is present
  for ( j = 0; j < nc ; j++ )
    {
      r = 8;
      d = 0;
      * ( target + j ) = 0;
      do
        {
          c = source + ( *bit0_offset + d ) / 8;
          i = ( *bit0_offset + d ) % 8;
          if ( *c & bitf[i] )
            * ( target + j ) += ( 1U << ( r - 1 ) );
          else
            *has_data = 1;
          d += 1;
          r -= 1;
        }
      while ( r > 0 );
      *bit0_offset += 8; // update bit0_offset
    }
  * ( target + nc ) = '\0';
  return bit_length;
}
References bitf.
get_bits_as_uint32_t()
uint32_t get_bits_as_uint32_t (uint32_t * target, uint8_t * has_data, uint8_t * source, buf_t * bit0_offset, buf_t bit_length)
Definition at line 182 of file bufrdeco_utils.c.
{
  int i;
  uint8_t *c;
  uint64_t x;
  //bufrdeco_assert (has_data != NULL && source != NULL && target != NULL && bit0_offset != NULL);
  if ( bit_length > 32 || bit_length == 0 )
    return 0;
  if ( bit_length < 8 )
    return get_bits_as_uint32_t2 ( target, has_data, source, bit0_offset, bit_length );
  *target = 0;
  *has_data = 0; // marc if no missing data is present
  c = source + ( *bit0_offset ) / 8;
  i = ( *bit0_offset ) % 8;
  x = ( ( uint64_t ) ( *c & biti[i] ) << 32 ) + ( ( uint64_t ) ( * ( c + 1 ) ) << 24 ) + ( ( uint64_t ) ( * ( c + 2 ) ) << 16 ) +
      ( ( uint64_t ) ( * ( c + 3 ) ) << 8 ) + ( uint64_t ) ( * ( c + 4 ) ); // 40 - i bits
  x >>= ( 40 - i - bit_length );
  *target = ( uint32_t ) x;
  if ( ( 1UL << bit_length ) != ( x + 1UL ) )
    *has_data = 1;
  *bit0_offset += bit_length; // update bit0_offset
  return bit_length;
}
References biti, and get_bits_as_uint32_t2().
Referenced by bufrdeco_get_atom_data_from_compressed_data_ref(), bufrdeco_parse_f2_compressed(), bufrdeco_tableB_compressed(), and bufrdeco_tableB_val().
get_bits_as_uint32_t2()
size_t get_bits_as_uint32_t2 (uint32_t * target, uint8_t * has_data, uint8_t * source, buf_t * bit0_offset, buf_t bit_length)
Read bits from an array of uint8_t and set them as an uint32_t.
Parameters
target uint32_t pointer where to set the result
has_data Output flags to check whether is missing data. If 0 then data is missing, othewise has data
source array of uint8_t elements. Most significant bit of first element is the bit offset reference
bit0_offset Bit offset
bit_length Lenght (in bits) for the chunck to extract
Returns
If returns the amount of bits readed. 0 if problems. It also update bits_offset with the new bits.
This is a version which extract bit a bit. For more than about 8 bits should be used the algorithm in get_bits_as_uint32_t
Definition at line 135 of file bufrdeco_utils.c.
{
  buf_t i;
  buf_t r, d;
  uint8_t *c;
  //bufrdeco_assert (has_data != NULL && source != NULL && target != NULL && bit0_offset != NULL);
  if ( bit_length > 32 || bit_length == 0 )
    return 0;
  r = bit_length;
  d = 0;
  *target = 0;
  *has_data = 0;
  do
    {
      c = source + ( *bit0_offset + d ) / 8;
      i = ( *bit0_offset + d ) % 8;
      if ( *c & bitf[i] )
        *target += ( 1U << ( r - 1 ) );
      else
        *has_data = 1;
      d += 1;
      r -= 1;
    }
  while ( r > 0 );
  *bit0_offset += bit_length; // update bit0_offset
  return bit_length;
}
References bitf.
Referenced by get_bits_as_uint32_t().
get_formatted_value_from_escale()
char * get_formatted_value_from_escale (char * fmt, size_t dim, int32_t escale, double val)
gets a string with formatted value depending of scale
Parameters
fmt The output target string
dim Size of available space (bytes) to write the result
escale value scale in descriptor
val double to printf
Returns
the resulting fmt string This version use 17 width for number plus a final space
Definition at line 410 of file bufrdeco_utils.c.
{
  char aux[32];
  //bufrdeco_assert (fmt != NULL);
  if ( escale >= 0 )
    {
      sprintf ( aux, "%%17.%dlf " , escale );
      snprintf ( fmt, dim, aux, val );
    }
  else
    snprintf ( fmt, dim, "%17.0lf " , val );
  return fmt;
}
Referenced by bufrdeco_print_atom_data(), and bufrdeco_print_atom_data_html().
get_formatted_value_from_escale2()
char * get_formatted_value_from_escale2 (char * fmt, size_t dim, int32_t escale, double val)
gets a string with formatted value depending of scale
Parameters
fmt The output target string
dim Size of available space (bytes) to write the result
escale value scale in descriptor
val double to printf
Returns
the resulting fmt string
Differs from get_formatted_value_from_escale that no blanks are written
Definition at line 436 of file bufrdeco_utils.c.
{
  char aux[32];
  //bufrdeco_assert (fmt != NULL);
  if ( escale >= 0 )
    {
      sprintf ( aux, "%%.%dlf" , escale );
      snprintf ( fmt, dim, aux, val );
    }
  else
    snprintf ( fmt, dim, "%.0lf" , val );
  return fmt;
}
Referenced by bufrdeco_print_json_object_atom_data().
get_table_b_reference_from_uint32_t()
int get_table_b_reference_from_uint32_t (int32_t * target, uint8_t bits, uint32_t source)
Get an int32_t from bits according with bufr criteria to change the reference of a descritor. Most significant bit in source is sign.
Parameters
target int32_t as result
bits number of bits to consider
source uint32_T with the data to transform
Returns
If success return 0, 1 otherwise
Definition at line 221 of file bufrdeco_utils.c.
{
  uint32_t mask = 1;
  //bufrdeco_assert (target != NULL);
  if ( bits > 32 || bits == 0 )
    return 1;
  if ( bits > 1 )
    mask = ( ( uint32_t ) 1 << ( bits - 1 ) );
  if ( mask & source )
    {
      // case of negative number
      *target = - ( int32_t ) ( source - mask );
    }
  else
    *target = ( int32_t ) ( source );
  return 0;
}
Referenced by bufrdeco_tableB_compressed(), and bufrdeco_tableB_val().
is_a_delayed_descriptor()
int is_a_delayed_descriptor (struct bufr_descriptor * d)
check if a descriptor is a delayed descriptor
Parameters
d pointer to a struct bufr_descriptor to check
Returns
If is a delayed desccriptor return 1, 0 otherwise.
Definition at line 351 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (d != NULL);
  if ( ( d->f == 0 ) &&
       ( d->x == 31 ) &&
       ( d->y == 1 || d->y == 2 || d->y == 11 || d->y == 12 ) )
    return 1;
  else
    return 0;
}
References bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufrdeco_fprint_tree_recursive(), bufrdeco_print_json_tree_recursive(), and bufrdeco_tableB_compressed().
is_a_local_descriptor()
int is_a_local_descriptor (struct bufr_descriptor * d)
check if a descriptor is a local descriptor
Parameters
d pointer to a struct bufr_descriptor to check
Returns
If is a local desccriptor return 1, 0 otherwise.
Definition at line 388 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (d != NULL);
  if ( ( d->f == 0 ) &&
       ( d->x >= 48 ) &&
       ( d->x <= 63 ) )
    return 1;
  else
    return 0;
}
References bufr_descriptor::f, and bufr_descriptor::x.
Referenced by bufrdeco_get_atom_data_from_compressed_data_ref(), bufrdeco_tableB_compressed(), and bufrdeco_tableB_val().
is_a_short_delayed_descriptor()
int is_a_short_delayed_descriptor (struct bufr_descriptor * d)
check if a descriptor is a short delayed descriptor
Parameters
d pointer to a struct bufr_descriptor to check
Returns
If is a delayed descriptor return 1, 0 otherwise.
Definition at line 369 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (d != NULL);
  if ( ( d->f == 0 ) &&
       ( d->x == 31 ) &&
       ( d->y == 0 ) )
    return 1;
  else
    return 0;
}
References bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufrdeco_fprint_tree_recursive(), bufrdeco_print_json_tree_recursive(), and bufrdeco_tableB_compressed().
three_bytes_to_uint32()
uint32_t three_bytes_to_uint32 (const uint8_t * source)
returns the uint32_t value from an array of three bytes, most significant first
Parameters
source pointer to source uint8_t
Returns
the uint32_t resulting
Definition at line 265 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (source != NULL);
  return ( ( uint32_t ) source[2] + ( uint32_t ) source[1] * 256 + ( uint32_t ) source[0] * 65536 );
}
Referenced by bufrdeco_read_buffer().
two_bytes_to_descriptor()
int two_bytes_to_descriptor (struct bufr_descriptor * d, const uint8_t * source)
set a struct bufr_descriptor from two consecutive bytes in bufr file
Parameters
source pointer to first byte (most significant)
d pointer to the resulting descriptor
Returns
0 if all is OK. 1 otherwise
Definition at line 297 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (source != NULL && d != NULL);
  d->y = source[1];
  d->x = source[0] & 0x3f;
  d->f = ( source[0] >> 6 ) & 0x03;
  sprintf ( d->c, "%u%02u%03u", d->f, d->x, d->y );
  return 0;
}
References bufr_descriptor::c, bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufrdeco_read_buffer().
two_bytes_to_uint32()
uint32_t two_bytes_to_uint32 (const uint8_t * source)
returns the uint32_t value from an array of two bytes, most significant first
Parameters
source pointer to source uint8_t
Returns
the uint32_t resulting
Definition at line 250 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (source != NULL);
  return ( ( uint32_t ) source[1] + ( uint32_t ) source[0] * 256 );
}
Referenced by bufrdeco_read_buffer().
uint32_t_to_descriptor()
int uint32_t_to_descriptor (struct bufr_descriptor * d, uint32_t id)
parse an integer with a descriptor fom bufr ECWMF libary
Parameters
d pointer to a struct bufr_descriptor where to set the result on output
id integer with the descriptor from ewcwf
Returns
the resulting uint32_t
Definition at line 278 of file bufrdeco_utils.c.
{
  //bufrdeco_assert (d != NULL);
  d->f = id / 100000;
  d->x = ( id % 100000 ) / 1000;
  d->y = id % 1000;
  sprintf ( d->c, "%06u", id );
  return 0;
}
References bufr_descriptor::c, bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufr_find_tableB_index(), bufr_find_tableC_csv_index(), bufr_read_tableB(), bufr_read_tableC(), bufr_read_tableD(), bufrdeco_tableD_get_descriptors_array(), and main().
Variable Documentation
bitf
uint8_t bitf[8] = {0x80,0x40,0x20,0x10,0x08,0x04,0x02,0x01}
Mask a single bit of a byte
Definition at line 26 of file bufrdeco_utils.c.
Referenced by get_bits_as_char_array2(), and get_bits_as_uint32_t2().
biti
uint8_t biti[8] = {0xFF,0x7f,0x3f,0x1F,0x0F,0x07,0x03,0x01}
Mask remaining bits in a byte (less significant)
Definition at line 27 of file bufrdeco_utils.c.
Referenced by get_bits_as_char_array(), and get_bits_as_uint32_t().
bitk
uint8_t bitk[8] = {0x80,0xc0,0xe0,0xf0,0xf8,0xfc,0xfe,0xff}
Mask first bits in a byte (most significant)
Definition at line 28 of file bufrdeco_utils.c.
Referenced by get_bits_as_char_array().