bufr2synop: src/libraries/bufr2tac_print_climat.c File Reference
bufr2tac_print_climat.c File Reference
file with the code to print the results for climat reports
#include "bufr2tac.h"
Macros
#define check_len(ori, inc) (c - *ori + inc < (int)lmax)
cheks if there still memory enough to add inc chars
Functions
char * print_climat_sec0 (char **sec0, size_t lmax, struct climat_chunks *cl)
Prints the climat section 0 (header)
char * print_climat_sec1 (char **sec1, size_t lmax, struct climat_chunks *cl)
Prints the climat section 1.
char * print_climat_sec2 (char **sec2, size_t lmax, struct climat_chunks *cl)
Prints the climat section 2.
char * print_climat_sec3 (char **sec3, size_t lmax, struct climat_chunks *cl)
Prints the climat section 3.
char * print_climat_sec4 (char **sec4, size_t lmax, struct climat_chunks *cl)
Prints the climat section 4.
int print_climat (char *report, size_t lmax, struct climat_chunks *cl)
prints a climat into a string
Detailed Description
file with the code to print the results for climat reports
Definition in file bufr2tac_print_climat.c.
Macro Definition Documentation
#define check_len (ori, inc) (c - *ori + inc < (int)lmax)
cheks if there still memory enough to add inc chars
Definition at line 30 of file bufr2tac_print_climat.c.
Referenced by print_climat_sec0(), print_climat_sec1(), print_climat_sec2(), print_climat_sec3(), and print_climat_sec4().
Function Documentation
int print_climat (char * report, size_t lmax, struct climat_chunks * cl)
prints a climat into a string
Parameters
report target string
lmax max size of string
cl pointer to a struct climat_chunks with the result of parse tasks
returns 0 if all went right
Definition at line 775 of file bufr2tac_print_climat.c.
References CLIMAT_SEC1, CLIMAT_SEC2, CLIMAT_SEC3, CLIMAT_SEC4, climat_chunks::e, climat_chunks::mask, report_date_ext::MM, print_climat_sec0(), print_climat_sec1(), print_climat_sec2(), print_climat_sec3(), print_climat_sec4(), and report_date_ext::YYYY.
Referenced by parse_subset_sequence().
 {
   char *c;
   c = report;
   // Needs time extension
   if ( cl->e.YYYY[0] == 0 || cl->e.MM[0] == 0)
     {
       return 1;
     }
   print_climat_sec0 ( &c, lmax, cl );
   if ( cl->mask & ( CLIMAT_SEC1 | CLIMAT_SEC2 | CLIMAT_SEC3 | CLIMAT_SEC4 ) )
     {
       print_climat_sec1 ( &c, lmax - strlen ( report ), cl );
       print_climat_sec2 ( &c, lmax - strlen ( report ), cl );
       print_climat_sec3 ( &c, lmax - strlen ( report ), cl );
       print_climat_sec4 ( &c, lmax - strlen ( report ), cl );
     }
   else
     {
       c += sprintf ( c, " NIL" );
     }
   c += sprintf ( c, "=" );
   return 0;
 }
char* print_climat_sec0 (char ** sec0, size_t lmax, struct climat_chunks * cl)
Prints the climat section 0 (header)
Parameters
sec0 the pointer where to print section
lmax max length permited
cl pointer to s atruct climat_chunks where the parse results are set
Definition at line 40 of file bufr2tac_print_climat.c.
References check_len, report_date_ext::DD, climat_chunks::e, report_date_ext::HH, climat_sec0::II, climat_sec0::iii, climat_sec0::JJJ, report_date_ext::MM, report_date_ext::mm, climat_sec0::MM, climat_chunks::s0, and report_date_ext::YYYY.
Referenced by print_climat().
 {
   char *c = *sec0;
   if ( check_len ( sec0,12 ) )
     {
       c += sprintf ( c, "%s%s%s%s%s", cl->e.YYYY, cl->e.MM, cl->e.DD, cl->e.HH, cl->e.mm );
     }
   // Print type
   if ( check_len ( sec0,6 ) )
     {
       c += sprintf ( c, " CLIMAT" );
     }
   // print MMJJJ
   if ( check_len ( sec0,8 ) )
     {
       c += sprintf ( c, " %s%s", cl->s0.MM, cl->s0.JJJ );
     }
   // print IIiii
   if ( check_len ( sec0,6 ) && cl->s0.II[0] )
     {
       c += sprintf ( c, " %s%s", cl->s0.II, cl->s0.iii );
     }
   *sec0 = c;
   return *sec0;
 }
char* print_climat_sec1 (char ** sec1, size_t lmax, struct climat_chunks * cl)
Prints the climat section 1.
Parameters
sec1 the pointer where to print section
lmax max length permited
cl pointer to s atruct climat_chunks where the parse results are set
Definition at line 78 of file bufr2tac_print_climat.c.
References check_len, climat_sec1::eee, climat_chunks::mask, climat_sec1::meme, climat_sec1::mpmp, climat_sec1::mrmr, climat_sec1::msms, climat_sec1::mtmt, climat_sec1::mtn, climat_sec1::mtx, climat_sec1::nrnr, climat_sec1::PoPoPoPo, climat_sec1::PPPP, climat_sec1::pspsps, climat_sec1::R1R1R1R1, climat_sec1::Rd, climat_sec1::s, climat_chunks::s1, climat_sec1::S1S1S1, climat_sec1::sn, climat_sec1::ststst, climat_sec1::sx, SYNOP_SEC1, climat_sec1::TnTnTn, climat_sec1::TTT, and climat_sec1::TxTxTx.
Referenced by print_climat().
 {
   char *c = *sec1;
   if ( cl->mask & SYNOP_SEC1 )
     {
       if ( check_len ( sec1,4 ) )
         {
           c += sprintf ( c, " 111" );
         }
       if ( check_len ( sec1,6 ) )
         {
           if ( cl->s1.PoPoPoPo[0] )
             {
               c += sprintf ( c, " 1%s", cl->s1.PoPoPoPo );
             }
         }
       if ( check_len ( sec1,6 ) )
         {
           if ( cl->s1.PPPP[0] )
             {
               c += sprintf ( c, " 2%s", cl->s1.PPPP );
             }
         }
       if ( check_len ( sec1,9 ) )
         {
           if ( cl->s1.TTT[0] || cl->s1.ststst[0] )
             {
               if ( cl->s1.TTT[0] == 0 )
                 {
                   strcpy ( cl->s1.s, "/" );
                   strcpy ( cl->s1.TTT, "///" );
                 }
               if ( cl->s1.ststst[0] == 0 )
                 {
                   strcpy ( cl->s1.ststst, "///" );
                 }
               c += sprintf ( c, " 3%s%s%s", cl->s1.s, cl->s1.TTT, cl->s1.ststst );
             }
         }
       if ( check_len ( sec1,10 ) )
         {
           if ( cl->s1.TxTxTx[0] || cl->s1.TnTnTn[0] )
             {
               if ( cl->s1.TxTxTx[0] == 0 )
                 {
                   strcpy ( cl->s1.sx, "/" );
                   strcpy ( cl->s1.TxTxTx, "///" );
                 }
               if ( cl->s1.TnTnTn[0] == 0 )
                 {
                   strcpy ( cl->s1.sn, "/" );
                   strcpy ( cl->s1.TnTnTn, "///" );
                 }
               c += sprintf ( c, " 4%s%s%s%s", cl->s1.sx, cl->s1.TxTxTx, cl->s1.sn, cl->s1.TnTnTn );
             }
         }
       if ( check_len ( sec1,5 ) )
         {
           if ( cl->s1.eee[0] )
             {
               c += sprintf ( c, " 5%s", cl->s1.eee );
             }
         }
       if ( check_len ( sec1,9 ) )
         {
           if ( cl->s1.R1R1R1R1[0] ||  cl->s1.Rd[0] ||  cl->s1.nrnr[0] )
             {
               if ( cl->s1.R1R1R1R1[0] == 0 )
                 {
                   strcpy ( cl->s1.R1R1R1R1, "////" );
                 }
               if ( cl->s1.Rd[0] == 0 )
                 {
                   strcpy ( cl->s1.Rd, "/" );
                 }
               if ( cl->s1.nrnr[0] == 0 )
                 {
                   strcpy ( cl->s1.nrnr, "//" );
                 }
               c += sprintf ( c, " 6%s%s%s", cl->s1.R1R1R1R1, cl->s1.Rd, cl->s1.nrnr );
             }
         }
       if ( check_len ( sec1,8 ) )
         {
           if ( cl->s1.S1S1S1[0] ||  cl->s1.pspsps[0] )
             {
               if ( cl->s1.S1S1S1[0] == 0 )
                 {
                   strcpy ( cl->s1.S1S1S1, "///" );
                 }
               if ( cl->s1.pspsps[0] == 0 )
                 {
                   strcpy ( cl->s1.pspsps, "///" );
                 }
               c += sprintf ( c, " 7%s%s", cl->s1.S1S1S1, cl->s1.pspsps );
             }
         }
       if ( check_len ( sec1,8 ) )
         {
           if ( cl->s1.mpmp[0] || cl->s1.mtmt[0] ||  cl->s1.mtx[0] ||  cl->s1.mtn[0] )
             {
               if ( cl->s1.mpmp[0] == 0 )
                 {
                   strcpy ( cl->s1.mpmp, "//" );
                 }
               if ( cl->s1.mtmt[0] == 0 )
                 {
                   strcpy ( cl->s1.mtmt, "//" );
                 }
               if ( cl->s1.mtx[0] == 0 )
                 {
                   strcpy ( cl->s1.mtx, "/" );
                 }
               if ( cl->s1.mtn[0] == 0 )
                 {
                   strcpy ( cl->s1.mtn, "/" );
                 }
               c += sprintf ( c, " 8%s%s%s%s", cl->s1.mpmp, cl->s1.mtmt, cl->s1.mtx, cl->s1.mtn );
             }
         }
       if ( check_len ( sec1,8 ) )
         {
           if ( cl->s1.meme[0] || cl->s1.mrmr[0] || cl->s1.msms[0] )
             {
               if ( cl->s1.meme[0] == 0 )
                 {
                   strcpy ( cl->s1.meme, "//" );
                 }
               if ( cl->s1.mrmr[0] == 0 )
                 {
                   strcpy ( cl->s1.mrmr, "//" );
                 }
               if ( cl->s1.msms[0] == 0 )
                 {
                   strcpy ( cl->s1.msms, "//" );
                 }
               c += sprintf ( c, " 9%s%s%s", cl->s1.meme, cl->s1.mrmr, cl->s1.msms );
             }
         }
     }
   *sec1 = c;
   return *sec1;
 }
char* print_climat_sec2 (char ** sec2, size_t lmax, struct climat_chunks * cl)
Prints the climat section 2.
Parameters
sec2 the pointer where to print section
lmax max length permited
cl pointer to s atruct climat_chunks where the parse results are set
Definition at line 241 of file bufr2tac_print_climat.c.
References check_len, climat_sec2::eee, climat_chunks::mask, climat_sec2::nrnr, climat_sec2::PoPoPoPo, climat_sec2::PPPP, climat_sec2::R1R1R1R1, climat_sec2::s, climat_sec2::S1S1S1, climat_chunks::s2, climat_sec2::sn, climat_sec2::ststst, climat_sec2::sx, SYNOP_SEC2, climat_sec2::TnTnTn, climat_sec2::TTT, climat_sec2::TxTxTx, climat_sec2::YbYb, climat_sec2::YcYc, climat_sec2::yeye, climat_sec2::ypyp, climat_sec2::yryr, climat_sec2::ysys, climat_sec2::ytxytx, and climat_sec2::ytyt.
Referenced by print_climat().
 {
   char *c = *sec2, *c0 = *sec2;
   if ( cl->mask & SYNOP_SEC2 )
     {
       //c += sprintf ( c, "\r\n      222" );
       c += sprintf ( c, " 222" );
       // init point to write info.
       // in case we finally write nothing in this section
       c0 = c;
       if ( check_len ( sec2,6 ) && ( cl->s2.YbYb[0] || cl->s2.YcYc[0] ) )
         {
           if ( cl->s2.YbYb[0] == 0 )
             {
               strcpy ( cl->s2.YbYb, "//" );
             }
           if ( cl->s2.YcYc[0] == 0 )
             {
               strcpy ( cl->s2.YcYc, "//" );
             }
           c += sprintf ( c, " 0%s%s", cl->s2.YbYb, cl->s2.YcYc );
         }
       if ( check_len ( sec2,6 ) && cl->s2.PoPoPoPo[0] )
         {
           c += sprintf ( c, " 1%s", cl->s2.PoPoPoPo );
         }
       if ( check_len ( sec2,6 ) && cl->s2.PPPP[0] )
         {
           c += sprintf ( c, " 2%s", cl->s2.PPPP );
         }
       if ( check_len ( sec2,9 ) && ( cl->s2.s[0] || cl->s2.TTT[0] || cl->s2.ststst[0] ) )
         {
           if ( cl->s2.s[0] == 0 )
             {
               strcpy ( cl->s2.s, "/" );
             }
           if ( cl->s2.TTT[0] == 0 )
             {
               strcpy ( cl->s2.TTT, "///" );
             }
           if ( cl->s2.ststst[0] == 0 )
             {
               strcpy ( cl->s2.ststst, "///" );
             }
           c += sprintf ( c, " 3%s%s%s", cl->s2.s, cl->s2.TTT, cl->s2.ststst );
         }
       if ( check_len ( sec2,10 ) && ( cl->s2.sx[0] || cl->s2.TxTxTx[0] || cl->s2.sn[0] || cl->s2.TnTnTn[0] ) )
         {
           if ( cl->s2.sx[0] == 0 )
             {
               strcpy ( cl->s2.sx, "/" );
             }
           if ( cl->s2.TxTxTx[0] == 0 )
             {
               strcpy ( cl->s2.TxTxTx, "///" );
             }
           if ( cl->s2.sn[0] == 0 )
             {
               strcpy ( cl->s2.sn, "/" );
             }
           if ( cl->s2.TnTnTn[0] == 0 )
             {
               strcpy ( cl->s2.TnTnTn, "///" );
             }
           c += sprintf ( c, " 4%s%s%s%s", cl->s2.sx, cl->s2.TxTxTx, cl->s2.sn, cl->s2.TnTnTn );
         }
       if ( check_len ( sec2,5 ) && cl->s2.eee[0] )
         {
           c += sprintf ( c, " 5%s", cl->s2.eee );
         }
       if ( check_len ( sec2,8 ) && ( cl->s2.R1R1R1R1[0] || cl->s2.nrnr[0] ) )
         {
           if ( cl->s2.R1R1R1R1[0] == 0 )
             {
               strcpy ( cl->s2.R1R1R1R1, "////" );
             }
           if ( cl->s2.nrnr[0] == 0 )
             {
               strcpy ( cl->s2.nrnr, "//" );
             }
           c += sprintf ( c, " 6%s%s", cl->s2.R1R1R1R1, cl->s2.nrnr );
         }
       if ( check_len ( sec2,5 ) && cl->s2.S1S1S1[0] )
         {
           c += sprintf ( c, " 7%s", cl->s2.S1S1S1 );
         }
       if ( check_len ( sec2,8 ) && ( cl->s2.ypyp[0] || cl->s2.ytyt[0] || cl->s2.ytxytx[0] ) )
         {
           if ( cl->s2.ypyp[0] == 0 )
             {
               strcpy ( cl->s2.ypyp, "//" );
             }
           if ( cl->s2.ytyt[0] == 0 )
             {
               strcpy ( cl->s2.ytyt, "//" );
             }
           if ( cl->s2.ytxytx[0] == 0 )
             {
               strcpy ( cl->s2.ytxytx, "//" );
             }
           c += sprintf ( c, " 8%s%s%s", cl->s2.ypyp, cl->s2.ytyt, cl->s2.ytxytx );
         }
       if ( check_len ( sec2,8 ) && ( cl->s2.yeye[0] || cl->s2.yryr[0] || cl->s2.ysys[0] ) )
         {
           if ( cl->s2.yeye[0] == 0 )
             {
               strcpy ( cl->s2.yeye, "//" );
             }
           if ( cl->s2.yryr[0] == 0 )
             {
               strcpy ( cl->s2.yryr, "//" );
             }
           if ( cl->s2.ysys[0] == 0 )
             {
               strcpy ( cl->s2.ysys, "//" );
             }
           c += sprintf ( c, " 9%s%s%s", cl->s2.yeye, cl->s2.yryr, cl->s2.ysys );
         }
     }
   if ( c != c0 )
     {
       *sec2 = c;
     }
   return *sec2;
 }
char* print_climat_sec3 (char ** sec3, size_t lmax, struct climat_chunks * cl)
Prints the climat section 3.
Parameters
sec3 the pointer where to print section
lmax max length permited
cl pointer to s atruct climat_chunks where the parse results are set
Definition at line 394 of file bufr2tac_print_climat.c.
References check_len, climat_sec3::f10, climat_sec3::f20, climat_sec3::f30, climat_chunks::mask, climat_sec3::R01, climat_sec3::R05, climat_sec3::R10, climat_sec3::R100, climat_sec3::R150, climat_sec3::R50, climat_sec3::s00, climat_sec3::s01, climat_sec3::s10, climat_chunks::s3, climat_sec3::s50, SYNOP_SEC3, climat_sec3::T25, climat_sec3::T30, climat_sec3::T35, climat_sec3::T40, climat_sec3::Tn0, climat_sec3::Tx0, climat_sec3::V1, climat_sec3::V2, and climat_sec3::V3.
Referenced by print_climat().
 {
   char *c = *sec3, *c0 = *sec3;
   if ( cl->mask & SYNOP_SEC3 )
     {
       //c += sprintf ( c, "\r\n      333" );
       c += sprintf ( c, " 333" );
       // init point to write info.
       // in case we finally write nothing in this section
       c0 = c;
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.T25[0] && strcmp ( cl->s3.T25, "00" ) ) ||
              ( cl->s3.T30[0] && strcmp ( cl->s3.T30, "00" ) )
            )
          )
         {
           if ( cl->s3.T25[0] == 0 )
             {
               strcpy ( cl->s3.T25,"//" );
             }
           if ( cl->s3.T30[0] == 0 )
             {
               strcpy ( cl->s3.T30,"//" );
             }
           c += sprintf ( c, " 0%s%s", cl->s3.T25, cl->s3.T30 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.T35[0] && strcmp ( cl->s3.T35, "00" ) ) ||
              ( cl->s3.T40[0] && strcmp ( cl->s3.T40, "00" ) )
            )
          )
         {
           if ( cl->s3.T35[0] == 0 )
             {
               strcpy ( cl->s3.T35,"//" );
             }
           if ( cl->s3.T40[0] == 0 )
             {
               strcpy ( cl->s3.T40,"//" );
             }
           c += sprintf ( c, " 1%s%s", cl->s3.T35, cl->s3.T40 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.Tn0[0] && strcmp ( cl->s3.Tn0, "00" ) ) ||
              ( cl->s3.Tx0[0] && strcmp ( cl->s3.Tx0, "00" ) )
            )
          )
         {
           if ( cl->s3.Tn0[0] == 0 )
             {
               strcpy ( cl->s3.Tn0,"//" );
             }
           if ( cl->s3.Tx0[0] == 0 )
             {
               strcpy ( cl->s3.Tx0,"//" );
             }
           c += sprintf ( c, " 2%s%s", cl->s3.Tn0, cl->s3.Tx0 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.R01[0] && strcmp ( cl->s3.R01, "00" ) ) ||
              ( cl->s3.R05[0] && strcmp ( cl->s3.R05, "00" ) )
            )
          )
         {
           if ( cl->s3.R01[0] == 0 )
             {
               strcpy ( cl->s3.R01,"//" );
             }
           if ( cl->s3.R05[0] == 0 )
             {
               strcpy ( cl->s3.R05,"//" );
             }
           c += sprintf ( c, " 3%s%s", cl->s3.R01, cl->s3.R05 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.R10[0] && strcmp ( cl->s3.R10, "00" ) ) ||
              ( cl->s3.R50[0] && strcmp ( cl->s3.R50, "00" ) )
            )
          )
         {
           if ( cl->s3.R10[0] == 0 )
             {
               strcpy ( cl->s3.R10,"//" );
             }
           if ( cl->s3.R50[0] == 0 )
             {
               strcpy ( cl->s3.R50,"//" );
             }
           c += sprintf ( c, " 4%s%s", cl->s3.R10, cl->s3.R50 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.R100[0] && strcmp ( cl->s3.R100, "00" ) ) ||
              ( cl->s3.R150[0] && strcmp ( cl->s3.R150, "00" ) )
            )
          )
         {
           if ( cl->s3.R100[0] == 0 )
             {
               strcpy ( cl->s3.R100,"//" );
             }
           if ( cl->s3.R150[0] == 0 )
             {
               strcpy ( cl->s3.R150,"//" );
             }
           c += sprintf ( c, " 5%s%s", cl->s3.R100, cl->s3.R150 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.s00[0] && strcmp ( cl->s3.s00, "00" ) ) ||
              ( cl->s3.s01[0] && strcmp ( cl->s3.s01, "00" ) )
            )
          )
         {
           if ( cl->s3.s00[0] == 0 )
             {
               strcpy ( cl->s3.s00,"//" );
             }
           if ( cl->s3.s01[0] == 0 )
             {
               strcpy ( cl->s3.s01,"//" );
             }
           c += sprintf ( c, " 6%s%s", cl->s3.s00, cl->s3.s01 );
         }
       if ( check_len ( sec3,8 ) &&
            (
              ( cl->s3.s10[0] && strcmp ( cl->s3.s10, "00" ) ) ||
              ( cl->s3.s50[0] && strcmp ( cl->s3.s50, "00" ) )
            )
          )
         {
           if ( cl->s3.s10[0] == 0 )
             {
               strcpy ( cl->s3.s10,"//" );
             }
           if ( cl->s3.s50[0] == 0 )
             {
               strcpy ( cl->s3.s50,"//" );
             }
           c += sprintf ( c, " 7%s%s", cl->s3.s10, cl->s3.s50 );
         }
       if ( check_len ( sec3,10 ) &&
            (
              ( cl->s3.f10[0] && strcmp ( cl->s3.f10, "00" ) ) ||
              ( cl->s3.f20[0] && strcmp ( cl->s3.f20, "00" ) ) ||
              ( cl->s3.f30[0] && strcmp ( cl->s3.f30, "00" ) )
            )
          )
         {
           if ( cl->s3.f10[0] == 0 )
             {
               strcpy ( cl->s3.f10,"//" );
             }
           if ( cl->s3.f20[0] == 0 )
             {
               strcpy ( cl->s3.f20,"//" );
             }
           if ( cl->s3.f30[0] == 0 )
             {
               strcpy ( cl->s3.f30,"//" );
             }
           c += sprintf ( c, " 8%s%s%s", cl->s3.f10, cl->s3.f20, cl->s3.f30 );
         }
       if ( check_len ( sec3,10 ) &&
            (
              ( cl->s3.V1[0] && strcmp ( cl->s3.V1, "00" ) ) ||
              ( cl->s3.V2[0] && strcmp ( cl->s3.V2, "00" ) ) ||
              ( cl->s3.V3[0] && strcmp ( cl->s3.V3, "00" ) )
            )
          )
         {
           if ( cl->s3.V1[0] == 0 )
             {
               strcpy ( cl->s3.V1,"//" );
             }
           if ( cl->s3.V2[0] == 0 )
             {
               strcpy ( cl->s3.V2,"//" );
             }
           if ( cl->s3.V3[0] == 0 )
             {
               strcpy ( cl->s3.V3,"//" );
             }
           c += sprintf ( c, " 9%s%s%s", cl->s3.V1, cl->s3.V2, cl->s3.V3 );
         }
     }
   if ( c != c0 )
     {
       *sec3 = c;
     }
   return *sec3;
 }
char* print_climat_sec4 (char ** sec4, size_t lmax, struct climat_chunks * cl)
Prints the climat section 4.
Parameters
sec4 the pointer where to print section
lmax max length permited
cl pointer to s atruct climat_chunks where the parse results are set
Definition at line 614 of file bufr2tac_print_climat.c.
References check_len, CLIMAT_SEC4, climat_sec4::Dgr, climat_sec4::Dts, climat_sec4::fxfxfx, climat_sec4::GnGn, climat_sec4::GxGx, climat_sec4::iw, climat_sec4::iy, climat_chunks::mask, climat_sec4::RxRxRxRx, climat_chunks::s4, climat_sec4::san, climat_sec4::sax, climat_sec4::sn, climat_sec4::sx, climat_sec4::Tan, climat_sec4::Tax, climat_sec4::Tnd, climat_sec4::Txd, climat_sec4::yan, climat_sec4::yax, climat_sec4::yfx, climat_sec4::yn, climat_sec4::yr, and climat_sec4::yx.
Referenced by print_climat().
 {
   char *c = *sec4, *c0 = *sec4;
   if ( cl->mask & CLIMAT_SEC4 )
     {
       //c += sprintf ( c, "\r\n      444" );
       c += sprintf ( c, " 444" );
       // init point to write info.
       // in case we finally write nothing in this section
       c0 = c;
       if ( check_len ( sec4,8 ) && ( cl->s4.sx[0] || cl->s4.Txd[0] || cl->s4.yx[0] ) )
         {
           if ( cl->s4.sx[0] == 0 )
             {
               strcpy ( cl->s4.sx, "/" );
             }
           if ( cl->s4.Txd[0] == 0 )
             {
               strcpy ( cl->s4.Txd, "///" );
             }
           if ( cl->s4.yx[0] == 0 )
             {
               strcpy ( cl->s4.yx, "//" );
             }
           c += sprintf ( c, " 0%s%s%s", cl->s4.sx, cl->s4.Txd, cl->s4.yx );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.sn[0] || cl->s4.Tnd[0] || cl->s4.yn[0] ) )
         {
           if ( cl->s4.sn[0] == 0 )
             {
               strcpy ( cl->s4.sn, "/" );
             }
           if ( cl->s4.Tnd[0] == 0 )
             {
               strcpy ( cl->s4.Tnd, "///" );
             }
           if ( cl->s4.yn[0] == 0 )
             {
               strcpy ( cl->s4.yn, "//" );
             }
           c += sprintf ( c, " 1%s%s%s", cl->s4.sn, cl->s4.Tnd, cl->s4.yn );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.sax[0] || cl->s4.Tax[0] || cl->s4.yax[0] ) )
         {
           if ( cl->s4.sax[0] == 0 )
             {
               strcpy ( cl->s4.sax, "/" );
             }
           if ( cl->s4.Tax[0] == 0 )
             {
               strcpy ( cl->s4.Tax, "///" );
             }
           if ( cl->s4.yax[0] == 0 )
             {
               strcpy ( cl->s4.yax, "//" );
             }
           c += sprintf ( c, " 2%s%s%s", cl->s4.sax, cl->s4.Tax, cl->s4.yax );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.san[0] || cl->s4.Tan[0] || cl->s4.yan[0] ) )
         {
           if ( cl->s4.san[0] == 0 )
             {
               strcpy ( cl->s4.san, "/" );
             }
           if ( cl->s4.Tan[0] == 0 )
             {
               strcpy ( cl->s4.Tan, "///" );
             }
           if ( cl->s4.yan[0] == 0 )
             {
               strcpy ( cl->s4.yan, "//" );
             }
           c += sprintf ( c, " 3%s%s%s", cl->s4.san, cl->s4.Tan, cl->s4.yan );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.RxRxRxRx[0] || cl->s4.yr[0] ) )
         {
           if ( cl->s4.RxRxRxRx[0] == 0 )
             {
               strcpy ( cl->s4.RxRxRxRx, "////" );
             }
           if ( cl->s4.yx[0] == 0 )
             {
               strcpy ( cl->s4.Tan, "//" );
             }
           c += sprintf ( c, " 4%s%s", cl->s4.RxRxRxRx, cl->s4.yr );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.fxfxfx[0] || cl->s4.yfx[0] ) )
         {
           if ( cl->s4.iw[0] == 0 )
             {
               strcpy ( cl->s4.iw, "/" );
             }
           if ( cl->s4.fxfxfx[0] == 0 )
             {
               strcpy ( cl->s4.fxfxfx, "///" );
             }
           if ( cl->s4.yfx[0] == 0 )
             {
               strcpy ( cl->s4.yfx, "//" );
             }
           c += sprintf ( c, " 5%s%s%s", cl->s4.iw, cl->s4.fxfxfx, cl->s4.yfx );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.Dts[0] || cl->s4.Dgr[0] ) )
         {
           if ( cl->s4.Dts[0] == 0 )
             {
               strcpy ( cl->s4.Dts,"//" );
             }
           if ( cl->s4.Dgr[0] == 0 )
             {
               strcpy ( cl->s4.Dgr,"//" );
             }
           c += sprintf ( c, " 6%s%s", cl->s4.Dts, cl->s4.Dgr );
         }
       if ( check_len ( sec4,8 ) && ( cl->s4.iy[0] || cl->s4.GxGx[0] || cl->s4.GnGn[0] ) )
         {
           if ( cl->s4.iw[0] == 0 )
             {
               strcpy ( cl->s4.iy, "/" );
             }
           if ( cl->s4.GxGx[0] == 0 )
             {
               strcpy ( cl->s4.GxGx, "///" );
             }
           if ( cl->s4.GnGn[0] == 0 )
             {
               strcpy ( cl->s4.GnGn, "//" );
             }
           c += sprintf ( c, " 7%s%s%s", cl->s4.iy, cl->s4.GxGx, cl->s4.GnGn );
         }
     }
   if ( c != c0 )
     {
       *sec4 = c;
     }
   return *sec4;
 }