bufr2synop: src/libraries/bufr2syn_mrproper.c File Reference
bufr2syn_mrproper.c File Reference
file with the code to clean and init structures
#include "bufr2syn.h"
Functions
void clean_syn_sec0 (struct synop_sec0 *s)
clean a synop_sec0 struct
void clean_syn_sec1 (struct synop_sec1 *s)
clean a synop_sec1 struct
void clean_syn_sec2 (struct synop_sec2 *s)
clean a synop_sec2 struct
void clean_syn_sec3 (struct synop_sec3 *s)
clean a synop_sec3 struct
void clean_syn_sec5 (struct synop_sec5 *s)
clean a synop_sec5 struct
void clean_report_date_ext (struct report_date_ext *s)
clean a synop_ext struct
void clean_synop_chunks (struct synop_chunks *syn)
cleans a synop_chunks struct
void clean_buoy_sec0 (struct buoy_sec0 *s)
clean a buoy_sec0 struct
void clean_buoy_sec1 (struct buoy_sec1 *s)
clean a buoy_sec1 struct
void clean_buoy_sec2 (struct buoy_sec2 *s)
clean a buoy_sec2 struct
void clean_buoy_sec3 (struct buoy_sec3 *s)
clean a buoy_sec3 struct
void clean_buoy_sec4 (struct buoy_sec4 *s)
clean a buoy_sec4 struct
void clean_buoy_chunks (struct buoy_chunks *b)
cleans a buoy_chunks struct
Detailed Description
file with the code to clean and init structures
Definition in file bufr2syn_mrproper.c.
Function Documentation
void clean_buoy_chunks (struct buoy_chunks * b)
cleans a buoy_chunks struct
Parameters
b pointer to the struct to clean
Definition at line 159 of file bufr2syn_mrproper.c.
References clean_buoy_sec0(), clean_buoy_sec1(), clean_buoy_sec2(), clean_buoy_sec3(), clean_buoy_sec4(), clean_report_date_ext(), buoy_chunks::e, buoy_chunks::error, buoy_chunks::mask, buoy_chunks::s0, buoy_chunks::s1, buoy_chunks::s2, buoy_chunks::s3, and buoy_chunks::s4.
Referenced by parse_subset_as_buoy().
 {
   b->mask = 0;
   clean_report_date_ext( &(b->e));
   clean_buoy_sec0( &(b->s0));
   clean_buoy_sec1( &(b->s1));
   clean_buoy_sec2( &(b->s2));
   clean_buoy_sec3( &(b->s3));
   clean_buoy_sec4( &(b->s4));
   b->error[0] = '\0';
 }
void clean_buoy_sec0 (struct buoy_sec0 * s)
clean a buoy_sec0 struct
Parameters
s pointer to the buoy_sec0 struct
Definition at line 113 of file bufr2syn_mrproper.c.
Referenced by clean_buoy_chunks().
 {
   memset(s, 0, sizeof(struct buoy_sec0));
 }
void clean_buoy_sec1 (struct buoy_sec1 * s)
clean a buoy_sec1 struct
Parameters
s pointer to the buoy_sec1 struct
Definition at line 122 of file bufr2syn_mrproper.c.
Referenced by clean_buoy_chunks().
 {
   memset(s, 0, sizeof(struct buoy_sec1));
 }
void clean_buoy_sec2 (struct buoy_sec2 * s)
clean a buoy_sec2 struct
Parameters
s pointer to the buoy_sec2 struct
Definition at line 131 of file bufr2syn_mrproper.c.
Referenced by clean_buoy_chunks().
 {
   memset(s, 0, sizeof(struct buoy_sec2));
 }
void clean_buoy_sec3 (struct buoy_sec3 * s)
clean a buoy_sec3 struct
Parameters
s pointer to the buoy_sec3 struct
Definition at line 140 of file bufr2syn_mrproper.c.
Referenced by clean_buoy_chunks().
 {
   memset(s, 0, sizeof(struct buoy_sec3));
 }
void clean_buoy_sec4 (struct buoy_sec4 * s)
clean a buoy_sec4 struct
Parameters
s pointer to the buoy_sec3 struct
Definition at line 149 of file bufr2syn_mrproper.c.
Referenced by clean_buoy_chunks().
 {
   memset(s, 0, sizeof(struct buoy_sec4));
 }
void clean_report_date_ext (struct report_date_ext * s)
clean a synop_ext struct
Parameters
s pointer to the synop_ext struct
Definition at line 76 of file bufr2syn_mrproper.c.
Referenced by clean_buoy_chunks(), and clean_synop_chunks().
 {
   memset(s, 0, sizeof(struct report_date_ext));
 }
void clean_syn_sec0 (struct synop_sec0 * s)
clean a synop_sec0 struct
Parameters
s pointer to the synop_sec0 struct
Definition at line 30 of file bufr2syn_mrproper.c.
Referenced by clean_synop_chunks().
 {
   memset(s, 0, sizeof(struct synop_sec0));
 }
void clean_syn_sec1 (struct synop_sec1 * s)
clean a synop_sec1 struct
Parameters
s pointer to the synop_sec1 struct
Definition at line 39 of file bufr2syn_mrproper.c.
Referenced by clean_synop_chunks().
 {
   memset(s, 0, sizeof(struct synop_sec1));
 }
void clean_syn_sec2 (struct synop_sec2 * s)
clean a synop_sec2 struct
Parameters
s pointer to the synop_sec2 struct
Definition at line 48 of file bufr2syn_mrproper.c.
Referenced by clean_synop_chunks().
 {
   memset(s, 0, sizeof(struct synop_sec2));
 }
void clean_syn_sec3 (struct synop_sec3 * s)
clean a synop_sec3 struct
Parameters
s pointer to the synop_sec3 struct
Definition at line 57 of file bufr2syn_mrproper.c.
Referenced by clean_synop_chunks().
 {
   memset(s, 0, sizeof(struct synop_sec3));
 }
void clean_syn_sec5 (struct synop_sec5 * s)
clean a synop_sec5 struct
Parameters
s pointer to the synop_sec5 struct
Definition at line 66 of file bufr2syn_mrproper.c.
Referenced by clean_synop_chunks().
 {
   memset(s, 0, sizeof(struct synop_sec5));
 }
void clean_synop_chunks (struct synop_chunks * syn)
cleans a synop_chunks struct
Parameters
syn pointer to the struct to clean
Definition at line 86 of file bufr2syn_mrproper.c.
References clean_report_date_ext(), clean_syn_sec0(), clean_syn_sec1(), clean_syn_sec2(), clean_syn_sec3(), clean_syn_sec5(), synop_sec1::dd, synop_chunks::e, synop_chunks::error, synop_sec1::ff, synop_sec1::h, synop_sec1::ir, synop_sec0::iw, synop_sec1::ix, synop_chunks::mask, synop_sec1::N, synop_chunks::s0, synop_chunks::s1, synop_chunks::s2, synop_chunks::s3, synop_chunks::s5, and synop_sec1::VV.
Referenced by parse_subset_as_synop().
 {
   syn->mask = 0;
   clean_report_date_ext( &(syn->e));
   clean_syn_sec0( &(syn->s0));
   clean_syn_sec1( &(syn->s1));
   clean_syn_sec2( &(syn->s2));
   clean_syn_sec3( &(syn->s3));
   clean_syn_sec5( &(syn->s5));
   // default
   strcpy(syn->s0.iw,"/");
   strcpy(syn->s1.ir,"/");
   strcpy(syn->s1.ix,"/");
   strcpy(syn->s1.h,"/");
   strcpy(syn->s1.VV,"//");
   strcpy(syn->s1.N,"/");
   strcpy(syn->s1.dd,"//");
   strcpy(syn->s1.ff,"//");
   syn->error[0] = '\0';
 }