bufr2synop: src/libraries/bufr2syn_x10.c File Reference
bufr2syn_x10.c File Reference
decodes the descriptors with X = 10
#include "bufr2syn.h"
Functions
char * pascal_to_ppp (char *target, double P)
Converts pascal values (variation) into a ppp string.
char * pascal_to_PPPP (char *target, double P)
Converts pascal values into a PPPP string.
int syn_parse_x10 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 10.
int buoy_parse_x10 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 10.
Detailed Description
decodes the descriptors with X = 10
Definition in file bufr2syn_x10.c.
Function Documentation
int buoy_parse_x10 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 108 of file bufr2syn_x10.c.
References buoy_sec1::a, bufr_subset_state::a, BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, buoy_chunks::mask, bufr_atom_data::mask, pascal_to_ppp(), pascal_to_PPPP(), buoy_sec1::PoPoPoPo, buoy_sec1::ppp, buoy_sec1::PPPP, buoy_chunks::s1, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 4: // 0 10 004
       pascal_to_PPPP ( aux, s->val );
       strcpy ( b->s1.PoPoPoPo, aux );
       b->mask |= BUOY_SEC1;
       break;
     case 51: // 0 10 051
       pascal_to_PPPP ( aux, s->val );
       strcpy ( b->s1.PPPP, aux );
       b->mask |= BUOY_SEC1;
       break;
     case 63: // 0 10 063
       sprintf ( b->s1.a, "%1d",s->ival );
       b->mask |= BUOY_SEC1;
       break;
     case 61: // 0 10 061
       pascal_to_ppp ( aux, s->val );
       sprintf ( b->s1.ppp, "%s", aux );
       b->mask |= BUOY_SEC1;
       break;
     default:
       break;
     }
   return 0;
 }
char* pascal_to_ppp (char * target, double P)
Converts pascal values (variation) into a ppp string.
Parameters
P the pressure variation in Pascal units
target string with the result
Definition at line 32 of file bufr2syn_x10.c.
Referenced by buoy_parse_x10(), and syn_parse_x10().
 {
   int ic;
   if ( P > 0 )
     ic = ( int ) ( P * 0.1 );
   else
     ic = ( int ) ( -P * 0.1 );
   sprintf ( target, "%03d", ic % 1000 );
   return target;
 }
char* pascal_to_PPPP (char * target, double P)
Converts pascal values into a PPPP string.
Parameters
P the pressure variation in Pascal units
target string with the result
Definition at line 50 of file bufr2syn_x10.c.
Referenced by buoy_parse_x10(), and syn_parse_x10().
 {
   int ic;
   ic = ( int ) ( P * 0.1 );
   sprintf ( target, "%04d", ic % 10000 );
   return target;
 }
int syn_parse_x10 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 66 of file bufr2syn_x10.c.
References synop_sec1::a, bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, bufr_atom_data::mask, synop_chunks::mask, pascal_to_ppp(), pascal_to_PPPP(), synop_sec1::PoPoPoPo, synop_sec1::ppp, synop_sec1::PPPP, synop_chunks::s1, SYNOP_SEC1, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 4: // 0 10 004
       pascal_to_PPPP ( aux, s->val );
       strcpy ( syn->s1.PoPoPoPo, aux );
       syn->mask |= SYNOP_SEC1;
       break;
     case 51: // 0 10 051
       pascal_to_PPPP ( aux, s->val );
       strcpy ( syn->s1.PPPP, aux );
       syn->mask |= SYNOP_SEC1;
       break;
     case 63: // 0 10 063
       sprintf ( syn->s1.a, "%1d",s->ival );
       syn->mask |= SYNOP_SEC1;
       break;
     case 61: // 0 10 061
       pascal_to_ppp ( aux, s->val );
       sprintf ( syn->s1.ppp, "%s", aux );
       syn->mask |= SYNOP_SEC1;
       break;
     default:
       break;
     }
   return 0;
 }