bufr2synop: src/libraries/bufr2tac_sqparse.c File Reference
bufr2tac_sqparse.c File Reference
file with the code to parse a sequence of descriptors for a subset
#include "bufr2tac.h"
Functions
int find_descriptor (int *haystack, size_t nlst, int needle)
Try to find a descriptor in an array.
int find_descriptor_interval (int *haystack, size_t nlst, int needlemin, int needlemax)
int parse_subset_sequence (struct metreport *m, struct bufr_subset_sequence_data *sq, struct bufr2tac_subset_state *st, int *kdtlst, size_t nlst, int *ksec1, char *err)
Parse a sequence of expanded descriptors for a subset.
Detailed Description
file with the code to parse a sequence of descriptors for a subset
Definition in file bufr2tac_sqparse.c.
Function Documentation
find_descriptor()
int find_descriptor (int * haystack, size_t nlst, int needle)
Try to find a descriptor in an array.
Parameters
haystack array of integers as descriptors
nlst number of descriptors in array
needle descriptor to find
it returns 1 if found, 0 otherwise.
Definition at line 35 of file bufr2tac_sqparse.c.
{
  size_t i = 0;
  while ( ( i < nlst ) && ( haystack[i] != needle ) )
    {
      i++;
    }
  return ( i < nlst );
}
Referenced by parse_subset_sequence().
find_descriptor_interval()
int find_descriptor_interval (int * haystack, size_t nlst, int needlemin, int needlemax)
Definition at line 59 of file bufr2tac_sqparse.c.
{
  size_t i = 0;
  while ( ( i < nlst ) && ( haystack[i] > needlemax || haystack[i] < needlemin ) )
    {
      i++;
    }
  return ( i < nlst );
}
Referenced by parse_subset_sequence().
parse_subset_sequence()
int parse_subset_sequence (struct metreport * m, struct bufr_subset_sequence_data * sq, struct bufr2tac_subset_state * st, int * kdtlst, size_t nlst, int * ksec1, char * err)
Parse a sequence of expanded descriptors for a subset.
Parameters
m pointer to a struct metreport where to set the data
sq pointer to a struct bufr_subset_sequence_data where the values for sequence of descriptors for a subset has been decoded
st pointer to a struct bufr2tac_subset_state
kdtlst array of integers with descriptors
nlst number of descriptors in kdtlst
ksec1 array of auxiliar integers decoded by bufrdc ECMWF library
err string where to write errors if any
Definition at line 81 of file bufr2tac_sqparse.c.
{
  /* Clean the state */
  memset ( st, 0, sizeof ( struct bufr2tac_subset_state ) );
  /* First task to do is figure out the type of report */
  switch ( ksec1[5] )
    {
    case 0:
      if ( find_descriptor_interval ( kdtlst, nlst, 307071, 307073 ) )
        {
          strcpy ( st->type_report, "CLIMAT" );  // FM-71 CLIMAT
        }
      else if ( find_descriptor_interval ( kdtlst, nlst, 307079, 307086 ) ||
                find_descriptor ( kdtlst, nlst,307091 ) ||
                find_descriptor ( kdtlst, nlst,307092 ) ||
                find_descriptor ( kdtlst, nlst,307096 ) ||
                find_descriptor ( kdtlst, nlst,307182 ) ||
                ksec1[6] == 0 || ksec1[6] == 1 || ksec1[6] == 2 )
        {
          strcpy ( st->type_report,"AAXX" );  // FM-12 synop
        }
      else if ( find_descriptor ( kdtlst, nlst,307090 ) ||
                find_descriptor ( kdtlst, nlst,301092 ) ||
                ksec1[6] == 3 || ksec1[6] == 4 || ksec1[6] == 5 )
        {
          strcpy ( st->type_report,"OOXX" );  // FM-14 synop-mobil
        }
      break;
    case 1:
      if ( find_descriptor_interval ( kdtlst, nlst, 308004, 308005 ) ||
           find_descriptor ( kdtlst, nlst,301093 ) ||
           find_descriptor ( kdtlst, nlst,308009 ) ||
           find_descriptor ( kdtlst, nlst,1011 ) )
        {
          strcpy ( st->type_report,"BBXX" );  // FM-13 ship
        }
      else if ( find_descriptor_interval ( kdtlst, nlst, 308001, 308003 ) ||
                find_descriptor ( kdtlst, nlst,315008 ) ||
                find_descriptor ( kdtlst, nlst,315009 ) ||
                find_descriptor ( kdtlst, nlst,1005 ) ||
                find_descriptor ( kdtlst, nlst,2036 ) ||
                find_descriptor ( kdtlst, nlst,2149 ) ||
                ksec1[6] == 25 )
        {
          strcpy ( st->type_report,"ZZYY" );  // FM-18 buoy
        }
      else if ( find_descriptor_interval ( kdtlst, nlst, 308011, 308013 ) )
        {
          strcpy ( st->type_report, "CLIMAT SHIP" );  // FM-71 CLIMAT SHIP
        }
      else if ( find_descriptor ( kdtlst, nlst,307090 ) )
        {
          // FIXME Some FM-14 are coded as category 1
          strcpy ( st->type_report,"OOXX" );  // FM-14 synop-mobil
        }
      break;
    case 2:
      if ( find_descriptor_interval ( kdtlst, nlst, 309050, 309051 ) )
        {
          strcpy ( st->type_report,"PPXX" );  // PILOT, PILOT SHIP, PILOT DROP or PILOT MOBIL
        }
      else if ( find_descriptor ( kdtlst, nlst, 309052 ) ||
                find_descriptor ( kdtlst, nlst, 309057 )
              )
        {
          strcpy ( st->type_report,"TTXX" );  // TEMP, TEMP SHIP, TEMP MOBIL
        }
      break;
    default:
      sprintf ( err, "The data category %d is not parsed at the moment", ksec1[5] );
      return 1;
    }
  if ( st->type_report[0] == '\0' )
    {
      sprintf ( err, "Cannot find the report type\n" );
      return 1;
    }
  //if(DEBUG)
  //  printf("Going to parse a %s report\n", st->type_report);
  if ( strcmp ( st->type_report,"AAXX" ) == 0 || strcmp ( st->type_report,"BBXX" ) == 0 || strcmp ( st->type_report,"OOXX" ) == 0 )
    {
      // Parse FM-12, FM-13 and FM-14
      if ( parse_subset_as_synop ( m, st, sq, err ) == 0 )
        {
          if (BUFR2TAC_DEBUG_LEVEL)
            bufr2tac_print_error(&st->e);
          return print_synop_report ( m );
        }
    }
  else if ( strcmp ( st->type_report,"ZZYY" ) == 0 )
    {
      // parse BUOY
      if ( parse_subset_as_buoy ( m, st, sq, err ) == 0 )
        {
          if (BUFR2TAC_DEBUG_LEVEL)
            bufr2tac_print_error(&st->e);
          return print_buoy_report ( m );
        }
    }
  else if ( strcmp ( st->type_report,"TTXX" ) == 0 )
    {
      // psrse TEMP
      if ( parse_subset_as_temp ( m, st, sq, err ) == 0 )
        {
          if (BUFR2TAC_DEBUG_LEVEL)
            bufr2tac_print_error(&st->e);
          return print_temp_report ( m );
        }
    }
  else if ( strcmp ( st->type_report,"CLIMAT" ) == 0 )
    {
      // psrse CLIMAT
      if ( parse_subset_as_climat ( m, st, sq, err ) == 0 )
        {
          if (BUFR2TAC_DEBUG_LEVEL)
            bufr2tac_print_error(&st->e);
          return print_climat_report ( m );
        }
    }
  // when reached this point we have han error
  if (BUFR2TAC_DEBUG_LEVEL)
    bufr2tac_print_error(&st->e);
  return 1;
}
References BUFR2TAC_DEBUG_LEVEL, bufr2tac_print_error(), bufr2tac_subset_state::e, find_descriptor(), find_descriptor_interval(), parse_subset_as_buoy(), parse_subset_as_climat(), parse_subset_as_synop(), parse_subset_as_temp(), print_buoy_report(), print_climat_report(), print_synop_report(), print_temp_report(), and bufr2tac_subset_state::type_report.
Referenced by bufrtotac_parse_subset_sequence().