bufr2synop: src/libraries/bufr2tac_x12.c File Reference
bufr2tac_x12.c File Reference
decodes the descriptors with X = 12 (Temperature)
#include "bufr2tac.h"
Functions
char * kelvin_to_snTTT (char *target, double T)
converts a kelvin temperature value into a snTTT string
char * kelvin_to_snTT (char *target, double T)
converts a kelvin temperature value into a snTT string
char * kelvin_to_TT (char *target, double T)
converts a kelvin temperature value into a TT string
char * kelvin_to_TTTT (char *target, double T)
converts a kelvin temperature value into a TTTT string
char * kelvin_to_TTTa (char *target, double T)
Set temperature TTTa.
char * dewpoint_depression_to_DnDn (char *target, double T, double Td)
Set DnDn (dewpoint depression)
int syn_parse_x12 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 12.
int buoy_parse_x12 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 12.
int climat_parse_x12 (struct climat_chunks *c, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 12.
int temp_parse_x12 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 12.
Detailed Description
decodes the descriptors with X = 12 (Temperature)
Definition in file bufr2tac_x12.c.
Function Documentation
buoy_parse_x12()
int buoy_parse_x12 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 466 of file bufr2tac_x12.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 12 001 . Air temperature
    case 4: // 0 12 004 . Air temperatura at 2 m
    case 101: // 0 12 101 . Air temperature
    case 104: // 0 12 104 . Air temperature at 2 m
      if ( b->s1.TTT[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              b->s1.sn1[0] = aux[0];
              strcpy ( b->s1.TTT, aux + 1 );
              b->mask |= BUOY_SEC1;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "buoy_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 3: // 0 12 003 . Dewpoint temperature
    case 6: // 0 12 006 . Dewpoint temperature at 2 m
    case 103: // 0 12 103 . Dewpoint temperature
    case 106: // 0 12 106 . Dewpoint temperature at 2 m
      if ( b->s1.TdTdTd[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              b->s1.sn2[0] = aux[0];
              strcpy ( b->s1.TdTdTd, aux + 1 );
              b->mask |= BUOY_SEC1;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "buoy_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x12()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, kelvin_to_snTTT(), bufr_atom_data::mask, buoy_chunks::mask, buoy_chunks::s1, buoy_sec1::sn1, buoy_sec1::sn2, buoy_sec1::TdTdTd, buoy_sec1::TTT, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
climat_parse_x12()
int climat_parse_x12 (struct climat_chunks * c, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
c pointer to a struct climat_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 526 of file bufr2tac_x12.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  if ( c == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 101:
      if ( s->is_normal == 0 )
        {
          if ( s->isq_val == 4 ) // mean value
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s1.s[0] = aux[0];
                  strcpy ( c->s1.TTT, aux + 1 );
                  c->mask |= CLIMAT_SEC1;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
          else if ( s->isq_val == 2 ) // maximum value
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s4.sax[0] = aux[0];
                  strcpy ( c->s4.Tax, aux + 1 );
                  if ( s->more_days == 0 )
                    {
                      sprintf ( c->s4.yax, "%02d", s->day );
                    }
                  else
                    {
                      sprintf ( c->s4.yax, "%02d", ( s->day + 50 ) % 100 );
                    }
                  c->mask |= CLIMAT_SEC4;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
          else if ( s->isq_val == 3 ) // minimum value
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s4.san[0] = aux[0];
                  strcpy ( c->s4.Tan, aux + 1 );
                  if ( s->more_days == 0 )
                    {
                      sprintf ( c->s4.yan, "%02d", s->day );
                    }
                  else
                    {
                      sprintf ( c->s4.yan, "%02d", ( s->day + 50 ) % 100 );
                    }
                  c->mask |= CLIMAT_SEC4;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
        }
      else
        {
          if ( c->s2.TTT[0] == 0 )
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s2.s[0] = aux[0];
                  strcpy ( c->s2.TTT, aux + 1 );
                  c->mask |= CLIMAT_SEC2;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
        }
      break;
    case 118: // 0 12 118 . Maximum temperature at heigh specified, past 24 h
      if ( s->is_normal == 0 )
        {
          if ( c->s1.TxTxTx[0] == 0 )
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s1.sx[0] = aux[0];
                  strcpy ( c->s1.TxTxTx, aux + 1 );
                  c->mask |= CLIMAT_SEC1;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
        }
      else
        {
          if ( c->s2.TxTxTx[0] == 0 )
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s2.sx[0] = aux[0];
                  strcpy ( c->s2.TxTxTx, aux + 1 );
                  c->mask |= CLIMAT_SEC2;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
        }
      break;
    case 119: // 0 12 119 . Minimum temperature at heigh specified, past 24 h
      if ( s->is_normal == 0 )
        {
          if ( c->s1.TnTnTn[0] == 0 )
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s1.sn[0] = aux[0];
                  strcpy ( c->s1.TnTnTn, aux + 1 );
                  c->mask |= CLIMAT_SEC1;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
        }
      else
        {
          if ( c->s2.TnTnTn[0] == 0 )
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  c->s2.sn[0] = aux[0];
                  strcpy ( c->s2.TnTnTn, aux + 1 );
                  c->mask |= CLIMAT_SEC2;
                }
              else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
                bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
            }
        }
      break;
    case 151: // 0 12 151 . Standard deviation of daily mean temperature
      sprintf ( aux, "%03d", ( int ) ( s->val * 10.0 + 0.5 ) );
      if ( s->is_normal == 0 )
        {
          strcpy ( c->s1.ststst, aux );
          c->mask |= CLIMAT_SEC1;
        }
      else
        {
          strcpy ( c->s2.ststst, aux );
          c->mask |= CLIMAT_SEC2;
        }
      break;
    case 152: // 0 12 152 . Highest daily mean temperature
      if ( s->a1->desc.x == 4 && s->a1->desc.y == 3 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              c->s4.sx[0] = aux[0];
              strcpy ( c->s4.Txd, aux + 1 );
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
          if ( s->isq_val == 0 )
            {
              sprintf ( c->s4.yx, "%02d", s->day );
            }
          else
            {
              sprintf ( c->s4.yx, "%02d", ( s->day + 50 ) % 100 );
            }
          c->mask |= CLIMAT_SEC4;
        }
      break;
    case 153: // 0 12 153 . Lowest daily mean temperature
      if ( s->a1->desc.x == 4 && s->a1->desc.y == 3 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              c->s4.sn[0] = aux[0];
              strcpy ( c->s4.Tnd, aux + 1 );
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "climat_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
          if ( s->isq_val == 0 )
            {
              sprintf ( c->s4.yn, "%02d", s->day );
            }
          else
            {
              sprintf ( c->s4.yn, "%02d", ( s->day + 50 ) % 100 );
            }
          c->mask |= CLIMAT_SEC4;
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "climat_parse_x12()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, bufr2tac_subset_state::a1, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), CLIMAT_SEC1, CLIMAT_SEC2, CLIMAT_SEC4, bufr2tac_subset_state::day, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::is_normal, bufr2tac_subset_state::isq_val, kelvin_to_snTTT(), bufr_atom_data::mask, climat_chunks::mask, bufr2tac_subset_state::more_days, climat_sec1::s, climat_sec2::s, climat_chunks::s1, climat_chunks::s2, climat_chunks::s4, climat_sec4::san, climat_sec4::sax, climat_sec1::sn, climat_sec2::sn, climat_sec4::sn, climat_sec1::ststst, climat_sec2::ststst, climat_sec1::sx, climat_sec2::sx, climat_sec4::sx, climat_sec4::Tan, climat_sec4::Tax, climat_sec4::Tnd, climat_sec1::TnTnTn, climat_sec2::TnTnTn, climat_sec1::TTT, climat_sec2::TTT, climat_sec4::Txd, climat_sec1::TxTxTx, climat_sec2::TxTxTx, bufr2tac_subset_state::val, bufr_descriptor::x, bufr_descriptor::y, climat_sec4::yan, climat_sec4::yax, climat_sec4::yn, and climat_sec4::yx.
Referenced by parse_subset_as_climat().
dewpoint_depression_to_DnDn()
char * dewpoint_depression_to_DnDn (char * target, double T, double Td)
Set DnDn (dewpoint depression)
Parameters
target string to set as result
T temperature (Kelvin)
Td dewpoint (Kelvin)
Definition at line 179 of file bufr2tac_x12.c.
{
  int ix;
  double dpd = T - Td;
  if ( T == MISSING_REAL || Td == MISSING_REAL )
    {
      strcpy ( target, "//" );
      return target;
    }
  if ( dpd < 0.0 )
    {
      return NULL;
    }
  if ( dpd > 50.0 )
    {
      strcpy ( target, "//" );
      return target;
    }
  ix = ( int ) ( 10.0 * dpd );
  if ( ix >= 55 )
    {
      ix = 50 + ( ix + 5 ) / 10;
    }
  sprintf ( target, "%02d", ix );
  return target;
}
References MISSING_REAL.
Referenced by parse_temp_raw_data().
kelvin_to_snTT()
char * kelvin_to_snTT (char * target, double T)
converts a kelvin temperature value into a snTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 69 of file bufr2tac_x12.c.
{
  int ic;
  if ( T < 173.65 || T > 340.0 )
    {
      return NULL;
    }
  // Whole degrees (Celsius)
  ic = ( int ) ( floor ( ( T - 273.15 ) + 0.5 ) );
  if ( ic < 0 )
    {
      sprintf ( target, "1%02d", -ic );
    }
  else
    {
      sprintf ( target, "%03d", ic );
    }
  return target;
}
Referenced by syn_parse_x12().
kelvin_to_snTTT()
char * kelvin_to_snTTT (char * target, double T)
converts a kelvin temperature value into a snTTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 32 of file bufr2tac_x12.c.
{
  int ic;
  double Tx = T;
  if ( Tx > 15 && Tx < 34.0 ) // guess there is an scale error on coding , we better manage T * 10
    {
      Tx *= 10.0;
    }
  if ( Tx < 173.205 || Tx > 340.0 )
    {
      return NULL;
    }
  // tenths of degree (Celsius)
  // Patch introduced on 22-Dec-2019 due to some roundings errors from India and Australia
  // not converting properly from Kelvin to Celsius for Tmax and Tmin
  // Changed '0.5' to '0.45'
  //ic = ( int ) ( floor ( 10.0 * ( Tx - 273.15 ) + 0.5 ) );
  ic = ( int ) ( floor ( 10.0 * ( Tx - 273.15 ) + 0.45 ) );
  if ( ic < 0 )
    {
      sprintf ( target, "1%03d",  -ic );
    }
  else
    {
      sprintf ( target, "0%03d",  ic );
    }
  return target;
}
Referenced by buoy_parse_x12(), buoy_parse_x22(), climat_parse_x12(), syn_parse_x12(), syn_parse_x22(), and temp_parse_x22().
kelvin_to_TT()
char * kelvin_to_TT (char * target, double T)
converts a kelvin temperature value into a TT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 96 of file bufr2tac_x12.c.
{
  int ic;
  if ( T < 150.0 || T > 340.0 )
    {
      return NULL;
    }
  // Whole degrees (Celsius)
  ic = ( int ) ( floor ( ( T - 273.15 ) + 0.5 ) );
  if ( ic < 0 )
    {
      sprintf ( target, "%02d", 50 - ic );
    }
  else
    {
      sprintf ( target, "%02d", ic );
    }
  return target;
}
Referenced by syn_parse_x12().
kelvin_to_TTTa()
char * kelvin_to_TTTa (char * target, double T)
Set temperature TTTa.
Parameters
target result as string
T temperature (kelvin)
Definition at line 147 of file bufr2tac_x12.c.
{
  int ix;
  if ( T == MISSING_REAL )
    {
      sprintf ( target, "///" );
      return target;
    }
  ix = ( int ) ( 10.0 * ( T - 273.15 ) );
  if ( ix >= 0 )
    {
      ix &= ~1;
    }
  else
    {
      ix = ( -ix );
      ix |= 1;
    }
  sprintf ( target, "%03d", ix );
  return target;
}
References MISSING_REAL.
Referenced by parse_temp_raw_data().
kelvin_to_TTTT()
char * kelvin_to_TTTT (char * target, double T)
converts a kelvin temperature value into a TTTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 123 of file bufr2tac_x12.c.
{
  int ic;
  if ( T < 150.0 || T > 340.0 )
    {
      return NULL;
    }
  // hundreth of degrees (Celsius)
  ic = ( int ) ( floor ( 100.0 * ( T - 273.15 ) + 0.5 ) );
  if ( ic < 0 )
    {
      ic = 5000 - ic;
    }
  sprintf ( target, "%04d", ic );
  return target;
}
Referenced by buoy_parse_x22().
syn_parse_x12()
int syn_parse_x12 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 220 of file bufr2tac_x12.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  switch ( s->a->desc.y )
    {
    case 1: // 0 12 001 . Air temperature
    case 4: // 0 12 004 . Air temperatura at 2 m
    case 101: // 0 12 101 . Air temperature
    case 104: // 0 12 104 . Air temperature at 2 m
      if ( syn->s1.TTT[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s1.sn1[0] = aux[0];
              strcpy ( syn->s1.TTT, aux + 1 );
              syn->mask |= SYNOP_SEC1;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 3: // 0 12 003 . Dewpoint temperature
    case 6: // 0 12 006 . Dewpoint temperature at 2 m
    case 103: // 0 12 103 . Dewpoint temperature
    case 106: // 0 12 106 . Dewpoint temperature at 2 m
      if ( syn->s1.TdTdTd[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s1.sn2[0] = aux[0];
              strcpy ( syn->s1.TdTdTd, aux + 1 );
              syn->mask |= SYNOP_SEC1;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 14: // 0 12 014 . Maximum temperature at 2 m , past 12 hours
    case 21: // 0 12 021 . Maximum temperature.
    case 114: // 0 12 114 . Maximum temperature at 2 m , past 12 hours
    case 116: // 0 12 116 . Maximum temperature at 2 m , past 24 hours
      if ( syn->s3.TxTxTx[0] == 0 && ( s->itval % ( 3 * 3600 ) ) == 0 ) // only for 3, 6 ... hours
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s3.snx[0] = aux[0];
              strcpy ( syn->s3.TxTxTx, aux + 1 );
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 11: // 0 12 011 . Maximum temperature at heigh and over the period specified
    case 111: // 0 12 111 . Maximum temperature at heigh and over the period specified
      if ( syn->s3.TxTxTx[0] == 0 &&
           ( s->hsensor >= 1.0 || s->hsensor <= 0 ) &&
           ( time_period_duration ( s ) % ( 12 * 3600 ) ) == 0 ) // only for 12 , 24 hours
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s3.snx[0] = aux[0];
              strcpy ( syn->s3.TxTxTx, aux + 1 );
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 15: // 0 12 015 . Minimum temperature at 2 m , past 12 hours
    case 22: // 0 12 022 . Minimum temperature.
    case 115: // 0 12 115 . Minimum temperature at 2 m , past 12 hours
    case 117: // 0 12 117 . Minimum temperature at 2 m , past 24 hours
      if ( syn->s3.TnTnTn[0] == 0 && ( s->itval % ( 3 * 3600 ) ) == 0 ) // only for 3, 6 ... hours
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s3.snn[0] = aux[0];
              strcpy ( syn->s3.TnTnTn, aux + 1 );
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 12: // 0 12 012 . Minimum temperature at heigh and over the period specified
    case 112: // 0 12 112 . Minimum temperature at heigh and over the period specified
      if ( syn->s3.TnTnTn[0] == 0 &&
           ( s->hsensor >= 1.0 || s->hsensor <= 0 ) &&
           ( time_period_duration ( s ) % ( 12 * 3600 ) ) == 0 ) // only for 12 , 24 hours
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s3.snn[0] = aux[0];
              strcpy ( syn->s3.TnTnTn, aux + 1 );
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 2: // 0 12 002 . Wet bulb temperature
    case 5: // 0 12 005 . Wet bulb temperature at 2 m
    case 102: // 0 12 102 . Wet bulb temperature
    case 105: // 0 12 105 . Wet bulb temperature at 2 m
      if ( syn->s2.TbTbTb[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s2.sw[0] = aux[0];
              strcpy ( syn->s2.TbTbTb, aux + 1 );
              syn->mask |= SYNOP_SEC2;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTTT()", "Unspected parse problem" );
        }
      break;
    case 113: // 0 12 113 . Ground minimum temperature, past 12 hours
      if ( strcmp ( "6", syn->s0.A1 ) == 0 ||
           strcmp ( "3", syn->s0.A1 ) == 0 ||
           strcmp ( "2", syn->s0.A1 ) == 0
         ) // region III or VI
        {
          if ( kelvin_to_snTT ( aux, s->val ) )
            {
              strcpy ( syn->s3.jjj, aux );
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTT()", "Unspected parse problem" );
        }
      else if ( strcmp ( "1", syn->s0.A1 ) == 0 )
        {
          if ( kelvin_to_TT ( aux, s->val ) )
            {
              syn->s3.XoXoXoXo[0] = aux[0];
              syn->s3.XoXoXoXo[1] = aux[1];
              if ( syn->s3.XoXoXoXo[2] == 0 )
                {
                  syn->s3.XoXoXoXo[2] = '/';
                }
              if ( syn->s3.XoXoXoXo[3] == 0 )
                {
                  syn->s3.XoXoXoXo[3] = '/';
                }
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTT()", "Unspected parse problem" );
        }
      break;
    case 121: // 0 12 121 . Ground minimum temperature (at the time of observation)
      if ( strcmp ( "2", syn->s0.A1 ) == 0 ) // region II
        {
          if ( kelvin_to_snTT ( aux, s->val ) )
            {
              syn->s3.XoXoXoXo[1] = aux[0];
              syn->s3.XoXoXoXo[2] = aux[1];
              syn->s3.XoXoXoXo[3] = aux[2];
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTT()", "Unspected parse problem" );
        }
      break;
    case 120: // 0 12 120 . Ground temperature
      if ( strcmp ( "2", syn->s0.A1 ) == 0 ) // Only for Region II
        {
          if ( kelvin_to_snTT ( aux, s->val ) )
            {
              if ( syn->s3.E1[0] )
                syn->s3.XoXoXoXo[0] = '/';
              else if ( syn->s3.E[0] )
                syn->s3.XoXoXoXo[0] = syn->s3.E[0];
              syn->s3.XoXoXoXo[1] = aux[0];
              syn->s3.XoXoXoXo[2] = aux[1];
              syn->s3.XoXoXoXo[3] = aux[2];
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_snTT()", "Unspected parse problem" );
        }
      break;
    case 122: // 0 12 122 . Ground minimum temperature during preceding night
      if ( strcmp ( "1", syn->s0.A1 ) == 0 ) // Only for Region I
        {
          if ( kelvin_to_TT ( aux, s->val ) )
            {
              syn->s3.XoXoXoXo[0] = aux[0];
              syn->s3.XoXoXoXo[1] = aux[1];
              if ( syn->s3.XoXoXoXo[2] == 0 )
                {
                  syn->s3.XoXoXoXo[2] = '/';
                }
              if ( syn->s3.XoXoXoXo[3] == 0 )
                {
                  syn->s3.XoXoXoXo[3] = '/';
                }
              syn->mask |= SYNOP_SEC3;
            }
          else if ( BUFR2TAC_DEBUG_LEVEL > 0 )
            bufr2tac_set_error ( s, 1, "syn_parse_x12()->kelvin_to_TT()", "Unspected parse problem" );
        }
      else if ( strcmp ( "2", syn->s0.A1 ) == 0 ||
                strcmp ( "3", syn->s0.A1 ) == 0 ) // Region II and III
        {
          if ( kelvin_to_snTT ( aux, s->val ) )
            {
              strcpy ( syn->s3.jjj, aux );
              syn->mask |= SYNOP_SEC3;
            }
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x12()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, synop_sec0::A1, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec3::E, synop_sec3::E1, bufr2tac_subset_state::hsensor, bufr2tac_subset_state::itval, synop_sec3::jjj, kelvin_to_snTT(), kelvin_to_snTTT(), kelvin_to_TT(), bufr_atom_data::mask, synop_chunks::mask, synop_chunks::s0, synop_chunks::s1, synop_chunks::s2, synop_chunks::s3, synop_sec1::sn1, synop_sec1::sn2, synop_sec3::snn, synop_sec3::snx, synop_sec2::sw, SYNOP_SEC1, SYNOP_SEC2, SYNOP_SEC3, synop_sec2::TbTbTb, synop_sec1::TdTdTd, time_period_duration(), synop_sec3::TnTnTn, synop_sec1::TTT, synop_sec3::TxTxTx, bufr2tac_subset_state::val, synop_sec3::XoXoXoXo, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x12()
int temp_parse_x12 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 751 of file bufr2tac_x12.c.
{
  if ( t == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 101: // 0 12 101. Temperature/dry-bulb temperature (scale 2)
      if ( s->rep > 0 && s->r->n > 0 )
        {
          if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
            {
              s->r->raw[s->r->n - 1].T = MISSING_REAL;
            }
          else
            {
              s->r->raw[s->r->n - 1].T = s->val;
            }
        }
      break;
    case 103: // 0 12 103. Dew-point temperature (scale 2)
      if ( s->rep > 0 && s->r->n > 0 )
        {
          if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
            {
              s->r->raw[s->r->n - 1].Td = MISSING_REAL;
            }
          else
            {
              s->r->raw[s->r->n - 1].Td = s->val;
            }
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x12()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::mask, MISSING_REAL, temp_raw_data::n, bufr2tac_subset_state::r, temp_raw_data::raw, bufr2tac_subset_state::rep, temp_raw_point_data::T, temp_raw_point_data::Td, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().