bufr2synop: src/bufrdeco/bufrdeco_print_html.c File Reference
bufrdeco_print_html.c File Reference
file with the code to print data or any output from library decobufr in html format
#include "bufrdeco.h"
Functions
int sprint_sec0_info_html (char *target, size_t lmax, struct bufrdeco *b)
Prints info from sec0 in html format.
int sprint_sec1_info_html (char *target, size_t lmax, struct bufrdeco *b)
Prints info from sec1.
int sprint_sec3_info_html (char *target, size_t lmax, struct bufrdeco *b)
Prints info from sec3 formatted as html.
int sprint_sec4_info_html (char *target, size_t lmax, struct bufrdeco *b)
Prints info from sec4.
char * bufrdeco_print_atom_data_html (char *target, size_t lmax, struct bufr_atom_data *a, uint32_t ss)
print the data in a struct bufr_atom_data to a string as cells of table rows
int bufrdeco_fprint_subset_sequence_data_html (FILE *f, struct bufrdeco_subset_sequence_data *s)
int bufrdeco_print_subset_sequence_data_html (struct bufrdeco_subset_sequence_data *s)
int bufrdeco_fprint_subset_sequence_data_tagged_html (FILE *f, struct bufrdeco_subset_sequence_data *s, char *id)
int bufrdeco_print_subset_sequence_data_tagged_html (struct bufrdeco_subset_sequence_data *s, char *id)
Detailed Description
file with the code to print data or any output from library decobufr in html format
Definition in file bufrdeco_print_html.c.
Function Documentation
bufrdeco_fprint_subset_sequence_data_html()
int bufrdeco_fprint_subset_sequence_data_html (FILE * f, struct bufrdeco_subset_sequence_data * s)
Definition at line 241 of file bufrdeco_print_html.c.
{
  size_t i;
  char aux[1024];
  bufrdeco_assert ( f != NULL && s != NULL );
  fprintf ( f, "<div class='bufr_subset'>\n" );
  fprintf ( f, "<table>\n" );
  for ( i = 0; i < s->nd ; i++ )
    {
      fprintf ( f, "<tr><td>%5lu:</td>%s</tr>\n", i, bufrdeco_print_atom_data_html ( aux, sizeof (aux), &s->sequence[i], s->ss ) );
    }
  fprintf ( f, "</table>\n" );
  fprintf ( f, "</div>\n" );
  return 0;
}
References bufrdeco_assert, bufrdeco_print_atom_data_html(), bufrdeco_subset_sequence_data::nd, bufrdeco_subset_sequence_data::sequence, and bufrdeco_subset_sequence_data::ss.
Referenced by bufrdeco_print_subset_sequence_data_html().
bufrdeco_fprint_subset_sequence_data_tagged_html()
int bufrdeco_fprint_subset_sequence_data_tagged_html (FILE * f, struct bufrdeco_subset_sequence_data * s, char * id)
Definition at line 279 of file bufrdeco_print_html.c.
{
  size_t i;
  char aux[1024];
  bufrdeco_assert ( f != NULL && s != NULL && id != NULL );
  fprintf ( f, "\n<div class='bufr_subset' id='%s'>\n", id );
  fprintf ( f, "<table>\n" );
  fprintf ( f, "<caption>%s</caption>\n", id );
  fprintf ( f, "<tr><th></th><th>Descriptor</th><th>Name</th><th>Unit</th><th>Value</th><th>Description</th></tr>\n" );
  for ( i = 0; i < s->nd ; i++ )
    {
      fprintf ( f, "<tr><td class='ndesc' id='d_%u_%lu' >#%lu</td>%s</tr>\n", s->ss, i, i, bufrdeco_print_atom_data_html ( aux, sizeof (aux), &s->sequence[i], s->ss ) );
    }
  fprintf ( f, "</table>\n" );
  fprintf ( f, "</div>\n" );
  return 0;
}
References bufrdeco_assert, bufrdeco_print_atom_data_html(), bufrdeco_subset_sequence_data::nd, bufrdeco_subset_sequence_data::sequence, and bufrdeco_subset_sequence_data::ss.
Referenced by bufrdeco_print_subset_sequence_data_tagged_html().
bufrdeco_print_atom_data_html()
char * bufrdeco_print_atom_data_html (char * target, size_t lmax, struct bufr_atom_data * a, uint32_t ss)
print the data in a struct bufr_atom_data to a string as cells of table rows
Parameters
target string where to print the result
lmax dimension of target
a pointer to struct ref bufr_atom_data with data to print
ss index of subset in bufr
Returns
a pointer to result string
Definition at line 160 of file bufrdeco_print_html.c.
{
  char aux[256];
  size_t used = 0;
  bufrdeco_assert ( a != NULL && lmax != 0 && target != NULL );
  used += snprintf ( target + used , lmax - used,"<td class='desc'>%u %02u %03u</td>", a->desc.f, a->desc.x, a->desc.y );
  used += snprintf ( target + used , lmax - used,"<td class='name'>%s</td>", a->name );
  used += snprintf ( target + used , lmax - used,"<td class='unit'>%s</td>", a->unit );
  if ( a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      if ( a->is_bitmaped_by != 0 )
        used += snprintf ( target + used , lmax - used,"<td class='missing'>MISSING</td><td>NOTE: Bitmaped by <a href='#d%u_%u'>#%u</a></td>", ss, a->is_bitmaped_by, a->is_bitmaped_by );
      else if ( a->bitmap_to != 0 )
        used += snprintf ( target + used , lmax - used,"<td class='missing'>MISSING</td><td>NOTE: Bitmap to <a href='#d%u_%u'>#%u</a></td>", ss, a->bitmap_to, a->bitmap_to );
      else if ( a->related_to != 0 )
        used += snprintf ( target + used , lmax - used,"<td class='missing'>MISSING</td><td>NOTE: Related to <a href='#d%u_%u'>#%u</a></td>", ss, a->related_to, a->related_to );
      else
        used += snprintf ( target + used , lmax - used,"<td class='missing'>MISSING</td><td></td>" );
    }
  else
    {
      if ( a->mask & DESCRIPTOR_HAVE_STRING_VALUE )
        {
          if ( a->is_bitmaped_by != 0 )
            used += snprintf ( target + used , lmax - used,"<td></td><td class='cval'>%s<br>NOTE: Bitmaped by <a href='#d%u_%u'>#%u</a></td>\n", a->cval, ss, a->is_bitmaped_by, a->is_bitmaped_by );
          else if ( a->bitmap_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td></td><td class='cval'>%s<br>NOTE: Bitmap to <a href='#d%u_%u'>#%u</a></td>\n", a->cval, ss, a->bitmap_to, a->bitmap_to );
          else if ( a->related_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td></td><td class='cval'>%s<br>NOTE: Related to <a href='#d%u_%u'>#%u</a></td>\n", a->cval, ss, a->related_to, a->related_to );
          else
            used += snprintf ( target + used , lmax - used,"<td></td><td class='cval'>%s</td>\n", a->cval );
        }
      else if ( a->mask & DESCRIPTOR_HAVE_CODE_TABLE_STRING
                || strstr ( a->unit, "CODE TABLE" ) == a->unit
                || strstr ( a->unit, "Code table" ) == a->unit )
        {
          used += snprintf ( target + used , lmax - used,"<td class='ival'>%17u</td>", ( uint32_t ) a->val );
          if ( a->is_bitmaped_by != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s<br>NOTE: Bitmaped by <a href='#d%u_%u'>#%u</a></td>\n", a->ctable, ss, a->is_bitmaped_by, a->is_bitmaped_by );
          else if ( a->bitmap_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s<br>NOTE: Bitmap to <a href='#d%u_%u'>#%u</a></td>\n", a->ctable, ss, a->bitmap_to, a->bitmap_to  );
          else if ( a->related_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s<br>NOTE: Related to <a href='#d%u_%u'>#%u</a></td>\n", a->ctable, ss, a->related_to, a->related_to  );
          else
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s</td>\n", a->ctable );
        }
      else if ( a->mask & DESCRIPTOR_HAVE_FLAG_TABLE_STRING )
        {
          used += snprintf ( target + used , lmax - used,"<td class='hval'>0x%08X</td>", ( uint32_t ) a->val );
          if ( a->is_bitmaped_by != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s<br>NOTE: Bitmaped by <a href='#%du_%u'>#%u</a></td>\n", a->ctable, ss, a->is_bitmaped_by, a->is_bitmaped_by );
          else if ( a->bitmap_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s<br>NOTE: Bitmap to <a href='#d%u_%u'>#%u</a></td>\n", a->ctable, ss, a->bitmap_to, a->bitmap_to  );
          else if ( a->related_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s<br>NOTE: Related to <a href='#d%u_%u'>#%u</a></td>\n", a->ctable, ss, a->related_to, a->related_to  );
          else
            used += snprintf ( target + used , lmax - used,"<td class='ctable'>%s</td>\n", a->ctable );
        }
      else
        {
          if ( a->is_bitmaped_by != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='rval'>%s</td><td>NOTE: Bitmaped by <a href='#d%u_%u'>#%u</a></td>" , get_formatted_value_from_escale ( aux, sizeof (aux), a->escale, a->val ), ss, a->is_bitmaped_by, a->is_bitmaped_by );
          else if ( a->bitmap_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='rval'>%s</td><td>NOTE: Bitmap to <a href='#d%u_%u'>#%u</a></td>" , get_formatted_value_from_escale ( aux, sizeof (aux), a->escale, a->val ) , ss, a->bitmap_to, a->bitmap_to );
          else if ( a->related_to != 0 )
            used += snprintf ( target + used , lmax - used,"<td class='rval'>%s</td><td>NOTE: Related to <a href='#d%u_%u'>#%u</a></td>" , get_formatted_value_from_escale ( aux, sizeof (aux), a->escale, a->val ), ss, a->related_to, a->related_to );
          else
            used += snprintf ( target + used , lmax - used,"<td class='rval'>%s</td><td></td>" , get_formatted_value_from_escale ( aux, sizeof (aux), a->escale, a->val ) );
        }
    }
  return target;
}
References bufr_atom_data::bitmap_to, bufrdeco_assert, bufr_atom_data::ctable, bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_HAVE_CODE_TABLE_STRING, DESCRIPTOR_HAVE_FLAG_TABLE_STRING, DESCRIPTOR_HAVE_STRING_VALUE, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::escale, bufr_descriptor::f, get_formatted_value_from_escale(), bufr_atom_data::is_bitmaped_by, bufr_atom_data::mask, bufr_atom_data::name, bufr_atom_data::related_to, bufr_atom_data::unit, bufr_atom_data::val, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by bufrdeco_fprint_subset_sequence_data_html(), and bufrdeco_fprint_subset_sequence_data_tagged_html().
bufrdeco_print_subset_sequence_data_html()
int bufrdeco_print_subset_sequence_data_html (struct bufrdeco_subset_sequence_data * s)
Definition at line 265 of file bufrdeco_print_html.c.
{
  bufrdeco_assert ( s != NULL );
  return bufrdeco_fprint_subset_sequence_data_html ( stdout, s );
}
References bufrdeco_assert, and bufrdeco_fprint_subset_sequence_data_html().
bufrdeco_print_subset_sequence_data_tagged_html()
int bufrdeco_print_subset_sequence_data_tagged_html (struct bufrdeco_subset_sequence_data * s, char * id)
Definition at line 306 of file bufrdeco_print_html.c.
{
  bufrdeco_assert ( s != NULL );
  return bufrdeco_fprint_subset_sequence_data_tagged_html ( stdout, s, id );
}
References bufrdeco_assert, and bufrdeco_fprint_subset_sequence_data_tagged_html().
Referenced by main().
sprint_sec0_info_html()
int sprint_sec0_info_html (char * target, size_t lmax, struct bufrdeco * b)
Prints info from sec0 in html format.
Parameters
target string target
lmax available size in target
b pointer to the source struct bufrdeco
Returns
If succeeded return 0
Definition at line 34 of file bufrdeco_print_html.c.
{
  size_t used = 0;
  bufrdeco_assert ( b != NULL && lmax != 0 && target != NULL );
  used += snprintf ( target + used, lmax - used, "<table class='bufr_sec0'>\n<caption>SEC 0 INFO</caption>\n" );
  used += snprintf ( target + used, lmax - used, "<tr><td>Bufr length</td><td>%5u</td></tr>\n", b->sec0.bufr_length );
  used += snprintf ( target + used, lmax - used, "<tr><td>Bufr edition</td><td>%5u</td></tr>\n", b->sec0.edition );
  used += snprintf ( target + used, lmax - used, "</table>\n" );
  return 0;
}
References bufr_sec0::bufr_length, bufrdeco_assert, bufr_sec0::edition, and bufrdeco::sec0.
Referenced by sprint_sec0_info().
sprint_sec1_info_html()
int sprint_sec1_info_html (char * target, size_t lmax, struct bufrdeco * b)
Prints info from sec1.
Parameters
target string target
lmax available size in target
b pointer to the source struct bufrdeco
Returns
If succeeded return 0
Definition at line 55 of file bufrdeco_print_html.c.
{
  size_t used = 0;
  bufrdeco_assert ( b != NULL && lmax != 0 && target != NULL );
  used += snprintf ( target + used , lmax - used,"<div class='bufr_sec1'>\n" );
  used += snprintf ( target + used , lmax - used,"<table>\n<caption>SEC 1 INFO</caption>\n" );
  used += snprintf ( target + used , lmax - used,"<tr><td>Sec1 length</td><td>%5u</td></tr>\n", b->sec1.length );
  used += snprintf ( target + used , lmax - used,"<tr><td>Bufr master table</td><td>%5u</td></tr>\n", b->sec1.master );
  used += snprintf ( target + used , lmax - used,"<tr><td>Centre</td><td>%5u</td></tr>\n", b->sec1.centre );
  used += snprintf ( target + used , lmax - used,"<tr><td>Sub-Centre</td><td>%5u</td></tr>\n", b->sec1.subcentre );
  used += snprintf ( target + used , lmax - used,"<tr><td>Update sequence</td><td>%5u</td></tr>\n", b->sec1.update );
  used += snprintf ( target + used , lmax - used,"<tr><td>Options</td><td>%5x</td></tr>\n", b->sec1.options );
  used += snprintf ( target + used , lmax - used,"<tr><td>Category</td><td>%5u</td></tr>\n", b->sec1.category );
  used += snprintf ( target + used , lmax - used,"<tr><td>Subcategory</td><td>%5u</td></tr>\n", b->sec1.subcategory );
  used += snprintf ( target + used , lmax - used,"<tr><td>Sub-category local</td><td>%5u</td></tr>\n", b->sec1.subcategory_local );
  used += snprintf ( target + used , lmax - used,"<tr><td>Master table version</td><td>%5u</td></tr>\n", b->sec1.master_version );
  used += snprintf ( target + used , lmax - used,"<tr><td>Master table local</td><td>%5u</td></tr>\n", b->sec1.master_local );
  used += snprintf ( target + used , lmax - used,"<tr><td>Year</td><td>%5u</td></tr>\n", b->sec1.year );
  used += snprintf ( target + used , lmax - used,"<tr><td>Month</td><td>%5u</td></tr>\n", b->sec1.month );
  used += snprintf ( target + used , lmax - used,"<tr><td>Day</td><td>%5u</td></tr>\n", b->sec1.day );
  used += snprintf ( target + used , lmax - used,"<tr><td>Hour</td><td>%5u</td></tr>\n", b->sec1.hour );
  used += snprintf ( target + used , lmax - used,"<tr><td>Minute</td><td>%5u</td></tr>\n", b->sec1.minute );
  used += snprintf ( target + used , lmax - used,"<tr><td>Second</td><td>%5u</td></tr>\n", b->sec1.second );
  if ( b->sec0.edition == 3 )
    used += snprintf ( target + used , lmax - used,"<tr><td>Aditional space</td><td>%5u</td></tr>\n", b->sec1.length - 17 );
  else
    used += snprintf ( target + used , lmax - used,"<tr><td>Aditional space</td><td>%5u</td></tr>\n", b->sec1.length - 22 );
  if ( b->tables->b.path[0] )
    {
      used += snprintf ( target + used , lmax - used,"<tr><td>Tables used</td><td>'%s'<br>\n", b->tables->b.path );
      used += snprintf ( target + used , lmax - used,"'%s'<br>\n", b->tables->c.path );
      used += snprintf ( target + used , lmax - used,"'%s'</td></tr>\n", b->tables->d.path );
    }
  used += snprintf ( target + used , lmax - used,"</table>\n" );
  used += snprintf ( target + used , lmax - used,"</div>\n" );
  return 0;
}
References bufr_tables::b, bufrdeco_assert, bufr_tables::c, bufr_sec1::category, bufr_sec1::centre, bufr_tables::d, bufr_sec1::day, bufr_sec0::edition, bufr_sec1::hour, bufr_sec1::length, bufr_sec1::master, bufr_sec1::master_local, bufr_sec1::master_version, bufr_sec1::minute, bufr_sec1::month, bufr_sec1::options, bufr_tableB::path, bufr_tableC::path, bufr_tableD::path, bufrdeco::sec0, bufrdeco::sec1, bufr_sec1::second, bufr_sec1::subcategory, bufr_sec1::subcategory_local, bufr_sec1::subcentre, bufrdeco::tables, bufr_sec1::update, and bufr_sec1::year.
Referenced by sprint_sec1_info().
sprint_sec3_info_html()
int sprint_sec3_info_html (char * target, size_t lmax, struct bufrdeco * b)
Prints info from sec3 formatted as html.
Parameters
target string target
lmax available size in target
b pointer to the source struct bufrdeco
Returns
If succeeded return 0
Definition at line 104 of file bufrdeco_print_html.c.
{
  size_t i;
  size_t used = 0;
  bufrdeco_assert ( b != NULL && lmax != 0 && target != NULL );
  used += snprintf ( target + used , lmax - used,"<div class='bufr_sec3'>\n" );
  used += snprintf ( target + used , lmax - used,"<table>\n<caption>SEC 3 INFO</caption>\n" );
  used += snprintf ( target + used , lmax - used,"<tr><td>Sec3 length</td><td>%5u\n", b->sec3.length );
  used += snprintf ( target + used , lmax - used,"<tr><td>Subsets</td><td>%5u\n", b->sec3.subsets );
  used += snprintf ( target + used , lmax - used,"<tr><td>Observed</td><td>%5u\n", b->sec3.observed );
  used += snprintf ( target + used , lmax - used,"<tr><td>Compressed</td><td>%5u\n", b->sec3.compressed );
  used += snprintf ( target + used , lmax - used,"<tr><td>Unexpanded descriptors</td><td>%5u</td></tr>\n", b->sec3.ndesc );
  for ( i = 0; i < b->sec3.ndesc; i++ )
    {
      used += snprintf ( target + used , lmax - used,"<tr><td>%3lu:</td><td>%u %02u %03u</td></tr>\n", i, b->sec3.unexpanded[i].f,
                     b->sec3.unexpanded[i].x, b->sec3.unexpanded[i].y );
    }
  used += snprintf ( target + used , lmax - used,"</table>\n" );
  used += snprintf ( target + used , lmax - used,"</div>\n" );
  return 0;
}
References bufrdeco_assert, bufr_sec3::compressed, bufr_descriptor::f, bufr_sec3::length, bufr_sec3::ndesc, bufr_sec3::observed, bufrdeco::sec3, bufr_sec3::subsets, bufr_sec3::unexpanded, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by sprint_sec3_info().
sprint_sec4_info_html()
int sprint_sec4_info_html (char * target, size_t lmax, struct bufrdeco * b)
Prints info from sec4.
Parameters
target string target
lmax available size in target
b pointer to the source struct bufrdeco
Returns
If succeeded return 0, 1 otherwise
Definition at line 136 of file bufrdeco_print_html.c.
{
  size_t used = 0;
  bufrdeco_assert ( b != NULL && lmax != 0 && target != NULL );
  used += snprintf ( target + used , lmax - used,"<div class='bufr_sec4'>\n" );
  used += snprintf ( target + used , lmax - used,"<table>\n<caption>SEC 4 INFO</caption>\n" );
  used += snprintf ( target + used , lmax - used,"<tr><td>Sec4 length</td><td>%5u</td></tr>\n", b->sec4.length );
  used += snprintf ( target + used , lmax - used,"</table>\n" );
  used += snprintf ( target + used , lmax - used,"</div>\n" );
  return 0;
}
References bufrdeco_assert, bufr_sec4::length, and bufrdeco::sec4.
Referenced by sprint_sec4_info().