bufr2synop: src/bufrdeco/bufrdeco.c File Reference
bufrdeco.c File Reference
This file has the code for library bufrdeco API functions.
#include "config.h"
#include "bufrdeco.h"
Macros
#define CONFIG_H
Functions
char * bufrdeco_get_version (char *version, size_t dversion, char *build, size_t dbuild, char *builder, size_t dbuilder, int *version_major, int *version_minor, int *version_patch)
int bufrdeco_parse_tree (struct bufrdeco *b)
Parse the tree of descriptors without expand the replicators.
int bufrdeco_init (struct bufrdeco *b)
Inits and allocate memory for a struct bufrdeco.
int bufrdeco_reset (struct bufrdeco *b)
Reset an struct bufrdeco. This is needed when changing to another bufr.
int bufrdeco_close (struct bufrdeco *b)
Free all allocated memory. Needed when no more task to do with bufrdeco library.
int bufrdeco_set_tables_dir (struct bufrdeco *b, char *tables_dir)
Sets the directory path for BUFR tables. Needed if it is not any default directories.
int bufrdeco_get_bufr (struct bufrdeco *b, char *filename)
Read file and try to find a bufr report inserted in. Once found do the same that bufrdeco_read_bufr()
int bufrdeco_write_subset_offset_bits (struct bufrdeco *b, char *filename)
Write offset bit array for subsets in a non-compressed bufr.
int bufrdeco_read_subset_offset_bits (struct bufrdeco *b, char *filename)
Write offset bit array for subsets in a non-compressed bufr.
struct bufrdeco_subset_sequence_data * bufrdeco_get_target_subset_sequence_data (buf_t nset, struct bufrdeco *b)
Prepare the struct.
Detailed Description
This file has the code for library bufrdeco API functions.
Definition in file bufrdeco.c.
Macro Definition Documentation
CONFIG_H
#define CONFIG_H
Definition at line 26 of file bufrdeco.c.
Function Documentation
bufrdeco_close()
int bufrdeco_close (struct bufrdeco * b)
Free all allocated memory. Needed when no more task to do with bufrdeco library.
Parameters
b pointer to the target struct
This function must be called at the end when no more calls to bufrdeco library is needed
If succeeded return 0, otherwise 1
Definition at line 220 of file bufrdeco.c.
{
  bufrdeco_assert ( b != NULL );
  // first deallocate all memory
  bufrdeco_free_subset_sequence_data ( & ( b->seq ) );
  bufrdeco_free_compressed_data_references ( & ( b->refs ) );
  bufrdeco_free_expanded_tree ( & ( b->tree ) );
  if (b->mask & BUFRDECO_USE_TABLES_CACHE)
  {
    bufrdeco_free_cache_tables(&(b->cache));
    b->tables = 0;
  }
  else
  {
    bufrdeco_free_tables ( & ( b->tables ) );
  }
  bufrdeco_free_bitmap_array ( & ( b->bitmap ) );
  return 0;
}
References bufrdeco::bitmap, bufrdeco_assert, bufrdeco_free_bitmap_array(), bufrdeco_free_cache_tables(), bufrdeco_free_compressed_data_references(), bufrdeco_free_expanded_tree(), bufrdeco_free_subset_sequence_data(), bufrdeco_free_tables(), BUFRDECO_USE_TABLES_CACHE, bufrdeco::cache, bufrdeco::mask, bufrdeco::refs, bufrdeco::seq, bufrdeco::tables, and bufrdeco::tree.
Referenced by main().
bufrdeco_get_bufr()
int bufrdeco_get_bufr (struct bufrdeco * b, char * filename)
Read file and try to find a bufr report inserted in. Once found do the same that bufrdeco_read_bufr()
Parameters
b pointer to struct bufrdeco
filename complete path of BUFR file
This function does the folowing tasks:
Try to find first buffer of bytes begining with 'BUFR' chars and ending with '7777'. This will be considered as a bufr file.
Read the file and checks the marks at the begining and end to see wheter is a BUFR file
Init the structs and allocate the needed memory for raw data if not done previously
Splits and parse the BUFR sections (without expanding descriptors nor parsing data)
Reads the needed Table files and store them in memory.
Returns 0 if all is OK, 1 otherwise
Definition at line 275 of file bufrdeco.c.
{
  bufrdeco_assert_with_return_val ( b != NULL || filename == NULL, 1 );
  return bufrdeco_extract_bufr ( b, filename );
}
References bufrdeco_assert_with_return_val, and bufrdeco_extract_bufr().
bufrdeco_get_target_subset_sequence_data()
struct bufrdeco_subset_sequence_data * bufrdeco_get_target_subset_sequence_data (buf_t nset, struct bufrdeco * b)
Prepare the struct.
Definition at line 354 of file bufrdeco.c.
{
  buf_t n = 0;
  bufrdeco_assert ( b != NULL );
  if ( b->sec3.subsets <= nset )
    {
      snprintf ( b->error, sizeof ( b->error ), "%s(): The index of target subset is over the bufr subsets (%d)\n", __func__, b->sec3.subsets );
      return NULL;
    }
  if ( b->sec3.compressed )
    {
#ifdef __DEBUG
      printf ("# Compressed\n");
#endif
      // case of compressed, we just need the compressed references
      if ( b->refs.nd == 0 )
        {
          // case of compressed data and still not parsed the refs
          if ( bufrdeco_parse_compressed ( & ( b->refs ), b ) )
            {
              return NULL;
            }
        }
    }
  else if ( nset > 0 )
    {
      // In case of not compressed bufr, to parse a subset we need to know the bit offset of the subset data in sec4
      // There are only two ways to know that offset:
      //    1) Parse the data of all prior subsets from n = 0 to (nset - 1).
      //    2) Get the subset bit offset from the struct bufrdeco_subset_bit_offset already stored.
      //       This is only possible if we already parsed this subset in this session (among two bufrdeco_reset() calls)
      //       or if readed the struct from a file
      // In any case the subset bit offset array must be poluted for all n < (nset - 1)
      if ( b->offsets.nr == 0 || b->offsets.ofs[nset] == 0 )
        {
          for ( n = b->state.subset ; n < nset ; n++ )
            {
              // In every call to bufrdeco_decode_data_subset(), b->state.subset is incremented and b->offsets is updated if needed
#ifdef __DEBUG
              printf ("# Go to parse for subset %lu waiting %lu\n", b->state.subset, nset);
#endif
              bufrdeco_decode_data_subset ( b );
            }
        }
    }
  // Once the previous task is made, we just adjust the subset
  b->state.subset = nset;
  // and now parse and get the desired subset data
#ifdef __DEBUG
  printf ("# Finally going to target parse for subset %lu\n", b->state.subset);
#endif
  return bufrdeco_get_subset_sequence_data ( b );
}
References bufrdeco_assert, bufrdeco_decode_data_subset(), bufrdeco_get_subset_sequence_data(), bufrdeco_parse_compressed(), bufr_sec3::compressed, bufrdeco::error, bufrdeco_compressed_data_references::nd, bufrdeco_subset_bit_offsets::nr, bufrdeco::offsets, bufrdeco_subset_bit_offsets::ofs, bufrdeco::refs, bufrdeco::sec3, bufrdeco::state, bufrdeco_decoding_data_state::subset, and bufr_sec3::subsets.
Referenced by main().
bufrdeco_get_version()
char * bufrdeco_get_version (char * version, size_t dversion, char * build, size_t dbuild, char * builder, size_t dbuilder, int * version_major, int * version_minor, int * version_patch)
Definition at line 50 of file bufrdeco.c.
{
  int major = 0, minor = 0, patch = 0;
  size_t used;
  // Check argument
  if ( version == NULL )
    return NULL;
  snprintf ( version, dversion, "%s", VERSION );
  // default
  sscanf ( version, "%d.%d.%d", &major, &minor, &patch );
  if ( build )
    {
      used = 0;
#if defined(__INTEL_COMPILER)
      used += snprintf ( build + used, dbuild - used, "using INTEL C compiler icc %d.%d ", __INTEL_COMPILER, __INTEL_COMPILER_UPDATE );
#elif defined(__clang_version__)
      used += snprintf ( build + used, dbuild - used, "using clang C compiler ", __clang_version__ );
#elif defined(__GNUC__)
      used += snprintf ( build + used, dbuild - used, "using GNU C compiler gcc %d.%d.%d ", __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__ );
#elif defined(_MSC_VER)
      used += snprintf ( build + used, dbuild - used, "using MICROSOFT C compiler %d ", _MSC_VER );
#else
      used += snprintf ( build + used, dbuild - used, "using an unknown C compiler " );
#endif
      snprintf ( build + used, dbuild - used,"at %s %s",__DATE__,__TIME__ );
    }
  if ( builder )
#ifdef BUILD_USING_CMAKE
    strncpy_safe ( builder, "cmake", dbuilder );
#else
    strncpy_safe ( builder, "autotools", dbuilder );
#endif
  if ( version_major )
    *version_major = major;
  if ( version_minor )
    *version_minor = minor;
  if ( version_patch )
    *version_patch = patch;
  return version;
}
References strncpy_safe, and VERSION.
Referenced by bufrtotac_print_version().
bufrdeco_init()
int bufrdeco_init (struct bufrdeco * b)
Inits and allocate memory for a struct bufrdeco.
Parameters
b pointer to the target struct
This function only must be called once. When finished the function bufrdeco_close must be called to free all needed memory
If succeeded return 0, otherwise 1
Definition at line 138 of file bufrdeco.c.
{
  bufrdeco_assert ( b != NULL );
  // First clear all
  memset ( b, 0, sizeof ( struct bufrdeco ) );
  // Then allocate all needed memory when starting. Further we will need to allocate some more depending on
  // data
  // allocate memory for Tables
  if ( bufrdeco_init_tables ( &b->tables ) )
    {
      snprintf ( b->error, sizeof ( b->error ),"%s(): Cannot allocate space for tables\n", __func__ );
      return 1;
    }
  // allocate memory for expanded tree of descriptors
  if ( bufrdeco_init_expanded_tree ( &b->tree ) )
    {
      snprintf ( b->error, sizeof ( b->error ),"%s(): Cannot allocate space for expanded tree of descriptors\n", __func__ );
      return 1;
    }
  return 0;
}
References bufrdeco_assert, bufrdeco_init_expanded_tree(), bufrdeco_init_tables(), bufrdeco::error, bufrdeco::tables, and bufrdeco::tree.
Referenced by main().
bufrdeco_parse_tree()
int bufrdeco_parse_tree (struct bufrdeco * b)
Parse the tree of descriptors without expand the replicators.
Parameters
b Pointer to the source struct bufrdeco
This is the user function to parse the descriptor structure of a BUFR report. This is the first task we need to perform after read the bufr report with the aid of bufrdeco_read_bufr function.
At the end we will get an array of structs bufr_sequence defining the tree
A sequence layer is needed when parsing expanded descriptor sec3 and sec4
First bufr_sequence is the sequence of descriptors in sec3 after byte 8. This is a bufr_sequence in level 0.
When a sequence descriptor is found in a layer, the sequence entries found in table D form this descriptor is a son bufr_sequence. This son has then a father and also can have one or more sons. The index level is incremented by one every step it go into decendents.
And so we go in a recursive way up to the end.
If success return 0, if something went wrong return 1
Definition at line 120 of file bufrdeco.c.
{
  bufrdeco_assert ( b != NULL );
  // here we start the parse
  return  bufrdeco_parse_tree_recursive ( b, NULL, NULL );
}
References bufrdeco_assert, and bufrdeco_parse_tree_recursive().
Referenced by main().
bufrdeco_read_subset_offset_bits()
int bufrdeco_read_subset_offset_bits (struct bufrdeco * b, char * filename)
Write offset bit array for subsets in a non-compressed bufr.
Parameters
filename complete path of input file to open
b pointer to the struct bufrdeco
Definition at line 316 of file bufrdeco.c.
{
  struct stat st;
  FILE *f;
  // assert nice args
  bufrdeco_assert_with_return_val ( b != NULL || filename == NULL, 1 );
  // silently return if cannot stat the file
  if ( stat ( filename, &st ) < 0 )
    {
      return 1;
    }
  // open the file
  f = fopen ( filename, "r" );
  bufrdeco_assert_with_return_val ( f != NULL, 1 );
  // Read the offsets
  if ( bufr_read_subset_offset_bits ( f, & ( b->offsets ) ) )
    {
      fclose ( f );
      return 1;
    }
  fclose ( f );
  return 0;
}
References bufr_read_subset_offset_bits(), bufrdeco_assert_with_return_val, and bufrdeco::offsets.
Referenced by main().
bufrdeco_reset()
int bufrdeco_reset (struct bufrdeco * b)
Reset an struct bufrdeco. This is needed when changing to another bufr.
Parameters
b pointer to the target struct to be resed with another bufrfile
This function must be called when parsing another bufrfile without calling bufrdeco_close and bufrdeco_init. It
If succeeded return 0, otherwise 1
Definition at line 176 of file bufrdeco.c.
{
  struct bufr_tables *tb;
  struct bufr_tables_cache ch;
  uint32_t mask;
  bufrdeco_assert ( b != NULL );
  // save the data we do not reset
  memcpy(&ch, &b->cache, sizeof (struct bufr_tables_cache));
  tb = b->tables;
  mask = b->mask;
  bufrdeco_free_subset_sequence_data ( & ( b->seq ) );
  bufrdeco_free_compressed_data_references ( & ( b->refs ) );
  bufrdeco_free_expanded_tree ( & ( b->tree ) );
  bufrdeco_free_bitmap_array ( & ( b->bitmap ) );
  memset ( b, 0, sizeof ( struct bufrdeco ) );
  // Restore data
  b->mask = mask;
  b->tables = tb;
  memcpy(&b->cache, &ch, sizeof (struct bufr_tables_cache));
  // allocate memory for expanded tree of descriptors
  if ( bufrdeco_init_expanded_tree ( &b->tree ) )
    {
      snprintf ( b->error, sizeof ( b->error ),"%s(): Cannot allocate space for expanded tree of descriptors\n", __func__ );
      return 1;
    }
  return 0;
}
References bufrdeco::bitmap, bufrdeco_assert, bufrdeco_free_bitmap_array(), bufrdeco_free_compressed_data_references(), bufrdeco_free_expanded_tree(), bufrdeco_free_subset_sequence_data(), bufrdeco_init_expanded_tree(), bufrdeco::cache, bufrdeco::error, bufrdeco::mask, bufrdeco::refs, bufrdeco::seq, bufrdeco::tables, and bufrdeco::tree.
Referenced by main().
bufrdeco_set_tables_dir()
int bufrdeco_set_tables_dir (struct bufrdeco * b, char * tables_dir)
Sets the directory path for BUFR tables. Needed if it is not any default directories.
Parameters
b pointer to the target struct
tables_dir Source path of tables directory
The default directories are '/usr/share/bufr2synop' and '/usr/local/share/bufr2synop'
Retuns 1 if problems, 0 otherwise
Definition at line 251 of file bufrdeco.c.
{
  bufrdeco_assert_with_return_val ( b != NULL || tables_dir == NULL, 1 );
  strncpy_safe ( b->bufrtables_dir, tables_dir, BUFRDECO_PATH_LENGTH );
  return 0;
}
References bufrdeco_assert_with_return_val, BUFRDECO_PATH_LENGTH, bufrdeco::bufrtables_dir, and strncpy_safe.
bufrdeco_write_subset_offset_bits()
int bufrdeco_write_subset_offset_bits (struct bufrdeco * b, char * filename)
Write offset bit array for subsets in a non-compressed bufr.
Parameters
filename complete path of output file to open
b pointer to the struct bufrdeco
Definition at line 289 of file bufrdeco.c.
{
  FILE *f;
  // assert nice args
  bufrdeco_assert_with_return_val ( b != NULL || filename == NULL, 1 );
  // open the file
  f = fopen ( filename, "w" );
  bufrdeco_assert_with_return_val ( f != NULL, 1 );
  // Read the offsets
  if ( bufr_write_subset_offset_bits ( f, & ( b->offsets ) ) )
    {
      fclose ( f );
      return 1;
    }
  fclose ( f );
  return 0;
}
References bufr_write_subset_offset_bits(), bufrdeco_assert_with_return_val, and bufrdeco::offsets.
Referenced by main().