bufr2synop: src/bufrdeco/bufrdeco_memory.c File Reference
bufrdeco_memory.c File Reference
This file has the memory stufs for library bufrdeco.
#include "bufrdeco.h"
Functions
int bufrdeco_init_tables (struct bufr_tables **t)
Init a struct bufr_tables allocating space.
int bufrdeco_free_tables (struct bufr_tables **t)
Frees the allocated space for a struct bufr_tables.
int bufrdeco_init_expanded_tree (struct bufrdeco_expanded_tree **t)
Init a struct bufrdeco_expanded_tree allocating space.
int bufrdeco_free_expanded_tree (struct bufrdeco_expanded_tree **t)
Frees the allocated space for a struct bufrdeco_expanded_tree.
int bufrdeco_substitute_tables (struct bufr_tables **replaced, struct bufr_tables *source, struct bufrdeco *b)
substitute an struct bufr_tables into a struct bufrdeco
int bufrdeco_init_subset_sequence_data (struct bufrdeco_subset_sequence_data *ba)
Init a struct bufrdeco_subset_sequence_data.
int bufrdeco_clean_subset_sequence_data (struct bufrdeco_subset_sequence_data *ba)
Cleans a struct bufrdeco_subset_sequence_data.
int bufrdeco_free_subset_sequence_data (struct bufrdeco_subset_sequence_data *ba)
Free the memory for sequence array in a struct bufrdeco_subset_sequence_data.
int bufrdeco_init_compressed_data_references (struct bufrdeco_compressed_data_references *rf)
Init a struct bufrdeco_compressed_data_references.
int bufrdeco_clean_compressed_data_references (struct bufrdeco_compressed_data_references *rf)
Clean a struct bufrdeco_compressed_data_references.
int bufrdeco_free_compressed_data_references (struct bufrdeco_compressed_data_references *rf)
Free the memory allocated for array of references in a struct bufrdeco_compressed_data_references.
int bufrdeco_init (struct bufrdeco *b)
Inits and allocate memory for a struct bufrdeco.
int bufrdeco_reset (struct bufrdeco *b)
Reset an struct bufrdeco to be resed with another bufrfile.
int bufrdeco_close (struct bufrdeco *b)
Free all allocated memory.
int bufrdeco_allocate_bitmap (struct bufrdeco *b)
int bufrdeco_clean_bitmaps (struct bufrdeco *b)
int bufrdeco_free_bitmap_array (struct bufrdeco_bitmap_array *a)
Detailed Description
This file has the memory stufs for library bufrdeco.
Definition in file bufrdeco_memory.c.
Function Documentation
bufrdeco_allocate_bitmap()
int bufrdeco_allocate_bitmap (struct bufrdeco * b)
Definition at line 318 of file bufrdeco_memory.c.
{
  size_t nba = b->bitmap.nba;
  if ( nba < BUFR_MAX_BITMAPS )
    {
      if ( b->bitmap.bmap[nba] != NULL )
        {
          // the bitmap already is allocated
          return 0;
        }
      // let's try to allocate it!
      if ( ( b->bitmap.bmap[nba] = ( struct bufrdeco_bitmap * ) calloc ( 1, sizeof ( struct bufrdeco_bitmap ) ) ) == NULL )
        {
          sprintf ( b->error,"bufrdeco_allocate_bitmap(): Cannot allocate space for struct bufrdeco_bitmap\n" );
          return 1;
        }
      // Update de counter
      ( b->bitmap.nba )++;
      return 0;
    }
  else
    {
      sprintf ( b->error,"bufrdeco_allocate_bitmap(): Too much bitmaps to allocate. The limit is %d\n" , BUFR_MAX_BITMAPS );
      return 1;
    }
}
References bufrdeco::bitmap, bufrdeco_bitmap_array::bmap, BUFR_MAX_BITMAPS, bufrdeco::error, and bufrdeco_bitmap_array::nba.
Referenced by bufrdeco_parse_f2_compressed(), and bufrdeco_parse_f2_descriptor().
bufrdeco_clean_bitmaps()
int bufrdeco_clean_bitmaps (struct bufrdeco * b)
Definition at line 349 of file bufrdeco_memory.c.
{
  size_t i;
  for ( i = 0; i < b->bitmap.nba ; i++ )
    {
      if ( b->bitmap.bmap[i] == NULL )
        continue;
      memset ( b->bitmap.bmap[i] , 0 , sizeof ( struct bufrdeco_bitmap ) );
    }
  b->bitmap.nba = 0;
  return 0;
}
References bufrdeco::bitmap, bufrdeco_bitmap_array::bmap, and bufrdeco_bitmap_array::nba.
Referenced by bufrdeco_decode_data_subset().
bufrdeco_clean_compressed_data_references()
int bufrdeco_clean_compressed_data_references (struct bufrdeco_compressed_data_references * rf)
Clean a struct bufrdeco_compressed_data_references.
Definition at line 215 of file bufrdeco_memory.c.
{
  if ( rf->refs != NULL && rf->nd != 0 )
    rf->nd = 0;
  else
    return bufrdeco_init_compressed_data_references ( rf );
  return 0;
}
References bufrdeco_init_compressed_data_references(), bufrdeco_compressed_data_references::nd, and bufrdeco_compressed_data_references::refs.
bufrdeco_clean_subset_sequence_data()
int bufrdeco_clean_subset_sequence_data (struct bufrdeco_subset_sequence_data * ba)
Cleans a struct bufrdeco_subset_sequence_data.
For eficience, if sequence in the struct bufrdeco_subset_sequence_data is allocated, just set the used elements to zero. If is still no allocated memory for sequence inits the struct
Returns 0 if succeeded, 1 otherwise
Definition at line 153 of file bufrdeco_memory.c.
{
  if ( ba->sequence != NULL )
    {
      ba->nd = 0;
      return 0;
    }
  else
    return bufrdeco_init_subset_sequence_data ( ba );
}
References bufrdeco_init_subset_sequence_data(), bufrdeco_subset_sequence_data::nd, and bufrdeco_subset_sequence_data::sequence.
Referenced by bufrdeco_decode_data_subset().
bufrdeco_close()
int bufrdeco_close (struct bufrdeco * b)
Free all allocated memory.
Parameters
b pointer to the target struct
This function must be called at the end when no more calls to bufrdeco library is needed
Definition at line 307 of file bufrdeco_memory.c.
{
  // first deallocate all memory
  bufrdeco_free_subset_sequence_data ( & ( b->seq ) );
  bufrdeco_free_compressed_data_references ( & ( b->refs ) );
  bufrdeco_free_expanded_tree ( & ( b->tree ) );
  bufrdeco_free_tables ( & ( b->tables ) );
  bufrdeco_free_bitmap_array ( & ( b->bitmap ) );
  return 0;
}
References bufrdeco::bitmap, bufrdeco_free_bitmap_array(), bufrdeco_free_compressed_data_references(), bufrdeco_free_expanded_tree(), bufrdeco_free_subset_sequence_data(), bufrdeco_free_tables(), bufrdeco::refs, bufrdeco::seq, bufrdeco::tables, and bufrdeco::tree.
Referenced by main().
bufrdeco_free_bitmap_array()
int bufrdeco_free_bitmap_array (struct bufrdeco_bitmap_array * a)
Definition at line 364 of file bufrdeco_memory.c.
{
  size_t i;
  for ( i = 0; i < a->nba ; i++ )
    {
      if ( a->bmap[i] == NULL )
        continue;
      free ( ( void* ) a->bmap[i] );
      a->bmap[i] = NULL;
    }
  a->nba = 0;
  return 0;
}
References bufrdeco_bitmap_array::bmap, and bufrdeco_bitmap_array::nba.
Referenced by bufrdeco_close().
bufrdeco_free_compressed_data_references()
int bufrdeco_free_compressed_data_references (struct bufrdeco_compressed_data_references * rf)
Free the memory allocated for array of references in a struct bufrdeco_compressed_data_references.
Returns 0
Definition at line 230 of file bufrdeco_memory.c.
{
  if ( rf->refs != NULL )
    {
      free ( ( void * ) rf->refs );
      rf->refs = NULL;
    }
  return 0;
}
References bufrdeco_compressed_data_references::refs.
Referenced by bufrdeco_close().
bufrdeco_free_expanded_tree()
int bufrdeco_free_expanded_tree (struct bufrdeco_expanded_tree ** t)
Frees the allocated space for a struct bufrdeco_expanded_tree.
Parameters
t pointer to the target pointer to struct bufrdeco_expanded_tree
Returns 0 and *t is set to NULL
Definition at line 85 of file bufrdeco_memory.c.
{
  if ( *t != NULL )
    {
      free ( ( void * ) *t );
      *t = NULL;
    }
  return 0;
}
Referenced by bufrdeco_close().
bufrdeco_free_subset_sequence_data()
int bufrdeco_free_subset_sequence_data (struct bufrdeco_subset_sequence_data * ba)
Free the memory for sequence array in a struct bufrdeco_subset_sequence_data.
Parameters
ba pointer to the target struct to free
Returns 0
Definition at line 171 of file bufrdeco_memory.c.
{
  if ( ba->sequence != NULL )
    {
      free ( ( void * ) ba->sequence );
      ba->sequence = NULL;
    }
  return 0;
}
References bufrdeco_subset_sequence_data::sequence.
Referenced by bufrdeco_close().
bufrdeco_free_tables()
int bufrdeco_free_tables (struct bufr_tables ** t)
Frees the allocated space for a struct bufr_tables.
Parameters
t pointer to the target pointer to struct bufr_tables
Returns 0 and *t is set to NULL
Definition at line 51 of file bufrdeco_memory.c.
{
  if ( *t != NULL )
    {
      free ( ( void * ) *t );
      *t = NULL;
    }
  return 0;
}
Referenced by bufrdeco_close().
bufrdeco_init()
int bufrdeco_init (struct bufrdeco * b)
Inits and allocate memory for a struct bufrdeco.
Parameters
b pointer to the target struct
This function only must be called once. When finished the function bufrdeco_close must be called to free all needed memory
Definition at line 248 of file bufrdeco_memory.c.
{
  if ( b == NULL )
    return 1;
  // First clear all
  memset ( b, 0, sizeof ( struct bufrdeco ) );
  // Then allocate all needed memory when starting. Further we will need to allocate some more depending on
  // data
  // allocate memory for Tables
  if ( bufrdeco_init_tables ( &b->tables ) )
    {
      sprintf ( b->error,"bufrdeco_init(): Cannot allocate space for tables\n" );
      return 1;
    }
  // allocate memory for expanded tree of descriptors
  if ( bufrdeco_init_expanded_tree ( &b->tree ) )
    {
      sprintf ( b->error,"bufrdeco_init(): Cannot allocate space for expanded tree of descriptors\n" );
      return 1;
    }
  return 0;
}
References bufrdeco_init_expanded_tree(), bufrdeco_init_tables(), bufrdeco::error, bufrdeco::tables, and bufrdeco::tree.
Referenced by main().
bufrdeco_init_compressed_data_references()
int bufrdeco_init_compressed_data_references (struct bufrdeco_compressed_data_references * rf)
Init a struct bufrdeco_compressed_data_references.
Parameters
rf pointer ti the target struct
If already memory is allocated for array of references then just adjust the used index to zero. Otherwise it allocate the needed memory and init the struct
If succeeded return 0, otherwise 1
Definition at line 191 of file bufrdeco_memory.c.
{
  if ( rf->refs != NULL && rf->dim != 0 )
    {
      rf->nd = 0;
    }
  else if ( rf->refs == NULL )
    {
      if ( ( rf->refs = ( struct bufrdeco_compressed_ref * ) calloc ( 1, BUFR_NMAXSEQ * sizeof ( struct bufrdeco_compressed_ref ) ) ) == NULL )
        {
          fprintf ( stderr,"bufr_init_compressed_data_references():Cannot allocate memory for bufrdeco_compressed_ref array\n" );
          return 1;
        }
      rf->nd = 0;
      rf->dim = BUFR_NMAXSEQ;
    }
  return 0;
}
References BUFR_NMAXSEQ, bufrdeco_compressed_data_references::dim, bufrdeco_compressed_data_references::nd, and bufrdeco_compressed_data_references::refs.
Referenced by bufrdeco_clean_compressed_data_references(), and bufrdeco_parse_compressed().
bufrdeco_init_expanded_tree()
int bufrdeco_init_expanded_tree (struct bufrdeco_expanded_tree ** t)
Init a struct bufrdeco_expanded_tree allocating space.
Parameters
t pointer to the target pointer to struct bufrdeco_expanded_tree
Returns 0 if succeeded, 1 otherwise
Definition at line 68 of file bufrdeco_memory.c.
{
  if ( *t != NULL )
    free ( ( void * ) *t );
  if ( ( *t = ( struct bufrdeco_expanded_tree * ) calloc ( 1, sizeof ( struct bufrdeco_expanded_tree ) ) ) == NULL )
    return 1;
  return 0;
}
Referenced by bufrdeco_init().
bufrdeco_init_subset_sequence_data()
int bufrdeco_init_subset_sequence_data (struct bufrdeco_subset_sequence_data * ba)
Init a struct bufrdeco_subset_sequence_data.
Parameters
ba pointer to the target struct
It is supossed that no memory is allocated for sequence. If we are not sure better use function bufrdeco_clean_subset_sequence_data
Returns 0 if succeeded, 1 otherwise
Definition at line 132 of file bufrdeco_memory.c.
{
  memset ( ba, 0, sizeof ( struct bufrdeco_subset_sequence_data ) );
  if ( ( ba->sequence = ( struct bufr_atom_data * ) calloc ( 1, BUFR_NMAXSEQ * sizeof ( struct bufr_atom_data ) ) ) == NULL )
    {
      fprintf ( stderr,"bufr_init_subset_sequence_data():Cannot allocate memory for atom data array\n" );
      return 1;
    }
  ba->dim = BUFR_NMAXSEQ;
  return 0;
}
References BUFR_NMAXSEQ, bufrdeco_subset_sequence_data::dim, and bufrdeco_subset_sequence_data::sequence.
Referenced by bufrdeco_clean_subset_sequence_data().
bufrdeco_init_tables()
int bufrdeco_init_tables (struct bufr_tables ** t)
Init a struct bufr_tables allocating space.
Parameters
t pointer to the target pointer to struct bufr_tables
Returns 0 if succeeded, 1 otherwise
Definition at line 33 of file bufrdeco_memory.c.
{
  if ( *t != NULL )
    free ( ( void * ) *t );
  if ( ( *t = ( struct bufr_tables * ) calloc ( 1, sizeof ( struct bufr_tables ) ) ) == NULL )
    return 1;
  return 0;
}
Referenced by bufr_read_tables_ecmwf(), bufr_read_tables_wmo(), bufrdeco_init(), and bufrdeco_substitute_tables().
bufrdeco_reset()
int bufrdeco_reset (struct bufrdeco * b)
Reset an struct bufrdeco to be resed with another bufrfile.
Parameters
b pointer to the target struct
This function must be called when parsing another bufrfile without callimg bufrdeco_close and bufrdeco_init.
Definition at line 285 of file bufrdeco_memory.c.
{
  memset ( & ( b->header ), 0, sizeof ( struct gts_header ) );
  memset ( & ( b->sec0 ), 0, sizeof ( struct bufr_sec0 ) );
  memset ( & ( b->sec1 ), 0, sizeof ( struct bufr_sec1 ) );
  memset ( & ( b->sec2 ), 0, sizeof ( struct bufr_sec2 ) );
  memset ( & ( b->sec3 ), 0, sizeof ( struct bufr_sec3 ) );
  memset ( & ( b->sec4 ), 0, sizeof ( struct bufr_sec4 ) );
  memset ( b->tree, 0, sizeof ( struct bufrdeco_expanded_tree ) );
  memset ( & ( b->state ), 0, sizeof ( struct bufrdeco_decoding_data_state ) );
  b->refs.nd = 0;
  b->seq.nd = 0;
  return 0;
}
References bufrdeco::header, bufrdeco_subset_sequence_data::nd, bufrdeco_compressed_data_references::nd, bufrdeco::refs, bufrdeco::sec0, bufrdeco::sec1, bufrdeco::sec2, bufrdeco::sec3, bufrdeco::sec4, bufrdeco::seq, bufrdeco::state, and bufrdeco::tree.
Referenced by main().
bufrdeco_substitute_tables()
int bufrdeco_substitute_tables (struct bufr_tables ** replaced, struct bufr_tables * source, struct bufrdeco * b)
substitute an struct bufr_tables into a struct bufrdeco
Parameters
replaced Pointer where to set the replaced pointer
source Pointer to a struct bufr_tables
b pointer to the container basic struct bufrdeco
Remember that the struct bufr_tables used in bufrdeco library is the one which pointer is in struct bufrdeco . To avoid problems the struct must be initialized before substituted in this fucntion. Both source and replaced structs are not modified.
This is useful if we do not want to read and parse tables again if the caller has a pool of already readed tables.
Definition at line 109 of file bufrdeco_memory.c.
{
  *replaced = b->tables;
  if ( source == NULL )
    {
      // allocate memory for table
      return bufrdeco_init_tables ( & ( b->tables ) );
    }
  else
    b->tables = source;
  return 0;
}
References bufrdeco_init_tables(), and bufrdeco::tables.