bufr2synop: src/libraries/bufr2syn.h File Reference
bufr2syn.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include "metsynop.h"
#include "metbuoy.h"
Data Structures
struct bufr_descriptor
BUFR descriptor.
struct bufr_atom_data
Contains all the information for a single descriptor in a expanded squence.
struct bufr_subset_sequence_data
Contains all the information for a subset in a expanded squence.
struct bufr_subset_state
stores information needed to parse a sequential list of expanded descriptors for a subset
struct gts_header
stores WMO GTS header info
struct met_datetime
stores date and time reference of a report, commonly the observation time
struct met_geo
Geographic meta information.
struct metreport
all the information for a meteorological report in WMO ascii format
Macros
#define _GNU_SOURCE
#define KELEM (8192)
max dimension of elements for a single report
#define KVALS (32768 * 512)
dimension of arrays of doubles. It must store all the data for all subset
#define KSUBS (KVALS / KELEM)
Maximum number of subset this version can manage.
#define BUFR_LEN 512000
max length of a bufrfile
#define BUFR_OBS_DATA_MASK 128
bit mask for Observed data
#define BUFR_COMPRESSED_DATA_MASK 64
bit mask for Observed data
#define MISSING_REAL (1.7e38)
The missing default value for real values.
#define MISSING_INTEGER (2147483647)
The missing default value for integer values.
#define MAXLINES_TABLEC (8192)
The maximum expected lines in a Table C file.
#define NMAXSEQ (16384)
Maximum expected descriptor in a expanded sequence for a single subset.
#define DESCRIPTOR_VALUE_MISSING (1)
Bit mask for a missing value in a struct bufr_atom_data.
#define DESCRIPTOR_HAVE_REAL_VALUE (2)
Bit mask for a real value in a struct bufr_atom_data.
#define DESCRIPTOR_HAVE_STRING_VALUE (4)
Bit mask for a string in a struct bufr_atom_data.
#define DESCRIPTOR_IS_CODE_TABLE (8)
Bit mask for a code table in a struct bufr_atom_data.
#define DESCRIPTOR_HAVE_CODE_TABLE_STRING (16)
Bit mask for a code table string in a struct bufr_atom_data.
#define DESCRIPTOR_HAVE_FLAG_TABLE_STRING (32)
Bit mask for a flag table string in a struct bufr_atom_data.
#define DESCRIPTOR_IS_FLAG_TABLE (64)
Bit mask for a flag table in a struct bufr_atom_data.
#define DESCRIPTOR_IS_A_REPLICATOR (128)
Bit mask for a flag table string in a struct bufr_atom_data.
#define SUBSET_MASK_LATITUDE_SOUTH (1)
Bit mask to mark a struct bufr_subset_sequence_data with south latitude.
#define SUBSET_MASK_LONGITUDE_WEST (2)
Bit mask to mark a struct bufr_subset_sequence_data with west longitude.
#define SUBSET_MASK_HAVE_TYPE_STATION (4)
Bit mask to mark a struct bufr_subset_sequence_data having type station information.
#define SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW (8)
Bit mask to mark a struct bufr_subset_sequence_data without WW information.
#define SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1 (16)
Bit mask to mark a struct bufr_subset_sequence_data without W1 information.
#define SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2 (32)
Bit mask to mark a struct bufr_subset_sequence_data without W1 information.
#define SUBSET_MASK_HAVE_LATITUDE (64)
Bit mask to mark a struct bufr_subset_sequence_data having latitude.
#define SUBSET_MASK_HAVE_LONGITUDE (128)
Bit mask to mark a struct bufr_subset_sequence_data having longitude.
#define SUBSET_MASK_HAVE_ALTITUDE (256)
Bit mask to mark a struct bufr_subset_sequence_data having altitude.
#define SUBSET_MASK_HAVE_NAME (512)
Bit mask to mark a struct bufr_subset_sequence_data having station name.
#define SUBSET_MASK_HAVE_COUNTRY (1024)
Bit mask to mark a struct bufr_subset_sequence_data having country name.
#define SUBSET_MASK_HAVE_YEAR (2048)
Bit mask to mark a struct bufr_subset_sequence_data having observation year.
#define SUBSET_MASK_HAVE_MONTH (4096)
Bit mask to mark a struct bufr_subset_sequence_data having observation month.
#define SUBSET_MASK_HAVE_DAY (8192)
Bit mask to mark a struct bufr_subset_sequence_data having observation day in a month.
#define SUBSET_MASK_HAVE_HOUR (16384)
Bit mask to mark a struct bufr_subset_sequence_data having observation hour.
#define SUBSET_MASK_HAVE_MINUTE (32768)
Bit mask to mark a struct bufr_subset_sequence_data having observation minute.
#define SUBSET_MASK_HAVE_GUST (65536)
Bit mask to mark a struct bufr_subset_sequence_data having wind gust observation other than 10 minutes.
Functions
void clean_buoy_chunks (struct buoy_chunks *b)
cleans a buoy_chunks struct
void clean_synop_chunks (struct synop_chunks *s)
cleans a synop_chunks struct
int set_environment (char *default_bufrtables, char *bufrtables_dir)
int integer_to_descriptor (struct bufr_descriptor *d, int id)
parse an integer with a descriptor fom bufr ECWMF libary
unsigned int three_bytes_to_uint (const unsigned char *source)
returns the integer value from an array of three bytes, most significant first
char * charray_to_string (char *s, unsigned char *buf, size_t size)
get a null termitated c-string from an array of unsigned chars
char * adjust_string (char *s)
Supress trailing blanks of a string.
char * get_explained_table_val (char *expl, size_t dim, char tablec[MAXLINES_TABLEC][92], size_t nlines_tablec, struct bufr_descriptor *d, int ival)
char * get_explained_flag_val (char *expl, size_t dim, char tablec[MAXLINES_TABLEC][92], size_t nlines_tablec, struct bufr_descriptor *d, unsigned long ival)
char * get_ecmwf_tablename (char *target, char type, char *bufrtables_dir, int ksec1[40])
Get the complete pathname of a table file needed by a bufr message.
char * get_bufrfile_path (char *filename, char *err)
Get bufr file names to parse.
int parse_subset_as_buoy (struct metreport *m, struct buoy_chunks *b, struct bufr_subset_state *s, struct bufr_subset_sequence_data *sq, char *err)
int parse_subset_as_synop (struct metreport *m, struct synop_chunks *syn, struct bufr_subset_state *s, struct bufr_subset_sequence_data *sq, char *err)
int YYYYMMDDHHmm_to_met_datetime (struct met_datetime *t, const char *source)
Parse the string YYYYMMDDHHmm and set a struct met_datetime.
int synop_YYYYMMDDHHmm_to_YYGG (struct synop_chunks *syn)
Sets YYGG from YYYYMMDDHHmm extended group.
int buoy_YYYYMMDDHHmm_to_JMMYYGGgg (struct buoy_chunks *b)
Sets YYGG from YYYYMMDDHHmm extended group.
char * guess_WMO_region (struct synop_chunks *syn)
Try to find WMO region if it is not already set and WMO Block and number index are known.
int read_table_c (char tablec[MAXLINES_TABLEC][92], size_t *nlines_tablec, char *bufrtables_dir, int ksec1[40])
int parse_subset_sequence (struct metreport *m, struct bufr_subset_sequence_data *sq, struct bufr_subset_state *st, struct synop_chunks *synop, struct buoy_chunks *buoy, int *kdtlst, size_t nlst, int *ksec1, char *err)
int find_descriptor (int *haystack, size_t nlst, int needle)
Try to find a descriptor in an array.
int find_descriptor_interval (int *haystack, size_t nlst, int needlemin, int needlemax)
int bufr_set_environment (char *default_bufrtables, char *bufrtables_dir)
set the environment vars needed to work properly with ECMWF bufrdc library
int guess_gts_header (struct gts_header *h, const char *f)
Guess the WMO GTS header from filename.
int read_bufr (unsigned char *bufr, char *filename, int *length)
read a bufr file as an array of unsigned chars
char * latlon_to_MMM (char *target, double lat, double lon)
convert latitude and longitude to a MMM string
char * kelvin_to_TTTT (char *target, double T)
converts a kelvin temperature value into a TTTT string
char * kelvin_to_snTTT (char *target, double T)
converts a kelvin temperature value into a snTTT string
char * kelvin_to_snTT (char *target, double T)
converts a kelvin temperature value into a snTT string
char * kelvin_to_TT (char *target, double T)
converts a kelvin temperature value into a TT string
char * m_to_h (char *target, double h)
converts the altitude of cloud layer into h string code
char * m_to_hh (char *target, double h)
converts the altitude of cloud layer into hh string code
char * pascal_to_ppp (char *target, double P)
Converts pascal values (variation) into a ppp string.
char * pascal_to_PPPP (char *target, double P)
Converts pascal values into a PPPP string.
char * percent_to_okta (char *target, double perc)
Converts percent cloud cover into okta.
char * prec_to_RRR (char *target, double r)
converts a precipitation in Kg/m2 into a RRR string
char * prec_to_RRRR24 (char *target, double r)
converts a precipitation in Kg/m2 into a RRRR24 string
char * secs_to_tt (char *tt, int secs)
char * vism_to_VV (char *target, double V)
Convert horizontal visibilty in meters to a VV string.
int print_synop (char *report, size_t lmax, struct synop_chunks *syn)
prints a synop into a string
char * print_synop_sec0 (char **sec0, size_t lmax, struct synop_chunks *syn)
Prints the synop section 0 (header)
char * print_synop_sec1 (char **sec1, size_t lmax, struct synop_chunks *syn)
Prints the synop section 1.
char * print_synop_sec2 (char **sec2, size_t lmax, struct synop_chunks *syn)
Prints the synop section 2.
char * print_synop_sec3 (char **sec3, size_t lmax, struct synop_chunks *syn)
Prints the synop section 3.
int print_buoy (char *report, size_t lmax, struct buoy_chunks *syn)
prints a buoy into a string
char * print_buoy_sec0 (char **sec0, size_t lmax, struct buoy_chunks *syn)
Prints the buoy section 1.
char * print_buoy_sec1 (char **sec1, size_t lmax, struct buoy_chunks *syn)
Prints the buoy section 1.
char * print_buoy_sec2 (char **sec2, size_t lmax, struct buoy_chunks *syn)
Prints the buoy section 1.
char * print_buoy_sec3 (char **sec3, size_t lmax, struct buoy_chunks *syn)
Prints the buoy section 3.
int print_csv (FILE *f, struct metreport *m)
prints a struct metreport in labeled csv format
int print_json (FILE *f, struct metreport *m)
prints a struct metreport in json format
int print_xml (FILE *f, struct metreport *m)
prints a struct metreport in xml format
int syn_parse_x01 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 01.
int syn_parse_x02 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 02.
int syn_parse_x04 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 04.
int syn_parse_x05 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 05.
int syn_parse_x06 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 06.
int syn_parse_x07 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 07.
int syn_parse_x08 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 08.
int syn_parse_x10 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 10.
int syn_parse_x11 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 11.
int syn_parse_x12 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 12.
int syn_parse_x13 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 13.
int syn_parse_x14 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 14.
int syn_parse_x20 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 20.
int syn_parse_x22 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 01.
int syn_parse_x31 (struct synop_chunks *syn, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 31.
int buoy_parse_x01 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 01.
int buoy_parse_x02 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 02.
int buoy_parse_x04 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 04.
int buoy_parse_x05 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 05.
int buoy_parse_x06 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 06.
int buoy_parse_x07 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 07.
int buoy_parse_x08 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 08.
int buoy_parse_x10 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 10.
int buoy_parse_x11 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 11.
int buoy_parse_x12 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 12.
int buoy_parse_x13 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 13.
int buoy_parse_x14 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 14.
int buoy_parse_x20 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 20.
int buoy_parse_x22 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 22.
int buoy_parse_x31 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 31.
int buoy_parse_x33 (struct buoy_chunks *b, struct bufr_subset_state *s)
Parse a expanded descriptor with X = 33.
int bus012_ (int *, unsigned int *, int *, int *, int *, int *, int *)
int buprs0_ (int *)
int buprs1_ (int *)
int buprs3_ (int *, int *, int *, int *, int *, int *, char **)
int bufrex_ (int *, int *, int *, int *, int *, int *, int *, int *, int *, char **, char **, int *, double *, char **, int *)
int busel_ (int *, int *, int *, int *, int *)
int busel2_ (int *, int *, int *, char **, int *, char **, char **, char **, int *)
int buukey_ (int *, int *, int *, int *, int *)
int buprt_ (int *, int *, int *, int *, char **, char **, char **, int *, double *, int *, int *, int *)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 28 of file bufr2syn.h.
#define BUFR_COMPRESSED_DATA_MASK 64
bit mask for Observed data
Definition at line 79 of file bufr2syn.h.
#define BUFR_LEN 512000
max length of a bufrfile
Definition at line 67 of file bufr2syn.h.
Referenced by main().
#define BUFR_OBS_DATA_MASK 128
bit mask for Observed data
Definition at line 73 of file bufr2syn.h.
#define DESCRIPTOR_HAVE_CODE_TABLE_STRING (16)
Bit mask for a code table string in a struct bufr_atom_data.
Definition at line 133 of file bufr2syn.h.
Referenced by main().
#define DESCRIPTOR_HAVE_FLAG_TABLE_STRING (32)
Bit mask for a flag table string in a struct bufr_atom_data.
Definition at line 139 of file bufr2syn.h.
Referenced by main().
#define DESCRIPTOR_HAVE_REAL_VALUE (2)
Bit mask for a real value in a struct bufr_atom_data.
Definition at line 115 of file bufr2syn.h.
Referenced by main().
#define DESCRIPTOR_HAVE_STRING_VALUE (4)
Bit mask for a string in a struct bufr_atom_data.
Definition at line 121 of file bufr2syn.h.
Referenced by main().
#define DESCRIPTOR_IS_A_REPLICATOR (128)
Bit mask for a flag table string in a struct bufr_atom_data.
Definition at line 151 of file bufr2syn.h.
#define DESCRIPTOR_IS_CODE_TABLE (8)
Bit mask for a code table in a struct bufr_atom_data.
Definition at line 127 of file bufr2syn.h.
Referenced by main().
#define DESCRIPTOR_IS_FLAG_TABLE (64)
Bit mask for a flag table in a struct bufr_atom_data.
Definition at line 145 of file bufr2syn.h.
Referenced by main().
#define DESCRIPTOR_VALUE_MISSING (1)
Bit mask for a missing value in a struct bufr_atom_data.
Definition at line 109 of file bufr2syn.h.
Referenced by buoy_parse_x01(), buoy_parse_x02(), buoy_parse_x04(), buoy_parse_x05(), buoy_parse_x06(), buoy_parse_x07(), buoy_parse_x08(), buoy_parse_x10(), buoy_parse_x11(), buoy_parse_x12(), buoy_parse_x13(), buoy_parse_x14(), buoy_parse_x20(), buoy_parse_x22(), buoy_parse_x31(), buoy_parse_x33(), main(), parse_subset_as_buoy(), syn_parse_x01(), syn_parse_x02(), syn_parse_x04(), syn_parse_x05(), syn_parse_x06(), syn_parse_x07(), syn_parse_x08(), syn_parse_x10(), syn_parse_x11(), syn_parse_x12(), syn_parse_x13(), syn_parse_x14(), syn_parse_x20(), syn_parse_x22(), and syn_parse_x31().
#define KELEM (8192)
max dimension of elements for a single report
Definition at line 49 of file bufr2syn.h.
#define KSUBS (KVALS / KELEM)
Maximum number of subset this version can manage.
Definition at line 61 of file bufr2syn.h.
Referenced by main().
#define KVALS (32768 * 512)
dimension of arrays of doubles. It must store all the data for all subset
Definition at line 55 of file bufr2syn.h.
#define MAXLINES_TABLEC (8192)
The maximum expected lines in a Table C file.
Definition at line 97 of file bufr2syn.h.
#define MISSING_INTEGER (2147483647)
The missing default value for integer values.
Definition at line 91 of file bufr2syn.h.
#define MISSING_REAL (1.7e38)
The missing default value for real values.
Definition at line 85 of file bufr2syn.h.
Referenced by main().
#define NMAXSEQ (16384)
Maximum expected descriptor in a expanded sequence for a single subset.
Definition at line 103 of file bufr2syn.h.
#define SUBSET_MASK_HAVE_ALTITUDE (256)
Bit mask to mark a struct bufr_subset_sequence_data having altitude.
Definition at line 206 of file bufr2syn.h.
Referenced by parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x07().
#define SUBSET_MASK_HAVE_COUNTRY (1024)
Bit mask to mark a struct bufr_subset_sequence_data having country name.
Definition at line 218 of file bufr2syn.h.
Referenced by buoy_parse_x01(), parse_subset_as_synop(), and syn_parse_x01().
#define SUBSET_MASK_HAVE_DAY (8192)
Bit mask to mark a struct bufr_subset_sequence_data having observation day in a month.
Definition at line 236 of file bufr2syn.h.
Referenced by buoy_parse_x04(), parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x04().
#define SUBSET_MASK_HAVE_GUST (65536)
Bit mask to mark a struct bufr_subset_sequence_data having wind gust observation other than 10 minutes.
Definition at line 254 of file bufr2syn.h.
Referenced by syn_parse_x11().
#define SUBSET_MASK_HAVE_HOUR (16384)
Bit mask to mark a struct bufr_subset_sequence_data having observation hour.
Definition at line 242 of file bufr2syn.h.
Referenced by buoy_parse_x04(), parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x04().
#define SUBSET_MASK_HAVE_LATITUDE (64)
Bit mask to mark a struct bufr_subset_sequence_data having latitude.
Definition at line 194 of file bufr2syn.h.
Referenced by buoy_parse_x05(), parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x05().
#define SUBSET_MASK_HAVE_LONGITUDE (128)
Bit mask to mark a struct bufr_subset_sequence_data having longitude.
Definition at line 200 of file bufr2syn.h.
Referenced by buoy_parse_x05(), buoy_parse_x06(), parse_subset_as_buoy(), parse_subset_as_synop(), syn_parse_x05(), and syn_parse_x06().
#define SUBSET_MASK_HAVE_MINUTE (32768)
Bit mask to mark a struct bufr_subset_sequence_data having observation minute.
Definition at line 248 of file bufr2syn.h.
Referenced by buoy_parse_x04(), and syn_parse_x04().
#define SUBSET_MASK_HAVE_MONTH (4096)
Bit mask to mark a struct bufr_subset_sequence_data having observation month.
Definition at line 230 of file bufr2syn.h.
Referenced by buoy_parse_x04(), parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x04().
#define SUBSET_MASK_HAVE_NAME (512)
Bit mask to mark a struct bufr_subset_sequence_data having station name.
Definition at line 212 of file bufr2syn.h.
Referenced by buoy_parse_x01(), parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x01().
#define SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1 (16)
Bit mask to mark a struct bufr_subset_sequence_data without W1 information.
Definition at line 182 of file bufr2syn.h.
Referenced by parse_subset_as_synop(), and syn_parse_x20().
#define SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2 (32)
Bit mask to mark a struct bufr_subset_sequence_data without W1 information.
Definition at line 188 of file bufr2syn.h.
Referenced by parse_subset_as_synop(), and syn_parse_x20().
#define SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW (8)
Bit mask to mark a struct bufr_subset_sequence_data without WW information.
Definition at line 176 of file bufr2syn.h.
Referenced by parse_subset_as_synop(), and syn_parse_x20().
#define SUBSET_MASK_HAVE_TYPE_STATION (4)
Bit mask to mark a struct bufr_subset_sequence_data having type station information.
Definition at line 170 of file bufr2syn.h.
Referenced by buoy_parse_x02(), parse_subset_as_synop(), and syn_parse_x02().
#define SUBSET_MASK_HAVE_YEAR (2048)
Bit mask to mark a struct bufr_subset_sequence_data having observation year.
Definition at line 224 of file bufr2syn.h.
Referenced by buoy_parse_x04(), parse_subset_as_buoy(), parse_subset_as_synop(), and syn_parse_x04().
#define SUBSET_MASK_LATITUDE_SOUTH (1)
Bit mask to mark a struct bufr_subset_sequence_data with south latitude.
Definition at line 158 of file bufr2syn.h.
Referenced by buoy_parse_x05(), parse_subset_as_buoy(), syn_parse_x05(), and syn_parse_x06().
#define SUBSET_MASK_LONGITUDE_WEST (2)
Bit mask to mark a struct bufr_subset_sequence_data with west longitude.
Definition at line 164 of file bufr2syn.h.
Referenced by buoy_parse_x05(), buoy_parse_x06(), parse_subset_as_buoy(), syn_parse_x05(), and syn_parse_x06().
Function Documentation
char * adjust_string (char * s)
Supress trailing blanks of a string.
Parameters
s string to process
Definition at line 74 of file bufr2syn_utils.c.
Referenced by buoy_parse_x01(), and syn_parse_x01().
 {
    size_t l;
    l = strlen(s);
    while (l && s[--l] == ' ')
      s[l] = '\0';
    return s;
 }
int bufr_set_environment (char * default_bufrtables, char * bufrtables_dir)
set the environment vars needed to work properly with ECMWF bufrdc library
Parameters
default_bufrtables defaut bufr tables dir. ususally '/usr/local/lib/bufrtables/'
bufrtables_dir alternative char with bufr tables dir
During decoding Bufr table path and the names are printed. If user doeas not want that, set: VARIABLE PRINT_TABLE_NAMES=false
During decoding code/flag tables could be read if code figure meaning is needed. If user want to use code and flag tables set: VARIABLE USE TABLE C=true
Then we set the proper environment here
Definition at line 41 of file bufr2syn_env.c.
Referenced by main().
 {
   int i;
   char aux[256], *c;
   struct stat s;
   i = stat(default_bufrtables, &s);
   if (putenv("PRINT_TABLE_NAMES=false") || putenv("USE_TABLE_C=true"))
     {
       fprintf(stderr, "bufr2syn: Failure setting the environment\n");
       exit (EXIT_FAILURE);
     }
   /*
     Default path for Bufr Tables is hard coded in the software. To change the path set environmental variable
     BUFR_TABLES . The path must end with '/'
   */
   if (bufrtables_dir[0])
     {
       sprintf(aux,"BUFR_TABLES=%s", bufrtables_dir);
       if (putenv(aux))
         {
           fprintf(stderr, "bufr2syn: Failure setting the environment\n");
           exit (EXIT_FAILURE);
         }
     }
   else if ((c = getenv("BUFR_TABLES")) != NULL)
     {
       strcpy(bufrtables_dir, c); // otherwise check if BUFRRABLES_DIR if is on environment
     }
   else if (i == 0 && S_ISDIR(s.st_mode)) // last chance, the default dir
     {
       strcpy(bufrtables_dir, default_bufrtables);
       sprintf(aux,"BUFR_TABLES=%s", bufrtables_dir);
       if (putenv(aux))
         {
           fprintf(stderr, "bufr2syn: Failure setting the environment\n");
           exit (EXIT_FAILURE);
         }
     }
   else
     {
       fprintf(stderr,"bufr2syn: Unable to find bufrtables directory\n");
       fprintf(stderr,"    Please set the proper enviromnet 'BUFR_TABLES=my_bufrtables_dir' or\n");
       fprintf(stderr,"    use '-t' argument . i. e.'-t my_bufrtables_dir/'\n");
       exit (EXIT_FAILURE);
     }
   return 0;
 }
int bufrex_ (int * , int * , int * , int * , int * , int * , int * , int * , int * , char ** , char ** , int * , double * , char ** , int *)
int buoy_parse_x01 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
b pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 109 of file bufr2syn_x01.c.
References bufr_subset_state::a, buoy_sec0::A1, adjust_string(), buoy_sec0::bw, bufr_atom_data::ctable, bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, bufr_atom_data::mask, bufr_subset_state::mask, bufr_subset_state::name, buoy_sec0::nbnbnb, buoy_chunks::s0, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   char aux[80];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 3: // 0 01 003
       if (s->ival > 0)
         sprintf ( b->s0.A1, "%d", s->ival );
       else if (s->ival == 0)
         sprintf ( b->s0.A1, "7");
       break;
     case 4: // 0 01 004
     case 20: // 0 01 004
       sprintf ( b->s0.bw, "%d", s->ival );
       break;
     case 5: // 0 01 005
       if ( s->ival < 1000)
         sprintf(b->s0.nbnbnb, "%03d", s->ival);
       else
         sprintf(b->s0.nbnbnb, "%05d", s->ival); // note this is a nnnnn extension
       break;
     case 15: // 0 01 015
       if (strlen(s->a->cval) <= 80)
         {
           strcpy(aux, s->a->cval);
           adjust_string(aux);
           strcpy(s->name, aux);
           s->mask |= SUBSET_MASK_HAVE_NAME;
         }
       break;
     case 101: // 0 01 101
       if (strlen(s->a->ctable) <= 80)
         {
           strcpy(aux, s->a->ctable);
           adjust_string(aux);
           strcpy(s->name, aux);
           s->mask |= SUBSET_MASK_HAVE_COUNTRY;
         }
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x02 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 02.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 71 of file bufr2syn_x02.c.
References bufr_subset_state::a, BUOY_SEC3, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, buoy_sec0::iw, buoy_sec3::k2, buoy_sec3::k3, buoy_sec3::k6, buoy_chunks::mask, bufr_atom_data::mask, bufr_subset_state::mask, buoy_chunks::s0, buoy_chunks::s3, SUBSET_MASK_HAVE_TYPE_STATION, bufr_subset_state::type, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
    return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 02 001
       s->type = s->ival;
       s->mask |= SUBSET_MASK_HAVE_TYPE_STATION;
       break;
     case 2: // 0 02 002
       if ( s->ival & 4 )
         strcpy ( b->s0.iw, "4" );
       else
         strcpy ( b->s0.iw, "1" );
       break;
     case 31: // 0 02 031
       if (b->s3.k3[0] == 0 && s->ival < 10)
         sprintf(b->s3.k3 ,"%d",s->ival);
       b->mask |= BUOY_SEC3;
       break;
     case 33: // 0 02 033
       sprintf(b->s3.k2 ,"%d",s->ival);
       b->mask |= BUOY_SEC3;
       break;
     case 40: // 0 02 040
       if (b->s3.k6[0] == 0)
         sprintf(b->s3.k6 ,"%d",s->ival);
       b->mask |= BUOY_SEC3;
       break;
       default:
       break;
     }
   return 0;
 }
int buoy_parse_x04 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 04.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 141 of file bufr2syn_x04.c.
References bufr_subset_state::a, report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_chunks::e, report_date_ext::HH, bufr_subset_state::i, bufr_subset_state::itval, bufr_subset_state::ival, bufr_subset_state::jtval, bufr_subset_state::k_itval, bufr_subset_state::k_jtval, bufr_atom_data::mask, bufr_subset_state::mask, report_date_ext::MM, report_date_ext::mm, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_MINUTE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_YEAR, bufr_descriptor::y, and report_date_ext::YYYY.
Referenced by parse_subset_as_buoy().
 {
   switch ( s->a->desc.y )
     {
     case 1: // 0 04 001
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (b->e.YYYY[0] == 0)
         sprintf ( b->e.YYYY, "%04d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_YEAR;
       break;
     case 2: // 0 04 002
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (b->e.MM[0] == 0)
         sprintf ( b->e.MM, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_MONTH;
       break;
     case 3: // 0 04 003
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (b->e.DD[0] == 0)
         sprintf ( b->e.DD, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_DAY;
       //sprintf(b->s0.YY, "%02d", (int) sq->sequence[is].val);
       break;
     case 4: // 0 04 004
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (b->e.HH[0] == 0)
         sprintf ( b->e.HH, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_HOUR;
       //sprintf(b->s0.GG, "%02d", (int) sq->sequence[is].val);
       break;
     case 5: // 0 04 005
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (b->e.mm[0] == 0)
         sprintf ( b->e.mm, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_MINUTE;
       break;
       // store latest displacement in seconds
     case 23: // 0 04 023
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival * 86400;
       break;
     case 24: // 0 04 024
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival * 3600;
       break;
     case 25: // 0 04 025
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival * 60;
       break;
     case 26: // 0 04 026
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival;
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x05 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 05.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 103 of file bufr2syn_x05.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec0::LaLaLaLaLa, bufr_subset_state::lat, buoy_sec0::LoLoLoLoLoLo, bufr_subset_state::lon, bufr_atom_data::mask, bufr_subset_state::mask, buoy_chunks::s0, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 05 001
     case 2: // 0 05 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LATITUDE_SOUTH; // Sign for latitude
       s->mask |= SUBSET_MASK_HAVE_LATITUDE;
       ia = (int) (fabs(s->val) * 1000.0 + 0.5);
       sprintf(b->s0.LaLaLaLaLa, "%05d",ia);
       s->lat = s->val;
       break;
     case 11: // 0 05 001
     case 12: // 0 05 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = (int) (fabs(s->val) * 1000.0 + 0.5);
       sprintf(b->s0.LoLoLoLoLoLo, "%06d",ia);
       s->lon = s->val;
     break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x06 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 06.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 126 of file bufr2syn_x06.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec0::LoLoLoLoLoLo, bufr_subset_state::lon, bufr_atom_data::mask, bufr_subset_state::mask, buoy_chunks::s0, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LONGITUDE_WEST, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 06 001
     case 2: // 0 06 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       s->lon = s->val;
       ia = (int) (fabs(s->val) * 1000.0 + 0.5);
       sprintf(b->s0.LoLoLoLoLoLo, "%06d",ia);
       break;
       default:
       break;
     }
   return 0;
 }
int buoy_parse_x07 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 07.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 72 of file bufr2syn_x07.c.
References bufr_subset_state::a, bufr_subset_state::deep, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::i, bufr_subset_state::k_rep, bufr_subset_state::layer, bufr_atom_data::mask, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
       case 62:
       case 63: // 0 07 063 Profundity below sea/water level
         if (s->k_rep == (s->i - 1) ) // Case of first layer after a replicator
            s->layer = 0;
         else
            (s->layer)++;
         s->deep = (int)(s->val + 0.5);
         break;
       default:
       break;
     }
   return 0;
 }
int buoy_parse_x08 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 08.
Parameters
b pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 79 of file bufr2syn_x08.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::isq, bufr_atom_data::mask, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     case 22:
     case 23:
     case 24:
       if (s->isq)
         s->isq = 0;
       else
         s->isq = 1;
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x10 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 108 of file bufr2syn_x10.c.
References buoy_sec1::a, bufr_subset_state::a, BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, buoy_chunks::mask, bufr_atom_data::mask, pascal_to_ppp(), pascal_to_PPPP(), buoy_sec1::PoPoPoPo, buoy_sec1::ppp, buoy_sec1::PPPP, buoy_chunks::s1, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 4: // 0 10 004
       pascal_to_PPPP ( aux, s->val );
       strcpy ( b->s1.PoPoPoPo, aux );
       b->mask |= BUOY_SEC1;
       break;
     case 51: // 0 10 051
       pascal_to_PPPP ( aux, s->val );
       strcpy ( b->s1.PPPP, aux );
       b->mask |= BUOY_SEC1;
       break;
     case 63: // 0 10 063
       sprintf ( b->s1.a, "%1d",s->ival );
       b->mask |= BUOY_SEC1;
       break;
     case 61: // 0 10 061
       pascal_to_ppp ( aux, s->val );
       sprintf ( b->s1.ppp, "%s", aux );
       b->mask |= BUOY_SEC1;
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x11 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 164 of file bufr2syn_x11.c.
References bufr_subset_state::a, BUOY_SEC1, buoy_sec1::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec1::ff, buoy_sec1::fff, bufr_subset_state::ival, buoy_sec0::iw, buoy_chunks::mask, bufr_atom_data::mask, buoy_chunks::s0, buoy_chunks::s1, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 11 001
     case 11: // 0 11 011
       sprintf ( b->s1.dd, "%02d", ( s->ival + 5 ) / 10 );
       b->mask |= BUOY_SEC1;
       break;
     case 2: // 0 11 002
     case 12: // 0 11 012
       if ( b->s0.iw[0] == '4' )
         s->val *= 1.94384449;
       if ( s->val < 100.0 )
         sprintf ( b->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
       else
         {
           sprintf ( b->s1.ff,"99" );
           sprintf ( b->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
         }
       b->mask |= BUOY_SEC1;
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x12 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 239 of file bufr2syn_x12.c.
References bufr_subset_state::a, BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, kelvin_to_snTTT(), buoy_chunks::mask, bufr_atom_data::mask, buoy_chunks::s1, buoy_sec1::sn1, buoy_sec1::sn2, buoy_sec1::TdTdTd, buoy_sec1::TTT, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 12 001
     case 4: // 0 12 004
     case 101: // 0 12 101
     case 104: // 0 12 104
       if (b->s1.TTT[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               b->s1.sn1[0] = aux[0];
               strcpy ( b->s1.TTT, aux + 1 );
               b->mask |= BUOY_SEC1;
             }
         }
       break;
     case 3: // 0 12 003
     case 5: // 0 12 006
     case 103: // 0 12 103
     case 106: // 0 12 106
       if (b->s1.TdTdTd[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               b->s1.sn2[0] = aux[0];
               strcpy ( b->s1.TdTdTd, aux + 1 );
               b->mask |= BUOY_SEC1;
             }
         }
       break;
       default:
       break;
     }
   return 0;
 }
int buoy_parse_x13 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 13.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 299 of file bufr2syn_x13.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::mask, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
       default:
       break;
     }
   return 0;
 }
int buoy_parse_x14 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 14.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 155 of file bufr2syn_x14.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::mask, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
       default:
       break;
     }
   return 0;
 }
int buoy_parse_x20 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 20.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 349 of file bufr2syn_x20.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_atom_data::mask, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x22 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 22.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 139 of file bufr2syn_x22.c.
References bufr_subset_state::a, BUOY_SEC2, BUOY_SEC3, b_sec3_layer2::dd, bufr_subset_state::deep, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec2::HwaHwa, buoy_sec2::HwaHwaHwa, kelvin_to_snTTT(), kelvin_to_TTTT(), buoy_sec3::l1, buoy_sec3::l2, bufr_subset_state::layer, buoy_chunks::mask, bufr_atom_data::mask, buoy_sec2::PwaPwa, buoy_sec2::PwaPwaPwa, buoy_chunks::s2, buoy_chunks::s3, buoy_sec2::sn, b_sec3_layer1::SSSS, b_sec3_layer1::TTTT, buoy_sec2::TwTwTw, bufr_subset_state::val, bufr_descriptor::y, b_sec3_layer1::zzzz, and b_sec3_layer2::zzzz.
Referenced by parse_subset_as_buoy().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 4: // 0 22 004 Direction of current
        if(s->layer < 32) // only 32 max layers
        {
          if(b->s3.l2[s->layer].dd[0] == 0)
          {
             sprintf(b->s3.l2[s->layer].dd, "%02d", (int)(s->val + 5.0)/ 10) ;
             b->mask |= BUOY_SEC3;
          }
          if (b->s3.l2[s->layer].zzzz[0] == 0) // also stores pendent deep
          {
             sprintf(b->s3.l2[s->layer].zzzz, "%04d", s->deep);
             b->mask |= BUOY_SEC3;
          }
        }
     case 12: // 0 22 012 wind wave period in seconds
       if (b->s2.PwaPwa[0] == 0)
         {
           sprintf(b->s2.PwaPwa, "%02d", (int)(s->val));
           b->mask |= BUOY_SEC2; // have sec2 data
           if (b->s2.PwaPwaPwa[0] == 0)
             sprintf(b->s2.PwaPwaPwa, "%03d", (int)(s->val * 10 + 0.5));
         }
       break;
     case 22: // 0 22 022 wind wave heigh in meters
       if (b->s2.HwaHwa[0] == 0)
         {
           sprintf(b->s2.HwaHwa, "%02d", (int)(s->val * 2.0 + 0.01));  // 0.5 m units
           b->mask |= BUOY_SEC2; // have sec2 data
         }
       if (b->s2.HwaHwaHwa[0] == 0)
         {
           sprintf(b->s2.HwaHwaHwa, "%03d", (int)(s->val * 10.0 + 0.01));  // 0.1 m units
           b->mask |= BUOY_SEC2; // have sec2 data
         }
       break;
     case 31: // 0 22 033 current speed
        if(s->layer < 32) // only 32 max layers
        {
          if(b->s3.l2[s->layer].dd[0] == 0)
          {
             sprintf(b->s3.l2[s->layer].dd, "%03d", (int)(s->val * 100.0 + 0.5)) ;
             b->mask |= BUOY_SEC3;
          }
          if (b->s3.l2[s->layer].zzzz[0] == 0) // also stores pendent deep
          {
             sprintf(b->s3.l2[s->layer].zzzz, "%04d", s->deep);
             b->mask |= BUOY_SEC3;
          }
        }
       break;
     case 42:
     case 43:
       if (s->deep == 0)
         {
           if (b->s2.TwTwTw[0] == 0)
             {
               if (kelvin_to_snTTT ( aux, s->val ))
                 {
                   b->s2.sn[0] = aux[0];
                   strcpy ( b->s2.TwTwTw, aux + 1 );
                   b->mask |= BUOY_SEC2; // have sec2 data
                 }
             }
         }
        if(s->layer < 32) // only 32 max layers
        {
          if(b->s3.l1[s->layer].TTTT[0] == 0)
          {
             kelvin_to_TTTT(b->s3.l1[s->layer].TTTT, s->val);
             b->mask |= BUOY_SEC3;
          }
          if (b->s3.l1[s->layer].zzzz[0] == 0) // also stores pendent deep
          {
             sprintf(b->s3.l1[s->layer].zzzz, "%04d", s->deep);
             b->mask |= BUOY_SEC3;
          }
        }
       break;
     case 45:
     case 49: // 0 22 049 Sea surface temperature
       if (b->s2.TwTwTw[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               b->s2.sn[0] = aux[0];
               strcpy ( b->s2.TwTwTw, aux + 1 );
               b->mask |= BUOY_SEC2; // have sec2 data
             }
         }
       break;
     case 62: // 0 22 062 Salinity
        if(s->layer < 32) // only 32 max layers
        {
          if(b->s3.l1[s->layer].SSSS[0] == 0)
          {
             sprintf(b->s3.l1[s->layer].SSSS, "%04d", (int)(s->val * 100.0 + 0.5));
             b->mask |= BUOY_SEC3;
          }
          if (b->s3.l1[s->layer].zzzz[0] == 0) // also stores pendent deep
          {
             sprintf(b->s3.l1[s->layer].zzzz, "%04d", s->deep);
             b->mask |= BUOY_SEC3;
          }
        }
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x31 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 31.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 64 of file bufr2syn_x31.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::i, bufr_subset_state::ival, bufr_subset_state::k_rep, bufr_atom_data::mask, bufr_subset_state::rep, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (b == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     case 1:
       s->rep = s->ival;
       s->k_rep = s->i;
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_parse_x33 (struct buoy_chunks * b, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 33.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x33.c.
References bufr_subset_state::a, BUOY_SEC1, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, buoy_chunks::mask, bufr_atom_data::mask, buoy_sec0::QA, buoy_sec4::QA, buoy_sec1::Qd, buoy_sec2::Qd, buoy_sec0::Ql, buoy_sec4::QL, buoy_sec4::Qp, buoy_sec0::Qt, buoy_chunks::s0, buoy_chunks::s1, buoy_chunks::s2, buoy_chunks::s4, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 20:
       sprintf(b->s0.Qt, "%d", s->ival);
       b->mask |= BUOY_SEC1;
       break;
     case 21:
       sprintf(b->s4.Qp, "%d", s->ival);
       b->mask |= BUOY_SEC1;
       break;
     case 22:
       if (s->ival == 0)
         {
           if ( b->s0.Qt[0] == 0)
             sprintf(b->s0.Qt, "1");
           if ( b->s1.Qd[0] == 0)
             sprintf(b->s1.Qd, "1");
           if ( b->s2.Qd[0] == 0)
             sprintf(b->s2.Qd, "1");
         }
       if (s->ival == 2)
         {
           if (b->s0.Qt[0] == 0)
             sprintf(b->s0.Qt, "3");
           if ( b->s1.Qd[0] == 0)
             sprintf(b->s1.Qd, "3");
           if ( b->s2.Qd[0] == 0)
             sprintf(b->s2.Qd, "3");
         }
       break;
     case 23:
       sprintf(b->s0.Ql, "%d", s->ival);
       sprintf(b->s4.QL, "%d", s->ival);
       break;
     case 27:
       sprintf(b->s0.QA, "%d", s->ival);
       sprintf(b->s4.QA, "%d", s->ival);
       break;
     default:
       break;
     }
   return 0;
 }
int buoy_YYYYMMDDHHmm_to_JMMYYGGgg (struct buoy_chunks * b)
Sets YYGG from YYYYMMDDHHmm extended group.
Parameters
b pointer to the target struct buoy_chunks
Definition at line 31 of file bufr2syn_buoy.c.
References report_date_ext::DD, buoy_chunks::e, buoy_sec0::GG, buoy_sec0::gg, report_date_ext::HH, buoy_sec0::J, buoy_sec0::MM, report_date_ext::MM, report_date_ext::mm, buoy_chunks::s0, buoy_sec0::YY, and report_date_ext::YYYY.
Referenced by parse_subset_as_buoy().
 {
   char aux[20];
   time_t t;
   struct tm tim;
   if ( strlen ( b->e.YYYY ) &&
        strlen ( b->e.MM ) &&
        strlen ( b->e.DD ) &&
        strlen ( b->e.HH ) &&
        strlen ( b->e.MM ) )
     sprintf ( aux,"%s%s%s%s%s", b->e.YYYY, b->e.MM, b->e.DD, b->e.HH, b->e.mm );
   if ( strlen ( aux ) != 12 )
     return 1;
   memset ( &tim, 0, sizeof ( struct tm ) );
   strptime ( aux, "%Y%m%d%H%M", &tim );
   t = mktime ( &tim );
   gmtime_r ( &t, &tim );
   sprintf ( b->s0.YY, "%02d", tim.tm_mday );
   sprintf ( b->s0.GG, "%02d", tim.tm_hour );
   sprintf ( b->s0.MM, "%02d", tim.tm_mon + 1);
   sprintf ( b->s0.J, "%d", tim.tm_year % 10);
   sprintf ( b->s0.gg, "%02d", tim.tm_min);
   return 0;
 }
int buprs0_ (int *)
int buprs1_ (int *)
int buprs3_ (int * , int * , int * , int * , int * , int * , char **)
int buprt_ (int * , int * , int * , int * , char ** , char ** , char ** , int * , double * , int * , int * , int *)
int bus012_ (int * , unsigned int * , int * , int * , int * , int * , int *)
int busel2_ (int * , int * , int * , char ** , int * , char ** , char ** , char ** , int *)
int busel_ (int * , int * , int * , int * , int *)
int buukey_ (int * , int * , int * , int * , int *)
char * charray_to_string (char * s, unsigned char * buf, size_t size)
get a null termitated c-string from an array of unsigned chars
Parameters
s resulting string
buf pointer to first element in array
size number of chars in array
Definition at line 60 of file bufr2syn_utils.c.
Referenced by main().
 {
    // copy
    memcpy(s , buf, size);
    // add final string mark
    s[size] = '\0';
    return s;
 }
void clean_buoy_chunks (struct buoy_chunks * b)
cleans a buoy_chunks struct
Parameters
b pointer to the struct to clean
Definition at line 159 of file bufr2syn_mrproper.c.
References clean_buoy_sec0(), clean_buoy_sec1(), clean_buoy_sec2(), clean_buoy_sec3(), clean_buoy_sec4(), clean_report_date_ext(), buoy_chunks::e, buoy_chunks::error, buoy_chunks::mask, buoy_chunks::s0, buoy_chunks::s1, buoy_chunks::s2, buoy_chunks::s3, and buoy_chunks::s4.
Referenced by parse_subset_as_buoy().
 {
   b->mask = 0;
   clean_report_date_ext( &(b->e));
   clean_buoy_sec0( &(b->s0));
   clean_buoy_sec1( &(b->s1));
   clean_buoy_sec2( &(b->s2));
   clean_buoy_sec3( &(b->s3));
   clean_buoy_sec4( &(b->s4));
   b->error[0] = '\0';
 }
void clean_synop_chunks (struct synop_chunks * syn)
cleans a synop_chunks struct
Parameters
syn pointer to the struct to clean
Definition at line 86 of file bufr2syn_mrproper.c.
Referenced by parse_subset_as_synop().
 {
   syn->mask = 0;
   clean_report_date_ext( &(syn->e));
   clean_syn_sec0( &(syn->s0));
   clean_syn_sec1( &(syn->s1));
   clean_syn_sec2( &(syn->s2));
   clean_syn_sec3( &(syn->s3));
   clean_syn_sec5( &(syn->s5));
   // default
   strcpy(syn->s0.iw,"/");
   strcpy(syn->s1.ir,"/");
   strcpy(syn->s1.ix,"/");
   strcpy(syn->s1.h,"/");
   strcpy(syn->s1.VV,"//");
   strcpy(syn->s1.N,"/");
   strcpy(syn->s1.dd,"//");
   strcpy(syn->s1.ff,"//");
   syn->error[0] = '\0';
 }
int find_descriptor (int * haystack, size_t nlst, int needle)
Try to find a descriptor in an array.
Parameters
haystack array of integers as descriptors
nlst number of descriptors in array
needle descriptor to find
it returns 1 if found, 0 otherwise.
Definition at line 35 of file bufr2syn_sqparse.c.
Referenced by parse_subset_sequence().
 {
   size_t i = 0;
   while (haystack[i] != needle && i < nlst)
     i++;
   return (i < nlst);
 }
int find_descriptor_interval (int * haystack, size_t nlst, int needlemin, int needlemax)
Definition at line 57 of file bufr2syn_sqparse.c.
Referenced by parse_subset_sequence().
 {
   size_t i = 0;
   while ((haystack[i] > needlemax || haystack[i] < needlemin) && i < nlst)
     i++;
   return (i < nlst);
 }
char* get_bufrfile_path (char * filename, char * err)
Get bufr file names to parse.
Parameters
filename string where the file is on output
err string where to set the error if any
If success, it returns a pointer to filename. If there is no more files to parse, or error returns NULL.
This routine is also opens the file with file list and close it when no more file available in list
The content format in LISTOFFILES is compatible with 'ls -1'. Example assume we want to parse all *.bufr files in current directory, we can do
ls -1 *.bufr > list_file && bufr2synop -I list_file
Definition at line 146 of file bufr2synop_io.c.
References FL, INPUTFILE, LISTOFFILES, and NFILES.
 {
    char aux[256], *c;
    if (LISTOFFILES[0] == 0)
    {
       if (NFILES == 0)
       {
          strcpy(filename, INPUTFILE);
          return filename;
       }
       else
          return 0;
    }
    else if (NFILES == 0)
    {
      if ((FL = fopen(LISTOFFILES,"r")) == NULL)
      {
         sprintf(err,"Cannot open '%s'", LISTOFFILES);
         return NULL;
      }
    }
    if (fgets(aux, 256, FL))
    {
       c =  strrchr(aux,'\n');
       if (c)
        *c = 0;
       strcpy(filename, aux);
       return filename;
    }
    else
    {
       fclose(FL);
       return NULL;
    }
 }
char * get_ecmwf_tablename (char * target, char type, char * bufrtables_dir, int ksec1[40])
Get the complete pathname of a table file needed by a bufr message.
Parameters
target the resulting name
type a char with type, i.e, 'B', 'C', or 'D'
bufrtables_dir string with path to bufr file tables dir
ksec1 array of integer processed prevoiously by ecmwf bufr library In ECMWF library the name of a table file is Kssswwwwwxxxxxyyyzzz.TXT , where
K - type of table, i.e, 'B', 'C', or 'D'
sss - Master table number (zero for WMO meteorological tables)
wwwww - Originating sub-centre
xxxxx - Originating centre
yyy - Version number of master table used
zzz - Version number of local table used
If standard WMO tables are used, the Originating centre xxxxx will be set to
Definition at line 43 of file bufr2syn_tablec.c.
Referenced by read_table_c().
 {
   if (0)
     {
       if (ksec1[13] != 0) // case of not WMO tables
         sprintf(target,"%s%c%03d%05d%05d%03d%03d.TXT", bufrtables_dir, type, ksec1[13], ksec1[15], ksec1[2], ksec1[14], ksec1[7]);
       else
         sprintf(target,"%s%c000%05d00000%03d%03d.TXT", bufrtables_dir, type, ksec1[15], ksec1[14], ksec1[7]);
     }
   else
     {
       //FIXME Some countries uses latest C tables instead of the version they said in bufr
       sprintf(target,"%s%c0000000000000019000.TXT", bufrtables_dir, type);
     }
   return target;
 }
char* get_explained_flag_val (char * expl, size_t dim, char tablec[MAXLINES_TABLEC][92], size_t nlines_tablec, struct bufr_descriptor * d, unsigned long ival)
Definition at line 181 of file bufr2syn_tablec.c.
References bufr_descriptor::c.
Referenced by main().
 {
   char *c, *s;
   unsigned long test, test0;
   unsigned long nb, nx, v,  nl;
   size_t i, j;
   // Find first line for descriptor
   for (i = 0; i <  nlines_tablec; i++)
     {
       if (tablec[i][0] != d->c[0] ||
           tablec[i][1] != d->c[1] ||
           tablec[i][2] != d->c[2] ||
           tablec[i][3] != d->c[3] ||
           tablec[i][4] != d->c[4] ||
           tablec[i][5] != d->c[5])
         continue;
       else
         break;
     }
   if (i == nlines_tablec)
     {
       //printf("Descriptor %s No encontrado\n", d->c);
       return NULL;
     }
   //printf("Descriptor %s en linea %d\n", d->c, i);
   // reads the amount of possible bits
   if (tablec[i][7] != ' ')
     nb = strtol(&tablec[i][7], &c, 10);
   else
     return NULL;
   // read a value
   s = expl;
   s[0] = '\0';
   for (j = 0, test0 = 2; j < nb && i < nlines_tablec ; i++)
     {
       if (tablec[i][12] != ' ')
         {
           v = strtol(&tablec[i][12], &c, 10); // v is the bit number
           j++;
           // case 0 with meaning
           if (v == 0)
             {
               test0 = 1;
               if (ival == 0)
                 {
                   nl = strtol(&tablec[i][21], &c, 10);
                   if (strlen(expl) && (strlen(expl) + 1) < dim)
                     s += sprintf(s, "|");
                   s += sprintf(s,"%s", &tablec[i][24]);
                   if (nl > 1)
                     {
                       for (nx = 1 ; nx < nl; nx++)
                         if ((strlen(expl) + strlen(&tablec[i + nx][22]))  < dim)
{
                             s += sprintf(s, "%s", &tablec[i + nx][22]);
                           }
                     }
                   return expl;
                 }
             }
           test = test0 << (nb - v);
           if (v && (test & ival) != 0)
             {
               // bit match
               // read how many lines for the descriptors
               nl = strtol(&tablec[i][21], &c, 10);
               if (strlen(expl) && (strlen(expl) + 1) < dim)
                 s += sprintf(s, "|");
               s += sprintf(s,"%s", &tablec[i][24]);
               if (nl > 1)
                 {
                   for (nx = 1 ; nx < nl; nx++)
                     if ((strlen(expl) + strlen(&tablec[i + nx][22]))  < dim)
                       {
                         s += sprintf(s, "%s", &tablec[i + nx][22]);
                       }
                 }
             }
           else
             continue;
         }
     }
   // if match then we have finished the search
   return expl;
 }
char* get_explained_table_val (char * expl, size_t dim, char tablec[MAXLINES_TABLEC][92], size_t nlines_tablec, struct bufr_descriptor * d, int ival)
Definition at line 103 of file bufr2syn_tablec.c.
References bufr_descriptor::c.
Referenced by main().
 {
   char *c;
   long nv, v,  nl;
   size_t i, j;
   // Find first line for descriptor
   for (i = 0; i <  nlines_tablec; i++)
     {
       if (tablec[i][0] != d->c[0] ||
           tablec[i][1] != d->c[1] ||
           tablec[i][2] != d->c[2] ||
           tablec[i][3] != d->c[3] ||
           tablec[i][4] != d->c[4] ||
           tablec[i][5] != d->c[5])
         continue;
       else
         break;
     }
   if (i == nlines_tablec)
     {
       //printf("Descriptor %s No encontrado\n", d->c);
       return NULL;
     }
   //printf("Descriptor %s en linea %d\n", d->c, i);
   // reads the amount of possible values
   if (tablec[i][7] != ' ')
     nv = strtol(&tablec[i][7], &c, 10);
   else
     return NULL;
   // read a value
   for (j = 0; (long)j < nv && i < nlines_tablec ; i++)
     {
       if (tablec[i][12] != ' ')
         {
           v = strtol(&tablec[i][12], &c, 10);
           j++;
           if (v != ival)
             continue;
           break;
         }
     }
   if ((long)j == nv || i == nlines_tablec)
     return NULL; // Value not found
   // read how many lines for the descriptors
   nl = strtol(&tablec[i][21], &c, 10);
   // if match then we have finished the search
   strcpy(expl, &tablec[i][24]);
   if (nl > 1)
     {
       for (nv = 1 ; nv < nl; nv++)
         if ((strlen(expl) + strlen(&tablec[i + nv][22])) < dim)
           strcat(expl, &tablec[i + nv][22]);
     }
   return expl;
 }
int guess_gts_header (struct gts_header * h, const char * f)
Guess the WMO GTS header from filename.
Parameters
h pointer to a struct gts_header where to set the results
f pathname of bufrfile
It returns 1 if guessed, 0 otherwise
This routine assume the filename format of a bufr file is
  YYYYMMDDHHmmss_BULLNN_ICAO_YYGGgg_ORD.bufr
where
 YYYYMMDDHHmmss
is the timestamp (UTC) of the file in GTS (as example, in NOAA gateway)
BULLNN is the bulletin identifier in GTS. It is a six chars lenght in the form T1 T2 A1 A2 N1 N2
  For observations, T1 is 'I'
  Possible values of T2 for T1 = 'I' are
     O   Oceanographic/limnographic (water properties)
     P   Pictorial
     S   Surface/sea level
     T   Text (plain language information)
     U   Upper air
     X   Other data types
     Z   Mixed data types
  For T1T2 = 'IS' Then A1:
     IS A 0129 Routinely scheduled observations for n/a 000/006
                distribution from automatic (fixed or mobile)
                land stations (e.g. 0000, 0100,  or 0220, 0240,
                0300, , or 0715, 0745, ... UTC)
     IS A 3059 N-minute observations from automatic (fixed n/a 000/007
                or mobile) land stations
     IS B   Radar reports (parts A and B) RADOB 006/003
     IS C 0145 Climatic observations from land stations CLIMAT 000/020
     IS C 4659 Climatic observations from marine stations CLIMAT SHIP 001/0202009 edition
                ATTACHmENT II-5 I
     IS D   Radiological observation RADREP 010/001
     IS E   Ozone measurement at surface n/a 008/000
     IS F   Source of atmospherics SFAZI, SFLOC, SFAZU 000/030
     IS I 0145 Intermediate synoptic observations from fixed SYNOP (SIxx) 000/001
            land stations 000/051
     IS I 4659 Intermediate synoptic observations from mobile SYNOP mOBIL 000/004
            land stations
     IS M 0145 Main synoptic observations from fixed land SYNOP (SMxx) 000/002
            stations 000/052
     IS M 4659 Main synoptic observations from mobile land SYNOP mOBIL 000/005
             stations
     IS N 0145 Synoptic observations from fixed land stations SYNOP (SNxx) 000/000
            at non-standard time (i.e. 0100, 0200, 0400,   000/050
            0500, ... UTC)
     IS N 4659 Synoptic observations from mobile land stations SYNOP mOBIL 000/003
            at non-standard time (i.e. 0100, 0200, 0400,
            0500, ... UTC)
     IS R   Hydrologic reports HYDRA 000/040
     IS S 0119 Synoptic observations from marine stations SHIP 001/000
     IS S 2039 One-hour observations from automatic marine n/a 001/006
           stations
     IS S 4059 N-minute observations from automatic marine n/a 001/007
           stations
     IS T 0119 Tide gauge observations n/a 001/030
     IS T 2039 Observed water level time series n/a 001/031
     IS V   Special aeronautical observations (SPECI) SPECI 000/011
     IS W   Aviation routine weather observations (mETAR) mETAR 000/010
     IS X   Other surface data IAC, IAC FLEET
  For T1T2 = 'IU'  then A1:
     IU A   Single level aircraft reports (automatic) AmDAR 004/000
     IU A   Single level aircraft reports (manual) AIREP/PIREP 004/001
     IU B   Single level balloon reports n/a
     IU C   (used for single level satellite-derived SAREP/SATOB 005/000
             reports  see Note 3)
     IU D   Dropsonde/Dropwindsondes TEmP DROP 002/007
     IU E   Ozone vertical sounding n/a 008/001
     IU I   Dispersal and transport analysis n/a 009/000
     IU J 0119 Upper wind from fixed land stations (entire PILOT (parts A, 002/001
            sounding) B, C, D)
     IU J 2039 Upper wind from mobile land stations (entire PILOT mOBIL 002/003
            sounding) (parts A, B, C, D)
     IU J 4059 Upper wind from marine stations (entire PILOT SHIP 002/002
           sounding) (parts A, B, C, D)
     IU K 0119 Radio soundings from fixed land stations TEmP (parts A, B) 002/004
           (up to 100 hPa)
     IU K 2039 Radio soundings from mobile land stations TEmP mOBIL 002/006
          (up to 100 hPa) (parts A, B)
     IU K 4059 Radio soundings from marine stations TEmP SHIP (parts A, B) 002/005
           (up to 100 hPa)
     IU M   Model derived sondes
     IU N   Rocketsondes
     IU O   Profiles of aircraft observations in ascending/ AmDAR 002/020
            descending
     IU P   Profilers PILOT 002/010
     IU Q   RASS temperature profilers TEmP 002/011
     IU R   (used for radiance data  see Note 3)
     IU S   0119 Radiosondes/pibal reports from fixed land TEmP (parts A, B, C, D) 002/004
             stations (entire sounding)
     IU S 2039 Radio soundings from mobile land stations TEmP mOBIL (parts A, 002/006
             (entire sounding) B, C, D)
     IU S 4059 Radio soundings from marine stations TEmP SHIP (parts A, 002/005
             (entire sounding) B, C, D)
     IU T   (used for satellite-derived sondes  see Note 3) SATEm, SARAD, SATOB
     IU U 0145 Monthly statistics of data from upper-air stations CLImAT TEmP 002/025
     IU U 4659 Monthly statistics of data from marine stations CLImAT TEmP, SHIP 002/026
     IU W 0119 Upper wind from fixed land stations (up to PILOT (parts A, B) 002/001
             100 hPa)
     IU W 2039 Upper wind from mobile land stations (up to PILOT mOBIL 002/003
             100 hPa) (parts A, B)
     IU W 4059 Upper wind from marine stations (up to PILOT SHIP 002/002
             100 hPa) (parts A, B)
     IU X   Other upper-air reports
  for T1T2 = 'IO' then  A1:
     IO B   Buoy observations BUOY 001/025
     IO I   Sea ice
     IO P   Sub-surface profiling floats TESAC 031/004
     IO R   Sea surface observations TRACKOB 031/001
     IO S   Sea surface and below soundings BATHY, TESAC 031/005
     IO T   Sea surface temperature
     IO W   Sea surface waves WAVEOB 031/002
     IO X   Other sea environmental
  About A2
     A   0 - 90W northern hemisphere
     B   90W - 180 northern hemisphere
     C   180 - 90E northern hemisphere
     D   90E - 0 northern hemisphere
     E   0 - 90W tropical belt
     F   90W - 180 tropical belt
     G   180 - 90E tropical belt
     H   90E - 0 tropical belt
     I   0 - 90W southern hemisphere
     J   90W - 180 southern hemisphere
     K   180 - 90E southern hemisphere
     L   90E - 0 southern hemisphere
     M   Lower left 10S 100E/upper right 70N 110W
     N   Northern hemisphere
     P   Area between 64.69N - 136.76W, 55.61N - 13.43W
     64.69N - 156.76W, 55.61N - 33.43W
     S   Southern hemisphere
     T   45W - 180 northern hemisphere
     U   Area between 21.0N - 128.1W, 36.0N - 130.9W
               21.1N - 113.0W, 36.2N - 110.5W
     V   Area between 30.3N - 83.7W, 51.0N - 68.9W
               19.8N - 64.5W, 33.3N - 47.1W
     X   Global Area (area not definable)
 ICAO is the ICAO index for release center.
 YYGGgg is the nominal release time (day, hour, minute) UTC
 ORD is the order sequence as RRA, RRB, CCA .... is optional
Definition at line 305 of file bufr2syn_utils.c.
References gts_header::bname, gts_header::center, gts_header::dtrel, gts_header::filename, gts_header::order, gts_header::timestamp, and tokenize_string().
Referenced by main().
 {
    size_t nt;
    char aux[256], *tk[16], *c;
    // parse file name
    strcpy(h->filename, f);
    strcpy(aux, f);
    // check latest '/' in filename
    if ((c = strrchr(aux,'/')) == NULL)
      c = &aux[0];
    else
      c++;
    nt = tokenize_string(tk, 16, aux, strlen(c), "_.");
    // parse filenames with format as example 'AAAAMMDDHHmmss_ISIE06_SBBR_012100_RRB.bufr'
    // 5 or 6 items
    if ( nt < 5 || nt > 6)
      return 0;
    // extension bufr
    if (strcmp(tk[nt - 1],"bufr"))
      return 0;
    // item 0 the timestamp of file in NOAA GTS gateway
    if (strlen(tk[0]) != 14 || strspn(tk[0], "0123456789") != 14)
      return 0;
    strcpy(h->timestamp, tk[0]);
    // item 1
    if (strlen(tk[1]) != 6 || strspn(&tk[1][4],"0123456789") != 2)
      return 0;
    strcpy(h->bname, tk[1]);
    // item 2
    if (strlen(tk[2]) != 4)
      return 0;
    strcpy(h->center, tk[2]);
    if (strlen(tk[3]) != 6 || strspn(tk[3], "0123456789") != 6)
      return 0;
    strcpy(h->dtrel, tk[3]);
    if (nt == 5)
    {
       strcpy(h->order, "BBB");
    }
    else
    {
      if (strlen(tk[4]) == 3)
       strcpy(h->order, tk[4]);
      else
       return 0;
    }
   return 1;
 }
char * guess_WMO_region (struct synop_chunks * syn)
Try to find WMO region if it is not already set and WMO Block and number index are known.
Parameters
syn pointer to the struct synop_chunks with all known data for a synop
It returns a pointer to the string with WMO region
Definition at line 64 of file bufr2syn_synop.c.
References synop_sec0::A1, synop_sec0::II, synop_sec0::iii, synop_sec0::Reg, and synop_chunks::s0.
Referenced by syn_parse_x12().
 {
   char aux[8];
   if (syn->s0.A1[0])
     {
       return syn->s0.A1;
     }
   if (syn->s0.II[0] == 0  || syn->s0.iii[0] == 0)
     return syn->s0.A1;
   sprintf(aux,"%s%s",syn->s0.II, syn->s0.iii);
   if ((syn->s0.II[0] == '0' && (strstr(aux,"042") != aux) && (strstr(aux,"043") != aux)  &&
        (strstr(aux,"044") != aux)  && (strstr(aux,"0858") != aux) &&  (strstr(aux,"0859") != aux)) ||
       syn->s0.II[0] == '1' || (strstr(aux,"201") == aux) ||
       strcmp(syn->s0.II,"22") == 0 || strcmp(syn->s0.II,"26") == 0 || strcmp(syn->s0.II,"27") == 0 ||
       strcmp(syn->s0.II,"33") == 0 || strcmp(syn->s0.II,"34") == 0 || strcmp(syn->s0.II,"22") == 0 ||
       (strstr(aux,"201") == aux))
     {
       // Reg 6. Europe
       syn->s0.A1[0] = '6';
       strcpy(syn->s0.Reg,"VI");
     }
   else if (syn->s0.II[0] == '6' || (strstr(aux,"0858") == aux) ||  (strstr(aux,"0859") == aux))
     {
       // Reg 1. Africa
       syn->s0.A1[0] = '1';
       strcpy(syn->s0.Reg,"I");
     }
   else if (syn->s0.II[0] == '5' || (strcmp(syn->s0.II,"49") == 0) || (strcmp(syn->s0.II,"21") == 0) ||
            (strcmp(syn->s0.II,"23") == 0) || (strcmp(syn->s0.II,"24") == 0) || (strcmp(syn->s0.II,"25") == 0) ||
            (strcmp(syn->s0.II,"28") == 0) || (strcmp(syn->s0.II,"29") == 0) || (strcmp(syn->s0.II,"30") == 0) ||
            (strcmp(syn->s0.II,"31") == 0) || (strcmp(syn->s0.II,"32") == 0) || (strcmp(syn->s0.II,"38") == 0) ||
            (strcmp(syn->s0.II,"35") == 0) || (strcmp(syn->s0.II,"36") == 0) || (strcmp(syn->s0.II,"39") == 0) ||
            (strcmp(aux, "20200") >= 0 && strcmp(aux, "20999") <= 0) ||
            (strcmp(aux, "40000") >= 0 && strcmp(aux, "48599") <= 0) ||
            (strcmp(aux, "48800") >= 0 && strcmp(aux, "49999") <= 0))
     {
       // Reg 2. Asia
       syn->s0.A1[0] = '2';
       strcpy(syn->s0.Reg,"II");
     }
   else if (strcmp(aux, "80000") >= 0 && strcmp(aux, "88999") <= 0)
     {
       // Reg 3. South america
       syn->s0.A1[0] = '3';
       strcpy(syn->s0.Reg,"III");
     }
   else if (syn->s0.II[0] == '7' || strstr(aux,"042") == aux ||
            strstr(aux,"043") == aux  || strstr(aux,"044") == aux)
     {
       // Reg 4. North and central america
       syn->s0.A1[0] = '4';
       strcpy(syn->s0.Reg,"IV");
     }
   else if ((strcmp(aux, "48600") >= 0 && strcmp(aux, "48799") <= 0) ||
            (strcmp(aux, "90000") >= 0 && strcmp(aux, "98999") <= 0))
     {
       // Reg 5. Pacific South
       syn->s0.A1[0] = '4';
       strcpy(syn->s0.Reg,"IV");
     }
   else if (strcmp(syn->s0.II,"89") == 0)
     {
       // Reg 0. Antarctica
       syn->s0.A1[0] = '0';
       strcpy(syn->s0.Reg,"0");
     }
   return syn->s0.A1;
 }
int integer_to_descriptor (struct bufr_descriptor * d, int id)
parse an integer with a descriptor fom bufr ECWMF libary
Parameters
d pointer to a struct bufr_descriptor where to set the result on output
id integer with the descriptor from ewcwf
Definition at line 42 of file bufr2syn_utils.c.
References bufr_descriptor::c, bufr_descriptor::f, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by main().
 {
    if (d == NULL)
      return 1;
    d->f = id / 100000;
    d->x = (id % 100000) / 1000;
    d->y = id % 1000;
    sprintf(d->c, "%06d", id);
    return 0;
 }
char * kelvin_to_snTT (char * target, double T)
converts a kelvin temperature value into a snTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 55 of file bufr2syn_x12.c.
Referenced by syn_parse_x12().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   ic /= 100;
   if ( ic < 0 )
     sprintf ( target, "1%02d", -ic );
   else
     sprintf ( target, "%03d", ic );
   return target;
 }
char * kelvin_to_snTTT (char * target, double T)
converts a kelvin temperature value into a snTTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 32 of file bufr2syn_x12.c.
Referenced by buoy_parse_x12(), buoy_parse_x22(), syn_parse_x12(), and syn_parse_x22().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   if ( ic < 0 )
   {
     sprintf ( target, "1%03d",(-ic + 5)/10 );
   }
   else
   {
     sprintf ( target, "%04d", (ic  + 5)/10);
   }
   return target;
 }
char * kelvin_to_TT (char * target, double T)
converts a kelvin temperature value into a TT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 75 of file bufr2syn_x12.c.
Referenced by syn_parse_x12().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   ic /= 100;
   if ( ic < 0 )
     sprintf ( target, "%02d", 50 - ic );
   else
     sprintf ( target, "%02d", ic );
   return target;
 }
char * kelvin_to_TTTT (char * target, double T)
converts a kelvin temperature value into a TTTT string
Parameters
T the temperature (Kelvin)
target string with the result
Definition at line 95 of file bufr2syn_x12.c.
Referenced by buoy_parse_x22().
 {
   int ic;
   if ( T < 150.0 || T > 340.0)
     return NULL;
   ic = ( int ) (100.0 * T + 0.001) - 27315;
   if (ic < 0)
     ic = 5000 - ic;
   sprintf ( target, "%04d", ic );
   return target;
 }
char * latlon_to_MMM (char * target, double lat, double lon)
convert latitude and longitude to a MMM string
Parameters
lat latitude (degree, N positive)
lon longitude (degree, E positive)
target resulting MMM string
Definition at line 34 of file bufr2syn_x06.c.
Referenced by syn_parse_x05(), and syn_parse_x06().
 {
    int col, row, ori = 0;
    if (lon < 0.0)
       col = (int)(-lat * 0.1) + 1;
    else
       col = 36 - (int)(lat * 0.1);
    if (lat >= 80.0)
       row = 25;
    else if (lat >=  0.0)
       row = (int)(lat * 0.1);
    else
    {
       ori = 299;
       row = (int)(-lat * 0.1);
    }
    sprintf(target,"%03d", col + ori + row * 36);
    return target;
 }
char * m_to_h (char * target, double h)
converts the altitude of cloud layer into h string code
Parameters
h the altitude in meters
target the resulting h coded string
Definition at line 63 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   if ( h < 50.0 )
     strcpy ( target,"0" );
   else if ( h < 100.0 )
     strcpy ( target,"1" );
   else if ( h < 200.0 )
     strcpy ( target,"2" );
   else if ( h < 300.0 )
     strcpy ( target,"3" );
   else if ( h < 600.0 )
     strcpy ( target,"4" );
   else if ( h < 1000.0 )
     strcpy ( target,"5" );
   else if ( h < 1500.0 )
     strcpy ( target,"6" );
   else if ( h < 2000.0 )
     strcpy ( target,"7" );
   else if ( h < 2500.0 )
     strcpy ( target,"8" );
   else
     strcpy ( target,"9" );
   return target;
 }
char * m_to_hh (char * target, double h)
converts the altitude of cloud layer into hh string code
Parameters
h the altitude in meters
target the resulting h coded string
Definition at line 95 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   int ih = (int)h;
   if ( ih <= 1500 )
   {
     sprintf(target, "%02d", ih / 30);
   }
   else if ( ih <= 9000 )
   {
     sprintf(target, "%2d", (ih / 300) + 50);
   }
   else if (ih <= 21000 )
   {
     sprintf(target, "%2d", (ih / 500) + 50);
   }
   else
     strcpy ( target,"89" );
   return target;
 }
int parse_subset_as_buoy (struct metreport * m, struct buoy_chunks * b, struct bufr_subset_state * s, struct bufr_subset_sequence_data * sq, char * err)
Definition at line 71 of file bufr2syn_buoy.c.
References bufr_subset_state::a, buoy_sec0::A1, bufr_subset_state::alt, met_geo::alt, BUOY_EXT, buoy_parse_x01(), buoy_parse_x02(), buoy_parse_x04(), buoy_parse_x05(), buoy_parse_x06(), buoy_parse_x07(), buoy_parse_x08(), buoy_parse_x10(), buoy_parse_x11(), buoy_parse_x12(), buoy_parse_x13(), buoy_parse_x14(), buoy_parse_x20(), buoy_parse_x22(), buoy_parse_x31(), buoy_parse_x33(), BUOY_SEC0, buoy_YYYYMMDDHHmm_to_JMMYYGGgg(), buoy_sec0::bw, clean_buoy_chunks(), report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_chunks::e, buoy_sec1::ff, metreport::g, report_date_ext::HH, bufr_subset_state::i, met_geo::index, bufr_subset_state::isq, bufr_subset_state::ival, buoy_sec0::iw, buoy_sec3::k2, buoy_sec3::k3, buoy_sec3::k6, buoy_sec0::LaLaLaLaLa, bufr_subset_state::lat, met_geo::lat, buoy_sec0::LoLoLoLoLoLo, bufr_subset_state::lon, met_geo::lon, buoy_chunks::mask, bufr_atom_data::mask, bufr_subset_state::mask, buoy_sec0::MiMi, buoy_sec0::MjMj, report_date_ext::MM, report_date_ext::mm, bufr_subset_state::name, met_geo::name, buoy_sec0::nbnbnb, bufr_subset_sequence_data::nd, buoy_sec0::Qc, buoy_sec1::Qd, buoy_sec2::Qd, buoy_sec3::Qd1, buoy_sec3::Qd2, buoy_sec1::Qx, buoy_sec2::Qx, buoy_chunks::s0, buoy_chunks::s1, buoy_chunks::s2, buoy_chunks::s3, bufr_subset_sequence_data::sequence, SUBSET_MASK_HAVE_ALTITUDE, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_YEAR, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, metreport::t, bufr_subset_state::type_report, bufr_atom_data::val, bufr_subset_state::val, bufr_descriptor::x, report_date_ext::YYYY, and YYYYMMDDHHmm_to_met_datetime().
Referenced by parse_subset_sequence().
 {
   int ival; // integer value for a descriptor
   size_t is;
   char aux[16];
   // clean data
   clean_buoy_chunks ( b );
   // reject if still not coded type
   if (strcmp(s->type_report,"ZZYY"))
     {
       sprintf(err,"bufr2syn: '%s' report still not decoded in this software", s->type_report);
       return 1;
     }
   strcpy(b->s0.MiMi, "ZZ");
   strcpy(b->s0.MjMj, "YY");
   b->mask = BUOY_SEC0;
   /**** First pass, sequential analysis *****/
   for ( is = 0; is < sq->nd; is++ )
     {
       // check if is a significance qualifier
       if (sq->sequence[is].desc.x == 8)
       {
         s->i = is;
         s->a = &sq->sequence[is];
         buoy_parse_x08 ( b, s );
       }
       if ( sq->sequence[is].mask & DESCRIPTOR_VALUE_MISSING ||
            s->isq   // case of an significance qualifier
          )
         continue;
       s->i = is;
       s->ival = ( int ) sq->sequence[is].val;
       ival = ival;
       s->val = sq->sequence[is].val;
       s->a = &sq->sequence[is];
       switch ( sq->sequence[is].desc.x )
         {
         case 1: //localization descriptors
           buoy_parse_x01 ( b, s );
           break;
         case 2: //Date time descriptors
           buoy_parse_x02 ( b, s );
           break;
         case 4: //Date time descriptors
           buoy_parse_x04 ( b, s );
           break;
         case 5: //Position
           buoy_parse_x05 ( b, s );
           break;
         case 6: // Horizontal Position -2
           buoy_parse_x06 ( b, s );
           break;
         case 7: // Vertical Position
           buoy_parse_x07 ( b, s );
           break;
         case 10: // Air Pressure descriptors
           buoy_parse_x10 ( b, s );
           break;
         case 11: // wind  data
           buoy_parse_x11 ( b, s );
           break;
         case 12: //Temperature descriptors
           buoy_parse_x12 ( b, s );
           break;
         case 13: // Humidity and precipitation data
           buoy_parse_x13 ( b, s );
           break;
         case 14: // Radiation
           buoy_parse_x14 ( b, s );
           break;
         case 20: // Cloud data
           buoy_parse_x20 ( b, s );
           break;
         case 22: // Oceanographic data
           buoy_parse_x22 ( b, s );
           break;
         case 31: // Replicators
           buoy_parse_x31 ( b, s );
           break;
         case 33: // Quality data
           buoy_parse_x33 ( b, s );
           break;
         default:
           break;
         }
     }
   if (((s->mask & SUBSET_MASK_HAVE_LATITUDE) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_LONGITUDE) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_YEAR) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_MONTH) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_DAY) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_HOUR) == 0))
       {
         sprintf(err,"bufr2syn: parse_subset_as_buoy(): lack of mandatory descriptor in sequence");
         return 1;
       }
   /****** Second pass. Global results and consistence analysis ************/
   // adjust iw
   if ( b->s0.iw[0] == '/' && b->s1.ff[0] != '/' )
     b->s0.iw[0] = '1';
   // fill date fields YYYYMMDDHHmm
   buoy_YYYYMMDDHHmm_to_JMMYYGGgg ( b );
   b->mask |= BUOY_EXT;
   // Fill some metreport fields
   if (s->mask & SUBSET_MASK_HAVE_LATITUDE)
     m->g.lat = s->lat;
   if (s->mask & SUBSET_MASK_HAVE_LONGITUDE)
     m->g.lon = s->lon;
   if (s->mask & SUBSET_MASK_HAVE_ALTITUDE)
     m->g.alt = s->alt;
   if (s->mask & SUBSET_MASK_HAVE_NAME)
     strcpy(m->g.name, s->name);
   sprintf ( aux,"%s%s%s%s%s", b->e.YYYY, b->e.MM, b->e.DD, b->e.HH, b->e.mm );
   YYYYMMDDHHmm_to_met_datetime(&m->t, aux);
   // Fill some metreport fields
   if (b->s0.A1[0] && b->s0.bw[0] && b->s0.nbnbnb[0])
     {
       sprintf ( m->g.index, "%s%s%s", b->s0.A1, b->s0.bw, b->s0.nbnbnb);
     }
   // check if set both LaLaLa and LoLoLoLo to set Qc
   if ((b->s0.Qc[0] == 0) && b->s0.LaLaLaLaLa[0] && b->s0.LoLoLoLoLoLo[0])
     {
       if (s->mask & SUBSET_MASK_LATITUDE_SOUTH)
         {
           if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
             strcpy(b->s0.Qc, "5");
           else
             strcpy(b->s0.Qc, "3");
         }
       else
         {
           if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
             strcpy(b->s0.Qc, "7");
           else
             strcpy(b->s0.Qc, "1");
         }
     }
   // check Qx
   if (b->s2.Qd[0] ==  0)
     b->s2.Qd[0] = '0';
   if (b->s3.k2[0] == 0)
     b->s3.k2[0] = '0';
   if (b->s1.Qx[0] == 0 && b->s1.Qd[0])
     b->s1.Qx[0] = '9';
   if (b->s2.Qx[0] == 0 && b->s2.Qd[0])
     b->s2.Qx[0] = '9';
   if (b->s3.Qd1[0] ==  0)
     b->s3.Qd1[0] = '0';
   if (b->s3.Qd2[0] ==  0)
     b->s3.Qd2[0] = '0';
   if (b->s3.k3[0] == 0)
     b->s3.k3[0] = '/';
   if (b->s3.k6[0] == 0)
     b->s3.k6[0] = '/';
   return 0;
 }
int parse_subset_as_synop (struct metreport * m, struct synop_chunks * syn, struct bufr_subset_state * s, struct bufr_subset_sequence_data * sq, char * err)
Definition at line 149 of file bufr2syn_synop.c.
References bufr_subset_state::a, bufr_subset_state::alt, met_geo::alt, clean_synop_chunks(), bufr_subset_state::country, met_geo::country, synop_sec0::D_D, report_date_ext::DD, bufr_atom_data::desc, synop_chunks::e, synop_sec1::ff, metreport::g, synop_sec1::GG, synop_sec1::gg, report_date_ext::HH, bufr_subset_state::i, synop_sec0::II, synop_sec0::iii, synop_sec0::IIIII, met_geo::index, synop_sec1::ir, bufr_subset_state::isq, bufr_subset_state::ival, synop_sec0::iw, synop_sec1::ix, bufr_subset_state::lat, met_geo::lat, bufr_subset_state::lon, met_geo::lon, synop_chunks::mask, bufr_subset_state::mask, synop_sec0::MiMi, synop_sec0::MjMj, report_date_ext::MM, report_date_ext::mm, bufr_subset_state::name, met_geo::name, bufr_subset_sequence_data::nd, synop_sec1::RRR, synop_sec3::RRR, synop_sec3::RRRR24, synop_chunks::s0, synop_chunks::s1, synop_chunks::s3, bufr_subset_sequence_data::sequence, SUBSET_MASK_HAVE_ALTITUDE, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_NAME, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2, SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW, SUBSET_MASK_HAVE_TYPE_STATION, SUBSET_MASK_HAVE_YEAR, syn_parse_x01(), syn_parse_x02(), syn_parse_x04(), syn_parse_x05(), syn_parse_x06(), syn_parse_x07(), syn_parse_x08(), syn_parse_x10(), syn_parse_x11(), syn_parse_x12(), syn_parse_x13(), syn_parse_x14(), syn_parse_x20(), syn_parse_x22(), syn_parse_x31(), SYNOP_EXT, synop_YYYYMMDDHHmm_to_YYGG(), metreport::t, bufr_subset_state::type, metreport::type, bufr_subset_state::type_report, bufr_atom_data::val, bufr_subset_state::val, bufr_descriptor::x, report_date_ext::YYYY, and YYYYMMDDHHmm_to_met_datetime().
Referenced by parse_subset_sequence().
 {
   int ival; // integer value for a descriptor
   size_t is;
   char aux[16];
   // clean data
   clean_synop_chunks ( syn );
   // reject if still not coded type
   if (strcmp(s->type_report,"AAXX") && strcmp(s->type_report,"BBXX"))
   {
     sprintf(err,"bufr2syn: parse_subset_as_synop(): '%s' reports still not decoded in this software", s->type_report);
     return 1;
   }
   syn->s0.MiMi[0] = s->type_report[0];
   syn->s0.MiMi[1] = s->type_report[1];
   syn->s0.MjMj[0] = s->type_report[2];
   syn->s0.MjMj[1] = s->type_report[3];
   strcpy(m->type, s->type_report);
   /**** First pass, sequential analysis *****/
   for ( is = 0; is < sq->nd; is++ )
     {
       // check if is a significance qualifier
       if (sq->sequence[is].desc.x == 8)
       {
         s->i = is;
         s->a = &sq->sequence[is];
         s->ival = ( int ) sq->sequence[is].val;
         s->val = sq->sequence[is].val;
         syn_parse_x08 ( syn, s);
       }
       if ( s->isq)   // case of an significance qualifier
         continue;
       s->i = is;
       s->ival = ( int ) sq->sequence[is].val;
       ival = ival;
       s->val = sq->sequence[is].val;
       s->a = &sq->sequence[is];
       switch ( sq->sequence[is].desc.x )
         {
         case 1: //localization descriptors
           syn_parse_x01 ( syn, s);
           break;
         case 2: //Date time descriptors
           syn_parse_x02 ( syn, s);
           break;
         case 4: //Date time descriptors
           syn_parse_x04 ( syn, s);
           break;
         case 5: //Position
           syn_parse_x05 ( syn, s);
           break;
         case 6: // Horizontal Position -2
           syn_parse_x06 ( syn, s);
           break;
         case 7: // Vertical position
           syn_parse_x07 ( syn, s);
           break;
         case 10: // Air Pressure descriptors
           syn_parse_x10 ( syn, s);
           break;
         case 11: // wind  data
           syn_parse_x11 ( syn, s);
           break;
         case 12: //Temperature descriptors
           syn_parse_x12 ( syn, s);
           break;
         case 13: // Humidity and precipitation data
           syn_parse_x13 ( syn, s);
           break;
         case 14: // Radiation
           syn_parse_x14 ( syn, s);
           break;
         case 20: // Cloud data
           syn_parse_x20 ( syn, s);
           break;
         case 22: // Oceanographic data
           syn_parse_x22 ( syn, s);
           break;
         case 31: // Replicators
           syn_parse_x31 ( syn, s);
           break;
         default:
           break;
         }
     }
   /* Check about needed descriptors */
   if (((s->mask & SUBSET_MASK_HAVE_LATITUDE) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_LONGITUDE) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_YEAR) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_MONTH) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_DAY) == 0) ||
       ((s->mask & SUBSET_MASK_HAVE_HOUR) == 0)
       )
       {
         sprintf(err,"bufr2syn: parse_subset_as_synop(): lack of mandatory descriptor in sequence");
         return 1;
       }
   if (strcmp(s->type_report, "AAXX") == 0 && (syn->s0.II[0] == 0 || syn->s0.iii[0] == 0))
     {
        sprintf(err,"bufr2syn: parse_subset_as_synop(): lack of mandatory index station for AAXX report");
        return 1;
     }
   /****** Second pass. Global results and consistence analysis ************/
   // set ir
   if ( syn->s1.RRR[0] == 0 && syn->s3.RRR[0] == 0 && syn->s3.RRRR24[0] == 0 )
     {
       // no prec data case
       syn->s1.ir[0] = '4';
     }
   else if ( syn->s1.RRR[0] == 0 && syn->s3.RRR[0] != 0 )
     syn->s1.ir[0] = '2';
   else if ( syn->s1.RRR[0] != 0 && syn->s3.RRR[0] == 0 )
     syn->s1.ir[0] = '1';
   else
     syn->s1.ir[0] = '0';
   // adjust iw
   if ( syn->s0.iw[0] == '/' && syn->s1.ff[0] != '/' )
     syn->s0.iw[0] = '1';
   // adjust ix
   if (syn->s1.ix[0] == '/' /*&& syn->s1.ww[0] == 0*/)
     {
       if ((s->mask & SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW) &&
           (s->mask & SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1) &&
           (s->mask & SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2)
          )
         {
           if (s->mask & SUBSET_MASK_HAVE_TYPE_STATION)
             {
               if (s->type == 1 || s->type == 2)
                 strcpy(syn->s1.ix,"2");
               else if (s->type == 0)
                 strcpy(syn->s1.ix,"5");
             }
           else
             strcpy(syn->s1.ix,"6"); //NOTE: here we assume an automatic station without W data
         }
       else if (s->mask & SUBSET_MASK_HAVE_TYPE_STATION)
         {
           if (s->type == 1)
             strcpy(syn->s1.ix,"3");
           else if (s->type == 0)
             strcpy(syn->s1.ix,"6");
         }
       else
         strcpy(syn->s1.ix,"6"); //NOTE: here we assume an automatic station without W data
     }
   /****** Final Adjust ***********/
   // fix YYGG according with YYYYMMDDHHmm
   synop_YYYYMMDDHHmm_to_YYGG ( syn );
   if ( strcmp(syn->e.mm,"00"))
     {
       strcpy ( syn->s1.GG, syn->e.HH );
       strcpy ( syn->s1.gg, syn->e.mm );
     }
   syn->mask |= SYNOP_EXT;
   // Fill some metreport fields
   if (strlen(syn->s0.II))
   {
     strcpy(m->g.index, syn->s0.II);
     strcat(m->g.index, syn->s0.iii);
   }
   else if (strlen(syn->s0.D_D))
   {
     strcpy(m->g.index, syn->s0.D_D);
   }
   else if (strlen(syn->s0.IIIII))
   {
     strcpy(m->g.index, syn->s0.IIIII);
   }
   if (s->mask & SUBSET_MASK_HAVE_LATITUDE)
     m->g.lat = s->lat;
   if (s->mask & SUBSET_MASK_HAVE_LONGITUDE)
     m->g.lon = s->lon;
   if (s->mask & SUBSET_MASK_HAVE_ALTITUDE)
     m->g.alt = s->alt;
   if (s->mask & SUBSET_MASK_HAVE_NAME)
     strcpy(m->g.name, s->name);
   if (s->mask & SUBSET_MASK_HAVE_COUNTRY)
     strcpy(m->g.country, s->country);
   sprintf ( aux,"%s%s%s%s%s", syn->e.YYYY, syn->e.MM, syn->e.DD, syn->e.HH, syn->e.mm );
   YYYYMMDDHHmm_to_met_datetime(&m->t, aux);
   return 0;
 }
int parse_subset_sequence (struct metreport * m, struct bufr_subset_sequence_data * sq, struct bufr_subset_state * st, struct synop_chunks * synop, struct buoy_chunks * buoy, int * kdtlst, size_t nlst, int * ksec1, char * err)
Definition at line 76 of file bufr2syn_sqparse.c.
References metreport::alphanum, find_descriptor(), find_descriptor_interval(), parse_subset_as_buoy(), parse_subset_as_synop(), print_buoy(), print_synop(), and bufr_subset_state::type_report.
Referenced by main().
 {
   /* Clean the state */
   memset(st, 0, sizeof(struct bufr_subset_state));
   /* First task to do is figure out the type of report */
   switch (ksec1[5])
     {
     case 0:
       if (find_descriptor_interval(kdtlst, nlst, 307079, 307086) ||
           find_descriptor(kdtlst, nlst,307091) ||
           find_descriptor(kdtlst, nlst,307096) ||
           ksec1[6] == 0 || ksec1[6] == 1 || ksec1[6] == 2)
         strcpy(st->type_report,"AAXX"); // FM-12 synop
       else if (find_descriptor(kdtlst, nlst,307090)
          || ksec1[6] == 3 || ksec1[6] == 4 || ksec1[6] == 5 )
         strcpy(st->type_report,"OOXX"); // FM-14 synop-mobil
       break;
     case 1:
       if (find_descriptor_interval(kdtlst, nlst, 308004, 308005) ||
           find_descriptor(kdtlst, nlst,308009) || find_descriptor(kdtlst, nlst,1011))
         strcpy(st->type_report,"BBXX"); // FM-13 ship
       else if (find_descriptor_interval(kdtlst, nlst, 308001, 308003) ||
         find_descriptor(kdtlst, nlst,1005) ||
         find_descriptor(kdtlst, nlst,2036) ||
         find_descriptor(kdtlst, nlst,2149) ||
         ksec1[6] == 25)
         strcpy(st->type_report,"ZZYY"); // FM-18 buoy
       break;
     case 2:
       if (find_descriptor_interval(kdtlst, nlst, 309050, 309052))
         strcpy(st->type_report,"TTXX"); // FM-13 ship
       break;
     default:
       sprintf(err, "The data category %d is not parsed at the moment", ksec1[5]);
       return 1;
     }
   if (st->type_report[0] == '\0')
   {
     sprintf(err, "Cannot find the report type\n");
     return 1;
   }
   //if(DEBUG)
   //  printf("Going to parse a %s report\n", st->type_report);
   // Parse FM-12, FM-13 and FM-14
   if (strcmp(st->type_report,"AAXX") == 0 || strcmp(st->type_report,"BBXX") == 0 || strcmp(st->type_report,"OOXX") == 0)
   {
     if (parse_subset_as_synop(m, synop, st, sq, err) == 0)
       return print_synop(m->alphanum, 2048, synop);
   }
   else if (strcmp(st->type_report,"ZZYY") == 0)
   {
     if (parse_subset_as_buoy(m, buoy, st, sq, err) == 0)
       return print_buoy(m->alphanum, 2048, buoy);
   }
   // when reached this point we have han error
   return 1;
 }
char * pascal_to_ppp (char * target, double P)
Converts pascal values (variation) into a ppp string.
Parameters
P the pressure variation in Pascal units
target string with the result
Definition at line 32 of file bufr2syn_x10.c.
Referenced by buoy_parse_x10(), and syn_parse_x10().
 {
   int ic;
   if ( P > 0 )
     ic = ( int ) ( P * 0.1 );
   else
     ic = ( int ) ( -P * 0.1 );
   sprintf ( target, "%03d", ic % 1000 );
   return target;
 }
char * pascal_to_PPPP (char * target, double P)
Converts pascal values into a PPPP string.
Parameters
P the pressure variation in Pascal units
target string with the result
Definition at line 50 of file bufr2syn_x10.c.
Referenced by buoy_parse_x10(), and syn_parse_x10().
 {
   int ic;
   ic = ( int ) ( P * 0.1 );
   sprintf ( target, "%04d", ic % 10000 );
   return target;
 }
char * percent_to_okta (char * target, double perc)
Converts percent cloud cover into okta.
Parameters
perc the precent cloud cover
target the resulting okta string
Definition at line 32 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   if ( perc < 12.5 )
     strcpy ( target,"0" );
   else if ( perc < 25.0 )
     strcpy ( target,"1" );
   else if ( perc < 37.5)
     strcpy ( target,"2" );
   else if ( perc < 50.0 )
     strcpy ( target,"3" );
   else if ( perc < 62.5 )
     strcpy ( target,"4" );
   else if ( perc < 75.0 )
     strcpy ( target,"5" );
   else if ( perc < 87.5 )
     strcpy ( target,"6" );
   else if ( perc < 100.0 )
     strcpy ( target,"7" );
   else if ( perc <= 112.5 )
     strcpy ( target,"8" );
   else if ( perc == 113.0 )
     strcpy ( target,"9" );
   return target;
 }
char * prec_to_RRR (char * target, double r)
converts a precipitation in Kg/m2 into a RRR string
Parameters
r the precipitation
target the resulting string
Definition at line 32 of file bufr2syn_x13.c.
Referenced by syn_parse_x13().
 {
   if ( r == 0.0 )
     strcpy ( target,"000" );
   else if ( r < 0.1 )
     strcpy ( target,"990" );
   else if ( r < 1.0 )
     sprintf ( target, "99%d", ( int ) ( r * 10.0 ) );
   else
     sprintf ( target, "%03d", ( int ) ( r ) );
   return target;
 }
char * prec_to_RRRR24 (char * target, double r)
converts a precipitation in Kg/m2 into a RRRR24 string
Parameters
r the precipitation
target the resulting string
Definition at line 69 of file bufr2syn_x13.c.
Referenced by syn_parse_x13().
 {
   if ( r < 0.0 || (r > 0.0 && r < 0.1))
     strcpy ( target,"9999" );
   else if ( r <= 999.8 )
     sprintf ( target,"%04d", ( int ) ( r * 10.0 ) );
   else
     strcpy ( target,"9998" );
   return target;
 }
int print_buoy (char * report, size_t lmax, struct buoy_chunks * b)
prints a buoy into a string
Parameters
report target string
lmax max size of string
b pointer to a struct buoy_chunks with the result of parse tasks
returns 0 if all went right
Definition at line 754 of file bufr2syn_print.c.
References BUOY_SEC1, BUOY_SEC2, BUOY_SEC3, buoy_chunks::e, buoy_chunks::mask, print_buoy_sec0(), print_buoy_sec1(), print_buoy_sec2(), print_buoy_sec3(), and report_date_ext::YYYY.
Referenced by parse_subset_sequence().
 {
   char *c;
   c = report;
   // Needs time extension
   if (b->e.YYYY[0] == 0)
     return 1;
   print_buoy_sec0(&c, lmax, b);
   if (b->mask & (BUOY_SEC1 | BUOY_SEC2 | BUOY_SEC3))
     {
       print_buoy_sec1(&c, lmax - strlen(report), b);
       print_buoy_sec2(&c, lmax - strlen(report), b);
       print_buoy_sec3(&c, lmax - strlen(report), b);
     }
   else
     c+= sprintf(c, " NIL");
   c += sprintf ( c, "=" );
   return 0;
 }
char * print_buoy_sec0 (char ** sec0, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 1.
Parameters
sec0 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 493 of file bufr2syn_print.c.
References buoy_sec0::A1, buoy_sec0::bw, check_len, buoy_sec0::D_D, report_date_ext::DD, buoy_chunks::e, buoy_sec0::GG, buoy_sec0::gg, report_date_ext::HH, buoy_sec0::iw, buoy_sec0::J, buoy_sec0::LaLaLaLaLa, buoy_sec0::LoLoLoLoLoLo, buoy_sec0::MiMi, buoy_sec0::MjMj, buoy_sec0::MM, report_date_ext::MM, report_date_ext::mm, buoy_sec0::nbnbnb, buoy_sec0::QA, buoy_sec0::Qc, buoy_sec0::Ql, buoy_sec0::Qt, buoy_chunks::s0, buoy_sec0::YY, and report_date_ext::YYYY.
Referenced by print_buoy().
 {
   char *c = *sec0;
   if (check_len(sec0,12))
     c += sprintf ( c, "%s%s%s%s%s", b->e.YYYY, b->e.MM, b->e.DD, b->e.HH, b->e.mm );
   // Print type
   if (check_len(sec0,5))
     c += sprintf ( c, " %s%s", b->s0.MiMi, b->s0.MjMj );
   if (check_len(sec0,6) && b->s0.A1[0] && b->s0.bw[0] && b->s0.nbnbnb[0])
     {
       c += sprintf ( c, " %s%s%s", b->s0.A1, b->s0.bw, b->s0.nbnbnb);
     }
   else if (check_len(sec0, 10) && b->s0.D_D)
     c += sprintf ( c, " %s", b->s0.D_D );
   if (check_len(sec0,6))
     c += sprintf(c, " %s%s%s", b->s0.YY, b->s0.MM, b->s0.J);
   if (check_len(sec0,6))
     {
       if (  b->s0.iw[0])
         c += sprintf(c, " %s%s%s", b->s0.GG, b->s0.gg, b->s0.iw);
       else
         c += sprintf(c, " %s%s/", b->s0.GG, b->s0.gg);
     }
   if (check_len(sec0,7))
     c += sprintf(c, " %s%s", b->s0.Qc, b->s0.LaLaLaLaLa);
   if (check_len(sec0,7))
     c += sprintf(c, " %s", b->s0.LoLoLoLoLoLo);
   if (b->s0.QA[0] || b->s0.Ql[0] || b->s0.Qt[0])
     {
       if (b->s0.Ql[0])
         c +=sprintf(c, " 6%s", b->s0.Ql);
       else
         c +=sprintf(c, " 6/");
       if (b->s0.Qt[0])
         c +=sprintf(c, "%s", b->s0.Qt);
       else
         c +=sprintf(c, "/");
       if (b->s0.QA[0])
         c +=sprintf(c, "%s/", b->s0.QA);
       else
         c +=sprintf(c, "//");
     }
   *sec0 = c;
   return *sec0;
 }
char * print_buoy_sec1 (char ** sec1, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 1.
Parameters
sec1 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 559 of file bufr2syn_print.c.
References buoy_sec1::a, BUOY_SEC1, check_len, buoy_sec1::dd, buoy_sec1::ff, buoy_chunks::mask, buoy_sec1::PoPoPoPo, buoy_sec1::ppp, buoy_sec1::PPPP, buoy_sec1::Qd, buoy_sec1::Qx, buoy_chunks::s1, buoy_sec1::sn1, buoy_sec1::sn2, buoy_sec1::TdTdTd, and buoy_sec1::TTT.
Referenced by print_buoy().
 {
   char *c = *sec1;
   if ( b->mask & BUOY_SEC1)
     {
       // 111QdQx
       c += sprintf(c," 111");
       if (b->s1.Qd[0])
         c += sprintf(c,"%s", b->s1.Qd);
       else
         c += sprintf(c,"/");
       if (b->s1.Qx[0])
         c += sprintf(c,"%s", b->s1.Qx);
       else
         c += sprintf(c,"/");
       // 0ddff
       if (check_len(sec1,6))
         {
           if (b->s1.dd[0] || b->s1.ff[0])
             {
               c += sprintf(c, " 0");
               if (b->s1.dd[0])
                 c += sprintf ( c, "%s", b->s1.dd);
               else
                 c += sprintf ( c, "//");
               if (b->s1.ff[0])
                 c += sprintf ( c, "%s", b->s1.ff);
               else
                 c += sprintf ( c, "//");
             }
         }
       // 1snTTT
       if (check_len(sec1,6) && b->s1.TTT[0])
         c += sprintf(c, " 1%s%s", b->s1.sn1, b->s1.TTT);
       // 2snTdTdTd
       if (check_len(sec1,6) && b->s1.TdTdTd[0])
         c += sprintf(c, " 2%s%s", b->s1.sn2, b->s1.TdTdTd);
       // 3PoPoPoPo
       if (check_len(sec1,6) && b->s1.PoPoPoPo[0])
         c += sprintf(c, " 3%s", b->s1.PoPoPoPo);
       // printf 4PPPP
       if ( check_len(sec1,6) && b->s1.PPPP[0] )
         c += sprintf ( c, " 4%s", b->s1.PPPP );
       // printf 5appp
       if ( check_len(sec1,6) && (b->s1.a[0] || b->s1.ppp[0]))
         {
           if ( b->s1.a[0] == 0 )
             b->s1.a[0] = '/';
           if ( b->s1.ppp[0] == 0 )
             strcpy ( b->s1.ppp, "///" );
           c += sprintf ( c, " 5%s%s", b->s1.a, b->s1.ppp );
         }
     }
   *sec1 = c;
   return *sec1;
 }
char * print_buoy_sec2 (char ** sec2, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 1.
Parameters
sec2 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 634 of file bufr2syn_print.c.
References BUOY_SEC2, check_len, buoy_sec2::HwaHwa, buoy_sec2::HwaHwaHwa, buoy_chunks::mask, buoy_sec2::PwaPwa, buoy_sec2::PwaPwaPwa, buoy_sec2::Qd, buoy_sec2::Qx, buoy_chunks::s2, buoy_sec2::sn, and buoy_sec2::TwTwTw.
Referenced by print_buoy().
 {
   char *c = *sec2;
   if (b->mask & BUOY_SEC2)
     {
       // 222QdQx
       c += sprintf(c," 222");
       if (b->s2.Qd[0])
         c += sprintf(c,"%s", b->s2.Qd);
       else
         c += sprintf(c,"/");
       if (b->s2.Qx[0])
         c += sprintf(c,"%s", b->s2.Qx);
       else
         c += sprintf(c,"/");
       // 0snTwTwTw
       if (check_len(sec2,6) && b->s2.TwTwTw[0] )
         c += sprintf ( c, " 0%s%s", b->s2.sn, b->s2.TwTwTw );
       // 1PwaPwaHwaHwa
       if (check_len(sec2,6) && (b->s2.PwaPwa[0] || b->s2.HwaHwa[0]))
         {
           c += sprintf(c, " 1");
           if (b->s2.PwaPwa[0])
             c += sprintf(c,"%s", b->s2.PwaPwa);
           else
             c += sprintf(c,"//");
           if (b->s2.HwaHwa[0])
             c += sprintf(c,"%s", b->s2.HwaHwa);
           else
             c += sprintf(c,"//");
         }
       // 20PwaPwaPwa
       if (check_len(sec2,6) && b->s2.PwaPwaPwa[0])
         c += sprintf(c, " 20%s", b->s2.PwaPwaPwa);
       // 21HwaHwaHwa
       if (check_len(sec2,6) && b->s2.HwaHwaHwa[0])
         c += sprintf(c, " 21%s", b->s2.HwaHwaHwa);
     }
   *sec2 = c;
   return *sec2;
 }
char * print_buoy_sec3 (char ** sec3, size_t lmax, struct buoy_chunks * b)
Prints the buoy section 3.
Parameters
sec3 the pointer where to print section
lmax max length permited
b pointer to s atruct buoy_chunks where the parse results are set
Definition at line 694 of file bufr2syn_print.c.
References BUOY_SEC3, b_sec3_layer2::ccc, check_len, b_sec3_layer2::dd, buoy_sec3::k2, buoy_sec3::k3, buoy_sec3::k6, buoy_sec3::l1, buoy_sec3::l2, buoy_chunks::mask, buoy_sec3::Qd1, buoy_sec3::Qd2, buoy_chunks::s3, b_sec3_layer1::SSSS, b_sec3_layer1::TTTT, b_sec3_layer1::zzzz, and b_sec3_layer2::zzzz.
Referenced by print_buoy().
 {
   char *c = *sec3;
   size_t l;
   if (check_len(sec3,6) && (b->mask & BUOY_SEC3))
     {
       c += sprintf(c, " 333%s%s", b->s3.Qd1, b->s3.Qd2);
       // check if has 8887k2
       l = 0;
       while (b->s3.l1[l].zzzz[0] && l < 32)
         {
           if (l == 0)
             c += sprintf(c, " 8887%s", b->s3.k2);
           c += sprintf(c,  " 2%s", b->s3.l1[l].zzzz);
           if (b->s3.l1[l].TTTT[0])
             c += sprintf(c,  " 3%s", b->s3.l1[l].TTTT);
           if (b->s3.l1[l].SSSS[0])
             c += sprintf(c,  " 4%s", b->s3.l1[l].SSSS);
           l++;
         }
       l = 0;
       while (b->s3.l2[l].zzzz[0] && l < 32)
         {
           if (l == 0)
             c += sprintf(c, " 66%s9%s", b->s3.k6, b->s3.k3);
           c += sprintf(c,  " 2%s", b->s3.l2[l].zzzz);
           if (b->s3.l2[l].dd[0] || b->s3.l2[l].ccc[0])
             {
               if (b->s3.l2[l].dd[0])
                 c += sprintf(c,  " %s", b->s3.l2[l].dd);
               else
                 c += sprintf(c,  " //");
               if (b->s3.l2[l].ccc[0])
                 c += sprintf(c,  "%s", b->s3.l2[l].ccc);
               else
                 c += sprintf(c,  "///");
             }
           l++;
         }
     }
   *sec3 = c;
   return *sec3;
 }
int print_csv (FILE * f, struct metreport * m)
prints a struct metreport in labeled csv format
Parameters
f pointer to a file already open by caller routine
m pointer to a struct metreport containing the data to print
Definition at line 32 of file bufr2syn_csv.c.
References metreport::alphanum, met_geo::alt, gts_header::bname, gts_header::center, met_geo::country, met_datetime::datime, gts_header::dtrel, gts_header::filename, metreport::g, metreport::h, met_geo::index, met_geo::lat, met_geo::lon, met_geo::name, gts_header::order, metreport::t, and metreport::type.
Referenced by main().
 {
   // prints header
   fprintf(f, "\"%s\",", m->type);
   fprintf(f, "\"%s\",",m->h->filename);
   // print GTS_HEADER
   if (m->h != NULL)
     fprintf(f, "\"%s %s %s %s\",",m->h->bname, m->h->center, m->h->dtrel, m->h->order);
   else
     fprintf(f, ",");
   // print DATE AND TIME
   fprintf(f, "\"%s\",",m->t.datime);
   // Geo data
   if (strlen(m->g.index))
     fprintf(f, "\"%s\",", m->g.index);
   else
     fprintf(f, ",");
   if (strlen(m->g.name))
     fprintf(f, "\"%s\",", m->g.name);
   else
     fprintf(f, ",");
   if (strlen(m->g.country))
     fprintf(f, "\"%s\",", m->g.country);
   else
     fprintf(f, ",");
   fprintf(f, "%.6lf,", m->g.lat);
   fprintf(f, "%.6lf,", m->g.lon);
   fprintf(f, "%.1lf,", m->g.alt);
   fprintf(f, "\"%s\"\n", m->alphanum);
   return 0;
 }
int print_json (FILE * f, struct metreport * m)
prints a struct metreport in json format
Parameters
f pointer to a file already open by caller routine
m pointer to a struct metreport containing the data to print
Definition at line 32 of file bufr2syn_json.c.
References metreport::alphanum, met_geo::alt, gts_header::bname, gts_header::center, met_geo::country, met_datetime::datime, gts_header::dtrel, gts_header::filename, metreport::g, metreport::h, met_geo::index, met_geo::lat, met_geo::lon, met_geo::name, gts_header::order, metreport::t, and metreport::type.
Referenced by main().
 {
   fprintf(f, "{\"metreport\" : { \n");
   fprintf(f, "  \"type\": \"%s\",\n", m->type);
   fprintf(f, "  \"bufrfile\": \"%s\",\n", m->h->filename);
   fprintf(f, "  \"gts_header\": \"%s %s %s %s\",\n", m->h->bname, m->h->center, m->h->dtrel, m->h->order);
   fprintf(f, "  \"observation_datetime\": \"%s\",\n", m->t.datime);
   fprintf(f, "  \"geo\": { \n");
   if (strlen(m->g.index))
     fprintf(f, "    \"index\": \"%s\",\n", m->g.index);
   if (strlen(m->g.name))
     fprintf(f, "    \"name\": \"%s\",\n", m->g.name);
   if (strlen(m->g.country))
     fprintf(f, "    \"country\": \"%s\",\n", m->g.country);
   fprintf(f, "    \"latitude\": %.6lf,\n", m->g.lat);
   fprintf(f, "    \"longitude\": %.6lf,\n", m->g.lon);
   fprintf(f, "    \"altitude\": %.1lf\n", m->g.alt);
   fprintf(f, "    },\n");
   fprintf(f, "  \"report\": \"%s\"\n", m->alphanum);
   fprintf(f, "  }\n");
   fprintf(f, "}\n");
   return 0;
 }
int print_synop (char * report, size_t lmax, struct synop_chunks * syn)
prints a synop into a string
Parameters
report target string
lmax max size of string
syn pointer to a struct synop_chunks with the result of parse tasks
returns 0 if all went right
Definition at line 456 of file bufr2syn_print.c.
References synop_chunks::e, synop_chunks::mask, print_synop_sec0(), print_synop_sec1(), print_synop_sec2(), print_synop_sec3(), print_synop_sec5(), SYNOP_SEC1, SYNOP_SEC2, SYNOP_SEC3, SYNOP_SEC5, and report_date_ext::YYYY.
Referenced by parse_subset_sequence().
 {
   char *c;
   c = report;
   // Needs time extension
   if (syn->e.YYYY[0] == 0)
     return 1;
   print_synop_sec0(&c, lmax, syn);
   if (syn->mask & (SYNOP_SEC1 | SYNOP_SEC2 | SYNOP_SEC3 | SYNOP_SEC5))
     {
       print_synop_sec1(&c, lmax - strlen(report), syn);
       print_synop_sec2(&c, lmax - strlen(report), syn);
       print_synop_sec3(&c, lmax - strlen(report), syn);
       print_synop_sec5(&c, lmax - strlen(report), syn);
     }
   else
     c += sprintf(c, " NIL");
   c += sprintf ( c, "=" );
   return 0;
 }
char * print_synop_sec0 (char ** sec0, size_t lmax, struct synop_chunks * syn)
Prints the synop section 0 (header)
Parameters
sec0 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 39 of file bufr2syn_print.c.
References synop_sec0::A1, synop_sec0::bw, check_len, synop_sec0::D_D, report_date_ext::DD, synop_chunks::e, synop_sec0::GG, synop_sec0::h0h0h0h0, report_date_ext::HH, synop_sec0::II, synop_sec0::iii, synop_sec0::im, synop_sec0::iw, synop_sec0::LaLaLa, synop_sec0::LoLoLoLo, synop_sec0::MiMi, synop_sec0::MjMj, report_date_ext::MM, report_date_ext::mm, synop_sec0::MMM, synop_sec0::nbnbnb, synop_sec0::Qc, synop_chunks::s0, synop_sec0::Ula, synop_sec0::Ulo, synop_sec0::YY, and report_date_ext::YYYY.
Referenced by print_synop().
 {
   char *c = *sec0;
   if (check_len(sec0,12))
     c += sprintf ( c, "%s%s%s%s%s", syn->e.YYYY, syn->e.MM, syn->e.DD, syn->e.HH, syn->e.mm );
   // Print type
   if (check_len(sec0,5))
     c += sprintf ( c, " %s%s", syn->s0.MiMi, syn->s0.MjMj );
   if (check_len(sec0,6))
     {
       if (syn->s0.D_D[0])
         c += sprintf ( c, " %s", syn->s0.D_D);
       else if (syn->s0.A1[0] && syn->s0.bw[0] && syn->s0.nbnbnb[0])
         c += sprintf ( c, " %s%s%s", syn->s0.A1, syn->s0.bw, syn->s0.nbnbnb);
     }
   // print YYGGiw
   if (check_len(sec0,6))
     c += sprintf ( c, " %s%s%s", syn->s0.YY, syn->s0.GG, syn->s0.iw );
   // print IIiii
   if (check_len(sec0,6) && syn->s0.II[0])
     c += sprintf ( c, " %s%s", syn->s0.II, syn->s0.iii );
   else
     {
       if (syn->s0.LaLaLa[0])
         c += sprintf ( c, " 99%s", syn->s0.LaLaLa );
       else
         c += sprintf ( c, " 99///");
       if (syn->s0.Qc[0] && syn->s0.LoLoLoLo[0])
         c += sprintf ( c, " %s%s", syn->s0.Qc, syn->s0.LoLoLoLo);
       else
         c += sprintf ( c, " /////");
     }
   if (strcmp(syn->s0.MiMi, "OO") == 0)
     {
       if (syn->s0.MMM[0] && syn->s0.Ula && syn->s0.Ulo)
         c += sprintf ( c, " %s%s%s", syn->s0.MMM, syn->s0.Ula, syn->s0.Ulo);
       if (syn->s0.h0h0h0h0[0])
         c += sprintf ( c, " %s%s", syn->s0.h0h0h0h0, syn->s0.im);
     }
   *sec0 = c;
   return *sec0;
 }
char * print_synop_sec1 (char ** sec1, size_t lmax, struct synop_chunks * syn)
Prints the synop section 1.
Parameters
sec1 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 99 of file bufr2syn_print.c.
References synop_sec1::a, synop_sec1::Ch, check_len, synop_sec1::Cl, synop_sec1::Cm, synop_sec1::dd, synop_sec1::ff, synop_sec1::fff, synop_sec1::GG, synop_sec1::gg, synop_sec1::h, synop_sec1::ir, synop_sec1::ix, synop_chunks::mask, synop_sec1::N, synop_sec1::Nh, synop_sec1::PoPoPoPo, synop_sec1::ppp, synop_sec1::PPPP, synop_sec1::RRR, synop_chunks::s1, synop_sec1::sn1, synop_sec1::sn2, SYNOP_SEC1, synop_sec1::TdTdTd, synop_sec1::tr, synop_sec1::TTT, synop_sec1::VV, synop_sec1::W1, synop_sec1::W2, and synop_sec1::ww.
Referenced by print_synop().
 {
   char *c = *sec1;
   if (syn->mask & SYNOP_SEC1)
     {
       // printf irixhVV
       if (check_len(sec1,6))
         c += sprintf ( c, " %s%s%s%s", syn->s1.ir, syn->s1.ix, syn->s1.h, syn->s1.VV );
       // printf Nddff
       if (check_len(sec1,6))
         c += sprintf ( c, " %s%s%s", syn->s1.N, syn->s1.dd, syn->s1.ff );
       if (check_len(sec1,6) && strlen ( syn->s1.fff ) )
         c += sprintf ( c, " 00%s", syn->s1.fff );
       // printf 1snTTT
       if (check_len(sec1,6) && syn->s1.TTT[0] )
         c += sprintf ( c, " 1%s%s", syn->s1.sn1, syn->s1.TTT );
       // printf 2snTdTdTd
       if ( check_len(sec1,6) && syn->s1.TdTdTd[0] )
         c += sprintf ( c, " 2%s%s", syn->s1.sn2, syn->s1.TdTdTd );
       // printf 3PoPoPoPo
       if ( check_len(sec1,6) && syn->s1.PoPoPoPo[0] )
         c += sprintf ( c, " 3%s", syn->s1.PoPoPoPo );
       // printf 4PPPP
       if ( check_len(sec1,6) && syn->s1.PPPP[0] )
         c += sprintf ( c, " 4%s", syn->s1.PPPP );
       // printf 5appp
       if ( check_len(sec1,6) && (syn->s1.a[0] || syn->s1.ppp[0]))
         {
           if ( syn->s1.a[0] == 0 )
             syn->s1.a[0] = '/';
           if ( syn->s1.ppp[0] == 0 )
             strcpy ( syn->s1.ppp, "///" );
           c += sprintf ( c, " 5%s%s", syn->s1.a, syn->s1.ppp );
         }
       // printf 6RRRtr
       if ( check_len(sec1,6) && (syn->s1.tr[0] || syn->s1.RRR[0]))
         {
           if ( syn->s1.tr[0] == 0 )
             syn->s1.tr[0] = '/';
           if ( syn->s1.RRR[0] == 0 )
             strcpy ( syn->s1.RRR, "///" );
           c += sprintf ( c, " 6%s%s", syn->s1.RRR, syn->s1.tr);
         }
       if ( check_len(sec1,6) && (syn->s1.ww[0] || syn->s1.W1[0] || syn->s1.W2[0]))
         {
           if ( syn->s1.ww[0] == 0 )
             strcpy ( syn->s1.ww, "//" );
           if ( syn->s1.W1[0] == 0 )
             strcpy ( syn->s1.W1, "/" );
           if ( syn->s1.W2[0] == 0 )
             strcpy ( syn->s1.W2, "/" );
           c += sprintf ( c, " 7%s%s%s", syn->s1.ww, syn->s1.W1, syn->s1.W2 );
         }
       if ( check_len(sec1,6) && ((syn->s1.Nh[0] && syn->s1.Nh[0] != '0' && syn->s1.Nh[0] != '/') ||
                                  (syn->s1.Cl[0] && syn->s1.Cl[0] != '0' && syn->s1.Cl[0] != '/') ||
                                  (syn->s1.Cm[0] && syn->s1.Cm[0] != '0' && syn->s1.Cm[0] != '/') ||
                                  (syn->s1.Ch[0] && syn->s1.Ch[0] != '0' && syn->s1.Ch[0] != '/')))
         {
           if ( syn->s1.Nh[0] == 0 )
             strcpy ( syn->s1.Nh, "/" );
           if ( syn->s1.Cl[0] == 0 )
             strcpy ( syn->s1.Cl, "/" );
           if ( syn->s1.Cm[0] == 0 )
             strcpy ( syn->s1.Cm, "/" );
           if ( syn->s1.Ch[0] == 0 )
             strcpy ( syn->s1.Ch, "/" );
           c += sprintf(c, " 8%s%s%s%s", syn->s1.Nh, syn->s1.Cl, syn->s1.Cm, syn->s1.Ch);
         }
       if ( check_len(sec1,6) && syn->s1.GG[0] )
         c+= sprintf ( c, " 9%s%s", syn->s1.GG, syn->s1.gg );
     }
   *sec1 = c;
   return *sec1;
 }
char * print_synop_sec2 (char ** sec2, size_t lmax, struct synop_chunks * syn)
Prints the synop section 2.
Parameters
sec2 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 195 of file bufr2syn_print.c.
References check_len, synop_sec2::Ds, synop_sec2::dw1dw1, synop_sec2::dw2dw2, synop_sec2::Hw1Hw1, synop_sec2::Hw2Hw2, synop_sec2::HwaHwa, synop_sec2::HwaHwaHwa, synop_sec2::HwHw, synop_chunks::mask, synop_sec2::Pw1Pw1, synop_sec2::Pw2Pw2, synop_sec2::PwaPwa, synop_sec2::PwPw, synop_chunks::s2, synop_sec2::ss, synop_sec2::sw, SYNOP_SEC2, synop_sec2::TbTbTb, synop_sec2::TwTwTw, and synop_sec2::vs.
Referenced by print_synop().
 {
   char *c = *sec2;
   if ( syn->mask & SYNOP_SEC2 )
     {
       // 222Dsvs
       if (check_len(sec2,46))
         {
           c += sprintf ( c, " 222");
           if (syn->s2.Ds[0])
             c += sprintf ( c, "%s", syn->s2.Ds);
           else
             c += sprintf ( c, "/");
           if (syn->s2.vs[0])
             c += sprintf ( c, "%s", syn->s2.vs);
           else
             c += sprintf ( c, "/");
         }
       // printf 0ssTwTwTw
       if (check_len(sec2,6) && syn->s2.TwTwTw[0] )
         c += sprintf ( c, " 0%s%s", syn->s2.ss, syn->s2.TwTwTw );
       if (check_len(sec2,6) && (syn->s2.PwaPwa[0] || syn->s2.HwaHwa[0]))
         {
           if (syn->s2.PwaPwa[0])
             c += sprintf ( c, " 1%s", syn->s2.PwaPwa);
           else
             c += sprintf ( c, " 1//");
           if (syn->s2.HwaHwa[0])
             c += sprintf ( c, "%s", syn->s2.HwaHwa);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.PwPw[0] || syn->s2.HwHw[0]))
         {
           if (syn->s2.PwPw[0])
             c += sprintf ( c, " 2%s", syn->s2.PwPw);
           else
             c += sprintf ( c, " 2//");
           if (syn->s2.HwHw[0])
             c += sprintf ( c, "%s", syn->s2.HwHw);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.dw1dw1[0] || syn->s2.dw2dw2[0]))
         {
           if (syn->s2.dw1dw1[0])
             c += sprintf ( c, " 3%s", syn->s2.dw1dw1);
           else
             c += sprintf ( c, " 3//");
           if (syn->s2.dw2dw2[0])
             c += sprintf ( c, "%s", syn->s2.dw2dw2);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.Pw1Pw1[0] || syn->s2.Hw1Hw1[0]))
         {
           if (syn->s2.Pw1Pw1[0])
             c += sprintf ( c, " 4%s", syn->s2.Pw1Pw1);
           else
             c += sprintf ( c, " 4//");
           if (syn->s2.Hw1Hw1[0])
             c += sprintf ( c, "%s", syn->s2.Hw1Hw1);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && (syn->s2.Pw2Pw2[0] || syn->s2.Hw2Hw2[0]))
         {
           if (syn->s2.Pw2Pw2[0])
             c += sprintf ( c, " 5%s", syn->s2.Pw2Pw2);
           else
             c += sprintf ( c, " 5//");
           if (syn->s2.Hw2Hw2[0])
             c += sprintf ( c, "%s", syn->s2.Hw2Hw2);
           else
             c += sprintf ( c, "//");
         }
       if (check_len(sec2,6) && syn->s2.HwaHwaHwa[0])
         {
           c += sprintf(c, " 70%s", syn->s2.HwaHwaHwa);
         }
       if (check_len(sec2,6) && syn->s2.TbTbTb[0] )
         c += sprintf ( c, " 8%s%s", syn->s2.sw, syn->s2.TbTbTb );
     }
   *sec2 = c;
   return *sec2;
 }
char * print_synop_sec3 (char ** sec3, size_t lmax, struct synop_chunks * syn)
Prints the synop section 3.
Parameters
sec3 the pointer where to print section
lmax max length permited
syn pointer to s atruct synop_chunks where the parse results are set
Definition at line 306 of file bufr2syn_print.c.
References nub3::C, check_len, synop_sec3::d9, synop_sec3::E, synop_sec3::FFFF, synop_sec3::FFFF24, nub3::hshs, synop_sec3::j5, synop_sec3::j524, synop_sec3::jjj, synop_chunks::mask, data9::misc, data9::n, nub3::Ns, synop_sec3::nub, synop_sec3::RRR, synop_sec3::RRRR24, synop_chunks::s3, synop_sec3::snn, synop_sec3::snx, misc3::SpSp, misc3::spsp, synop_sec3::SS, synop_sec3::SSS, SYNOP_SEC3, synop_sec3::TnTnTn, synop_sec3::tr, synop_sec3::TxTxTx, and synop_sec3::XoXoXoXo.
Referenced by print_synop().
 {
   size_t i;
   char *c = *sec3, *c0;
   if ( syn->mask & SYNOP_SEC3 )
     {
       if (check_len(sec3,4))
         c += sprintf ( c, " 333" );
       // init point to write info.
       // in case we finally write nothing in this section
       c0 = c;
       // printf 1snxTxTxTx
       if (check_len(sec3,6) && syn->s3.XoXoXoXo[0])
         {
           c += sprintf(c, " 0%s", syn->s3.XoXoXoXo);
         }
       // printf 1snxTxTxTx
       if (check_len(sec3,6) && syn->s3.snx[0])
         {
           c += sprintf(c, " 1%s%s", syn->s3.snx, syn->s3.TxTxTx);
         }
       // printf 1snnTnTnTn
       if (check_len(sec3,6) && syn->s3.snn[0])
         {
           c += sprintf(c, " 2%s%s", syn->s3.snn, syn->s3.TnTnTn);
         }
       // printf 3Ejjj
       if (check_len(sec3,6) && (syn->s3.E[0] || syn->s3.jjj[0]))
         {
           if (syn->s3.E[0] == 0)
             syn->s3.E[0] = '/';
           if (syn->s3.jjj[0] == 0)
             strcpy(syn->s3.jjj, "///");
           c += sprintf(c, " 3%s%s", syn->s3.E, syn->s3.jjj);
         }
       /**** Radiation Sunshine gropus ***/
       // print 55SSS
       if (check_len(sec3,6) && syn->s3.SSS[0] && strcmp(syn->s3.SSS,"///"))
         {
           c += sprintf(c, " 55%s", syn->s3.SSS);
           for (i = 0; i < 7; i++)
             {
               if (syn->s3.j524[i][0])
                 sprintf(c, " %s%s", syn->s3.j524[i], syn->s3.FFFF24[i]);
             }
         }
       // print 553SS
       if (check_len(sec3,6) && syn->s3.SS[0] && strcmp(syn->s3.SS,"//"))
         {
           c += sprintf(c, " 553%s", syn->s3.SS);
           for (i = 0; i < 7; i++)
             {
               if (syn->s3.j5[i][0])
                 sprintf(c, " %s%s", syn->s3.j5[i], syn->s3.FFFF[i]);
             }
         }
       // printf 6RRRtr
       if (check_len(sec3,6) && ( syn->s3.tr[0] || syn->s3.RRR[0]) )
         {
           if ( syn->s3.tr[0] == 0 )
             syn->s3.tr[0] = '/';
           if ( syn->s3.RRR[0] == 0 )
             strcpy ( syn->s3.RRR, "///" );
           c += sprintf ( c, " 6%s%s", syn->s3.RRR ,syn->s3.tr);
         }
       if ( check_len(sec3,6) && syn->s3.RRRR24[0] )
         c += sprintf ( c, " 7%s", syn->s3.RRRR24);
       // additional cloud layers
       i = 0;
       while (i < 4 && syn->s3.nub[i].hshs[0])
       {
         c += sprintf ( c, " 8%s%s%s", syn->s3.nub[i].Ns, syn->s3.nub[i].C, syn->s3.nub[i].hshs);
         i++;
       }
       // additional info
       for (i = 0; i < syn->s3.d9.n ; i++)
       {
         c += sprintf(c, " %s%s", syn->s3.d9.misc[i].SpSp, syn->s3.d9.misc[i].spsp);
       }
       if (c != c0)
         *sec3 = c;
     }
   return *sec3;
 }
int print_xml (FILE * f, struct metreport * m)
prints a struct metreport in xml format
Parameters
f pointer to a file already open by caller routine
m pointer to a struct metreport containing the data to print
Definition at line 32 of file bufr2syn_xml.c.
References metreport::alphanum, met_geo::alt, gts_header::bname, gts_header::center, met_geo::country, met_datetime::datime, gts_header::dtrel, gts_header::filename, metreport::g, metreport::h, met_geo::index, met_geo::lat, met_geo::lon, met_geo::name, gts_header::order, metreport::t, and metreport::type.
Referenced by main().
 {
   // prints header
   fprintf(f, "<metreport type=%s>\n", m->type);
   fprintf(f, "<bufrfile>%s</bufrfile>\n",m->h->filename);
   // print GTS_HEADER
   if (m->h != NULL)
     fprintf(f, " <gts_header>%s %s %s %s</gts_header>\n",m->h->bname, m->h->center, m->h->dtrel, m->h->order);
   // print DATE AND TIME
   fprintf(f, " <observation_datetime>%s</observation_datetime>\n",m->t.datime);
   // Geo data
   fprintf(f, " <geo>\n");
   if (strlen(m->g.index))
     fprintf(f, "  <index>%s</index>\n", m->g.index);
   if (strlen(m->g.name))
     fprintf(f, "  <name>%s</name>\n", m->g.name);
   if (strlen(m->g.country))
     fprintf(f, "  <country>%s</country>\n", m->g.country);
   fprintf(f, "  <latitude>%.6lf</latitude>\n", m->g.lat);
   fprintf(f, "  <longitude>%.6lf</longitude>\n", m->g.lon);
   fprintf(f, "  <altitude>%.1lf</altitude>\n", m->g.alt);
   fprintf(f, " </geo>\n");
   fprintf(f, " <report>%s</report>\n", m->alphanum);
   fprintf(f, "</metreport>\n");
   return 0;
 }
int read_bufr (unsigned char * bufr, char * filename, int * length)
read a bufr file as an array of unsigned chars
Parameters
bufr pointer to an array of unsigned chars. On output it will contain the bufr
filename string with complete pathname of bufr file to read
length On input max length allocated by caller. On output real length of bufr
Definition at line 34 of file bufr2syn_io.c.
References three_bytes_to_uint().
Referenced by main().
 {
   int aux;
   size_t n = 0;
   FILE *fp;
   /* Open input file */
   if ((fp = fopen(filename, "r")) == NULL )
     {
       fprintf(stderr, "cannot open file '%s'\n", filename);
       exit(EXIT_FAILURE);
     }
   while ((aux = fgetc(fp)) != EOF && (int)n < *length)
     bufr[n++] = aux;
   *length = n;
   // close the file
   fclose(fp);
   if (n < 8) // we need at least 8 bytes
     return -4;
   // check if begins with BUFR
   if (bufr[0] != 'B' || bufr[1] != 'U' || bufr[2] != 'F' || bufr[3] != 'R')
     return -1;
   // check if end with '7777'
   if (bufr[n - 4] != '7' || bufr[n - 3] != '7' || bufr[n - 2] != '7'
       || bufr[n - 1] != '7')
     return -2;
   //printf("%d %d\n", n, three_bytes_to_uint(bufr + 4));
   // check about the expected size
   if (n != three_bytes_to_uint(bufr + 4))
     return -3;
   return 0;
 }
int read_table_c (char tablec[MAXLINES_TABLEC][92], size_t * nlines_tablec, char * bufrtables_dir, int ksec1[40])
Definition at line 64 of file bufr2syn_tablec.c.
References get_ecmwf_tablename().
Referenced by main().
 {
   char *c, file[256];
   FILE *t;
   size_t i = 0;
   *nlines_tablec = 0;
   get_ecmwf_tablename(&file[0], 'C', bufrtables_dir, ksec1);
   if ((t = fopen(file, "r")) == NULL)
     {
       fprintf(stderr,"Unable to open table C file '%s'\n", file);
       return 0;
     }
   while (fgets(tablec[i], 90, t) != NULL && i < MAXLINES_TABLEC)
     {
       // supress the newline
       if ((c = strrchr(tablec[i],'\n')) != NULL)
         *c = '\0';
       i++;
     }
   fclose(t);
   *nlines_tablec = i;
   //printf("file='%s', NLINES_TABLEC=%d\n", file,NLINES_TABLEC);
   return i;
 }
char* secs_to_tt (char * tt, int secs)
Definition at line 26 of file bufr2syn_x11.c.
Referenced by syn_parse_x11().
 {
   int i;
   i = (-secs) / 360;
   if (i <= 60)
     sprintf(tt, "%02d", i);
   else if (i < 700)
     sprintf(tt, "61");
   else if (i < 800)
     sprintf(tt, "62");
   else if (i < 900)
     sprintf(tt, "63");
   else if (i < 1000)
     sprintf(tt, "64");
   else if (i < 1100)
     sprintf(tt, "65");
   else if (i < 1200)
     sprintf(tt, "66");
   else if (i < 1800)
     sprintf(tt, "67");
   else
     sprintf(tt, "68");
   return tt;
 }
int set_environment (char * default_bufrtables, char * bufrtables_dir)
int syn_parse_x01 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x01.c.
References bufr_subset_state::a, synop_sec0::A1, adjust_string(), synop_sec0::bw, bufr_subset_state::country, bufr_atom_data::ctable, bufr_atom_data::cval, synop_sec0::D_D, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::II, synop_sec0::iii, bufr_subset_state::ival, bufr_atom_data::mask, bufr_subset_state::mask, bufr_subset_state::name, synop_sec0::Reg, synop_chunks::s0, SUBSET_MASK_HAVE_COUNTRY, SUBSET_MASK_HAVE_NAME, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[80];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 01 001
       sprintf ( syn->s0.II, "%02d", s->ival );
       break;
     case 2: // 0 01 002
       sprintf ( syn->s0.iii, "%03d", s->ival );
       break;
     case 3: // 0 01 003
       sprintf ( syn->s0.A1, "%d", s->ival );
       if (strcmp(syn->s0.A1, "1") == 0)
         strcpy(syn->s0.Reg, "I");
       else if (strcmp(syn->s0.A1, "2") == 0)
         strcpy(syn->s0.Reg, "II");
       else if (strcmp(syn->s0.A1, "3") == 0)
         strcpy(syn->s0.Reg, "III");
       else if (strcmp(syn->s0.A1, "4") == 0)
         strcpy(syn->s0.Reg, "IV");
       else if (strcmp(syn->s0.A1, "5") == 0)
         strcpy(syn->s0.Reg, "V");
       else if (strcmp(syn->s0.A1, "6") == 0)
         strcpy(syn->s0.Reg, "VI");
       break;
     case 4: // 0 01 004
     case 20: // 0 01 004
       sprintf ( syn->s0.bw, "%d", s->ival );
       break;
     case 11: // 0 01 011
       if (strlen(s->a->cval) < 16)
         {
           strcpy(aux, s->a->cval);
           adjust_string(aux);
           if (strlen(aux) < 10)
             strcpy( syn->s0.D_D, aux);
         }
       break;
     case 15: // 0 01 015
       if (strlen(s->a->cval) <= 80)
         {
           strcpy(aux, s->a->cval);
           adjust_string(aux);
           strcpy(s->name, aux);
           s->mask |= SUBSET_MASK_HAVE_NAME;
         }
       break;
     case 101: // 0 01 101
       if (strlen(s->a->ctable) <= 256)
         {
           strcpy(aux, s->a->ctable);
           adjust_string(aux);
           strcpy(s->country, aux);
           s->mask |= SUBSET_MASK_HAVE_COUNTRY;
         }
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x02 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 02.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x02.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, synop_sec0::iw, synop_sec1::ix, bufr_atom_data::mask, bufr_subset_state::mask, synop_chunks::s0, synop_chunks::s1, SUBSET_MASK_HAVE_TYPE_STATION, bufr_subset_state::type, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   switch ( s->a->desc.y )
     {
     case 1: // 0 02 001
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         strcpy (syn->s1.ix,"/");
         return 0;
       }
       s->type = s->ival;
       s->mask |= SUBSET_MASK_HAVE_TYPE_STATION;
       break;
     case 2: // 0 02 002
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if ( s->ival & 4 )
         strcpy ( syn->s0.iw, "4" );
       else
         strcpy ( syn->s0.iw, "1" );
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x04 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 04.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x04.c.
References bufr_subset_state::a, report_date_ext::DD, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_chunks::e, report_date_ext::HH, bufr_subset_state::i, bufr_subset_state::itval, bufr_subset_state::ival, bufr_subset_state::jtval, bufr_subset_state::k_itval, bufr_subset_state::k_jtval, bufr_atom_data::mask, bufr_subset_state::mask, report_date_ext::MM, report_date_ext::mm, SUBSET_MASK_HAVE_DAY, SUBSET_MASK_HAVE_HOUR, SUBSET_MASK_HAVE_MINUTE, SUBSET_MASK_HAVE_MONTH, SUBSET_MASK_HAVE_YEAR, bufr_descriptor::y, and report_date_ext::YYYY.
Referenced by parse_subset_as_synop().
 {
   switch ( s->a->desc.y )
     {
     case 1: // 0 04 001
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       sprintf ( syn->e.YYYY, "%04d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_YEAR;
       break;
     case 2: // 0 04 002
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       sprintf ( syn->e.MM, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_MONTH;
       break;
     case 3: // 0 04 003
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       sprintf ( syn->e.DD, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_DAY;
       //sprintf(syn->s0.YY, "%02d", (int) sq->sequence[is].val);
       break;
     case 4: // 0 04 004
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       sprintf ( syn->e.HH, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_HOUR;
       //sprintf(syn->s0.GG, "%02d", (int) sq->sequence[is].val);
       break;
     case 5: // 0 04 005
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       sprintf ( syn->e.mm, "%02d", s->ival );
       s->mask |= SUBSET_MASK_HAVE_MINUTE;
       break;
       // store latest displacement in seconds
     case 23: // 0 04 023
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival * 86400;
       break;
     case 24: // 0 04 024
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival * 3600;
       break;
     case 25: // 0 04 025
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival * 60;
       break;
     case 26: // 0 04 026
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
       {
         s->k_jtval = s->k_itval;
         s->jtval = s->itval;
         s->k_itval = s->i;
         s->itval = 0;
         return 0;
       }
       s->k_jtval = s->k_itval;
       s->jtval = s->itval;
       s->k_itval = s->i;
       s->itval = s->ival;
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x05 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 05.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 35 of file bufr2syn_x05.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::LaLaLa, bufr_subset_state::lat, latlon_to_MMM(), synop_sec0::LoLoLoLo, bufr_subset_state::lon, bufr_atom_data::mask, bufr_subset_state::mask, synop_sec0::MMM, synop_sec0::Qc, synop_chunks::s0, SUBSET_MASK_HAVE_LATITUDE, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, synop_sec0::Ula, synop_sec0::Ulo, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 05 001
     case 2: // 0 05 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LATITUDE_SOUTH; // Sign for latitude
       s->mask |= SUBSET_MASK_HAVE_LATITUDE;
       ia = (int) (fabs(s->val) * 10.0 + 0.5);
       sprintf(syn->s0.LaLaLa, "%03d",ia);
       syn->s0.Ula[0] = syn->s0.LaLaLa[1];
       s->lat = s->val;
     break;
     case 11: // 0 05 011
     case 12: // 0 05 012
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = (int) (fabs(s->val) * 10.0 + 0.5);
       sprintf(syn->s0.LoLoLoLo, "%04d",ia);
       syn->s0.Ulo[0] = syn->s0.LoLoLoLo[2];
       s->lon = s->val;
     break;
     default:
       break;
     }
   // check if set both LaLaLa and LoLoLoLo to set Qc
   if ((syn->s0.Qc[0] == 0) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0])
   {
     if (s->mask & SUBSET_MASK_LATITUDE_SOUTH)
     {
        if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
          strcpy(syn->s0.Qc, "5");
        else
          strcpy(syn->s0.Qc, "3");
     }
     else
     {
        if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
          strcpy(syn->s0.Qc, "7");
        else
         strcpy(syn->s0.Qc, "1");
     }
   }
   // check if about MMM
   if ((syn->s0.MMM[0] == 0) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0])
   {
      latlon_to_MMM(syn->s0.MMM, s->lat, s->lon);
   }
   return 0;
 }
int syn_parse_x06 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 06.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 67 of file bufr2syn_x06.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::LaLaLa, bufr_subset_state::lat, latlon_to_MMM(), synop_sec0::LoLoLoLo, bufr_subset_state::lon, bufr_atom_data::mask, bufr_subset_state::mask, synop_sec0::MMM, synop_sec0::Qc, synop_chunks::s0, SUBSET_MASK_HAVE_LONGITUDE, SUBSET_MASK_LATITUDE_SOUTH, SUBSET_MASK_LONGITUDE_WEST, synop_sec0::Ulo, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   int ia;
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 06 001
     case 2: // 0 06 002
       if (s->val < 0.0)
         s->mask |= SUBSET_MASK_LONGITUDE_WEST; // Sign for longitude
       s->mask |= SUBSET_MASK_HAVE_LONGITUDE;
       ia = (int) (fabs(s->val) * 10.0 + 0.5);
       sprintf(syn->s0.LoLoLoLo, "%04d",ia);
       syn->s0.Ulo[0] = syn->s0.LoLoLoLo[2];
       s->lon = s->val;
       break;
     default:
       break;
     }
   // check if set both LaLaLa and LoLoLoLo to set Qc
   if ((syn->s0.Qc[0] == 0) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0])
     {
       if (s->mask & SUBSET_MASK_LATITUDE_SOUTH)
         {
           if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
             strcpy(syn->s0.Qc, "5");
           else
             strcpy(syn->s0.Qc, "3");
         }
       else
         {
           if (s->mask & SUBSET_MASK_LONGITUDE_WEST)
             strcpy(syn->s0.Qc, "7");
           else
             strcpy(syn->s0.Qc, "1");
         }
     }
   // check if about MMM
   if ((syn->s0.MMM[0] == 0) && syn->s0.LaLaLa[0] && syn->s0.LoLoLoLo[0])
   {
      latlon_to_MMM(syn->s0.MMM, s->lat, s->lon);
   }
   return 0;
 }
int syn_parse_x07 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 07.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x07.c.
References bufr_subset_state::a, bufr_subset_state::alt, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec0::h0h0h0h0, synop_sec0::im, bufr_subset_state::ival, bufr_atom_data::mask, bufr_subset_state::mask, synop_chunks::s0, SUBSET_MASK_HAVE_ALTITUDE, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   // this is to avoid warning
   if (syn == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     case 1: // 0 07 001
     case 30:
     case 31:
       if (syn->s0.h0h0h0h0[0] == 0)
       {
         sprintf(syn->s0.h0h0h0h0, "%04d", s->ival);
         syn->s0.im[0] = '1';// set unit as m
         s->mask |= SUBSET_MASK_HAVE_ALTITUDE;
       }
       s->alt = s->val;
      break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x08 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 08.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 37 of file bufr2syn_x08.c.
References bufr_subset_state::a, bufr_subset_state::clayer, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::isq, bufr_subset_state::ival, bufr_atom_data::mask, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (syn == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     case 2:
       if (s->ival == 21)
         s->clayer = 1; // first cloud layer
       else if (s->ival == 22)
         s->clayer = 2; // second cloud layer
       else if (s->ival == 23)
         s->clayer = 3; // third cloud layer
       else if (s->ival == 24)
         s->clayer = 4; // fourth cloud layer
       break;
     case 22:
     case 23:
     case 24:
       if (s->isq)
         s->isq = 0;
       else
         s->isq = 1;
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x10 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 10.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 66 of file bufr2syn_x10.c.
References synop_sec1::a, bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::ival, bufr_atom_data::mask, synop_chunks::mask, pascal_to_ppp(), pascal_to_PPPP(), synop_sec1::PoPoPoPo, synop_sec1::ppp, synop_sec1::PPPP, synop_chunks::s1, SYNOP_SEC1, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 4: // 0 10 004
       pascal_to_PPPP ( aux, s->val );
       strcpy ( syn->s1.PoPoPoPo, aux );
       syn->mask |= SYNOP_SEC1;
       break;
     case 51: // 0 10 051
       pascal_to_PPPP ( aux, s->val );
       strcpy ( syn->s1.PPPP, aux );
       syn->mask |= SYNOP_SEC1;
       break;
     case 63: // 0 10 063
       sprintf ( syn->s1.a, "%1d",s->ival );
       syn->mask |= SYNOP_SEC1;
       break;
     case 61: // 0 10 061
       pascal_to_ppp ( aux, s->val );
       sprintf ( syn->s1.ppp, "%s", aux );
       syn->mask |= SYNOP_SEC1;
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x11 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 11.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 60 of file bufr2syn_x11.c.
References bufr_subset_state::a, synop_sec3::d9, synop_sec5::d9, synop_sec1::dd, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec1::ff, synop_sec1::fff, bufr_subset_state::itval, bufr_subset_state::ival, synop_sec0::iw, bufr_atom_data::mask, synop_chunks::mask, bufr_subset_state::mask, data9::misc, data9::n, synop_chunks::s0, synop_chunks::s1, synop_chunks::s3, synop_chunks::s5, secs_to_tt(), misc3::SpSp, misc3::spsp, SUBSET_MASK_HAVE_GUST, SYNOP_SEC1, SYNOP_SEC3, SYNOP_SEC5, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 11 001
     case 11: // 0 11 011
       sprintf ( syn->s1.dd, "%02d", ( s->ival + 5 ) / 10 );
       syn->mask |= SYNOP_SEC1;
       break;
     case 2: // 0 11 002
     case 12: // 0 11 012
       if ( syn->s0.iw[0] == '4' )
         s->val *= 1.94384449;
       if ( s->val < 100.0 )
         sprintf ( syn->s1.ff, "%02d", ( int ) ( s->val + 0.5 ) );
       else
         {
           sprintf ( syn->s1.ff,"99" );
           sprintf ( syn->s1.fff, "%03d", ( int ) ( s->val + 0.5 ) );
         }
       syn->mask |= SYNOP_SEC1;
       break;
     case 41: // max wind gust speed
       if (s->itval == -600)
         {
           sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "910");
           if ( syn->s0.iw[0] == '4' )
             s->val *= 1.94384449;
           if ( s->val < 100.0 )
             sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
           else
             {
               sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
               syn->s3.d9.n++;
               sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00");
               sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
             }
           syn->s3.d9.n++;
         }
       else if (s->itval)
         {
           if (s->mask & SUBSET_MASK_HAVE_GUST)
             {
               sprintf( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "907");
               secs_to_tt(syn->s5.d9.misc[syn->s5.d9.n].spsp, s->itval);
               syn->s5.d9.n++;
               sprintf( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "911");
               if ( syn->s0.iw[0] == '4' )
                 s->val *= 1.94384449;
               if ( s->val < 100.0 )
                 sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
               else
                 {
                   sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp,"99" );
                   syn->s5.d9.n++;
                   sprintf( syn->s5.d9.misc[syn->s5.d9.n].SpSp, "00");
                   sprintf ( syn->s5.d9.misc[syn->s5.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                 }
               syn->s5.d9.n++;
               syn->mask |= SYNOP_SEC5;
             }
           else
             {
               sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "907");
               secs_to_tt(syn->s3.d9.misc[syn->s3.d9.n].spsp, s->itval);
               syn->s3.d9.n++;
               sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "911");
               if ( syn->s0.iw[0] == '4' )
                 s->val *= 1.94384449;
               if ( s->val < 100.0 )
                 sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%02d", ( int ) ( s->val + 0.5 ) );
               else
                 {
                   sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp,"99" );
                   syn->s3.d9.n++;
                   sprintf( syn->s3.d9.misc[syn->s3.d9.n].SpSp, "00");
                   sprintf ( syn->s3.d9.misc[syn->s3.d9.n].spsp, "%03d", ( int ) ( s->val + 0.5 ) );
                 }
               syn->s3.d9.n++;
               syn->mask |= SYNOP_SEC3;
               s->mask |= SUBSET_MASK_HAVE_GUST;
             }
         }
       break;
     case 43: // max wind gust direction
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x12 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 12.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 119 of file bufr2syn_x12.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, guess_WMO_region(), bufr_subset_state::itval, synop_sec3::jjj, kelvin_to_snTT(), kelvin_to_snTTT(), kelvin_to_TT(), bufr_atom_data::mask, synop_chunks::mask, synop_chunks::s1, synop_chunks::s2, synop_chunks::s3, synop_sec1::sn1, synop_sec1::sn2, synop_sec3::snn, synop_sec3::snx, synop_sec2::sw, SYNOP_SEC1, SYNOP_SEC2, SYNOP_SEC3, synop_sec2::TbTbTb, synop_sec1::TdTdTd, synop_sec3::TnTnTn, synop_sec1::TTT, synop_sec3::TxTxTx, bufr_subset_state::val, synop_sec3::XoXoXoXo, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 12 001
     case 4: // 0 12 004
     case 101: // 0 12 101
     case 104: // 0 12 104
       if (syn->s1.TTT[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s1.sn1[0] = aux[0];
               strcpy ( syn->s1.TTT, aux + 1 );
               syn->mask |= SYNOP_SEC1;
             }
         }
       break;
     case 3: // 0 12 003
     case 5: // 0 12 006
     case 103: // 0 12 103
     case 106: // 0 12 106
       if (syn->s1.TdTdTd[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s1.sn2[0] = aux[0];
               strcpy ( syn->s1.TdTdTd, aux + 1 );
               syn->mask |= SYNOP_SEC1;
             }
         }
       break;
     case 11: // 0 12 011
     case 14: // 0 12 014
     case 21: // 0 12 021
     case 111: // 0 12 115
     case 114: // 0 12 114
     case 116: // 0 12 116
       if (syn->s3.TxTxTx[0] == 0 && (s->itval % (3*3600)) == 0) // only for 3, 6 ... hours
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s3.snx[0] = aux[0];
               strcpy ( syn->s3.TxTxTx, aux + 1 );
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     case 12: // 0 12 012
     case 15: // 0 12 015
     case 22: // 0 12 022
     case 112: // 0 12 115
     case 115: // 0 12 115
     case 117: // 0 12 117
       if (syn->s3.TnTnTn[0] == 0 && (s->itval % (3*3600)) == 0) // only for 3, 6 ... hours
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s3.snn[0] = aux[0];
               strcpy ( syn->s3.TnTnTn, aux + 1 );
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     case 2:
     case 6:
     case 102:
     case 105: // 0 12 105 Wet bulb temperature
       if (syn->s2.TbTbTb[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s2.sw[0] = aux[0];
               strcpy ( syn->s2.TbTbTb, aux + 1 );
               syn->mask |= SYNOP_SEC2;
             }
         }
       break;
     case 113:
       if (strcmp("6", guess_WMO_region(syn)) == 0) // region VI
         {
           if (kelvin_to_snTT ( aux, s->val ))
             {
               strcpy ( syn->s3.jjj, aux);
               syn->mask |= SYNOP_SEC3;
             }
         }
       else if (strcmp("1", guess_WMO_region(syn)) == 0)
         {
           if (kelvin_to_TT ( aux, s->val ))
             {
               syn->s3.XoXoXoXo[0] = aux[0];
               syn->s3.XoXoXoXo[1] = aux[1];
               if (syn->s3.XoXoXoXo[2] == 0)
                 syn->s3.XoXoXoXo[2] = '/';
               if (syn->s3.XoXoXoXo[3] == 0)
                 syn->s3.XoXoXoXo[3] = '/';
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x13 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 13.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 89 of file bufr2syn_x13.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::itval, bufr_atom_data::mask, synop_chunks::mask, prec_to_RRR(), prec_to_RRRR24(), synop_sec1::RRR, synop_sec3::RRR, synop_sec5::RRR, synop_sec3::RRRR24, synop_chunks::s1, synop_chunks::s3, synop_chunks::s5, SYNOP_SEC1, SYNOP_SEC3, SYNOP_SEC5, synop_sec1::tr, synop_sec3::tr, synop_sec5::tr, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[8];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 11: // 0 13 011
       if ( s->itval ==  -3600 )
         {
           if (syn->s3.RRR[0] == 0)
             {
               syn->s3.tr[0] = '5'; // 1 hour
               prec_to_RRR ( syn->s3.RRR, s->val );
               syn->mask |= SYNOP_SEC3;
             }
           else if (syn->s5.RRR[0] == 0)
             {
               syn->s5.tr[0] = '5'; // 1 hour
               prec_to_RRR ( syn->s5.RRR, s->val );
               syn->mask |= SYNOP_SEC5;
             }
         }
       else if ( s->itval == -7200 )
         {
           if (syn->s1.RRR[0] == 0)
             {
               syn->s1.tr[0] = '6'; // 2 hour
               prec_to_RRR ( syn->s1.RRR, s->val );
               syn->mask |= SYNOP_SEC1;
             }
         }
       else if ( s->itval == -10800 )
         {
           if (syn->s3.RRR[0] == 0)
             {
               syn->s3.tr[0] = '7'; // 3 hour
               prec_to_RRR ( syn->s3.RRR, s->val );
               syn->mask |= SYNOP_SEC3;
             }
           else if (syn->s5.RRR[0] == 0)
             {
               syn->s5.tr[0] = '7'; // 3 hour
               prec_to_RRR ( syn->s5.RRR, s->val );
               // in case tr = 5 in sec 3 we interchange groups
               if (syn->s3.tr[0] == '5')
               {
                  strcpy(aux, syn->s3.RRR);
                  strcpy(syn->s3.RRR, syn->s5.RRR);
                  strcpy(syn->s5.RRR, aux);
                  syn->s3.tr[0] = '7';
                  syn->s5.tr[0] = '5';
               }
               syn->mask |= SYNOP_SEC5;
             }
         }
       else if ( s->itval == - ( 6 * 3600 ) )
         {
           if (syn->s1.RRR[0] == 0)
             {
               syn->s1.tr[0] = '1'; // 6 hour
               prec_to_RRR ( syn->s1.RRR, s->val );
               syn->mask |= SYNOP_SEC1;
             }
         }
       else if ( s->itval == - ( 9 * 3600 ) )
         {
           if (syn->s3.RRR[0] == 0)
             {
               syn->s3.tr[0] = '8'; // 9 hour
               prec_to_RRR ( syn->s3.RRR, s->val );
               syn->mask |= SYNOP_SEC3;
             }
           else if (syn->s5.RRR[0] == 0)
             {
               syn->s5.tr[0] = '8'; // 9 hour
               prec_to_RRR ( syn->s5.RRR, s->val );
               syn->mask |= SYNOP_SEC5;
             }
         }
       else if ( s->itval == - ( 12 * 3600 ) )
         {
           if (syn->s1.RRR[0] == 0 || syn->s1.tr[0] == '4')
             {
               syn->s1.tr[0] = '2'; // 12 hour
               prec_to_RRR ( syn->s1.RRR, s->val );
               syn->mask |= SYNOP_SEC1;
             }
         }
       else if ( s->itval == - ( 15 * 3600 ) )
         {
           if (syn->s3.RRR[0] == 0)
             {
               syn->s3.tr[0] = '9'; // 15 hour
               prec_to_RRR ( syn->s3.RRR, s->val );
               syn->mask |= SYNOP_SEC3;
             }
           else if (syn->s5.RRR[0] == 0)
             {
               syn->s5.tr[0] = '9'; // 15 hour
               prec_to_RRR ( syn->s5.RRR, s->val );
               syn->mask |= SYNOP_SEC5;
             }
         }
       else if ( s->itval == - ( 18 * 3600 ) )
         {
           if (syn->s1.RRR[0] == 0)
             {
               syn->s1.tr[0] = '3'; // 12 hour
               prec_to_RRR ( syn->s1.RRR, s->val );
               syn->mask |= SYNOP_SEC1;
             }
         }
       else if ( s->itval == - ( 24 * 3600 ) )
         {
           if (syn->s3.RRR[0] == 0)
             {
               syn->s3.tr[0] = '4'; // 24 hour
               prec_to_RRR ( syn->s3.RRR, s->val );
               syn->mask |= SYNOP_SEC3;
             }
           if (syn->s3.RRRR24[0] == 0)
             {
               prec_to_RRRR24 ( syn->s3.RRRR24, s->val );
               syn->mask |= SYNOP_SEC3;
             }
         }
       break;
     case 19: // 0 13 019
       if (syn->s3.RRR[0] == 0)
         {
           syn->s3.tr[0] = '5'; // 1 hour
           prec_to_RRR ( syn->s3.RRR, s->val );
           syn->mask |= SYNOP_SEC3;
         }
       else if (syn->s5.RRR[0] == 0)
         {
           syn->s5.tr[0] = '5'; // 1 hour
           prec_to_RRR ( syn->s5.RRR, s->val );
           syn->mask |= SYNOP_SEC5;
         }
       break;
     case 20: // 0 13 020
       if (syn->s3.RRR[0] == 0)
         {
           syn->s3.tr[0] = '7'; // 3 hour
           prec_to_RRR ( syn->s3.RRR, s->val );
           syn->mask |= SYNOP_SEC3;
         }
       else if (syn->s5.RRR[0] == 0)
         {
           syn->s5.tr[0] = '7'; // 3 hour
           prec_to_RRR ( syn->s5.RRR, s->val );
           // in case tr = 5 in sec 3 we interchange groups
           if (syn->s3.tr[0] == '5')
             {
               strcpy(aux, syn->s3.RRR);
               strcpy(syn->s3.RRR, syn->s5.RRR);
               strcpy(syn->s5.RRR, aux);
               syn->s3.tr[0] = '7';
               syn->s5.tr[0] = '5';
             }
           syn->mask |= SYNOP_SEC5;
         }
       break;
     case 21: // 0 13 021
       if (syn->s1.RRR[0] == 0)
         {
           syn->s1.tr[0] = '1'; // 6 hour
           prec_to_RRR ( syn->s1.RRR, s->val );
           syn->mask |= SYNOP_SEC1;
         }
       break;
     case 22: // 0 13 022
       if (syn->s1.RRR[0] == 0 || syn->s1.tr[0] == '4')
         {
           syn->s1.tr[0] = '2'; // 12 hour
           prec_to_RRR ( syn->s1.RRR, s->val );
           syn->mask |= SYNOP_SEC1;
         }
       break;
     case 23: // 0 13 023
       if (syn->s1.RRR[0] == 0)
         {
           syn->s1.tr[0] = '4'; // 24 hour
           prec_to_RRR ( syn->s1.RRR, s->val );
           syn->mask |= SYNOP_SEC1;
         }
       if (syn->s3.RRRR24[0] == 0)
         {
           prec_to_RRRR24 ( syn->s3.RRRR24, s->val );
           syn->mask |= SYNOP_SEC3;
         }
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x14 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 14.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 34 of file bufr2syn_x14.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec3::FFFF, synop_sec3::FFFF24, bufr_subset_state::itval, bufr_subset_state::ival, synop_sec3::j5, synop_sec3::j524, bufr_atom_data::mask, synop_chunks::mask, synop_chunks::s3, synop_sec3::SS, synop_sec3::SSS, SYNOP_SEC3, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   switch ( s->a->desc.y )
     {
     case 1: // 0 14 001 long-wave radiation 24 hours
     case 11:
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (syn->s3.SSS[0])
         {
           strcpy(syn->s3.j524[4], "4");
           sprintf(syn->s3.FFFF24[4], "%04d", s->ival / 10000);
           syn->mask |= SYNOP_SEC3;
         }
       break;
     case 2: // 0 14 002 Long-wave radiation
     case 12:
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (s->itval == (-24 * 3600))
         {
           if (syn->s3.SSS[0])
             {
               strcpy(syn->s3.j524[4], "4");
               sprintf(syn->s3.FFFF24[4], "%04d", s->ival / 10000);
               syn->mask |= SYNOP_SEC3;
             }
         }
       else if (s->itval == -3600)
         {
           if (syn->s3.SS[0])
             {
               strcpy(syn->s3.j5[4], "4");
               sprintf(syn->s3.FFFF[4], "%04d", s->ival / 1000);
             }
         }
       syn->mask |= SYNOP_SEC3;
       break;
     case 3: // 0 14 001 short-wave radiation 24 hours
     case 13:
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (syn->s3.SSS[0])
         {
           strcpy(syn->s3.j524[6], "6");
           sprintf(syn->s3.FFFF24[6], "%04d", s->ival / 10000);
           syn->mask |= SYNOP_SEC3;
         }
       break;
     case 4: // 0 14 002 short-wave radiation
     case 14:
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (s->itval == (-24 * 3600))
         {
           if (syn->s3.SSS[0])
             {
               strcpy(syn->s3.j524[6], "6");
               sprintf(syn->s3.FFFF24[6], "%04d", s->ival / 10000);
             }
         }
       else if (s->itval == -3600)
         {
           if (syn->s3.SS[0])
             {
               strcpy(syn->s3.j5[6], "6");
               sprintf(syn->s3.FFFF[6], "%04d", s->ival / 1000);
             }
         }
       syn->mask |= SYNOP_SEC3;
       break;
     case 31: // 0 14 031 Total sunshine
       if (s->itval == (-24 * 3600))
         {
           if (s->a->mask & DESCRIPTOR_VALUE_MISSING)
             sprintf(syn->s3.SSS, "///");
           else
             sprintf(syn->s3.SSS, "%03d", s->ival / 6);
         }
       else if (s->itval == -3600)
         {
           if (s->a->mask & DESCRIPTOR_VALUE_MISSING)
             sprintf(syn->s3.SS, "//");
           else
             sprintf(syn->s3.SS, "%02d", s->ival / 6);
         }
       syn->mask |= SYNOP_SEC3;
       break;
     case 32: // 0 14 032 Total sunshine (hours)
       if (s->itval == (-24 * 3600))
         {
           if (s->a->mask & DESCRIPTOR_VALUE_MISSING)
             sprintf(syn->s3.SSS, "///");
           else
             sprintf(syn->s3.SSS, "%03d", s->ival * 10);
         }
       else if (s->itval == -3600)
         {
           if (s->a->mask & DESCRIPTOR_VALUE_MISSING)
             sprintf(syn->s3.SS, "//");
           else
             sprintf(syn->s3.SS, "%02d", s->ival * 10);
         }
       syn->mask |= SYNOP_SEC3;
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x20 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 20.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 147 of file bufr2syn_x20.c.
References bufr_subset_state::a, nub3::C, synop_sec1::Ch, synop_sec1::Cl, bufr_subset_state::clayer, synop_sec1::Cm, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec3::E, synop_sec3::E1, synop_sec1::h, nub3::hshs, bufr_subset_state::ival, synop_sec1::ix, m_to_h(), m_to_hh(), bufr_atom_data::mask, synop_chunks::mask, bufr_subset_state::mask, synop_sec1::N, synop_sec1::Nh, nub3::Ns, synop_sec3::nub, percent_to_okta(), synop_chunks::s1, synop_chunks::s3, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1, SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2, SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW, SYNOP_SEC1, SYNOP_SEC3, bufr_subset_state::val, vism_to_VV(), synop_sec1::VV, synop_sec1::W1, synop_sec1::W2, synop_sec1::ww, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   switch ( s->a->desc.y )
     {
     case 1: // 0 20 001
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       vism_to_VV ( syn->s1.VV, s->val );
       break;
     case 3: // 0 20 003
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
           {
             s->mask |=  (SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1 | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2);
             return 0;
           }
       if ( s->ival < 100 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"1" );
           sprintf ( syn->s1.ww, "%02d", s->ival );
           syn->mask |= SYNOP_SEC1;
         }
       else if ( s->ival == 100)
         {
           s->mask |=  SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW;
         }
       else if ( s->ival < 200 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"7" );
           sprintf ( syn->s1.ww, "%02d", s->ival % 100 );
           syn->mask |= SYNOP_SEC1;
         }
       else if ( s->ival == 508)
         {
           s->mask |=  (SUBSET_MASK_HAVE_NO_SIGNIFICANT_WW | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1 | SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2);
         }
       break;
     case 4: // 0 20 004
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         {
           s->mask |=  SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1;
           return 0;
         }
       if ( s->ival < 10 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"1" );
           sprintf ( syn->s1.W1, "%d", s->ival );
           syn->mask |= SYNOP_SEC1;
         }
       else if (s->ival == 10)
         {
           s->mask |= SUBSET_MASK_HAVE_NO_SIGNIFICANT_W1;
         }
       else
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"7" );
           sprintf ( syn->s1.W1, "%d", s->ival % 10 );
           syn->mask |= SYNOP_SEC1;
         }
       break;
     case 5: // 0 20 005
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         {
           s->mask |=  SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2;
           return 0;
         }
       if ( s->ival < 10 )
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"1" );
           sprintf ( syn->s1.W2, "%d", s->ival );
           syn->mask |= SYNOP_SEC1;
         }
       else if (s->ival == 10)
         {
           s->mask |= SUBSET_MASK_HAVE_NO_SIGNIFICANT_W2;
         }
       else
         {
           if ( syn->s1.ix[0] == '/' )
             strcpy ( syn->s1.ix,"7" );
           sprintf ( syn->s1.W2, "%d", s->ival % 10 );
           syn->mask |= SYNOP_SEC1;
         }
       break;
     case 10: // 0 20 010
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       percent_to_okta ( syn->s1.N, s->val );
       break;
     case 11: // 0 20 011
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (s->clayer == 0)
         {
           if ( s->ival <= 8 )
             sprintf ( syn->s1.Nh, "%1d", s->ival );
           else if ( s->ival <= 10 )
             sprintf ( syn->s1.Nh, "9");
           else if ( s->ival == 15 )
             sprintf ( syn->s1.Nh, "/");
           syn->mask |= SYNOP_SEC1;
         }
       else
         {
           if ( s->ival <= 8 )
             sprintf ( syn->s3.nub[s->clayer - 1].Ns, "%1d", s->ival );
           else if ( s->ival <= 10 )
             sprintf ( syn->s3.nub[s->clayer - 1].Ns, "9");
           else if ( s->ival == 15 )
             sprintf ( syn->s3.nub[s->clayer - 1].Ns, "/");
           syn->mask |= SYNOP_SEC3;
         }
       break;
     case 12: // 0 20 012
       if (s->clayer == 0)
         {
           if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
             return 0;
           if (s->ival >= 10 && s->ival < 20)
             sprintf( syn->s1.Ch, "%1d", s->ival % 10);
           else if (s->ival >= 20 && s->ival < 30)
             sprintf( syn->s1.Cm, "%1d", s->ival % 10);
           else if (s->ival >= 30 && s->ival < 40)
             sprintf( syn->s1.Cl, "%1d", s->ival % 10);
           else if (s->ival == 59)
             sprintf( syn->s1.Nh, "/");
           else if (s->ival == 60)
             sprintf( syn->s1.Ch, "/");
           else if (s->ival == 61)
             sprintf( syn->s1.Cm, "/");
           else if (s->ival == 62)
             sprintf( syn->s1.Cl, "/");
           syn->mask |= SYNOP_SEC1;
         }
       else
         {
           if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
           {
             sprintf( syn->s3.nub[s->clayer - 1].C, "/");
             return 0;
           }
           if (s->ival == 59)
             sprintf( syn->s3.nub[s->clayer - 1].C, "/");
           else
             sprintf( syn->s3.nub[s->clayer - 1].C, "%1d", s->ival % 10);
           syn->mask |= SYNOP_SEC3;
         }
       break;
     case 13: // 0 20 013
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if (s->clayer == 0) // fisrt layer is for sec1
         m_to_h( syn->s1.h, s->val );
       else
         m_to_hh(syn->s3.nub[s->clayer - 1].hshs, s->val);
       break;
     case 62: // 0 20 062
       if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
         return 0;
       if ( s->ival < 10)
         sprintf(syn->s3.E,"%d", s->ival);
       else if (s->ival < 20)
         sprintf(syn->s3.E1,"%d", s->ival % 10);
       syn->mask |= SYNOP_SEC3;
       break;
     default:
       break;
     }
   // check about h
   if (syn->s1.h[0] == '/' && syn->s1.N[0] == '0')
     syn->s1.h[0] = '9';
   // Supress 7wwW1W2 if no significant weather
   if ((syn->s1.ww[0] == 0 || (syn->s1.ww[0] && (strcmp(syn->s1.ww,"04") < 0))) &&
       (syn->s1.W1[0] == 0 || (syn->s1.W1[0] && (strcmp(syn->s1.W1,"3") < 0))) &&
       (syn->s1.W2[0] == 0 || (syn->s1.W2[0] && (strcmp(syn->s1.W2,"3") < 0))))
     {
       syn->s1.ww[0] = 0;
       syn->s1.W1[0] = 0;
       syn->s1.W2[0] = 0;
       if (syn->s1.ix[0] == '1')
         syn->s1.ix[0] = '2';
     }
   return 0;
 }
int syn_parse_x22 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 35 of file bufr2syn_x22.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec2::dw1dw1, synop_sec2::dw2dw2, synop_sec2::Hw1Hw1, synop_sec2::Hw2Hw2, synop_sec2::HwaHwa, synop_sec2::HwaHwaHwa, synop_sec2::HwHw, bufr_subset_state::ival, kelvin_to_snTTT(), bufr_atom_data::mask, synop_chunks::mask, synop_sec2::Pw1Pw1, synop_sec2::Pw2Pw2, synop_sec2::PwaPwa, synop_sec2::PwPw, synop_chunks::s2, synop_sec2::ss, SYNOP_SEC2, synop_sec2::TwTwTw, bufr_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   char aux[16];
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   switch ( s->a->desc.y )
     {
     case 1: // 0 22 001
     case 3: // 0 22 003 wind direction
       if (syn->s2.dw1dw1[0] == 0)
         {
           sprintf(syn->s2.dw1dw1, "%02d", (s->ival + 5)/10);
         }
       else if (syn->s2.dw2dw2[0] == 0)
         {
           sprintf(syn->s2.dw2dw2, "%02d", (s->ival + 5)/10);
         }
       syn->mask |= SYNOP_SEC2; // have sec2 data
       break;
     case 11: // 0 22 011 wind period in seconds
       if (syn->s2.PwPw[0] == 0)
         {
           sprintf(syn->s2.PwPw, "%02d", (int)(s->val));
           syn->mask |= SYNOP_SEC2; // have sec2 data
         }
       break;
     case 12: // 0 22 012 wind wave period in seconds
       if (syn->s2.PwaPwa[0] == 0)
         {
           sprintf(syn->s2.PwaPwa, "%02d", (int)(s->val));
           syn->mask |= SYNOP_SEC2; // have sec2 data
         }
       break;
     case 13: // 0 22 013 swell wave period in seconds
       if (syn->s2.Pw1Pw1[0] == 0)
         {
           sprintf(syn->s2.Pw1Pw1, "%02d", (int)(s->val));
         }
       else if (syn->s2.Pw2Pw2[0] == 0)
         {
           sprintf(syn->s2.Pw2Pw2, "%02d", (int)(s->val));
         }
       syn->mask |= SYNOP_SEC2; // have sec2 data
       break;
     case 21: // 0 22 021  wind wave heigh in m
       if (syn->s2.HwHw[0] == 0)
         {
           sprintf(syn->s2.HwHw, "%02d", (int)(s->val * 2.0 + 0.01));
           syn->mask |= SYNOP_SEC2; // have sec2 data
         }
       break;
     case 22: // 0 22 022 wind wave heigh in meters
       if (syn->s2.HwaHwa[0] == 0)
         {
           sprintf(syn->s2.HwaHwa, "%02d", (int)(s->val * 2.0 + 0.01));  // 0.5 m units
           syn->mask |= SYNOP_SEC2; // have sec2 data
         }
       if (syn->s2.HwaHwaHwa[0] == 0)
         {
           sprintf(syn->s2.HwaHwaHwa, "%03d", (int)(s->val * 10.0 + 0.5));  // 0.1 m units
           syn->mask |= SYNOP_SEC2; // have sec2 data
         }
       break;
     case 23: // 0 22 023 swell wave heigh in meters
       if (syn->s2.Hw1Hw1[0] == 0)
         {
           sprintf(syn->s2.Hw1Hw1, "%02d", (int)(s->val * 2.0 + 0.01));
         }
       else if (syn->s2.Hw2Hw2[0] == 0)
         {
           sprintf(syn->s2.Hw2Hw2, "%02d",(int)(s->val * 2.0 + 0.01));
         }
       syn->mask |= SYNOP_SEC2; // have sec2 data
       break;
     case 42:
     case 43:
     case 45:
     case 49: // 0 22 049 Sea surface temperature
       if (syn->s2.TwTwTw[0] == 0)
         {
           if (kelvin_to_snTTT ( aux, s->val ))
             {
               syn->s2.ss[0] = aux[0];
               strcpy ( syn->s2.TwTwTw, aux + 1 );
               syn->mask |= SYNOP_SEC2; // have sec2 data
             }
         }
       break;
     default:
       break;
     }
   return 0;
 }
int syn_parse_x31 (struct synop_chunks * syn, struct bufr_subset_state * s)
Parse a expanded descriptor with X = 31.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 35 of file bufr2syn_x31.c.
References bufr_subset_state::a, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr_subset_state::i, bufr_subset_state::ival, bufr_subset_state::k_rep, bufr_atom_data::mask, bufr_subset_state::rep, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
 {
   if ( s->a->mask & DESCRIPTOR_VALUE_MISSING)
     return 0;
   if (syn == NULL)
     return 1;
   switch ( s->a->desc.y )
     {
     case 1:
       s->rep = s->ival;
       s->k_rep = s->i;
       break;
     default:
       break;
     }
   return 0;
 }
int synop_YYYYMMDDHHmm_to_YYGG (struct synop_chunks * syn)
Sets YYGG from YYYYMMDDHHmm extended group.
Parameters
syn pointer to the target struct synop_chunks
Definition at line 31 of file bufr2syn_synop.c.
References report_date_ext::DD, synop_chunks::e, synop_sec0::GG, report_date_ext::HH, report_date_ext::MM, report_date_ext::mm, synop_chunks::s0, synop_sec0::YY, and report_date_ext::YYYY.
Referenced by parse_subset_as_synop().
 {
   char aux[20];
   time_t t;
   struct tm tim;
   if ( strlen ( syn->e.YYYY ) &&
        strlen ( syn->e.MM ) &&
        strlen ( syn->e.DD ) &&
        strlen ( syn->e.HH ) &&
        strlen ( syn->e.mm ) )
     sprintf ( aux,"%s%s%s%s%s", syn->e.YYYY, syn->e.MM, syn->e.DD, syn->e.HH, syn->e.mm );
   if ( strlen ( aux ) != 12 )
     return 1;
   memset ( &tim, 0, sizeof ( struct tm ) );
   strptime ( aux, "%Y%m%d%H%M", &tim );
   t = mktime ( &tim ) + 1799 ; // rounding trick
   gmtime_r ( &t, &tim );
   sprintf ( syn->s0.YY, "%02d", tim.tm_mday );
   sprintf ( syn->s0.GG, "%02d", tim.tm_hour );
   return 0;
 }
three_bytes_to_uint (const unsigned char * source)
returns the integer value from an array of three bytes, most significant first
Definition at line 31 of file bufr2syn_utils.c.
Referenced by read_bufr().
 {
    return  (source[2] + source[1] * 256 + source[0] * 65536);
 }
char * vism_to_VV (char * target, double V)
Convert horizontal visibilty in meters to a VV string.
Parameters
V the visibility (m)
target the resulting VV string
Definition at line 124 of file bufr2syn_x20.c.
Referenced by syn_parse_x20().
 {
   if ( V < 100.0 )
     strcpy ( target, "00" );
   else if ( V <= 5000.0 )
     sprintf ( target, "%02d", ( int ) ( V + 0.1 ) / 100 );
   else if ( V <= 30000.0 )
     sprintf ( target, "%02d", ( int ) ( V + 0.1 ) / 1000 + 50 );
   else if ( V <= 70000.0 )
     sprintf ( target, "%02d", ( int ) ( V - 30000.0 ) / 5000 + 80 );
   else
     strcpy ( target, "89" );
   return target;
 }
int YYYYMMDDHHmm_to_met_datetime (struct met_datetime * t, const char * source)
Parse the string YYYYMMDDHHmm and set a struct met_datetime.
Parameters
source string with date in YYYYMMDDHHmm format
t pointer to a struct met_datetime where to set the results
Definition at line 131 of file bufr2syn_utils.c.
References met_datetime::datime, met_datetime::t, and met_datetime::tim.
Referenced by parse_subset_as_buoy(), and parse_subset_as_synop().
 {
   if (strlen(source) != 12)
     return 1;
   memset ( &t->tim, 0, sizeof ( struct tm ) );
   strptime (source, "%Y%m%d%H%M", &t->tim );
   strcpy(t->datime, source);
   t->t = mktime(&t->tim);
   return 0;
 }