bufr2synop: src/bufrdeco/bufrdeco_tabled_csv.c File Reference
bufrdeco_tabled_csv.c File Reference
file with the code to read table D (Descriptor sequences)
#include "bufrdeco.h"
Functions
int bufr_read_tabled_csv (struct bufr_tabled *td, char *error)
Reads a file with table D content according with WMO csv format.
Detailed Description
file with the code to read table D (Descriptor sequences)
Definition in file bufrdeco_tabled_csv.c.
Function Documentation
bufr_read_tabled_csv()
int bufr_read_tabled_csv (struct bufr_tabled * td, char * error)
Reads a file with table D content according with WMO csv format.
Parameters
td pointer to a target struct bufr_tabled
error string where to set error if any
If succeded return 0, otherwise 1
Definition at line 34 of file bufrdeco_tabled_csv.c.
{
  char aux[32], *c;
  char *tk[16];
  int nt;
  FILE *t;
  size_t ix = 0;
  size_t i = 0;
  int j0, nj = 0;
  char oldkey[8];
  char caux[256];
  char laux[CSV_MAXL];
  struct bufr_descriptor desc;
  if ( td->path[0] == 0 )
    {
      return 1;
    }
  // Check if we've already readed this table.
  if ( strcmp ( td->path, td->old_path ) == 0 )
    {
      return 0; // all done
    }
  strcpy ( caux, td->path );
  memset ( td, 0, sizeof ( struct bufr_tabled ) );
  strcpy ( td->path,caux );
  if ( ( t = fopen ( td->path, "r" ) ) == NULL )
    {
      sprintf ( error,"Unable to open table D file '%s'\n", td->path );
      return 1;
    }
  // read first line, it is ignored
  fgets ( laux, CSV_MAXL, t );
  oldkey[0] = 0;
  j0 = 0;
  while ( fgets ( laux, CSV_MAXL, t ) != NULL && i < BUFR_MAXLINES_TABLED )
    {
      // Parse line
      //printf("%s\n",laux);
      if ( parse_csv_line ( &nt, tk, laux ) < 0 || ( nt != 2 && nt != 4) )
        {
          sprintf ( error,"Error parsing csv line from table D file '%s' found %d tokens in line %lu\n", td->path, nt, i );
          return 1;
        }
      // item fields
      strcpy(td->item[i].key, tk[0]);
      strcpy(td->item[i].key2, tk[1]);
      if (nt == 4 && tk[2][0])
        strcpy(td->item[i].description, tk[2]);
      else
        td->item[i].description[0] = 0;
      if (nt == 4 && tk[3][0])
        strcpy(td->item[i].description2, tk[3]);
      else
        td->item[i].description2[0] = 0;
      if ( strcmp ( oldkey, tk[0] ) )
        {
          if ( oldkey[0] )
            {
              // write number of descriptors in emulated ECMWF line
              sprintf ( aux, "%s%3d", oldkey, nj );
              td->l[j0][1] = aux[0];
              td->l[j0][2] = aux[1];
              td->l[j0][3] = aux[2];
              td->l[j0][4] = aux[3];
              td->l[j0][5] = aux[4];
              td->l[j0][6] = aux[5];
              td->l[j0][7] = aux[6];
              td->l[j0][8] = aux[7];
              td->l[j0][9] = aux[8];
            }
          j0 = i;
          nj = 1;
        }
      else
        {
          nj++;
        }
      strcpy ( oldkey, tk[0] );
      ix = strtoul ( tk[0], &c, 10 );
      uint32_t_to_descriptor ( &desc, ix );
      if ( td->num[desc.x] == 0 )
        {
          td->x_start[desc.x] = i;  // marc the start
        }
      ( td->num[desc.x] ) ++;
      // Now emule ECMWF format
      sprintf ( td->l[i], "           %s", tk[1] );
      i++;
    }
  fclose ( t );
  // Last sequence
  sprintf ( aux, "%s%3d", oldkey, nj );
  td->l[j0][1] = aux[0];
  td->l[j0][2] = aux[1];
  td->l[j0][3] = aux[2];
  td->l[j0][4] = aux[3];
  td->l[j0][5] = aux[4];
  td->l[j0][6] = aux[5];
  td->l[j0][7] = aux[6];
  td->l[j0][8] = aux[7];
  td->l[j0][9] = aux[8];
  /*for ( kk = 0; kk < i; kk++ )
    printf ( "%s\n", td->l[kk] );*/
  td->nlines = i;
  td->wmo_table = 1;
  strcpy ( td->old_path, td->path ); // store latest path
  return 0;
}
References BUFR_MAXLINES_TABLED, bufr_descriptor::c, CSV_MAXL, bufr_tabled_decoded_item::description, bufr_tabled_decoded_item::description2, bufr_tabled::item, bufr_tabled_decoded_item::key, bufr_tabled_decoded_item::key2, bufr_tabled::l, bufr_tabled::nlines, bufr_tabled::num, bufr_tabled::old_path, parse_csv_line(), bufr_tabled::path, uint32_t_to_descriptor(), bufr_tabled::wmo_table, bufr_descriptor::x, and bufr_tabled::x_start.
Referenced by bufr_read_tables_wmo().