bufr2synop: src/libraries/bufr2tac_print_temp.c File Reference
bufr2tac_print_temp.c File Reference
file with the code to print the results in case of temp reposrt
#include "bufr2tac.h"
Functions
int print_temp_raw_data (struct temp_raw_data *r)
Prints for debug a struct temp_raw_data.
int print_temp_raw_wind_shear_data (struct temp_raw_wind_shear_data *w)
Prints for debug a struct temp_raw_data.
size_t print_temp_a_sec1 (char **sec1, size_t lmax, struct temp_chunks *t)
Prints the section 1 of part A of a TEMP report.
size_t print_temp_a_sec2 (char **sec2, size_t lmax, struct temp_chunks *t)
Prints the section 2 of part A of a TEMP report.
size_t print_temp_a_sec3 (char **sec3, size_t lmax, struct temp_chunks *t)
Prints the section 3 of part A of a TEMP report.
size_t print_temp_a_sec4 (char **sec4, size_t lmax, struct temp_chunks *t)
Prints the section 4 of part A of a TEMP report.
size_t print_temp_a_sec7 (char **sec7, size_t lmax, struct temp_chunks *t)
Prints the section 7 of part A of a TEMP report.
int print_temp_a (char *report, size_t lmax, struct temp_chunks *t, int mode)
Prints the part A of a TEMP report into a string.
size_t print_temp_b_sec1 (char **sec1, size_t lmax, struct temp_chunks *t)
Prints the section 1 of part B of a TEMP report.
size_t print_temp_b_sec5 (char **sec5, size_t lmax, struct temp_chunks *t)
Prints the section 5 of part B of a TEMP report.
size_t print_temp_b_sec6 (char **sec6, size_t lmax, struct temp_chunks *t)
Prints the section 6 of part B of a TEMP report.
size_t print_temp_b_sec7 (char **sec7, size_t lmax, struct temp_chunks *t)
Prints the section 7 of part B of a TEMP report.
size_t print_temp_b_sec8 (char **sec8, size_t lmax, struct temp_chunks *t)
Prints the section 8 of part B of a TEMP report.
int print_temp_b (char *report, size_t lmax, struct temp_chunks *t, int mode)
Prints the part B of a TEMP report into a string.
size_t print_temp_c_sec1 (char **sec1, size_t lmax, struct temp_chunks *t)
Prints the section 1 of part C of a TEMP report.
size_t print_temp_c_sec2 (char **sec2, size_t lmax, struct temp_chunks *t)
Prints the section 2 of part C of a TEMP report.
size_t print_temp_c_sec3 (char **sec3, size_t lmax, struct temp_chunks *t)
Prints the section 3 of part C of a TEMP report.
size_t print_temp_c_sec4 (char **sec4, size_t lmax, struct temp_chunks *t)
Prints the section 4 of part C of a TEMP report.
size_t print_temp_c_sec7 (char **sec7, size_t lmax, struct temp_chunks *t)
Prints the section 7 of part C of a TEMP report.
int print_temp_c (char *report, size_t lmax, struct temp_chunks *t, int mode)
Prints the part C of a TEMP report into a string.
size_t print_temp_d_sec1 (char **sec1, size_t lmax, struct temp_chunks *t)
Prints the section 1 of part D of a TEMP report.
size_t print_temp_d_sec5 (char **sec5, size_t lmax, struct temp_chunks *t)
Prints the section 5 of part D of a TEMP report.
size_t print_temp_d_sec6 (char **sec6, size_t lmax, struct temp_chunks *t)
Prints the section 6 of part D of a TEMP report.
size_t print_temp_d_sec7 (char **sec7, size_t lmax, struct temp_chunks *t)
Prints the section 7 of part D of a TEMP report.
size_t print_temp_wigos_id (char **wid, size_t lmax, struct temp_chunks *t)
int print_temp_d (char *report, size_t lmax, struct temp_chunks *t, int mode)
int print_temp (struct metreport *m, int mode)
print the four parts of a decoded TEMP report from a BUFR file into strings
Detailed Description
file with the code to print the results in case of temp reposrt
Definition in file bufr2tac_print_temp.c.
Function Documentation
print_temp()
int print_temp (struct metreport * m, int mode)
print the four parts of a decoded TEMP report from a BUFR file into strings
Parameters
m pointer to a struct metreport in which alphanumeric string members stores the reults
mode If == 0 legacy mode. Igf == 1 the print WIGOS identifier
Definition at line 1055 of file bufr2tac_print_temp.c.
{
  // It is required that al lesat a standard level where decoded in SEC A
  if ( m->temp.a.mask & TEMP_SEC_2 )
    {
      print_temp_a ( m->alphanum, REPORT_LENGTH, &m->temp, mode );
    }
  // It is required a significant TH or wind poind for sec B
  if ( m->temp.b.mask & ( TEMP_SEC_5 | TEMP_SEC_6 ) )
    {
      print_temp_b ( m->alphanum2, REPORT_LENGTH, &m->temp, mode );
    }
  // It is required a standard level for SEC C
  if ( m->temp.c.mask & TEMP_SEC_2 )
    {
      print_temp_c ( m->alphanum3, REPORT_LENGTH, &m->temp, mode );
    }
  // It is required a significant TH or wind poind for sec B
  if ( m->temp.d.mask & ( TEMP_SEC_5 | TEMP_SEC_6 ) )
    {
      print_temp_d ( m->alphanum4, REPORT_LENGTH, &m->temp, mode );
    }
  return 0;
}
References temp_chunks::a, metreport::alphanum, metreport::alphanum2, metreport::alphanum3, metreport::alphanum4, temp_chunks::b, temp_chunks::c, temp_chunks::d, temp_a::mask, temp_b::mask, temp_c::mask, temp_d::mask, print_temp_a(), print_temp_b(), print_temp_c(), print_temp_d(), REPORT_LENGTH, metreport::temp, TEMP_SEC_2, TEMP_SEC_5, and TEMP_SEC_6.
Referenced by parse_subset_sequence().
print_temp_a()
int print_temp_a (char * report, size_t lmax, struct temp_chunks * t, int mode)
Prints the part A of a TEMP report into a string.
Parameters
report string where to write the results
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
mode Flags the mode it prints. If = 1 then prints WIGOS identifier
Definition at line 347 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c;
  c = report;
  // Needs time extension
  if ( t->a.e.YYYY[0] == 0  || t->a.e.YYYY[0] == '0')
    {
      return 1;
    }
  if ( mode )
    used += print_temp_wigos_id ( &c, lmax, t );
  used += print_temp_a_sec1 ( &c, lmax - used, t );
  used += print_temp_a_sec2 ( &c, lmax - used, t );
  used += print_temp_a_sec3 ( &c, lmax - used, t );
  used += print_temp_a_sec4 ( &c, lmax - used, t );
  used += print_temp_a_sec7 ( &c, lmax - used, t );
  used += snprintf ( c, lmax - used, "=" );
  return 0;
}
References temp_chunks::a, temp_a::e, print_temp_a_sec1(), print_temp_a_sec2(), print_temp_a_sec3(), print_temp_a_sec4(), print_temp_a_sec7(), print_temp_wigos_id(), and report_date_ext::YYYY.
Referenced by print_temp().
print_temp_a_sec1()
size_t print_temp_a_sec1 (char ** sec1, size_t lmax, struct temp_chunks * t)
Prints the section 1 of part A of a TEMP report.
Parameters
sec1 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec1
Definition at line 145 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec1;
  used += snprintf ( c + used, lmax - used, "%s", t->t.datime );
  used += snprintf ( c + used, lmax - used, " %s%s", t->a.s1.MiMi, t->a.s1.MjMj );
  if ( t->a.s1.D_D[0] && t->a.s1.II[0] == 0 )
    {
      used += snprintf ( c + used, lmax - used, " %s", t->a.s1.D_D );
    }
  used += snprintf ( c + used, lmax - used, " %s%s", t->a.s1.YYGG, t->a.s1.id );
  // print IIiii
  if ( t->a.s1.II[0] )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->a.s1.II, t->a.s1.iii );
    }
  else
    {
      if ( t->a.s1.LaLaLa[0] )
        {
          used += snprintf ( c + used, lmax - used, " 99%s", t->a.s1.LaLaLa );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " 99///" );
        }
      if ( t->a.s1.Qc[0] && t->a.s1.LoLoLoLo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->a.s1.Qc, t->a.s1.LoLoLoLo );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " /////" );
        }
      if ( t->a.s1.MMM[0] && t->a.s1.Ula[0] && t->a.s1.Ulo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s%s", t->a.s1.MMM, t->a.s1.Ula, t->a.s1.Ulo );
        }
      if ( t->a.s1.h0h0h0h0[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->a.s1.h0h0h0h0, t->a.s1.im );
        }
    }
  *sec1 = c + used;
  return used;
}
References temp_chunks::a, temp_acd_sec1::D_D, met_datetime::datime, temp_acd_sec1::h0h0h0h0, temp_acd_sec1::id, temp_acd_sec1::II, temp_acd_sec1::iii, temp_acd_sec1::im, temp_acd_sec1::LaLaLa, temp_acd_sec1::LoLoLoLo, temp_acd_sec1::MiMi, temp_acd_sec1::MjMj, temp_acd_sec1::MMM, temp_acd_sec1::Qc, temp_a::s1, temp_chunks::t, temp_acd_sec1::Ula, temp_acd_sec1::Ulo, and temp_acd_sec1::YYGG.
Referenced by print_temp_a().
print_temp_a_sec2()
size_t print_temp_a_sec2 (char ** sec2, size_t lmax, struct temp_chunks * t)
Prints the section 2 of part A of a TEMP report.
Parameters
sec2 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec2
Definition at line 211 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec2;
  //Surface level
  used += snprintf ( c + used, lmax - used, " 99%s", t->a.s2.lev0.PnPnPn );
  used += snprintf ( c + used, lmax - used, " %s%s", t->a.s2.lev0.TnTnTan, t->a.s2.lev0.DnDn );
  used += snprintf ( c + used, lmax - used, " %s", t->a.s2.lev0.dndnfnfnfn );
  for ( i = 0; i < t->a.s2.n ; i++ )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->a.s2.std[i].PnPn, t->a.s2.std[i].hnhnhn );
      used += snprintf ( c + used, lmax - used, " %s%s", t->a.s2.std[i].TnTnTan, t->a.s2.std[i].DnDn );
      used += snprintf ( c + used, lmax - used, " %s", t->a.s2.std[i].dndnfnfnfn );
    }
  *sec2 = c + used;
  return used;
}
References temp_chunks::a, temp_main_level_data::DnDn, temp_std_level_data::DnDn, temp_main_level_data::dndnfnfnfn, temp_std_level_data::dndnfnfnfn, temp_std_level_data::hnhnhn, temp_a_sec2::lev0, temp_a_sec2::n, temp_std_level_data::PnPn, temp_main_level_data::PnPnPn, temp_a::s2, temp_a_sec2::std, temp_main_level_data::TnTnTan, and temp_std_level_data::TnTnTan.
Referenced by print_temp_a().
print_temp_a_sec3()
size_t print_temp_a_sec3 (char ** sec3, size_t lmax, struct temp_chunks * t)
Prints the section 3 of part A of a TEMP report.
Parameters
sec3 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec3
Definition at line 242 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec3;
  if ( t->a.s3.n == 0 )
    {
      used += snprintf ( c + used, lmax - used, " 88999" );
    }
  else
    {
      for ( i = 0; i < t->a.s3.n ; i++ )
        {
          used += snprintf ( c + used, lmax - used, " 88%s", t->a.s3.trop[i].PnPnPn );
          used += snprintf ( c + used, lmax - used, " %s%s", t->a.s3.trop[i].TnTnTan, t->a.s3.trop[i].DnDn );
          used += snprintf ( c + used, lmax - used, " %s", t->a.s3.trop[i].dndnfnfnfn );
        }
    }
  *sec3 = c + used;
  return used;
}
References temp_chunks::a, temp_main_level_data::DnDn, temp_main_level_data::dndnfnfnfn, temp_ac_sec3::n, temp_main_level_data::PnPnPn, temp_a::s3, temp_main_level_data::TnTnTan, and temp_ac_sec3::trop.
Referenced by print_temp_a().
print_temp_a_sec4()
size_t print_temp_a_sec4 (char ** sec4, size_t lmax, struct temp_chunks * t)
Prints the section 4 of part A of a TEMP report.
Parameters
sec4 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec1
Definition at line 276 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec4;
  if ( t->a.s4.n == 0 )
    {
      used += snprintf ( c + used, lmax - used, " 77999" );
    }
  else
    {
      for ( i = 0; i < t->a.s4.n ; i++ )
        {
          if ( t->a.s4.windx[i].no_last_wind )
            {
              used += snprintf ( c + used, lmax - used, " 77%s", t->a.s4.windx[i].PmPmPm );
            }
          else
            {
              used += snprintf ( c + used, lmax - used, " 66%s", t->a.s4.windx[i].PmPmPm );
            }
          used += snprintf ( c + used, lmax - used, " %s", t->a.s4.windx[i].dmdmfmfmfm );
          if ( t->a.s4.windx[i].vbvb[0] && t->a.s4.windx[i].vava[0] )
            {
              used += snprintf ( c + used, lmax - used, " 4%s%s", t->a.s4.windx[i].vbvb, t->a.s4.windx[i].vava );
            }
        }
    }
  *sec4 = c + used;
  return used;
}
References temp_chunks::a, temp_max_wind_data::dmdmfmfmfm, temp_ac_sec4::n, temp_max_wind_data::no_last_wind, temp_max_wind_data::PmPmPm, temp_a::s4, temp_max_wind_data::vava, temp_max_wind_data::vbvb, and temp_ac_sec4::windx.
Referenced by print_temp_a().
print_temp_a_sec7()
size_t print_temp_a_sec7 (char ** sec7, size_t lmax, struct temp_chunks * t)
Prints the section 7 of part A of a TEMP report.
Parameters
sec7 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec7
Definition at line 321 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec7;
  used += snprintf ( c + used, lmax - used, " 31313" );
  used += snprintf ( c + used, lmax - used, " %s%s%s", t->a.s7.sr, t->a.s7.rara, t->a.s7.sasa );
  used += snprintf ( c + used, lmax - used, " 8%s%s", t->a.s7.GG, t->a.s7.gg );
  if ( t->a.s7.TwTwTw[0] )
    {
      used += snprintf ( c + used, lmax - used, " 9%s%s", t->a.s7.sn, t->a.s7.TwTwTw );
    }
  *sec7 = c + used;
  return used;
}
References temp_chunks::a, temp_sec7::GG, temp_sec7::gg, temp_sec7::rara, temp_a::s7, temp_sec7::sasa, temp_sec7::sn, temp_sec7::sr, and temp_sec7::TwTwTw.
Referenced by print_temp_a().
print_temp_b()
int print_temp_b (char * report, size_t lmax, struct temp_chunks * t, int mode)
Prints the part B of a TEMP report into a string.
Parameters
report string where to write the results
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
mode Flags the mode it prints. If = 1 then prints WIGOS identifier
Definition at line 594 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c;
  c = report;
  // Needs time extension
  if ( t->b.e.YYYY[0] == 0  || t->b.e.YYYY[0] == '0')
    {
      return 1;
    }
  if ( mode )
    used += print_temp_wigos_id ( &c, lmax, t );
  used += print_temp_b_sec1 ( &c, lmax - used, t );
  used += print_temp_b_sec5 ( &c, lmax - used, t );
  used += print_temp_b_sec6 ( &c, lmax - used, t );
  used += print_temp_b_sec7 ( &c, lmax - used, t );
  used += print_temp_b_sec8 ( &c, lmax - used, t );
  used += snprintf ( c, lmax - used, "=" );
  return 0;
}
References temp_chunks::b, temp_b::e, print_temp_b_sec1(), print_temp_b_sec5(), print_temp_b_sec6(), print_temp_b_sec7(), print_temp_b_sec8(), print_temp_wigos_id(), and report_date_ext::YYYY.
Referenced by print_temp().
print_temp_b_sec1()
size_t print_temp_b_sec1 (char ** sec1, size_t lmax, struct temp_chunks * t)
Prints the section 1 of part B of a TEMP report.
Parameters
sec1 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec1
Definition at line 381 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec1;
  used += snprintf ( c + used, lmax - used, "%s", t->t.datime );
  used += snprintf ( c + used, lmax - used, " %s%s", t->b.s1.MiMi, t->b.s1.MjMj );
  if ( t->b.s1.D_D[0] && t->a.s1.II[0] == 0 )
    {
      used += snprintf ( c + used, lmax - used, " %s", t->b.s1.D_D );
    }
  used += snprintf ( c + used, lmax - used, " %s%s", t->b.s1.YYGG, t->b.s1.a4 );
  // print IIiii
  if ( t->b.s1.II[0] )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->b.s1.II, t->b.s1.iii );
    }
  else
    {
      if ( t->b.s1.LaLaLa[0] )
        {
          used += snprintf ( c + used, lmax - used, " 99%s", t->b.s1.LaLaLa );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " 99///" );
        }
      if ( t->b.s1.Qc[0] && t->b.s1.LoLoLoLo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->b.s1.Qc, t->b.s1.LoLoLoLo );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " /////" );
        }
      if ( t->b.s1.MMM[0] && t->b.s1.Ula[0] && t->b.s1.Ulo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s%s", t->b.s1.MMM, t->b.s1.Ula, t->b.s1.Ulo );
        }
      if ( t->b.s1.h0h0h0h0[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->b.s1.h0h0h0h0, t->b.s1.im );
        }
    }
  *sec1= c + used;
  return used;
}
References temp_chunks::a, temp_b_sec1::a4, temp_chunks::b, temp_b_sec1::D_D, met_datetime::datime, temp_b_sec1::h0h0h0h0, temp_acd_sec1::II, temp_b_sec1::II, temp_b_sec1::iii, temp_b_sec1::im, temp_b_sec1::LaLaLa, temp_b_sec1::LoLoLoLo, temp_b_sec1::MiMi, temp_b_sec1::MjMj, temp_b_sec1::MMM, temp_b_sec1::Qc, temp_a::s1, temp_b::s1, temp_chunks::t, temp_b_sec1::Ula, temp_b_sec1::Ulo, and temp_b_sec1::YYGG.
Referenced by print_temp_b().
print_temp_b_sec5()
size_t print_temp_b_sec5 (char ** sec5, size_t lmax, struct temp_chunks * t)
Prints the section 5 of part B of a TEMP report.
Parameters
sec5 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec5
Definition at line 446 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  size_t i;
  char *c = *sec5;
  for ( i = 0; i < t->b.s5.n && i < TEMP_NMAX_POINTS ; i++ )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->b.s5.th[i].nini, t->b.s5.th[i].PnPnPn );
      used += snprintf ( c + used, lmax - used, " %s%s", t->b.s5.th[i].TnTnTan, t->b.s5.th[i].DnDn );
    }
  *sec5 = c + used;
  return used;
}
References temp_chunks::b, temp_th_point::DnDn, temp_bd_sec5::n, temp_th_point::nini, temp_th_point::PnPnPn, temp_b::s5, TEMP_NMAX_POINTS, temp_bd_sec5::th, and temp_th_point::TnTnTan.
Referenced by print_temp_b().
print_temp_b_sec6()
size_t print_temp_b_sec6 (char ** sec6, size_t lmax, struct temp_chunks * t)
Prints the section 6 of part B of a TEMP report.
Parameters
sec6 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec6
Definition at line 471 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec6;
  used += snprintf ( c + used, lmax - used, " 21212" );
  for ( i = 0; i < t->b.s6.n && i < TEMP_NMAX_POINTS ; i++ )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->b.s6.wd[i].nini, t->b.s6.wd[i].PnPnPn );
      used += snprintf ( c + used, lmax - used, " %s", t->b.s6.wd[i].dndnfnfnfn );
    }
  *sec6 = c + used;
  return used;
}
References temp_chunks::b, temp_wind_point::dndnfnfnfn, temp_bd_sec6::n, temp_wind_point::nini, temp_wind_point::PnPnPn, temp_b::s6, TEMP_NMAX_POINTS, and temp_bd_sec6::wd.
Referenced by print_temp_b().
print_temp_b_sec7()
size_t print_temp_b_sec7 (char ** sec7, size_t lmax, struct temp_chunks * t)
Prints the section 7 of part B of a TEMP report.
Parameters
sec7 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec7
Definition at line 498 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec7;
  used += snprintf ( c + used, lmax - used, " 31313" );
  used += snprintf ( c + used, lmax - used, " %s%s%s", t->b.s7.sr, t->b.s7.rara, t->b.s7.sasa );
  used += snprintf ( c + used, lmax - used, " 8%s%s", t->b.s7.GG, t->b.s7.gg );
  if ( t->b.s7.TwTwTw[0] )
    {
      used += snprintf ( c + used, lmax - used, " 9%s%s", t->b.s7.sn, t->b.s7.TwTwTw );
    }
  *sec7 = c + used;
  return used;
}
References temp_chunks::b, temp_sec7::GG, temp_sec7::gg, temp_sec7::rara, temp_b::s7, temp_sec7::sasa, temp_sec7::sn, temp_sec7::sr, and temp_sec7::TwTwTw.
Referenced by print_temp_b().
print_temp_b_sec8()
size_t print_temp_b_sec8 (char ** sec8, size_t lmax, struct temp_chunks * t)
Prints the section 8 of part B of a TEMP report.
Parameters
sec8 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec8
Definition at line 525 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec8;
  if ( t->b.s8.h[0] )
    {
      used += snprintf ( c + used, lmax - used, " 41414 " );
      if ( t->b.s8.Nh[0] )
        {
          used += snprintf ( c + used, lmax - used, "%s", t->b.s8.Nh );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, "/" );
        }
      if ( t->b.s8.Cl[0] )
        {
          used += snprintf ( c + used, lmax - used, "%s", t->b.s8.Cl );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, "/" );
        }
      if ( t->b.s8.h[0] )
        {
          used += snprintf ( c + used, lmax - used, "%s", t->b.s8.h );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, "/" );
        }
      if ( t->b.s8.Cm[0] )
        {
          used += snprintf ( c + used, lmax - used, "%s", t->b.s8.Cm );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, "/" );
        }
      if ( t->b.s8.Ch[0] )
        {
          used += snprintf ( c + used, lmax - used, "%s", t->b.s8.Ch );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, "/" );
        }
      //used += snprintf ( c + used, lmax - used, " %s%s%s%s%s", t->b.s8.Nh, t->b.s8.Cl, t->b.s8.h, t->b.s8.Cm, t->b.s8.Ch );
    }
  *sec8 = c + used;
  return used;
}
References temp_chunks::b, temp_b_sec8::Ch, temp_b_sec8::Cl, temp_b_sec8::Cm, temp_b_sec8::h, temp_b_sec8::Nh, and temp_b::s8.
Referenced by print_temp_b().
print_temp_c()
int print_temp_c (char * report, size_t lmax, struct temp_chunks * t, int mode)
Prints the part C of a TEMP report into a string.
Parameters
report string where to write the results
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
mode Flags the mode it prints. If = 1 then prints WIGOS identifier
Definition at line 825 of file bufr2tac_print_temp.c.
{
  char *c;
  size_t used = 0;
  c = report;
  // Needs time extension
  if ( t->c.e.YYYY[0] == 0  || t->c.e.YYYY[0] == '0')
    {
      return 1;
    }
  if ( mode )
    used += print_temp_wigos_id ( &c, lmax, t );
  used += print_temp_c_sec1 ( &c, lmax - used, t );
  used += print_temp_c_sec2 ( &c, lmax - used, t );
  used += print_temp_c_sec3 ( &c, lmax - used, t );
  used += print_temp_c_sec4 ( &c, lmax - used, t );
  used += print_temp_c_sec7 ( &c, lmax - used, t );
  used += snprintf ( c, lmax - used, "=" );
  return 0;
}
References temp_chunks::c, temp_c::e, print_temp_c_sec1(), print_temp_c_sec2(), print_temp_c_sec3(), print_temp_c_sec4(), print_temp_c_sec7(), print_temp_wigos_id(), and report_date_ext::YYYY.
Referenced by print_temp().
print_temp_c_sec1()
size_t print_temp_c_sec1 (char ** sec1, size_t lmax, struct temp_chunks * t)
Prints the section 1 of part C of a TEMP report.
Parameters
sec1 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec1
Definition at line 629 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec1;
  used += snprintf ( c + used, lmax - used, "%s", t->t.datime );
  used += snprintf ( c + used, lmax - used, " %s%s", t->c.s1.MiMi, t->c.s1.MjMj );
  if ( t->c.s1.D_D[0] && t->a.s1.II[0] == 0 )
    {
      used += snprintf ( c + used, lmax - used, " %s", t->c.s1.D_D );
    }
  used += snprintf ( c + used, lmax - used, " %s%s", t->c.s1.YYGG, t->c.s1.id );
  // print IIiii
  if ( t->c.s1.II[0] )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->c.s1.II, t->c.s1.iii );
    }
  else
    {
      if ( t->c.s1.LaLaLa[0] )
        {
          used += snprintf ( c + used, lmax - used, " 99%s", t->c.s1.LaLaLa );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " 99///" );
        }
      if ( t->c.s1.Qc[0] && t->c.s1.LoLoLoLo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->c.s1.Qc, t->c.s1.LoLoLoLo );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " /////" );
        }
      if ( t->c.s1.MMM[0] && t->c.s1.Ula[0] && t->c.s1.Ulo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s%s", t->c.s1.MMM, t->c.s1.Ula, t->c.s1.Ulo );
        }
      if ( t->c.s1.h0h0h0h0[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->c.s1.h0h0h0h0, t->c.s1.im );
        }
    }
  *sec1 = c + used;
  return used;
}
References temp_chunks::a, temp_chunks::c, temp_acd_sec1::D_D, met_datetime::datime, temp_acd_sec1::h0h0h0h0, temp_acd_sec1::id, temp_acd_sec1::II, temp_acd_sec1::iii, temp_acd_sec1::im, temp_acd_sec1::LaLaLa, temp_acd_sec1::LoLoLoLo, temp_acd_sec1::MiMi, temp_acd_sec1::MjMj, temp_acd_sec1::MMM, temp_acd_sec1::Qc, temp_a::s1, temp_c::s1, temp_chunks::t, temp_acd_sec1::Ula, temp_acd_sec1::Ulo, and temp_acd_sec1::YYGG.
Referenced by print_temp_c().
print_temp_c_sec2()
size_t print_temp_c_sec2 (char ** sec2, size_t lmax, struct temp_chunks * t)
Prints the section 2 of part C of a TEMP report.
Parameters
sec2 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec2
Definition at line 694 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec2;
  for ( i = 0; i < t->c.s2.n ; i++ )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->c.s2.std[i].PnPn, t->c.s2.std[i].hnhnhn );
      used += snprintf ( c + used, lmax - used, " %s%s", t->c.s2.std[i].TnTnTan, t->c.s2.std[i].DnDn );
      used += snprintf ( c + used, lmax - used, " %s", t->c.s2.std[i].dndnfnfnfn );
    }
  *sec2 = c + used;
  return used;
}
References temp_chunks::c, temp_std_level_data::DnDn, temp_std_level_data::dndnfnfnfn, temp_std_level_data::hnhnhn, temp_c_sec2::n, temp_std_level_data::PnPn, temp_c::s2, temp_c_sec2::std, and temp_std_level_data::TnTnTan.
Referenced by print_temp_c().
print_temp_c_sec3()
size_t print_temp_c_sec3 (char ** sec3, size_t lmax, struct temp_chunks * t)
Prints the section 3 of part C of a TEMP report.
Parameters
sec3 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec3
Definition at line 721 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec3;
  if ( t->c.s3.n == 0 )
    {
      used += snprintf ( c + used, lmax - used, " 88999" );
    }
  else
    {
      for ( i = 0; i < t->c.s3.n ; i++ )
        {
          used += snprintf ( c + used, lmax - used, " 88%s", t->c.s3.trop[i].PnPnPn );
          used += snprintf ( c + used, lmax - used, " %s%s", t->c.s3.trop[i].TnTnTan, t->c.s3.trop[i].DnDn );
          used += snprintf ( c + used, lmax - used, " %s", t->c.s3.trop[i].dndnfnfnfn );
        }
    }
  *sec3 = c + used;
  return used;
}
References temp_chunks::c, temp_main_level_data::DnDn, temp_main_level_data::dndnfnfnfn, temp_ac_sec3::n, temp_main_level_data::PnPnPn, temp_c::s3, temp_main_level_data::TnTnTan, and temp_ac_sec3::trop.
Referenced by print_temp_c().
print_temp_c_sec4()
size_t print_temp_c_sec4 (char ** sec4, size_t lmax, struct temp_chunks * t)
Prints the section 4 of part C of a TEMP report.
Parameters
sec4 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec4
Definition at line 755 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec4;
  if ( t->c.s4.n == 0 )
    {
      used += snprintf ( c + used, lmax - used, " 77999" );
    }
  else
    {
      for ( i = 0; i < t->c.s4.n ; i++ )
        {
          if ( t->c.s4.windx[i].no_last_wind )
            {
              used += snprintf ( c + used, lmax - used, " 77%s", t->c.s4.windx[i].PmPmPm );
            }
          else
            {
              used += snprintf ( c + used, lmax - used, " 66%s", t->c.s4.windx[i].PmPmPm );
            }
          used += snprintf ( c + used, lmax - used, " %s", t->c.s4.windx[i].dmdmfmfmfm );
          if ( t->c.s4.windx[i].vbvb[0] && t->c.s4.windx[i].vava[0] )
            {
              used += snprintf ( c + used, lmax - used, " 4%s%s", t->c.s4.windx[i].vbvb, t->c.s4.windx[i].vava );
            }
        }
    }
  *sec4 = c + used;
  return used;
}
References temp_chunks::c, temp_max_wind_data::dmdmfmfmfm, temp_ac_sec4::n, temp_max_wind_data::no_last_wind, temp_max_wind_data::PmPmPm, temp_c::s4, temp_max_wind_data::vava, temp_max_wind_data::vbvb, and temp_ac_sec4::windx.
Referenced by print_temp_c().
print_temp_c_sec7()
size_t print_temp_c_sec7 (char ** sec7, size_t lmax, struct temp_chunks * t)
Prints the section 7 of part C of a TEMP report.
Parameters
sec7 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec7
Definition at line 799 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec7;
  used += snprintf ( c + used, lmax - used, " 31313" );
  used += snprintf ( c + used, lmax - used, " %s%s%s", t->c.s7.sr, t->c.s7.rara, t->c.s7.sasa );
  used += snprintf ( c + used, lmax - used, " 8%s%s", t->c.s7.GG, t->c.s7.gg );
  if ( t->c.s7.TwTwTw[0] )
    {
      used += snprintf ( c + used, lmax - used, " 9%s%s", t->c.s7.sn, t->c.s7.TwTwTw );
    }
  *sec7 = c + used;
  return used;
}
References temp_chunks::c, temp_sec7::GG, temp_sec7::gg, temp_sec7::rara, temp_c::s7, temp_sec7::sasa, temp_sec7::sn, temp_sec7::sr, and temp_sec7::TwTwTw.
Referenced by print_temp_c().
print_temp_d()
int print_temp_d (char * report, size_t lmax, struct temp_chunks * t, int mode)
Definition at line 1026 of file bufr2tac_print_temp.c.
{
  char *c;
  size_t used = 0;
  c = report;
  // Needs time extension
  if ( t->d.e.YYYY[0] == 0  || t->d.e.YYYY[0] == '0')
    {
      return 1;
    }
  if ( mode )
    used += print_temp_wigos_id ( &c, lmax, t );
  used += print_temp_d_sec1 ( &c, lmax - used, t );
  used += print_temp_d_sec5 ( &c, lmax - used, t );
  used += print_temp_d_sec6 ( &c, lmax - used, t );
  used += print_temp_d_sec7 ( &c, lmax - used, t );
  used += snprintf ( c, lmax - used, "=" );
  return 0;
}
References temp_chunks::d, temp_d::e, print_temp_d_sec1(), print_temp_d_sec5(), print_temp_d_sec6(), print_temp_d_sec7(), print_temp_wigos_id(), and report_date_ext::YYYY.
Referenced by print_temp().
print_temp_d_sec1()
size_t print_temp_d_sec1 (char ** sec1, size_t lmax, struct temp_chunks * t)
Prints the section 1 of part D of a TEMP report.
Parameters
sec1 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec1
Definition at line 859 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec1;
  used += snprintf ( c + used, lmax - used, "%s", t->t.datime );
  used += snprintf ( c + used, lmax - used, " %s%s", t->d.s1.MiMi, t->d.s1.MjMj );
  if ( t->d.s1.D_D[0] && t->a.s1.II[0] == 0 )
    {
      used += snprintf ( c + used, lmax - used, " %s", t->d.s1.D_D );
    }
  used += snprintf ( c + used, lmax - used, " %s/", t->d.s1.YYGG );
  // print IIiii
  if ( t->d.s1.II[0] )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->d.s1.II, t->d.s1.iii );
    }
  else
    {
      if ( t->d.s1.LaLaLa[0] )
        {
          used += snprintf ( c + used, lmax - used, " 99%s", t->d.s1.LaLaLa );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " 99///" );
        }
      if ( t->d.s1.Qc[0] && t->d.s1.LoLoLoLo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->d.s1.Qc, t->d.s1.LoLoLoLo );
        }
      else
        {
          used += snprintf ( c + used, lmax - used, " /////" );
        }
      if ( t->d.s1.MMM[0] && t->d.s1.Ula[0] && t->d.s1.Ulo[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s%s", t->d.s1.MMM, t->d.s1.Ula, t->d.s1.Ulo );
        }
      if ( t->d.s1.h0h0h0h0[0] )
        {
          used += snprintf ( c + used, lmax - used, " %s%s", t->d.s1.h0h0h0h0, t->d.s1.im );
        }
    }
  *sec1 = c + used;
  return used;
}
References temp_chunks::a, temp_chunks::d, temp_acd_sec1::D_D, met_datetime::datime, temp_acd_sec1::h0h0h0h0, temp_acd_sec1::II, temp_acd_sec1::iii, temp_acd_sec1::im, temp_acd_sec1::LaLaLa, temp_acd_sec1::LoLoLoLo, temp_acd_sec1::MiMi, temp_acd_sec1::MjMj, temp_acd_sec1::MMM, temp_acd_sec1::Qc, temp_a::s1, temp_d::s1, temp_chunks::t, temp_acd_sec1::Ula, temp_acd_sec1::Ulo, and temp_acd_sec1::YYGG.
Referenced by print_temp_d().
print_temp_d_sec5()
size_t print_temp_d_sec5 (char ** sec5, size_t lmax, struct temp_chunks * t)
Prints the section 5 of part D of a TEMP report.
Parameters
sec5 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec5
Definition at line 924 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec5;
  for ( i = 0; i < t->d.s5.n && i < TEMP_NMAX_POINTS ; i++ )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->d.s5.th[i].nini, t->d.s5.th[i].PnPnPn );
      used += snprintf ( c + used, lmax - used, " %s%s", t->d.s5.th[i].TnTnTan, t->d.s5.th[i].DnDn );
    }
  *sec5 = c + used;
  return used;
}
References temp_chunks::d, temp_th_point::DnDn, temp_bd_sec5::n, temp_th_point::nini, temp_th_point::PnPnPn, temp_d::s5, TEMP_NMAX_POINTS, temp_bd_sec5::th, and temp_th_point::TnTnTan.
Referenced by print_temp_d().
print_temp_d_sec6()
size_t print_temp_d_sec6 (char ** sec6, size_t lmax, struct temp_chunks * t)
Prints the section 6 of part D of a TEMP report.
Parameters
sec6 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec6
Definition at line 949 of file bufr2tac_print_temp.c.
{
  size_t i;
  size_t used = 0;
  char *c = *sec6;
  used += snprintf ( c + used, lmax - used, " 21212" );
  for ( i = 0; i < t->d.s6.n && i < TEMP_NMAX_POINTS ; i++ )
    {
      used += snprintf ( c + used, lmax - used, " %s%s", t->d.s6.wd[i].nini, t->d.s6.wd[i].PnPnPn );
      used += snprintf ( c + used, lmax - used, " %s", t->d.s6.wd[i].dndnfnfnfn );
    }
  *sec6 = c + used;
  return used;
}
References temp_chunks::d, temp_wind_point::dndnfnfnfn, temp_bd_sec6::n, temp_wind_point::nini, temp_wind_point::PnPnPn, temp_d::s6, TEMP_NMAX_POINTS, and temp_bd_sec6::wd.
Referenced by print_temp_d().
print_temp_d_sec7()
size_t print_temp_d_sec7 (char ** sec7, size_t lmax, struct temp_chunks * t)
Prints the section 7 of part D of a TEMP report.
Parameters
sec7 the pointer where to print section
lmax max length permited
t pointer to s atruct temp_chunks where the parse results are set
returns the string sec7
Definition at line 976 of file bufr2tac_print_temp.c.
{
  size_t used = 0;
  char *c = *sec7;
  used += snprintf ( c + used, lmax - used, " 31313" );
  used += snprintf ( c + used, lmax - used, " %s%s%s", t->d.s7.sr, t->d.s7.rara, t->d.s7.sasa );
  used += snprintf ( c + used, lmax - used, " 8%s%s", t->d.s7.GG, t->d.s7.gg );
  if ( t->d.s7.TwTwTw[0] )
    {
      used += snprintf ( c + used, lmax - used, " 9%s%s", t->d.s7.sn, t->d.s7.TwTwTw );
    }
  *sec7 = c + used;
  return used;
}
References temp_chunks::d, temp_sec7::GG, temp_sec7::gg, temp_sec7::rara, temp_d::s7, temp_sec7::sasa, temp_sec7::sn, temp_sec7::sr, and temp_sec7::TwTwTw.
Referenced by print_temp_d().
print_temp_raw_data()
int print_temp_raw_data (struct temp_raw_data * r)
Prints for debug a struct temp_raw_data.
Parameters
r the pointer of struct to print
This is used mainly for debug
Definition at line 33 of file bufr2tac_print_temp.c.
{
  size_t i;
  printf ( "raw points %lu\n", r->n );
  for ( i = 0; i < r->n ; i++ )
    {
      if ( r->raw[i].T != MISSING_REAL &&
           r->raw[i].Td != MISSING_REAL &&
           r->raw[i].dd != MISSING_REAL &&
           r->raw[i].ff != MISSING_REAL )
        printf ( "i=%3ld, dt=%4d, flags=%08X, P=%6.1lf, h=%6.0lf, dlat=%7.4lf, dlon=%7.4lf, T=%6.1lf, Td=%6.1lf, dd=%03.0lf, ff=%5.1lf\n",
                 i, r->raw[i].dt, r->raw[i].flags, r->raw[i].p * 0.01, r->raw[i].h, r->raw[i].dlat, r->raw[i].dlon,
                 r->raw[i].T - 273.15, r->raw[i].Td - 273.15, r->raw[i].dd, r->raw[i].ff );
      else
        {
          printf ( "i=%3ld, dt=%4d, flags=%08X, P=%6.1lf, h=%6.0lf, dlat=%7.4lf, dlon=%7.4lf, ",
                   i, r->raw[i].dt, r->raw[i].flags, r->raw[i].p * 0.01, r->raw[i].h, r->raw[i].dlat, r->raw[i].dlon );
          if ( r->raw[i].T != MISSING_REAL )
            {
              printf ( "T=%6.1lf, ", r->raw[i].T - 273.15 );
            }
          else
            {
              printf ( "T= ///./, " );
            }
          if ( r->raw[i].Td != MISSING_REAL )
            {
              printf ( "T=%6.1lf, ", r->raw[i].Td - 273.15 );
            }
          else
            {
              printf ( "Td= ///./, " );
            }
          if ( r->raw[i].dd != MISSING_REAL )
            {
              printf ( "dd=%03.0lf, ", r->raw[i].dd );
            }
          else
            {
              printf ( "dd=///, " );
            }
          if ( r->raw[i].dd != MISSING_REAL )
            {
              printf ( "ff=%5.1lf\n", r->raw[i].ff );
            }
          else
            {
              printf ( "ff= //./\n" );
            }
        }
    }
  return 0;
}
References temp_raw_point_data::dd, temp_raw_point_data::dlat, temp_raw_point_data::dlon, temp_raw_point_data::dt, temp_raw_point_data::ff, temp_raw_point_data::flags, temp_raw_point_data::h, MISSING_REAL, temp_raw_data::n, temp_raw_point_data::p, temp_raw_data::raw, temp_raw_point_data::T, and temp_raw_point_data::Td.
print_temp_raw_wind_shear_data()
int print_temp_raw_wind_shear_data (struct temp_raw_wind_shear_data * w)
Prints for debug a struct temp_raw_data.
Parameters
w the pointer of struct to print
Used in debug stage
Definition at line 98 of file bufr2tac_print_temp.c.
{
  size_t i;
  printf ( "raw share wind points %lu\n", w->n );
  for ( i = 0; i < w->n ; i++ )
    {
      if ( w->raw[i].ws_blw != MISSING_REAL && w->raw[i].ws_abv != MISSING_REAL )
        printf ( "i=%3ld, dt=%4d, flags=%08X, P=%6.1lf, dlat=%7.4lf, dlon=%7.4lf, ws_blw=%5.1lf, ws_abv=%5.1lf\n",
                 i, w->raw[i].dt, w->raw[i].flags, w->raw[i].p * 0.01, w->raw[i].dlat, w->raw[i].dlon,
                 w->raw[i].ws_blw, w->raw[i].ws_abv );
      else
        {
          printf ( "i=%3ld, dt=%4d, flags=%08X, P=%6.1lf, dlat=%7.4lf, dlon=%7.4lf, ",
                   i, w->raw[i].dt, w->raw[i].flags, w->raw[i].p * 0.01, w->raw[i].dlat, w->raw[i].dlon );
          if ( w->raw[i].ws_blw != MISSING_REAL )
            {
              printf ( "ws_blw=%5.1lf, ", w->raw[i].ws_blw );
            }
          else
            {
              printf ( "ws_blw= ///./, " );
            }
          if ( w->raw[i].ws_abv != MISSING_REAL )
            {
              printf ( "ws_abv=%5.1lf\n", w->raw[i].ws_abv );
            }
          else
            {
              printf ( "ws_abv= ///./\n" );
            }
        }
    }
  return 0;
}
References temp_raw_wind_shear_point::dlat, temp_raw_wind_shear_point::dlon, temp_raw_wind_shear_point::dt, temp_raw_wind_shear_point::flags, MISSING_REAL, temp_raw_wind_shear_data::n, temp_raw_wind_shear_point::p, temp_raw_wind_shear_data::raw, temp_raw_wind_shear_point::ws_abv, and temp_raw_wind_shear_point::ws_blw.
print_temp_wigos_id()
size_t print_temp_wigos_id (char ** wid, size_t lmax, struct temp_chunks * t)
Definition at line 998 of file bufr2tac_print_temp.c.
{
  char *c = *wid;
  size_t used = 0;
  if (t->wid.series == 0 && t->wid.issuer == 0 && t->wid.issue == 0 && t->wid.local_id[0] == '\0')
    used += snprintf (c, lmax, "0-0-0-MISSING");
  else
    used += snprintf ( c + used, lmax, "%d-%d-%d-%s", t->wid.series, t->wid.issuer, t->wid.issue, t->wid.local_id );
  while ( used < 32 )
    c[used++] = ' ';
  c[used++] = '|';
  c[used] = 0;
  *wid = c + used;
  return used;
}
References wigos_id::issue, wigos_id::issuer, wigos_id::local_id, wigos_id::series, and temp_chunks::wid.
Referenced by print_temp_a(), print_temp_b(), print_temp_c(), and print_temp_d().