bufr2synop: src/libraries/bufr2tac_x22.c File Reference
bufr2tac_x22.c File Reference
decodes the descriptors with X = 22 (oceanographic data)
#include "bufr2tac.h"
Functions
int syn_parse_x22 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 01.
int buoy_parse_x22 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 22.
int temp_parse_x22 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 22.
Detailed Description
decodes the descriptors with X = 22 (oceanographic data)
Definition in file bufr2tac_x22.c.
Function Documentation
buoy_parse_x22()
int buoy_parse_x22 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 22.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 148 of file bufr2tac_x22.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 4: // 0 22 004 Direction of current
      if ( s->layer < 32 ) // only 32 max layers
        {
          if ( b->s3.l2[s->layer].dd[0] == 0 )
            {
              sprintf ( b->s3.l2[s->layer].dd, "%02d", ( int ) ( s->val + 5.0 ) / 10 ) ;
              b->mask |= BUOY_SEC3;
            }
          if ( b->s3.l2[s->layer].zzzz[0] == 0 ) // also stores pendent deep
            {
              sprintf ( b->s3.l2[s->layer].zzzz, "%04d", s->deep );
              b->mask |= BUOY_SEC3;
            }
        }
      break;
    case 12: // 0 22 012 wind wave period in seconds
    case 74: // 0 22 074 significant wave period in seconds
      if ( b->s2.PwaPwa[0] == 0 )
        {
          sprintf ( b->s2.PwaPwa, "%02d", ( int ) ( s->val ) );
          b->mask |= BUOY_SEC2; // have sec2 data
          if ( b->s2.PwaPwaPwa[0] == 0 )
            sprintf ( b->s2.PwaPwaPwa, "%03d", ( int ) ( s->val * 10 + 0.5 ) );
        }
      break;
    case 22: // 0 22 022 wind wave heigh in meters
    case 70: // 0 22 070 significant wave height in meters
      if ( b->s2.HwaHwa[0] == 0 )
        {
          sprintf ( b->s2.HwaHwa, "%02d", ( int ) ( s->val * 2.0 + 0.01 ) ); // 0.5 m units
          b->mask |= BUOY_SEC2; // have sec2 data
        }
      if ( b->s2.HwaHwaHwa[0] == 0 )
        {
          sprintf ( b->s2.HwaHwaHwa, "%03d", ( int ) ( s->val * 10.0 + 0.01 ) ); // 0.1 m units
          b->mask |= BUOY_SEC2; // have sec2 data
        }
      break;
    case 31: // 0 22 033 current speed
      if ( s->layer < 32 ) // only 32 max layers
        {
          if ( b->s3.l2[s->layer].dd[0] == 0 )
            {
              sprintf ( b->s3.l2[s->layer].dd, "%03d", ( int ) ( s->val * 100.0 + 0.5 ) ) ;
              b->mask |= BUOY_SEC3;
            }
          if ( b->s3.l2[s->layer].zzzz[0] == 0 ) // also stores pendent deep
            {
              sprintf ( b->s3.l2[s->layer].zzzz, "%04d", s->deep );
              b->mask |= BUOY_SEC3;
            }
        }
      break;
    case 42:
    case 43:
      if ( s->deep == 0 )
        {
          if ( b->s2.TwTwTw[0] == 0 )
            {
              if ( kelvin_to_snTTT ( aux, s->val ) )
                {
                  b->s2.sn[0] = aux[0];
                  strcpy ( b->s2.TwTwTw, aux + 1 );
                  b->mask |= BUOY_SEC2; // have sec2 data
                }
            }
        }
      if ( s->layer < 32 ) // only 32 max layers
        {
          if ( b->s3.l1[s->layer].TTTT[0] == 0 )
            {
              kelvin_to_TTTT ( b->s3.l1[s->layer].TTTT, s->val );
              b->mask |= BUOY_SEC3;
            }
          if ( b->s3.l1[s->layer].zzzz[0] == 0 ) // also stores pendent deep
            {
              sprintf ( b->s3.l1[s->layer].zzzz, "%04d", s->deep );
              b->mask |= BUOY_SEC3;
            }
        }
      break;
    case 45:
    case 49: // 0 22 049 Sea surface temperature
      if ( b->s2.TwTwTw[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              b->s2.sn[0] = aux[0];
              strcpy ( b->s2.TwTwTw, aux + 1 );
              b->mask |= BUOY_SEC2; // have sec2 data
            }
        }
      break;
    case 62: // 0 22 062 Salinity
      if ( s->layer < 32 ) // only 32 max layers
        {
          if ( b->s3.l1[s->layer].SSSS[0] == 0 )
            {
              sprintf ( b->s3.l1[s->layer].SSSS, "%04d", ( int ) ( s->val * 100.0 + 0.5 ) );
              b->mask |= BUOY_SEC3;
            }
          if ( b->s3.l1[s->layer].zzzz[0] == 0 ) // also stores pendent deep
            {
              sprintf ( b->s3.l1[s->layer].zzzz, "%04d", s->deep );
              b->mask |= BUOY_SEC3;
            }
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x22()", "Descriptor not parsed" );
      break;
   }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), BUOY_SEC2, BUOY_SEC3, b_sec3_layer2::dd, bufr2tac_subset_state::deep, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, buoy_sec2::HwaHwa, buoy_sec2::HwaHwaHwa, kelvin_to_snTTT(), kelvin_to_TTTT(), buoy_sec3::l1, buoy_sec3::l2, bufr2tac_subset_state::layer, bufr_atom_data::mask, buoy_chunks::mask, buoy_sec2::PwaPwa, buoy_sec2::PwaPwaPwa, buoy_chunks::s2, buoy_chunks::s3, buoy_sec2::sn, b_sec3_layer1::SSSS, b_sec3_layer1::TTTT, buoy_sec2::TwTwTw, bufr2tac_subset_state::val, bufr_descriptor::y, b_sec3_layer1::zzzz, and b_sec3_layer2::zzzz.
Referenced by parse_subset_as_buoy().
syn_parse_x22()
int syn_parse_x22 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 01.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 35 of file bufr2tac_x22.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 1: // 0 22 001 Direction of waves
    case 3: // 0 22 003 Direction of swell waves
      if ( syn->s2.dw1dw1[0] == 0 )
        {
          sprintf ( syn->s2.dw1dw1, "%02d", abs(( s->ival + 5 ) /10) % 100 );
        }
      else if ( syn->s2.dw2dw2[0] == 0 )
        {
          sprintf ( syn->s2.dw2dw2, "%02d", abs(( s->ival + 5 ) /10) % 100 );
        }
      syn->mask |= SYNOP_SEC2; // have sec2 data
      break;
    case 11: // 0 22 011 wind period in seconds
      if ( syn->s2.PwPw[0] == 0 )
        {
          sprintf ( syn->s2.PwPw, "%02d", ( int ) ( s->val ) );
          syn->mask |= SYNOP_SEC2; // have sec2 data
        }
      break;
    case 12: // 0 22 012 wind wave period in seconds
      if ( syn->s2.PwaPwa[0] == 0 )
        {
          sprintf ( syn->s2.PwaPwa, "%02d", ( int ) ( s->val ) );
          syn->mask |= SYNOP_SEC2; // have sec2 data
        }
      break;
    case 13: // 0 22 013 swell wave period in seconds
      if ( syn->s2.Pw1Pw1[0] == 0 )
        {
          sprintf ( syn->s2.Pw1Pw1, "%02d", ( int ) ( s->val ) );
        }
      else if ( syn->s2.Pw2Pw2[0] == 0 )
        {
          sprintf ( syn->s2.Pw2Pw2, "%02d", ( int ) ( s->val ) );
        }
      syn->mask |= SYNOP_SEC2; // have sec2 data
      break;
    case 21: // 0 22 021  wind wave heigh in m
      if ( syn->s2.HwHw[0] == 0 )
        {
          sprintf ( syn->s2.HwHw, "%02d", ( int ) ( s->val * 2.0 + 0.01 ) );
          syn->mask |= SYNOP_SEC2; // have sec2 data
        }
      break;
    case 22: // 0 22 022 wind wave heigh in meters
      if ( syn->s2.HwaHwa[0] == 0 )
        {
          sprintf ( syn->s2.HwaHwa, "%02d", ( int ) ( s->val * 2.0 + 0.01 ) ); // 0.5 m units
          syn->mask |= SYNOP_SEC2; // have sec2 data
        }
      if ( syn->s2.HwaHwaHwa[0] == 0 )
        {
          sprintf ( syn->s2.HwaHwaHwa, "%03d", ( int ) ( s->val * 10.0 + 0.5 ) ); // 0.1 m units
          syn->mask |= SYNOP_SEC2; // have sec2 data
        }
      break;
    case 23: // 0 22 023 swell wave heigh in meters
      if ( syn->s2.Hw1Hw1[0] == 0 )
        {
          sprintf ( syn->s2.Hw1Hw1, "%02d", ( int ) ( s->val * 2.0 + 0.01 ) );
        }
      else if ( syn->s2.Hw2Hw2[0] == 0 )
        {
          sprintf ( syn->s2.Hw2Hw2, "%02d", ( int ) ( s->val * 2.0 + 0.01 ) );
        }
      syn->mask |= SYNOP_SEC2; // have sec2 data
      break;
    case 42:
    case 43:
    case 45:
    case 49: // 0 22 049 Sea surface temperature
      if ( syn->s2.TwTwTw[0] == 0 )
        {
          if ( kelvin_to_snTTT ( aux, s->val ) )
            {
              syn->s2.ss[0] = aux[0];
              strcpy ( syn->s2.TwTwTw, aux + 1 );
              syn->mask |= SYNOP_SEC2; // have sec2 data
            }
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x22()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, synop_sec2::dw1dw1, synop_sec2::dw2dw2, synop_sec2::Hw1Hw1, synop_sec2::Hw2Hw2, synop_sec2::HwaHwa, synop_sec2::HwaHwaHwa, synop_sec2::HwHw, bufr2tac_subset_state::ival, kelvin_to_snTTT(), bufr_atom_data::mask, synop_chunks::mask, synop_sec2::Pw1Pw1, synop_sec2::Pw2Pw2, synop_sec2::PwaPwa, synop_sec2::PwPw, synop_chunks::s2, synop_sec2::ss, SYNOP_SEC2, synop_sec2::TwTwTw, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x22()
int temp_parse_x22 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 22.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 289 of file bufr2tac_x22.c.
{
  char aux[16];
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    return 0;
  switch ( s->a->desc.y )
    {
    case 43:
      if ( kelvin_to_snTTT ( aux, s->val ) )
        {
          t->a.s7.sn[0] = aux[0];
          t->b.s7.sn[0] = aux[0];
          t->c.s7.sn[0] = aux[0];
          t->d.s7.sn[0] = aux[0];
          strcpy ( t->a.s7.TwTwTw, aux + 1 );
          strcpy ( t->b.s7.TwTwTw, aux + 1 );
          strcpy ( t->c.s7.TwTwTw, aux + 1 );
          strcpy ( t->d.s7.TwTwTw, aux + 1 );
          t->a.mask |= TEMP_SEC_7; // have sec7 data
        }
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x22()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, temp_chunks::a, temp_chunks::b, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), temp_chunks::c, temp_chunks::d, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, kelvin_to_snTTT(), bufr_atom_data::mask, temp_a::mask, temp_a::s7, temp_b::s7, temp_c::s7, temp_d::s7, temp_sec7::sn, TEMP_SEC_7, temp_sec7::TwTwTw, bufr2tac_subset_state::val, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().