bufr2synop: src/libraries/bufr2tac_csv.c File Reference
bufr2tac_csv.c File Reference
Output a struct metreport in csv labeled form.
#include "bufr2tac.h"
Functions
int print_csv_alphanum (FILE *f, char *type, char *alphanum, struct metreport *m)
int print_csv (FILE *f, struct metreport *m)
prints a struct metreport in labeled csv format
Detailed Description
Output a struct metreport in csv labeled form.
Definition in file bufr2tac_csv.c.
Function Documentation
int print_csv (FILE * f, struct metreport * m)
prints a struct metreport in labeled csv format
Parameters
f pointer to a file already open by caller routine
m pointer to a struct metreport containing the data to print
Definition at line 85 of file bufr2tac_csv.c.
References metreport::alphanum, metreport::alphanum2, metreport::alphanum3, metreport::alphanum4, print_csv_alphanum(), metreport::type, metreport::type2, metreport::type3, and metreport::type4.
Referenced by main().
 {
   // Single report
   if ( m->alphanum[0] )
     {
       print_csv_alphanum ( f, m->type, m->alphanum, m );
     }
   if ( m->alphanum2[0] ) //TTBB
     {
       print_csv_alphanum ( f, m->type2, m->alphanum2, m );
     }
   if ( m->alphanum3[0] ) //TTCC
     {
       print_csv_alphanum ( f, m->type3, m->alphanum3, m );
     }
   if ( m->alphanum4[0] ) //TTDD
     {
       print_csv_alphanum ( f, m->type4, m->alphanum4, m );
     }
   return 0;
 }
int print_csv_alphanum (FILE * f, char * type, char * alphanum, struct metreport * m)
Definition at line 26 of file bufr2tac_csv.c.
References met_geo::alt, gts_header::bname, gts_header::center, met_geo::country, met_datetime::datime, gts_header::dtrel, gts_header::filename, metreport::g, metreport::h, met_geo::index, met_geo::lat, met_geo::lon, met_geo::name, gts_header::order, and metreport::t.
Referenced by print_csv().
 {
   // prints header
   fprintf ( f, "\"%s\",", type );
   // print GTS_HEADER
   if ( m->h != NULL )
     {
       fprintf ( f, "\"%s\",",m->h->filename );
       fprintf ( f, "\"%s %s %s %s\",",m->h->bname, m->h->center, m->h->dtrel, m->h->order );
     }
   else
     {
       fprintf ( f, ",," );
     }
   // print DATE AND TIME
   fprintf ( f, "\"%s\",",m->t.datime );
   // Geo data
   if ( strlen ( m->g.index ) )
     {
       fprintf ( f, "\"%s\",", m->g.index );
     }
   else
     {
       fprintf ( f, "," );
     }
   if ( strlen ( m->g.name ) )
     {
       fprintf ( f, "\"%s\",", m->g.name );
     }
   else
     {
       fprintf ( f, "," );
     }
   if ( strlen ( m->g.country ) )
     {
       fprintf ( f, "\"%s\",", m->g.country );
     }
   else
     {
       fprintf ( f, "," );
     }
   fprintf ( f, "%.6lf,", m->g.lat );
   fprintf ( f, "%.6lf,", m->g.lon );
   fprintf ( f, "%.1lf,", m->g.alt );
   fprintf ( f, "\"%s=\"\n", alphanum );
   return 0;
 }