bufr2synop: src/libraries/bufr2tac_json.c File Reference
bufr2tac_json.c File Reference
Output a struct metreport in json form.
#include "bufr2tac.h"
Functions
int print_json_alphanum (FILE *f, char *type, char *alphanum, struct metreport *m)
int print_json (FILE *f, struct metreport *m)
prints a struct metreport in json format
Detailed Description
Output a struct metreport in json form.
Definition in file bufr2tac_json.c.
Function Documentation
int print_json (FILE * f, struct metreport * m)
prints a struct metreport in json format
Parameters
f pointer to a file already open by caller routine
m pointer to a struct metreport containing the data to print
Definition at line 62 of file bufr2tac_json.c.
References metreport::alphanum, metreport::alphanum2, metreport::alphanum3, metreport::alphanum4, print_json_alphanum(), metreport::type, metreport::type2, metreport::type3, and metreport::type4.
Referenced by main().
 {
   fprintf ( f, "{\"metreport\" :" );
   if ( m->alphanum[0] )
     {
       print_json_alphanum ( f, m->type, m->alphanum, m );
     }
   if ( m->alphanum2[0] ) //TTBB
     {
       fprintf ( f, "," );
       print_json_alphanum ( f, m->type2, m->alphanum2, m );
     }
   if ( m->alphanum3[0] ) //TTCC
     {
       fprintf ( f, "," );
       print_json_alphanum ( f, m->type3, m->alphanum3, m );
     }
   if ( m->alphanum4[0] ) //TTDD
     {
       fprintf ( f, "," );
       print_json_alphanum ( f, m->type4, m->alphanum4, m );
     }
   fprintf ( f, "\n}\n" );
   return 0;
 }
int print_json_alphanum (FILE * f, char * type, char * alphanum, struct metreport * m)
Definition at line 26 of file bufr2tac_json.c.
References met_geo::alt, gts_header::bname, gts_header::center, met_geo::country, met_datetime::datime, gts_header::dtrel, gts_header::filename, metreport::g, metreport::h, met_geo::index, met_geo::lat, met_geo::lon, met_geo::name, gts_header::order, and metreport::t.
Referenced by print_json().
 {
   fprintf ( f, " { \n  \"type\": \"%s\",\n", type );
   if ( m->h != NULL )
     {
       fprintf ( f, "  \"bufrfile\": \"%s\",\n", m->h->filename );
       fprintf ( f, "  \"gts_header\": \"%s %s %s %s\",\n", m->h->bname, m->h->center, m->h->dtrel, m->h->order );
     }
   fprintf ( f, "  \"observation_datetime\": \"%s\",\n", m->t.datime );
   fprintf ( f, "  \"geo\": { \n" );
   if ( strlen ( m->g.index ) )
     {
       fprintf ( f, "    \"index\": \"%s\",\n", m->g.index );
     }
   if ( strlen ( m->g.name ) )
     {
       fprintf ( f, "    \"name\": \"%s\",\n", m->g.name );
     }
   if ( strlen ( m->g.country ) )
     {
       fprintf ( f, "    \"country\": \"%s\",\n", m->g.country );
     }
   fprintf ( f, "    \"latitude\": %.6lf,\n", m->g.lat );
   fprintf ( f, "    \"longitude\": %.6lf,\n", m->g.lon );
   fprintf ( f, "    \"altitude\": %.1lf\n", m->g.alt );
   fprintf ( f, "    },\n" );
   fprintf ( f, "  \"report\": \"%s\"\n", alphanum );
   fprintf ( f, "  }" );
   return 0;
 }