bufr2synop: src/libraries/bufr2tac_error.c File Reference
bufr2tac_error.c File Reference
This file has the code for functions to manage errors in bufr2tac library.
#include "bufr2tac.h"
Functions
int bufr2tac_push_error (struct bufr2tac_error_stack *e, int severity, char *description)
int bufr2tac_clean_error_stack (struct bufr2tac_error_stack *e)
int bufr2tac_set_error (struct bufr2tac_subset_state *s, int severity, char *origin, char *explanation)
int bufr2tac_print_error (struct bufr2tac_error_stack *e)
Detailed Description
This file has the code for functions to manage errors in bufr2tac library.
Definition in file bufr2tac_error.c.
Function Documentation
bufr2tac_clean_error_stack()
int bufr2tac_clean_error_stack (struct bufr2tac_error_stack * e)
Definition at line 49 of file bufr2tac_error.c.
{
  if ( e != NULL )
    {
      memset ( e, 0, sizeof ( struct bufr2tac_error_stack ) );
      return 0;
    }
  return -1;
}
bufr2tac_print_error()
int bufr2tac_print_error (struct bufr2tac_error_stack * e)
Definition at line 87 of file bufr2tac_error.c.
{
  unsigned int i;
  if ( e->ne == 0 )
    {
      printf ( "# No info/warning/error \n" );
      return 0;
    }
  for ( i = 0; i < e->ne ; i++ )
    {
      if ( e->err[i].severity == 0 )
        printf ( "# INFO: " );
      else if ( e->err[i].severity == 1 )
        printf ( "# WARNING: " );
      else if ( e->err[i].severity == 2 )
        printf ( "# ERROR: " );
      else
        {
          printf ( "# %d\n", e->err[i].severity );
          return 1;
        }
      printf ( "%s\n", e->err[i].description );
    }
  if ( e->full > 0 )
    printf ( "# More debug info follows, stack of logs full\n" );
  return 0;
}
References bufr2tac_error::description, bufr2tac_error_stack::err, bufr2tac_error_stack::full, bufr2tac_error_stack::ne, and bufr2tac_error::severity.
Referenced by parse_subset_sequence().
bufr2tac_push_error()
int bufr2tac_push_error (struct bufr2tac_error_stack * e, int severity, char * description)
Definition at line 26 of file bufr2tac_error.c.
{
  // avoid segfaults
  if ( e == NULL )
    return -1; // Fatal error
  if ( e->ne < BUFR2TAC_ERROR_STACK_DIM )
    {
      e->err[e->ne].severity = severity;
      strcpy ( e->err[e->ne].description, description );
      ( e->ne )++;
      return 1;
    }
  else if ( e->ne == BUFR2TAC_ERROR_STACK_DIM )
    {
      // Do not pull error, but annotate the stack as rebased
      if ( e->full < severity )
        e->full = severity;
      return 0;
    }
  return -1; // bad e->ne
}
References BUFR2TAC_ERROR_STACK_DIM, bufr2tac_error::description, bufr2tac_error_stack::err, bufr2tac_error_stack::full, bufr2tac_error_stack::ne, and bufr2tac_error::severity.
Referenced by bufr2tac_set_error().
bufr2tac_set_error()
int bufr2tac_set_error (struct bufr2tac_subset_state * s, int severity, char * origin, char * explanation)
Definition at line 59 of file bufr2tac_error.c.
{
  char description[BUFR2TAC_ERROR_DESCRIPTION_LENGTH], *c;
  c = description;
  c += sprintf ( c, "%s: ", origin );
  c += sprintf ( c, " Descriptor: %u %02u %03u: \"%s\"",s->a->desc.f, s->a->desc.x, s->a->desc.y, s->a->name );
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      c+= sprintf ( c, " = MISSING. " );
    }
  else
    {
      if ( s->a->cval[0] )
        c += sprintf ( c, " = '%s'. ", s->a->cval );
      else if ( s->a->desc.x == 2 )
        c += sprintf ( c, " = '%s'. ", s->a->ctable );
      else
        c += sprintf ( c, " = %lf . ", s->a->val );
    }
  c += sprintf ( c, "%s", explanation );
  return bufr2tac_push_error ( &s->e, severity, description );
}
References bufr2tac_subset_state::a, BUFR2TAC_ERROR_DESCRIPTION_LENGTH, bufr2tac_push_error(), bufr_atom_data::ctable, bufr_atom_data::cval, bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::e, bufr_descriptor::f, bufr_atom_data::mask, bufr_atom_data::name, bufr_atom_data::val, bufr_descriptor::x, and bufr_descriptor::y.
Referenced by buoy_parse_x01(), buoy_parse_x02(), buoy_parse_x04(), buoy_parse_x05(), buoy_parse_x06(), buoy_parse_x07(), buoy_parse_x08(), buoy_parse_x10(), buoy_parse_x11(), buoy_parse_x12(), buoy_parse_x13(), buoy_parse_x14(), buoy_parse_x20(), buoy_parse_x22(), buoy_parse_x31(), buoy_parse_x33(), climat_parse_x01(), climat_parse_x02(), climat_parse_x04(), climat_parse_x05(), climat_parse_x06(), climat_parse_x07(), climat_parse_x08(), climat_parse_x10(), climat_parse_x11(), climat_parse_x12(), climat_parse_x13(), climat_parse_x14(), syn_parse_x01(), syn_parse_x02(), syn_parse_x04(), syn_parse_x05(), syn_parse_x06(), syn_parse_x07(), syn_parse_x08(), syn_parse_x10(), syn_parse_x11(), syn_parse_x12(), syn_parse_x13(), syn_parse_x14(), syn_parse_x20(), syn_parse_x22(), syn_parse_x31(), temp_parse_x01(), temp_parse_x02(), temp_parse_x04(), temp_parse_x05(), temp_parse_x06(), temp_parse_x07(), temp_parse_x08(), temp_parse_x10(), temp_parse_x11(), temp_parse_x12(), temp_parse_x20(), temp_parse_x22(), temp_parse_x31(), and temp_parse_x33().