bufr2synop: src/libraries/bufr2tac_x31.c File Reference
bufr2tac_x31.c File Reference
decodes the descriptors with X = 31 (Control)
#include "bufr2tac.h"
Functions
int syn_parse_x31 (struct synop_chunks *syn, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 31.
int buoy_parse_x31 (struct buoy_chunks *b, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 31.
int temp_parse_x31 (struct temp_chunks *t, struct bufr2tac_subset_state *s)
Parse a expanded descriptor with X = 31.
Detailed Description
decodes the descriptors with X = 31 (Control)
Definition in file bufr2tac_x31.c.
Function Documentation
buoy_parse_x31()
int buoy_parse_x31 (struct buoy_chunks * b, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 31.
Parameters
b pointer to a struct buoy_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 81 of file bufr2tac_x31.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  if ( b == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 0: // 0 31 000 .  Short delayed descriptor replication factor
      // It is no meaning here
      break;
    case 1:
      s->rep = s->ival;
      s->k_rep = s->i;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "buoy_parse_x31()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::i, bufr2tac_subset_state::ival, bufr2tac_subset_state::k_rep, bufr_atom_data::mask, bufr2tac_subset_state::rep, and bufr_descriptor::y.
Referenced by parse_subset_as_buoy().
syn_parse_x31()
int syn_parse_x31 (struct synop_chunks * syn, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 31.
Parameters
syn pointer to a struct synop_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 35 of file bufr2tac_x31.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      // 0 31 000 does not have DESCRIPTOR_VALUE_MISSING
      if (s->a->desc.y != 0)
        return 0;
      s->rep = 1;
      s->k_rep = s->i;
    }
  if ( syn == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 0: // 0 31 000 .  Short delayed descriptor replication factor
      s->rep = s->ival;
      s->k_rep = s->i;
      break;
    case 1:
      s->rep = s->ival;
      s->k_rep = s->i;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "syn_parse_x31()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::i, bufr2tac_subset_state::ival, bufr2tac_subset_state::k_rep, bufr_atom_data::mask, bufr2tac_subset_state::rep, and bufr_descriptor::y.
Referenced by parse_subset_as_synop().
temp_parse_x31()
int temp_parse_x31 (struct temp_chunks * t, struct bufr2tac_subset_state * s)
Parse a expanded descriptor with X = 31.
Parameters
t pointer to a struct temp_chunks where to set the results
s pointer to a struct bufr2tac_subset_state where is stored needed information in sequential analysis
It returns 0 if success, 1 if problems when processing. If a descriptor is not processed returns 0 anyway
Definition at line 120 of file bufr2tac_x31.c.
{
  if ( s->a->mask & DESCRIPTOR_VALUE_MISSING )
    {
      return 0;
    }
  if ( t == NULL )
    {
      return 1;
    }
  switch ( s->a->desc.y )
    {
    case 0: // 0 31 000 .  Short delayed descriptor replication factor
      // It is no meaning here
      break;
    case 1: // 0 31 001 .  Replicator
      // It is supposed that it is the extended replicator used when describing
      // wind shear points in raiosonde
      // It is the amount of points of wind shear data at pressure level
      if ( s->ival < TEMP_NMAX_POINTS )
        {
          s->itval = s->ival;
          s->rep = 0;  // used to mark it is a share point in sequent descriptors
        }
      else
        {
          return 1;  // too much points
        }
      s->k_itval = s->i;
      s->w->n = 0;
      break;
    case 2: // 0 31 002 . Extended replicator
      // It is supposed that it is the extended replicator used when describing
      // Temperature, dew-point and wind data at a pressure level with radiosonde position
      // So the integer value of repliactor IS the amount of points
      s->rep = s->ival; // replications and points we need. Also Used to mark this type of point
      s->itval = 0;
      s->k_rep = s->i;
      s->r->n = 0;
      break;
    default:
      if ( BUFR2TAC_DEBUG_LEVEL > 1 && (s->a->mask & DESCRIPTOR_VALUE_MISSING) == 0 )
        bufr2tac_set_error ( s, 0, "temp_parse_x31()", "Descriptor not parsed" );
      break;
    }
  return 0;
}
References bufr2tac_subset_state::a, BUFR2TAC_DEBUG_LEVEL, bufr2tac_set_error(), bufr_atom_data::desc, DESCRIPTOR_VALUE_MISSING, bufr2tac_subset_state::i, bufr2tac_subset_state::itval, bufr2tac_subset_state::ival, bufr2tac_subset_state::k_itval, bufr2tac_subset_state::k_rep, bufr_atom_data::mask, temp_raw_data::n, temp_raw_wind_shear_data::n, bufr2tac_subset_state::r, bufr2tac_subset_state::rep, TEMP_NMAX_POINTS, bufr2tac_subset_state::w, and bufr_descriptor::y.
Referenced by parse_subset_as_temp().