bufr2synop: src/libraries/metsynop.h File Reference
metsynop.h File Reference
Main header file for synop related tasks.
#include "metcommon.h"
Data Structures
struct synop_sec0
contains all possible substrings from section 0 when a report is parsed with success
struct synop_sec1
contains all possible substrings from section 1 when a report is parsed with success
struct synop_sec2
contains all possible substrings from section 2 when a report is parsed with success (still incomplete)
struct nub3
struct with info for a cloud group at section 3
struct misc3
struct with mixed info for group SpSpspsp at section at section 3.
struct data9
struct synop_sec3
contains most of substrings from section 3 when a report is parsed with success
struct synop_sec4
contains some of substrings from section 4 when a report is parsed with success
struct synop_sec5
contains some of substrings from section 5 when a report is parsed with success
struct synop_chunks
contains all possible substrings from a synop report is parsed with success
struct wmo_index_estado
contains an index interval associated with a country
Macros
#define SYNOP_SEC0 1
mask bit meaning section 0 or synop is solicited to or parsed with success
#define SYNOP_SEC1 2
mask bit meaning section 1 or synop is solicited to or parsed with success
#define SYNOP_SEC2 4
mask bit meaning section 2 or synop is solicited to or parsed with success
#define SYNOP_SEC3 8
mask bit meaning section 3 or synop is solicited to or parsed with success
#define SYNOP_SEC4 16
mask bit meaning section 4 or synop is solicited to or parsed with success
#define SYNOP_SEC5 32
mask bit meaning section 5 or synop is solicited to or parsed with success
#define SYNOP_EXT 64
mask bit meaning date extension is parsed with success
#define SYNOP_SEC3_8 128
mask bit meaning optional/regional 8 part, section 3 for synop is solicited to or parsed with success
#define SYNOP_BUFR 256
mask bit meaning date synop is decoded from a BUFR
#define SYNOP_NNUB 6
number of optional nub3 struct to store the parsed results of 8.... groups
#define SYNOP_NMISC 20
number of misc3 struct to store the parsed results of 9SpSpspsp groups
Functions
void clean_report_date_ext (struct report_date_ext *s)
clean a synop_ext struct
void clean_synop_chunks (struct synop_chunks *syn)
cleans a synop_chunks struct
void clean_syn_sec0 (struct synop_sec0 *s)
clean a synop_sec0 struct
void clean_syn_sec1 (struct synop_sec1 *s)
clean a synop_sec1 struct
void clean_syn_sec2 (struct synop_sec2 *s)
clean a synop_sec2 struct
void clean_syn_sec3 (struct synop_sec3 *s)
clean a synop_sec3 struct
void clean_syn_sec4 (struct synop_sec4 *s)
clean a synop_sec4 struct
void clean_syn_sec5 (struct synop_sec5 *s)
clean a synop_sec5 struct
Detailed Description
Main header file for synop related tasks.
Definition in file metsynop.h.
Macro Definition Documentation
SYNOP_BUFR
#define SYNOP_BUFR 256
mask bit meaning date synop is decoded from a BUFR
Definition at line 74 of file metsynop.h.
SYNOP_EXT
#define SYNOP_EXT 64
mask bit meaning date extension is parsed with success
Definition at line 64 of file metsynop.h.
SYNOP_NMISC
#define SYNOP_NMISC 20
number of misc3 struct to store the parsed results of 9SpSpspsp groups
Definition at line 84 of file metsynop.h.
SYNOP_NNUB
#define SYNOP_NNUB 6
number of optional nub3 struct to store the parsed results of 8.... groups
Definition at line 79 of file metsynop.h.
SYNOP_SEC0
#define SYNOP_SEC0 1
mask bit meaning section 0 or synop is solicited to or parsed with success
Definition at line 34 of file metsynop.h.
SYNOP_SEC1
#define SYNOP_SEC1 2
mask bit meaning section 1 or synop is solicited to or parsed with success
Definition at line 39 of file metsynop.h.
SYNOP_SEC2
#define SYNOP_SEC2 4
mask bit meaning section 2 or synop is solicited to or parsed with success
Definition at line 44 of file metsynop.h.
SYNOP_SEC3
#define SYNOP_SEC3 8
mask bit meaning section 3 or synop is solicited to or parsed with success
Definition at line 49 of file metsynop.h.
SYNOP_SEC3_8
#define SYNOP_SEC3_8 128
mask bit meaning optional/regional 8 part, section 3 for synop is solicited to or parsed with success
Definition at line 69 of file metsynop.h.
SYNOP_SEC4
#define SYNOP_SEC4 16
mask bit meaning section 4 or synop is solicited to or parsed with success
Definition at line 54 of file metsynop.h.
SYNOP_SEC5
#define SYNOP_SEC5 32
mask bit meaning section 5 or synop is solicited to or parsed with success
Definition at line 59 of file metsynop.h.
Function Documentation
clean_report_date_ext()
void clean_report_date_ext (struct report_date_ext * s)
clean a synop_ext struct
Parameters
s pointer to the synop_ext struct
Definition at line 85 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct report_date_ext ) );
}
Referenced by clean_buoy_chunks(), clean_climat_chunks(), and clean_synop_chunks().
clean_syn_sec0()
void clean_syn_sec0 (struct synop_sec0 * s)
clean a synop_sec0 struct
Parameters
s pointer to the synop_sec0 struct
Definition at line 30 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec0 ) );
}
Referenced by clean_synop_chunks().
clean_syn_sec1()
void clean_syn_sec1 (struct synop_sec1 * s)
clean a synop_sec1 struct
Parameters
s pointer to the synop_sec1 struct
Definition at line 39 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec1 ) );
}
Referenced by clean_synop_chunks().
clean_syn_sec2()
void clean_syn_sec2 (struct synop_sec2 * s)
clean a synop_sec2 struct
Parameters
s pointer to the synop_sec2 struct
Definition at line 48 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec2 ) );
}
Referenced by clean_synop_chunks().
clean_syn_sec3()
void clean_syn_sec3 (struct synop_sec3 * s)
clean a synop_sec3 struct
Parameters
s pointer to the synop_sec3 struct
Definition at line 57 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec3 ) );
}
Referenced by clean_synop_chunks().
clean_syn_sec4()
void clean_syn_sec4 (struct synop_sec4 * s)
clean a synop_sec4 struct
Parameters
s pointer to the synop_sec4 struct
Definition at line 66 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec4 ) );
}
clean_syn_sec5()
void clean_syn_sec5 (struct synop_sec5 * s)
clean a synop_sec5 struct
Parameters
s pointer to the synop_sec5 struct
Definition at line 75 of file bufr2tac_mrproper.c.
{
  memset ( s, 0, sizeof ( struct synop_sec5 ) );
}
Referenced by clean_synop_chunks().
clean_synop_chunks()
void clean_synop_chunks (struct synop_chunks * syn)
cleans a synop_chunks struct
Parameters
syn pointer to the struct to clean
Definition at line 95 of file bufr2tac_mrproper.c.
{
  syn->mask = 0;
  clean_report_date_ext ( & ( syn->e ) );
  clean_syn_sec0 ( & ( syn->s0 ) );
  clean_syn_sec1 ( & ( syn->s1 ) );
  clean_syn_sec2 ( & ( syn->s2 ) );
  clean_syn_sec3 ( & ( syn->s3 ) );
  clean_syn_sec5 ( & ( syn->s5 ) );
  // default
  strcpy ( syn->s0.iw,"/" );
  strcpy ( syn->s1.ir,"/" );
  strcpy ( syn->s1.ix,"/" );
  strcpy ( syn->s1.h,"/" );
  strcpy ( syn->s1.VV,"//" );
  strcpy ( syn->s1.N,"/" );
  strcpy ( syn->s1.dd,"//" );
  strcpy ( syn->s1.ff,"//" );
  syn->error[0] = '\0';
}