#!/bin/sh
#
if [[ ${#} -eq 0 ]] ; then
  echo "Usage:"
  "${0} original_wmo_file"
  exit 1
fi

cat ${1} |\
    sed -e "s|,\"\"\"|,\"--|g" |\
    sed -e "s|\"\"\",|--\",|g" |\
    sed -e "s|\"\"|\-\-|g"

