#!/bin/sh
###########################################################################
#   Project: bufr2synop                                                   #
#                                                                         #
#   Copyright (C) 2016-2022 by Guillermo Ballester Valor                  #
#   gbvalor@ogimet.com                                                    #
#                                                                         #
#   GNU General Public License v2 or above                                #
###########################################################################
#  Script to transform original file from WMO to reduced version used by bufrdeco library
#
#  It send the result to standard output
#
# Use:
#  prepare_TableA path_to_original_wmo_file

if test ${#} -lt 1 ; then
  echo "usage:"
  echo "prepare_TableA path_to_original_wmo_file"
  exit 1
fi

if test -s ${1} ; then
  cat ${1} | cut -d "," -f 2-3 
else
  echo "Cannot read file ${1}"
  exit 1
fi


