#!/bin/sh
###########################################################################
#   Project: bufr2synop                                                   #
#                                                                         #
#   Copyright (C) 2016-2023 by Guillermo Ballester Valor                  #
#   gbvalor@ogimet.com                                                    #
#                                                                         #
#   GNU General Public License v2 or above                                #
###########################################################################
#  Script to transform original files from WMO and ECMWF to reduced version 
#  used by bufrdeco library
#
#  It send the result to standard output
#
# Use:
#  prepare_TableC

# Original table dirs, change it as your convenience
WMO_DIR="/home/gbv/claves/bufr_tables"
ECMWF_DIR="/usr/local/lib/bufrtables"

# converter
CONVERTER=/usr/local/bin/build_bufrdeco_tables
# script to fix double quotes
FIXER=/usr/local/bin/fix_double_quotes

# versions
WMO_VERSIONS="18_0_0 18_1_0 19_0_0 19_1_1 20_0_0 21_0_0 22_0_1 23_0_0 24_0_0 25_0_0 26_0_0 27_0_0 28_0_0 29_0_0 30_0_0 31_0_0 32_0_0 33_0_0 34_0_0"
WMO_VERSIONS_2="35_0_0 36_0_0 37_0_0"
WMO_VERSIONS_3="38_1_0 39_0_0 40_0_0"

ECMWF_VERSIONS="13 14 15 16 17"

# WMO table C process
for ver in ${WMO_VERSIONS} ; do
  if test ! -s BUFR_${ver}_TableC_en.csv ; then
    ${FIXER} ${WMO_DIR}/BUFRCREX_${ver}/BUFRCREX_${ver}_CodeFlag_en.txt | ${CONVERTER} -t C > BUFR_${ver}_TableC_en.csv
  fi  
done  

for ver in ${WMO_VERSIONS_2} ; do
  if test ! -s BUFR_${ver}_TableC_en.csv ; then
    ${FIXER} ${WMO_DIR}/BUFRCREX_${ver}/BUFRCREX_CodeFlag_en.txt | ${CONVERTER} -2  -t C > BUFR_${ver}_TableC_en.csv
  fi  
done  

for ver in ${WMO_VERSIONS_3} ; do
  if test ! -s BUFR_${ver}_TableC_en.csv ; then
     ${FIXER} ${WMO_DIR}/BUFRCREX_${ver}/BUFRCREX_CodeFlag_en.txt | ${CONVERTER} -3 -t C > BUFR_${ver}_TableC_en.csv
  fi  
done  


# ECMWF table C process
for ver in ${ECMWF_VERSIONS} ; do
  if test ! -s BUFR_${ver}_0_0_TableC_en.csv ; then
    ${FIXER} ${ECMWF_DIR}/C00000000000000${ver}000.TXT | ${CONVERTER}  -t C -e > BUFR_${ver}_0_0_TableC_en.csv
  fi   
done

