#!/bin/sh
#  Script to transform original files from WMO and ECMWF to reduced version used by bufrdeco library
#
#  It send the result to standard output
#
# Use:
#  prepare_TableD 


# Original table dirs, change it as your convenience
WMO_DIR="/home/gbv/claves/bufr_tables"
ECMWF_DIR="/usr/local/lib/bufrtables"

# converter
CONVERTER=/usr/local/bin/build_bufrdeco_tables

# versions
WMO_VERSIONS="18_0_0 18_1_0 19_0_0 19_1_1 20_0_0 21_0_0 22_0_1 23_0_0 24_0_0 25_0_0 26_0_0 27_0_0"
ECMWF_VERSIONS="13 14 15 16 17"

# WMO table D process
for ver in ${WMO_VERSIONS} ; do
  ${CONVERTER} -i ${WMO_DIR}/BUFRCREX_${ver}/BUFR_${ver}_TableD_en.txt -t D > BUFR_${ver}_TableD_en.csv
done  

# ECMWF table D process
for ver in ${ECMWF_VERSIONS} ; do
  ${CONVERTER} -i ${ECMWF_DIR}/D00000000000000${ver}000.TXT -t D -e > BUFR_${ver}_0_0_TableD_en.csv
done


